const QURAN_TAFSIR = [
  // ═══════════════════════════════════════════════════════════════
  // WISDOM (حكمة إلهية) — Why Allah chose specific words/structures
  // ═══════════════════════════════════════════════════════════════

  {
    id: 1,
    verse_ref: '7:54',
    verse_ar: 'إِنَّ رَبَّكُمُ اللَّهُ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ فِي سِتَّةِ أَيَّامٍ ثُمَّ اسْتَوَىٰ عَلَى الْعَرْشِ',
    topic_ar: 'لماذا خلق الله في ستة أيام؟',
    topic_en: 'Why did God create in six days?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يطرح السامرائي سؤالاً جوهرياً: لماذا خلق الله السماوات والأرض في ستة أيام وهو القادر على أن يقول "كن فيكون"؟ الجواب أن الله يعلّم عباده التأني والتدبير. فإذا كان الخالق القدير لم يعجل في خلقه مع قدرته المطلقة، فكيف بالمخلوق الضعيف؟ هذا درس في التخطيط والصبر مبثوث في بنية الكون ذاتها.',
    insight_en: 'Al-Samarrai poses a profound question: why did Allah create the heavens and earth in six days when He could simply say "Be" and it would be? The answer is that Allah teaches His servants deliberation and planning. If the All-Powerful Creator did not rush His creation despite His absolute ability, then how should the weak creature behave? This is a lesson in patience and planning embedded in the very structure of the universe.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'لمسات بيانية في نصوص من التنزيل',
    source_en: 'Linguistic Touches in Quranic Texts',
    source_type: 'book'
  },
  {
    id: 2,
    verse_ref: '12:4',
    verse_ar: 'إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَا أَبَتِ إِنِّي رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًا وَالشَّمْسَ وَالْقَمَرَ رَأَيْتُهُمْ لِي سَاجِدِينَ',
    topic_ar: 'لماذا "كوكباً" وليس "نجماً"؟',
    topic_en: 'Why "planets" and not "stars"?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يلاحظ ابن عاشور أن القرآن استخدم "كوكباً" بدل "نجماً" في رؤيا يوسف. الكواكب تستمد نورها من غيرها (الشمس)، بينما النجوم مضيئة بذاتها. وهذا يناسب أن الإخوة يستمدون شرفهم من أبيهم يعقوب (الشمس في الرؤيا)، فهم تابعون لا أصول. الدقة في اختيار اللفظ تعكس حقيقة كونية لم تُعرف إلا حديثاً.',
    insight_en: 'Ibn Ashur observes that the Quran used "kawkab" (planet) rather than "najm" (star) in Yusuf\'s dream. Planets derive their light from another source (the sun), while stars are self-luminous. This fits perfectly: the brothers derive their honor from their father Ya\'qub (the sun in the dream) — they are dependents, not sources. The precision of this word choice reflects a cosmic reality that was only scientifically confirmed in modern times.',
    scholar_ar: 'ابن عاشور',
    scholar_en: 'Ibn Ashur',
    source_ar: 'التحرير والتنوير',
    source_en: 'Al-Tahrir wa Al-Tanwir',
    source_type: 'tafsir'
  },
  {
    id: 3,
    verse_ref: '2:67',
    verse_ar: 'وَإِذْ قَالَ مُوسَىٰ لِقَوْمِهِ إِنَّ اللَّهَ يَأْمُرُكُمْ أَن تَذْبَحُوا بَقَرَةً',
    topic_ar: 'لماذا سُمّيت أطول سورة باسم "البقرة"؟',
    topic_en: 'Why is the longest surah named "The Cow"?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يبيّن سيد قطب أن تسمية أطول سور القرآن بـ"البقرة" ليست عشوائية. قصة البقرة تكشف طبيعة بني إسرائيل في التلكؤ والمماطلة في تنفيذ أمر الله، إذ سألوا سؤالاً بعد سؤال بدل الامتثال الفوري. هذا النموذج يقابل استجابة المسلمين المطلوبة: "سمعنا وأطعنا". السورة كلها تدور حول هذا المحور: الاستجابة لأمر الله.',
    insight_en: 'Sayyid Qutb explains that naming the longest surah "The Cow" is not arbitrary. The cow story exposes the nature of the Children of Israel in their procrastination and evasion of God\'s command — they kept asking question after question instead of simply obeying. This pattern contrasts with the expected Muslim response: "We hear and we obey." The entire surah revolves around this axis: responding to God\'s command.',
    scholar_ar: 'سيد قطب',
    scholar_en: 'Sayyid Qutb',
    source_ar: 'في ظلال القرآن',
    source_en: 'In the Shade of the Quran',
    source_type: 'tafsir'
  },
  {
    id: 4,
    verse_ref: '18:9',
    verse_ar: 'أَمْ حَسِبْتَ أَنَّ أَصْحَابَ الْكَهْفِ وَالرَّقِيمِ كَانُوا مِنْ آيَاتِنَا عَجَبًا',
    topic_ar: 'لماذا "أم حسبتَ" في أصحاب الكهف؟',
    topic_en: 'Why "Or did you think" about the People of the Cave?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يشير الشعراوي إلى أن الله افتتح قصة أهل الكهف بقوله "أم حسبت" وكأنه يقول للنبي: لا تظن أن هذه القصة هي أعجب آياتي. فمن خلق السماوات والأرض وأحيا الموتى، ليس بعجيب عليه أن يُنيم فتية ثلاثمئة سنة. التعجب الحقيقي ينبغي أن يكون من عظمة الخالق لا من تفاصيل القصة.',
    insight_en: 'Al-Sha\'rawi points out that Allah opens the Cave story with "Or did you think" — as if telling the Prophet: do not consider this story the most wondrous of My signs. For the One who created the heavens and earth and gives life to the dead, putting youths to sleep for three hundred years is not remarkable. True wonder should be directed at the Creator\'s greatness, not at the details of the story.',
    scholar_ar: 'الشعراوي',
    scholar_en: 'Al-Sha\'rawi',
    source_ar: 'خواطر الشعراوي',
    source_en: 'Al-Sha\'rawi\'s Reflections',
    source_type: 'tafsir'
  },
  {
    id: 5,
    verse_ref: '6:76',
    verse_ar: 'فَلَمَّا جَنَّ عَلَيْهِ اللَّيْلُ رَأَىٰ كَوْكَبًا ۖ قَالَ هَٰذَا رَبِّي',
    topic_ar: 'هل شك إبراهيم في ربه حين قال "هذا ربي"؟',
    topic_en: 'Did Ibrahim doubt God when he said "This is my Lord"?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يوضح الطبري أن إبراهيم لم يكن يشك في ربه، بل كان يناظر قومه بأسلوب الاحتجاج. تقدير الكلام: "أهذا ربي؟" على سبيل الإنكار والتوبيخ. وهذا أسلوب بلاغي معروف في العربية حيث يُحذف حرف الاستفهام. إبراهيم كان يقود قومه خطوة بخطوة ليُريهم بأنفسهم أن ما يعبدونه باطل — وهو منهج دعوي بالغ الحكمة.',
    insight_en: 'Al-Tabari clarifies that Ibrahim was not doubting his Lord but was debating his people using the rhetorical method of argumentation. The implied meaning is "Is this my Lord?" — said in denial and rebuke. This is a well-known Arabic rhetorical device where the question particle is omitted. Ibrahim was leading his people step by step to see for themselves that what they worshipped was false — an extraordinarily wise method of calling to truth.',
    scholar_ar: 'الطبري',
    scholar_en: 'Al-Tabari',
    source_ar: 'جامع البيان عن تأويل آي القرآن',
    source_en: 'Jami\' Al-Bayan',
    source_type: 'tafsir'
  },
  {
    id: 6,
    verse_ref: '39:53',
    verse_ar: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا',
    topic_ar: 'لماذا "عبادي" وليس "الذين أسرفوا"؟',
    topic_en: 'Why "My servants" and not just "those who transgressed"?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يلفت السعدي النظر إلى أن الله قال "يا عبادي" قبل وصفهم بالإسراف. هذه الإضافة "عبادي" تحمل تكريماً وتطميناً: فهم رغم ذنوبهم لا يزالون عبيده المنسوبين إليه. ولم يقل "يا أيها المسرفون" بل ناداهم بأحب الأسماء إليهم. هذا من رحمة الله في خطابه للعاصين: يفتح لهم باب الأمل قبل أن يذكّرهم بخطئهم.',
    insight_en: 'Al-Sa\'di draws attention to Allah saying "My servants" before describing them as transgressors. This possessive attribution "My servants" carries honor and reassurance: despite their sins, they are still His servants, attributed to Him. He did not say "O you transgressors" but called them by the most beloved title. This reflects Allah\'s mercy in addressing sinners: He opens the door of hope before reminding them of their error.',
    scholar_ar: 'السعدي',
    scholar_en: 'Al-Sa\'di',
    source_ar: 'تيسير الكريم الرحمن في تفسير كلام المنان',
    source_en: 'Taysir Al-Karim Al-Rahman',
    source_type: 'tafsir'
  },
  {
    id: 7,
    verse_ref: '93:3',
    verse_ar: 'مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ',
    topic_ar: 'لماذا لم يقل "وما قلاك"؟',
    topic_en: 'Why did Allah not say "and He has not hated you"?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يلاحظ الزمخشري دقة بيانية بالغة: قال "ودّعك" بالضمير المتصل لكنه قال "قلى" بدون ضمير. في "ودّعك" ذكر المخاطب لأن التوديع فيه مواجهة ولطف. أما "قلى" (أبغض) فحذف الضمير تأدباً مع النبي، فلم يُضف فعل البغض إلى ضمير النبي مباشرة. حتى في النفي، تأدّب اللفظ القرآني مع مقام النبوة.',
    insight_en: 'Al-Zamakhshari notices an exquisite subtlety: Allah said "waddaAAaka" (bid you farewell) with the attached pronoun, but said "qala" (hated) without it. In "waddaAAaka," the addressee is mentioned because bidding farewell involves facing someone with kindness. But "qala" (hated) drops the pronoun out of courtesy to the Prophet — the act of hatred is not directly attached to the Prophet\'s pronoun. Even in negation, the Quranic wording maintains courtesy with the station of Prophethood.',
    scholar_ar: 'الزمخشري',
    scholar_en: 'Al-Zamakhshari',
    source_ar: 'الكشاف عن حقائق غوامض التنزيل',
    source_en: 'Al-Kashshaf',
    source_type: 'tafsir'
  },
  {
    id: 8,
    verse_ref: '20:40',
    verse_ar: 'إِذْ تَمْشِي أُخْتُكَ فَتَقُولُ هَلْ أَدُلُّكُمْ عَلَىٰ مَن يَكْفُلُهُ ۖ فَرَجَعْنَاكَ إِلَىٰ أُمِّكَ كَيْ تَقَرَّ عَيْنُهَا وَلَا تَحْزَنَ',
    topic_ar: 'لماذا "تقرّ عينها" وليس "تفرح"؟',
    topic_en: 'Why "her eye may be cooled" not "she may be happy"?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يبيّن السامرائي أن "قرّة العين" أبلغ من مجرد الفرح. العين التي تبكي تكون حارّة، فإذا استقرّت وبردت دلّ ذلك على زوال الحزن واستقرار النفس. أم موسى كانت تبكي على فراق ابنها، فالتعبير بـ"تقرّ عينها" يناسب حالتها تماماً: سكون بعد اضطراب، وبرد بعد حرارة الدمع. القرآن يختار التعبير الذي يصف الحالة النفسية بدقة طبية.',
    insight_en: 'Al-Samarrai explains that "cooling of the eye" is more eloquent than mere happiness. A weeping eye is hot, so when it settles and cools, it indicates the removal of grief and inner peace. Musa\'s mother was crying over separation from her son, so "cooling her eye" perfectly matches her state: calm after turmoil, coolness after the heat of tears. The Quran selects the expression that describes the psychological state with almost medical precision.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'التعبير القرآني',
    source_en: 'Quranic Expression',
    source_type: 'book'
  },
  {
    id: 9,
    verse_ref: '17:23',
    verse_ar: 'وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا ۚ إِمَّا يَبْلُغَنَّ عِندَكَ الْكِبَرَ أَحَدُهُمَا أَوْ كِلَاهُمَا فَلَا تَقُل لَّهُمَا أُفٍّ',
    topic_ar: 'لماذا جاء النهي عن "أفّ" وليس عن الضرب؟',
    topic_en: 'Why forbid saying "uff" rather than forbidding hitting?',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يشرح القرطبي أن النهي عن أقل درجات الأذى ("أفّ") ينطوي على النهي عن كل ما فوقها من باب أَولى. فإذا حُرّم التأفف حُرّم الضرب والشتم والعقوق من باب أحرى. هذا أسلوب بلاغي قرآني يسمى "دلالة الأَولى": ذكر الأدنى لينبّه على الأعلى. في كلمة واحدة "أفّ" اختصر القرآن قانوناً كاملاً لحقوق الوالدين.',
    insight_en: 'Al-Qurtubi explains that prohibiting the smallest degree of harm ("uff") inherently prohibits everything greater by logical priority. If even a sigh of annoyance is forbidden, then hitting, insulting, and disobedience are even more so. This is a Quranic rhetorical method called "dalaalat al-awla" (a fortiori reasoning): mentioning the lesser to alert to the greater. In one word — "uff" — the Quran encapsulated an entire law of parental rights.',
    scholar_ar: 'القرطبي',
    scholar_en: 'Al-Qurtubi',
    source_ar: 'الجامع لأحكام القرآن',
    source_en: 'Al-Jami\' li Ahkam Al-Quran',
    source_type: 'tafsir'
  },
  {
    id: 10,
    verse_ref: '49:6',
    verse_ar: 'يَا أَيُّهَا الَّذِينَ آمَنُوا إِن جَاءَكُمْ فَاسِقٌ بِنَبَإٍ فَتَبَيَّنُوا أَن تُصِيبُوا قَوْمًا بِجَهَالَةٍ فَتُصْبِحُوا عَلَىٰ مَا فَعَلْتُمْ نَادِمِينَ',
    topic_ar: 'منهج التثبت من الأخبار في القرآن',
    topic_en: 'The Quranic method of verifying news',
    cat: 'wisdom',
    cat_ar: 'حكمة إلهية',
    insight_ar: 'يبيّن ابن كثير أن هذه الآية أصّلت منهجاً إعلامياً كاملاً قبل الصحافة بقرون. لم يقل القرآن "لا تصدّقوا" بل قال "تبيّنوا" — أي تحققوا واستوثقوا. وعلّل ذلك بنتيجتين: إصابة قوم بجهالة (ضرر الغير) والندم (ضرر النفس). هذا المنهج يجعل المسلم مسؤولاً عن كل خبر ينقله، وهو أساس ما يسمى اليوم "التحقق من المصادر".',
    insight_en: 'Ibn Kathir explains that this verse established a complete media methodology centuries before journalism existed. The Quran did not say "do not believe" but said "verify" — meaning investigate and confirm. It justified this with two consequences: harming people through ignorance (harm to others) and regret (harm to self). This methodology makes every Muslim responsible for every piece of news they transmit — the foundation of what is now called "source verification."',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },

  // ═══════════════════════════════════════════════════════════════
  // LINGUISTIC (إعجاز لغوي) — Arabic linguistic miracles
  // ═══════════════════════════════════════════════════════════════

  {
    id: 11,
    verse_ref: '55:13',
    verse_ar: 'فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ',
    topic_ar: 'لماذا تتكرر "فبأيّ آلاء ربكما تكذبان" 31 مرة؟',
    topic_en: 'Why is "Which of your Lord\'s favors will you deny" repeated 31 times?',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يبيّن السامرائي أن التكرار في سورة الرحمن ليس تكراراً فارغاً بل هو كالّلازمة الموسيقية (refrain) التي تتغير دلالتها بتغيّر السياق. بعد ذكر نعم الدنيا يأتي التكرار توبيخاً، وبعد ذكر أهوال القيامة يأتي تخويفاً، وبعد ذكر نعيم الجنة يأتي تشويقاً وتحبيباً. فكل تكرار يحمل نبرة مختلفة. والعدد 31 يقسم السورة إلى ثلاثة مقاطع متوازنة.',
    insight_en: 'Al-Samarrai explains that the repetition in Surah Al-Rahman is not empty repetition but functions like a musical refrain whose meaning shifts with context. After mentioning worldly blessings, the repetition is a rebuke; after describing the horrors of Judgment Day, it becomes a warning; after describing Paradise, it becomes an enticement. Each repetition carries a different tone. The number 31 divides the surah into three balanced sections.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'لمسات بيانية في نصوص من التنزيل',
    source_en: 'Linguistic Touches in Quranic Texts',
    source_type: 'book'
  },
  {
    id: 12,
    verse_ref: '2:255',
    verse_ar: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ',
    topic_ar: 'البناء اللغوي لآية الكرسي',
    topic_en: 'The linguistic structure of Ayat Al-Kursi',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يحلل السامرائي آية الكرسي لغوياً فيجد بناءً فريداً: تبدأ بالإثبات (الله)، ثم النفي (لا إله إلا هو)، ثم الإثبات (الحي القيوم)، ثم النفي (لا تأخذه سنة)، وهكذا تتناوب بين النفي والإثبات. هذا التناوب يخلق إيقاعاً يشبه نبض القلب: إثبات-نفي، إثبات-نفي. وكل نفي يمهّد للإثبات الذي يليه، وكل إثبات يزداد قوة بالنفي الذي سبقه. لذلك هي أعظم آية في القرآن.',
    insight_en: 'Al-Samarrai analyzes Ayat Al-Kursi linguistically and finds a unique structure: it begins with affirmation (Allah), then negation (no deity except Him), then affirmation (the Ever-Living, Sustainer), then negation (neither drowsiness overtakes Him), alternating throughout. This alternation creates a rhythm like a heartbeat: affirmation-negation, affirmation-negation. Each negation prepares for the next affirmation, and each affirmation gains power from the preceding negation. This is why it is the greatest verse in the Quran.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'التعبير القرآني',
    source_en: 'Quranic Expression',
    source_type: 'book'
  },
  {
    id: 13,
    verse_ref: '19:4',
    verse_ar: 'قَالَ رَبِّ إِنِّي وَهَنَ الْعَظْمُ مِنِّي وَاشْتَعَلَ الرَّأْسُ شَيْبًا',
    topic_ar: '"اشتعل الرأس شيباً" — لماذا استعارة النار؟',
    topic_en: '"The head has ignited with white hair" — why the fire metaphor?',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يحلل الزمخشري هذه الاستعارة البديعة: الشيب في الرأس كاشتعال النار في الفحم. فكما تبدأ النار في نقطة ثم تنتشر حتى تعمّ الرأس كله، كذلك الشيب. واستخدام "اشتعل" بدل "ابيضّ" يضيف بُعد السرعة والانتشار الذي لا يمكن إيقافه. وقوله "الرأس" بالألف واللام للاستغراق: أي عمّ الرأس كله. في أربع كلمات رسم القرآن صورة كاملة للشيخوخة.',
    insight_en: 'Al-Zamakhshari analyzes this stunning metaphor: white hair on the head is like fire igniting charcoal. Just as fire starts at one point then spreads until it covers the entire surface, so does gray hair. Using "ignited" instead of "turned white" adds the dimension of speed and unstoppable spread. The definite article on "the head" indicates totality — it has engulfed the entire head. In four words, the Quran painted a complete portrait of old age.',
    scholar_ar: 'الزمخشري',
    scholar_en: 'Al-Zamakhshari',
    source_ar: 'الكشاف عن حقائق غوامض التنزيل',
    source_en: 'Al-Kashshaf',
    source_type: 'tafsir'
  },
  {
    id: 14,
    verse_ref: '11:44',
    verse_ar: 'وَقِيلَ يَا أَرْضُ ابْلَعِي مَاءَكِ وَيَا سَمَاءُ أَقْلِعِي وَغِيضَ الْمَاءُ وَقُضِيَ الْأَمْرُ وَاسْتَوَتْ عَلَى الْجُودِيِّ',
    topic_ar: 'أبلغ آية في العربية',
    topic_en: 'The most eloquent verse in Arabic',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يروي ابن كثير عن العلماء أن هذه الآية هي أبلغ آية في القرآن. فيها خمسة أوامر وأخبار متتالية في سطر واحد: أمر الأرض، أمر السماء، غيض الماء، قضاء الأمر، استواء السفينة. والتوازن بين "ابلعي" و"أقلعي" من أعجب ما في العربية. والبناء للمجهول "غيض" و"قُضي" يدل على عظمة الفاعل الذي لا يحتاج أن يُذكر. في سطر واحد انتهى طوفان ابتلع العالم.',
    insight_en: 'Ibn Kathir relates that scholars consider this the most eloquent verse in the Quran. It contains five consecutive commands and reports in a single line: commanding the earth, commanding the sky, the receding of water, the decree being fulfilled, and the ship settling. The parallelism between "ibla\'i" (swallow) and "aqli\'i" (cease) is among the most stunning in Arabic. The passive constructions "ghida" and "qudiya" indicate the grandeur of the Actor who needs no mention. In one line, a flood that swallowed the world was concluded.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 15,
    verse_ref: '36:36',
    verse_ar: 'سُبْحَانَ الَّذِي خَلَقَ الْأَزْوَاجَ كُلَّهَا مِمَّا تُنبِتُ الْأَرْضُ وَمِنْ أَنفُسِهِمْ وَمِمَّا لَا يَعْلَمُونَ',
    topic_ar: '"الأزواج كلها" — الزوجية في كل شيء',
    topic_en: '"All pairs" — duality in everything',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يشير ابن عاشور إلى أن لفظ "الأزواج" يشمل ثلاث دوائر متسعة: ما تنبته الأرض (النبات)، ومن أنفسهم (الإنسان والحيوان)، ومما لا يعلمون (ما لم يُكتشف بعد). العبارة الأخيرة نبوءة مفتوحة: فقد اكتشف العلم الزوجية في الذرة (بروتون وإلكترون)، وفي الكهرباء (موجب وسالب)، وفي المادة (مادة ومادة مضادة). "مما لا يعلمون" تتسع مع كل اكتشاف جديد.',
    insight_en: 'Ibn Ashur notes that "pairs" encompasses three expanding circles: what the earth grows (plants), from themselves (humans and animals), and from what they do not know (the undiscovered). The last phrase is an open prophecy: science has since discovered pairing in atoms (protons and electrons), in electricity (positive and negative), and in matter (matter and antimatter). "From what they do not know" expands with every new discovery.',
    scholar_ar: 'ابن عاشور',
    scholar_en: 'Ibn Ashur',
    source_ar: 'التحرير والتنوير',
    source_en: 'Al-Tahrir wa Al-Tanwir',
    source_type: 'tafsir'
  },
  {
    id: 16,
    verse_ref: '56:63',
    verse_ar: 'أَفَرَأَيْتُم مَّا تَحْرُثُونَ ۝ أَأَنتُمْ تَزْرَعُونَهُ أَمْ نَحْنُ الزَّارِعُونَ',
    topic_ar: 'الفرق بين "الحرث" و"الزرع"',
    topic_en: 'The difference between "plowing" and "growing"',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يلاحظ السامرائي دقة التفريق بين "تحرثون" و"تزرعون": نسب الحرث للبشر لأنه فعلهم الظاهر (حرث الأرض ووضع البذور)، لكن نسب الزرع لله لأن الإنبات الحقيقي من الله وحده. فالإنسان يحرث ويبذر لكنه لا يملك أن يُنبت. هذا تفريق بين السبب الظاهري والفاعل الحقيقي. في كلمتين فصل القرآن بين جهد الإنسان وقدرة الله.',
    insight_en: 'Al-Samarrai observes the precision in distinguishing "you plow" from "you make it grow": plowing is attributed to humans because it is their visible action (tilling the soil and placing seeds), but growing is attributed to Allah because actual germination belongs to God alone. A person plows and sows but cannot make things sprout. This separates the apparent cause from the true Actor. In two words, the Quran distinguished between human effort and divine power.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'لمسات بيانية في نصوص من التنزيل',
    source_en: 'Linguistic Touches in Quranic Texts',
    source_type: 'book'
  },
  {
    id: 17,
    verse_ref: '3:159',
    verse_ar: 'فَبِمَا رَحْمَةٍ مِّنَ اللَّهِ لِنتَ لَهُمْ ۖ وَلَوْ كُنتَ فَظًّا غَلِيظَ الْقَلْبِ لَانفَضُّوا مِنْ حَوْلِكَ',
    topic_ar: 'لماذا "انفضّوا" وليس "ابتعدوا"؟',
    topic_en: 'Why "scattered" and not "distanced"?',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يبيّن الزمخشري أن "انفضّوا" من الفضّ وهو التفرّق بسرعة وعنف، كانفضاض الماء. بينما "ابتعدوا" فيها تدرج وهدوء. اختيار "انفضّوا" يدل على أن القسوة في القيادة لا تؤدي إلى انصراف هادئ بل إلى تشتت سريع وعنيف. وهذا درس في القيادة: اللين يجمع الناس كما يجمع المغناطيس الحديد، والفظاظة تفرّقهم كما يتناثر الماء.',
    insight_en: 'Al-Zamakhshari explains that "infaddu" comes from "fadd" meaning to scatter rapidly and violently, like water splashing apart, whereas "ib\'tadu" (distanced) implies gradual, calm departure. Choosing "infaddu" indicates that harshness in leadership does not lead to quiet withdrawal but to rapid, violent scattering. This is a leadership lesson: gentleness gathers people as a magnet gathers iron, while harshness scatters them like water splashing apart.',
    scholar_ar: 'الزمخشري',
    scholar_en: 'Al-Zamakhshari',
    source_ar: 'الكشاف عن حقائق غوامض التنزيل',
    source_en: 'Al-Kashshaf',
    source_type: 'tafsir'
  },
  {
    id: 18,
    verse_ref: '68:1',
    verse_ar: 'ن ۚ وَالْقَلَمِ وَمَا يَسْطُرُونَ',
    topic_ar: 'الحروف المقطعة — سر "ن" في سورة القلم',
    topic_en: 'The disconnected letters — the mystery of "Nun"',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يذكر الطبري عدة أقوال في الحروف المقطعة، منها أنها تنبيه للسامع وإشعار بإعجاز القرآن: هذه هي حروفكم ذاتها، فأتوا بمثله إن استطعتم. وفي "نون" خاصة يرى بعض المفسرين أنها الدواة (المحبرة)، فيكون القسم: بالدواة والقلم وما يكتبون. هذا إعلاء لشأن العلم والكتابة في أول ما نزل: اقرأ، وفي القسم بأدوات الكتابة.',
    insight_en: 'Al-Tabari mentions several views on the disconnected letters, among them that they alert the listener and signal the Quran\'s inimitability: these are your very own letters, so produce something like it if you can. Regarding "Nun" specifically, some scholars hold it refers to the inkwell, making the oath: by the inkwell, the pen, and what they write. This elevates knowledge and writing — consistent with the first revelation "Read" and the oath by writing instruments.',
    scholar_ar: 'الطبري',
    scholar_en: 'Al-Tabari',
    source_ar: 'جامع البيان عن تأويل آي القرآن',
    source_en: 'Jami\' Al-Bayan',
    source_type: 'tafsir'
  },
  {
    id: 19,
    verse_ref: '54:1',
    verse_ar: 'اقْتَرَبَتِ السَّاعَةُ وَانشَقَّ الْقَمَرُ',
    topic_ar: 'لماذا "اقتربت" بصيغة الماضي؟',
    topic_en: 'Why "has drawn near" in past tense?',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يبيّن ابن عاشور أن استخدام الماضي "اقتربت" بدل المضارع "تقترب" يفيد التحقق واليقين. في العربية يُعبَّر عن المستقبل المؤكد بصيغة الماضي كأنه وقع فعلاً. فالقيامة في علم الله كأنها وقعت بالفعل. وهذا أسلوب يقطع الشك ويزيل التسويف: ليست مسألة "هل" ستقع بل "قد" وقعت في علم الله المحيط بالزمان.',
    insight_en: 'Ibn Ashur explains that using the past tense "has drawn near" instead of the present "is drawing near" conveys certainty and inevitability. In Arabic, the confirmed future is expressed in past tense as if it has already occurred. The Hour in God\'s knowledge is as good as having already happened. This style eliminates doubt and procrastination: it is not a question of "whether" it will happen but that it "has" happened in the knowledge of the One who encompasses all time.',
    scholar_ar: 'ابن عاشور',
    scholar_en: 'Ibn Ashur',
    source_ar: 'التحرير والتنوير',
    source_en: 'Al-Tahrir wa Al-Tanwir',
    source_type: 'tafsir'
  },
  {
    id: 20,
    verse_ref: '2:187',
    verse_ar: 'هُنَّ لِبَاسٌ لَّكُمْ وَأَنتُمْ لِبَاسٌ لَّهُنَّ',
    topic_ar: '"هنّ لباس لكم" — أعمق وصف للزواج',
    topic_en: '"They are garments for you" — the deepest description of marriage',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يتأمل سيد قطب في تشبيه الزوجين باللباس فيجد فيه أبعاداً متعددة: اللباس يستر (ستر العيوب)، ويدفئ (الحنان)، ويُجمّل (الزينة)، ويلاصق الجسد (القرب)، ولا يستغني عنه أحد (الحاجة المتبادلة). وجعل الوصف متبادلاً: "هنّ لباس لكم وأنتم لباس لهن" — أي المساواة في هذه الوظائف. في كلمة واحدة "لباس" جمع القرآن ميثاق الزواج كله.',
    insight_en: 'Sayyid Qutb reflects on comparing spouses to garments and finds multiple dimensions: garments conceal (covering faults), warm (tenderness), beautify (adornment), cling to the body (closeness), and are indispensable (mutual need). The description is reciprocal: "they are garments for you and you are garments for them" — meaning equality in all these functions. In one word — "garment" — the Quran encapsulated the entire covenant of marriage.',
    scholar_ar: 'سيد قطب',
    scholar_en: 'Sayyid Qutb',
    source_ar: 'في ظلال القرآن',
    source_en: 'In the Shade of the Quran',
    source_type: 'tafsir'
  },
  {
    id: 21,
    verse_ref: '12:31',
    verse_ar: 'فَلَمَّا رَأَيْنَهُ أَكْبَرْنَهُ وَقَطَّعْنَ أَيْدِيَهُنَّ',
    topic_ar: '"أكبرنه" — لماذا لم يقل "أُعجبن به"؟',
    topic_en: '"Akbarnahu" — why not "they were impressed"?',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يلاحظ السامرائي أن "أكبرنه" أبلغ من "أعجبن به" أو "استحسنّه". فعل "أكبر" يدل على أن جمال يوسف كان أكبر من تصورهن، فذُهلن وعظُم عليهن الأمر حتى فقدن الوعي بأيديهن فقطّعنها. ولو قال "أعجبن" لدلّ على إعجاب عادي. لكن "أكبرنه" يعني أن جماله تجاوز كل ما عرفنه، فصدمهن الجمال صدمة جعلتهن لا يشعرن بالألم.',
    insight_en: 'Al-Samarrai observes that "akbarnahu" (they were overwhelmed by his greatness) is more powerful than "they were impressed." The verb "akbara" indicates that Yusuf\'s beauty exceeded their imagination, stunning them to the point of losing awareness of their hands and cutting them. Had it said "they admired," it would indicate normal admiration. But "akbarnahu" means his beauty surpassed everything they had known — the shock of beauty made them unable to feel pain.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'التعبير القرآني',
    source_en: 'Quranic Expression',
    source_type: 'book'
  },
  {
    id: 22,
    verse_ref: '24:35',
    verse_ar: 'اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ ۚ مَثَلُ نُورِهِ كَمِشْكَاةٍ فِيهَا مِصْبَاحٌ',
    topic_ar: 'تشبيه نور الله بالمشكاة — أعقد تشبيه في القرآن',
    topic_en: 'The Light Parable — the most complex simile in the Quran',
    cat: 'linguistic',
    cat_ar: 'إعجاز لغوي',
    insight_ar: 'يحلل الزمخشري آية النور فيجد تشبيهاً مركّباً من خمس طبقات: المشكاة (الكوة في الجدار تركّز الضوء)، فيها مصباح، المصباح في زجاجة، الزجاجة كأنها كوكب درّي، يوقد من شجرة زيتونة. كل طبقة تُضاعف النور. وقوله "لا شرقية ولا غربية" أي تتلقى الشمس من كل الجهات فزيتها أنقى ما يكون. هذا التشبيه المتداخل لا نظير له في أدب أي لغة.',
    insight_en: 'Al-Zamakhshari analyzes the Light Verse and finds a compound simile of five layers: the niche (a wall alcove that concentrates light), containing a lamp, the lamp within glass, the glass like a radiant star, fueled by a blessed olive tree. Each layer multiplies the light. "Neither eastern nor western" means it receives sun from all directions, producing the purest oil. This nested simile has no parallel in the literature of any language.',
    scholar_ar: 'الزمخشري',
    scholar_en: 'Al-Zamakhshari',
    source_ar: 'الكشاف عن حقائق غوامض التنزيل',
    source_en: 'Al-Kashshaf',
    source_type: 'tafsir'
  },

  // ═══════════════════════════════════════════════════════════════
  // SCIENTIFIC (إشارات علمية) — Scientific references
  // ═══════════════════════════════════════════════════════════════

  {
    id: 23,
    verse_ref: '57:25',
    verse_ar: 'وَأَنزَلْنَا الْحَدِيدَ فِيهِ بَأْسٌ شَدِيدٌ وَمَنَافِعُ لِلنَّاسِ',
    topic_ar: 'لماذا "أنزلنا" الحديد وليس "خلقنا"؟',
    topic_en: 'Why "sent down" iron and not "created"?',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يلاحظ العلماء المعاصرون أن القرآن استخدم "أنزلنا" مع الحديد وليس "خلقنا" أو "جعلنا". وقد أثبتت الفيزياء الفلكية الحديثة أن الحديد لم يتكوّن على الأرض بل تشكّل في قلب النجوم العملاقة عبر الاندماج النووي، ثم وصل إلى الأرض عبر النيازك والانفجارات النجمية. فالحديد حرفياً "أُنزل" من السماء. ابن كثير ذكر أن بعض السلف فسّروها بأن الحديد نزل من السماء.',
    insight_en: 'Contemporary scholars note that the Quran used "We sent down" with iron, not "We created" or "We made." Modern astrophysics has confirmed that iron did not form on Earth but was forged in the cores of giant stars through nuclear fusion, then reached Earth via meteorites and stellar explosions. Iron was literally "sent down" from the sky. Ibn Kathir mentions that some early scholars interpreted this as iron descending from the heavens.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 24,
    verse_ref: '21:30',
    verse_ar: 'أَوَلَمْ يَرَ الَّذِينَ كَفَرُوا أَنَّ السَّمَاوَاتِ وَالْأَرْضَ كَانَتَا رَتْقًا فَفَتَقْنَاهُمَا',
    topic_ar: '"رتقاً ففتقناهما" — الانفجار العظيم',
    topic_en: '"Were a joined entity then We separated them" — the Big Bang',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يفسر الطبري "رتقاً" بأنهما كانتا شيئاً واحداً ملتصقاً ثم فصل الله بينهما. وهذا يتوافق مع نظرية الانفجار العظيم (Big Bang) التي تقول إن الكون كله كان في نقطة واحدة شديدة الكثافة ثم انفجرت وتوسعت. لفظ "رتق" يعني الالتصاق بلا فراغ، و"فتق" يعني الفصل بقوة. الطبري لم يكن يعرف الفيزياء الحديثة لكنه فسّر اللفظ بما يطابقها تماماً.',
    insight_en: 'Al-Tabari interprets "ratqan" as the heavens and earth being a single, joined entity that Allah then separated. This aligns with the Big Bang theory, which states that the entire universe was a single point of extreme density that then exploded and expanded. "Ratq" means joining with no gap, and "fatq" means separating with force. Al-Tabari knew nothing of modern physics, yet his linguistic interpretation matches it precisely.',
    scholar_ar: 'الطبري',
    scholar_en: 'Al-Tabari',
    source_ar: 'جامع البيان عن تأويل آي القرآن',
    source_en: 'Jami\' Al-Bayan',
    source_type: 'tafsir'
  },
  {
    id: 25,
    verse_ref: '51:47',
    verse_ar: 'وَالسَّمَاءَ بَنَيْنَاهَا بِأَيْدٍ وَإِنَّا لَمُوسِعُونَ',
    topic_ar: '"وإنا لموسعون" — توسع الكون',
    topic_en: '"And indeed, We are its expander" — the expanding universe',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يذكر ابن كثير أن "لموسعون" تعني القدرة والسعة. لكن المعنى اللغوي المباشر لاسم الفاعل "موسعون" هو: نحن نقوم بالتوسيع الآن وباستمرار. وقد اكتشف إدوين هابل عام 1929 أن الكون يتوسع فعلاً، وأن المجرات تتباعد عن بعضها. صيغة اسم الفاعل في العربية تفيد الاستمرار، وهذا مطابق للحقيقة العلمية: الكون لا يزال يتوسع منذ الانفجار العظيم.',
    insight_en: 'Ibn Kathir mentions that "lamoosi\'oon" means possessing power and vastness. But the direct linguistic meaning of the active participle "moosi\'oon" is: We are continuously expanding it. Edwin Hubble discovered in 1929 that the universe is indeed expanding and galaxies are moving apart. The active participle in Arabic denotes continuous action — matching the scientific reality that the universe has been expanding since the Big Bang and continues to do so.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 26,
    verse_ref: '96:15',
    verse_ar: 'كَلَّا لَئِن لَّمْ يَنتَهِ لَنَسْفَعًا بِالنَّاصِيَةِ ۝ نَاصِيَةٍ كَاذِبَةٍ خَاطِئَةٍ',
    topic_ar: '"ناصية كاذبة خاطئة" — الفص الجبهي والكذب',
    topic_en: '"A lying, sinful forelock" — the frontal lobe and lying',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يفسر المفسرون القدامى "الناصية" بمقدمة الرأس. ووصفها بالكذب والخطأ مجاز عند القرطبي: أي صاحبها كاذب. لكن علم الأعصاب الحديث أثبت أن الفص الجبهي (prefrontal cortex) الواقع خلف الناصية مباشرة هو المسؤول عن اتخاذ القرارات والتخطيط والكذب. فوصف الناصية ذاتها بالكذب — وليس صاحبها — دقة علمية لم تُعرف إلا في القرن العشرين.',
    insight_en: 'Classical scholars interpret "nasiyah" (forelock) as the front of the head. Al-Qurtubi considered describing the forelock as "lying, sinful" to be figurative — meaning its owner is a liar. But modern neuroscience has confirmed that the prefrontal cortex, located directly behind the forelock, is responsible for decision-making, planning, and lying. Describing the forelock itself — not its owner — as lying is a scientific precision unknown until the twentieth century.',
    scholar_ar: 'القرطبي',
    scholar_en: 'Al-Qurtubi',
    source_ar: 'الجامع لأحكام القرآن',
    source_en: 'Al-Jami\' li Ahkam Al-Quran',
    source_type: 'tafsir'
  },
  {
    id: 27,
    verse_ref: '23:12',
    verse_ar: 'وَلَقَدْ خَلَقْنَا الْإِنسَانَ مِن سُلَالَةٍ مِّن طِينٍ',
    topic_ar: '"سُلالة" — دقة وصف استخلاص الإنسان',
    topic_en: '"Sulalah" — precision in describing human extraction',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يبيّن ابن عاشور أن "سُلالة" مشتقة من "سلّ" أي استخرج بلطف. فالإنسان لم يُخلق من الطين كله بل من خلاصة مستخرجة منه. وهذا يطابق ما يعرفه العلم: العناصر المكوّنة لجسم الإنسان (كربون، حديد، كالسيوم، فوسفور) هي ذات العناصر الموجودة في التربة، لكن بنسب دقيقة جداً مستخلصة بدقة. كلمة واحدة "سلالة" وصفت عملية كيميائية حيوية معقدة.',
    insight_en: 'Ibn Ashur explains that "sulalah" derives from "salla" meaning to extract gently. The human was not created from all clay but from a refined extract of it. This matches scientific knowledge: the elements composing the human body (carbon, iron, calcium, phosphorus) are the same elements found in soil, but in very precise, carefully extracted proportions. One word — "sulalah" — described a complex biochemical process.',
    scholar_ar: 'ابن عاشور',
    scholar_en: 'Ibn Ashur',
    source_ar: 'التحرير والتنوير',
    source_en: 'Al-Tahrir wa Al-Tanwir',
    source_type: 'tafsir'
  },
  {
    id: 28,
    verse_ref: '25:53',
    verse_ar: 'وَهُوَ الَّذِي مَرَجَ الْبَحْرَيْنِ هَٰذَا عَذْبٌ فُرَاتٌ وَهَٰذَا مِلْحٌ أُجَاجٌ وَجَعَلَ بَيْنَهُمَا بَرْزَخًا وَحِجْرًا مَّحْجُورًا',
    topic_ar: 'البرزخ بين البحرين — حاجز لا يُرى',
    topic_en: 'The barrier between two seas — an invisible partition',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يفسر ابن كثير "البرزخ" بالحاجز الذي يمنع اختلاط البحرين. وقد اكتشف علم المحيطات الحديث أن مياه البحار المختلفة في الملوحة والحرارة والكثافة لا تمتزج عند التقائها بل يتكوّن بينها حاجز مائي يسمّيه العلماء "منطقة الانتقال" (pycnocline). هذا الحاجز غير مرئي للعين لكنه يمنع الاختلاط فعلاً. القرآن وصفه بـ"حجراً محجوراً" أي منعاً مؤكداً بالتكرار.',
    insight_en: 'Ibn Kathir interprets "barzakh" as a barrier preventing the two seas from mixing. Modern oceanography has discovered that waters of different salinity, temperature, and density do not mix when they meet — instead, a water barrier called a "pycnocline" forms between them. This barrier is invisible to the eye but effectively prevents mixing. The Quran described it as "hijran mahjura" — an emphatic double prohibition, confirmed by repetition.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 29,
    verse_ref: '86:6',
    verse_ar: 'خُلِقَ مِن مَّاءٍ دَافِقٍ ۝ يَخْرُجُ مِن بَيْنِ الصُّلْبِ وَالتَّرَائِبِ',
    topic_ar: '"من بين الصلب والترائب" — أصل الجهاز التناسلي',
    topic_en: '"From between the backbone and ribs" — origin of the reproductive system',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يفسر الطبري "الصلب" بالظهر و"الترائب" بعظام الصدر. وقد أوضح علم الأجنّة أن الخصيتين تتكونان في مرحلة الجنين بين الكلية والعمود الفقري (بين الصلب والترائب) ثم تنزلان إلى مكانهما. كذلك الشرايين التي تغذي الجهاز التناسلي (الشريان الأبهر) تنشأ من هذه المنطقة تحديداً. فالآية تصف الأصل الجنيني للجهاز، لا موقعه النهائي.',
    insight_en: 'Al-Tabari interprets "sulb" as the backbone and "tara\'ib" as the chest bones. Embryology has shown that the testes form during the embryonic stage between the kidney and spinal column (between the backbone and ribs) before descending to their final position. Likewise, the arteries supplying the reproductive system (the aorta) originate from precisely this region. The verse describes the embryonic origin of the system, not its final location.',
    scholar_ar: 'الطبري',
    scholar_en: 'Al-Tabari',
    source_ar: 'جامع البيان عن تأويل آي القرآن',
    source_en: 'Jami\' Al-Bayan',
    source_type: 'tafsir'
  },
  {
    id: 30,
    verse_ref: '39:6',
    verse_ar: 'يَخْلُقُكُمْ فِي بُطُونِ أُمَّهَاتِكُمْ خَلْقًا مِّن بَعْدِ خَلْقٍ فِي ظُلُمَاتٍ ثَلَاثٍ',
    topic_ar: '"ظلمات ثلاث" — الأغشية الثلاثة للجنين',
    topic_en: '"Three darknesses" — the three membranes of the embryo',
    cat: 'scientific',
    cat_ar: 'إشارات علمية',
    insight_ar: 'يذكر ابن كثير عن المفسرين أن "الظلمات الثلاث" هي ظلمة البطن وظلمة الرحم وظلمة المشيمة. وهذا يتطابق مع علم الأجنّة الحديث الذي يحدد ثلاث طبقات تحيط بالجنين: جدار البطن (peritoneum)، وجدار الرحم (uterine wall)، والأغشية الجنينية (amniochorionic membrane). كل طبقة تشكّل حاجزاً ضوئياً مستقلاً — فالجنين فعلاً في ثلاث ظلمات متتالية.',
    insight_en: 'Ibn Kathir relates that scholars identify "the three darknesses" as the darkness of the abdomen, the uterus, and the placental membranes. This matches modern embryology, which identifies three layers surrounding the fetus: the abdominal wall (peritoneum), the uterine wall, and the amniochorionic membrane. Each layer forms an independent light barrier — the fetus is indeed in three sequential darknesses.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },

  // ═══════════════════════════════════════════════════════════════
  // HISTORICAL (سياق تاريخي) — Historical context / Asbab Al-Nuzul
  // ═══════════════════════════════════════════════════════════════

  {
    id: 31,
    verse_ref: '111:1',
    verse_ar: 'تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ',
    topic_ar: 'لماذا أبو لهب بالاسم في القرآن؟',
    topic_en: 'Why is Abu Lahab mentioned by name in the Quran?',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'يروي ابن كثير سبب النزول: حين صعد النبي على الصفا ونادى قريشاً محذّراً إياهم، ردّ عليه أبو لهب: "تبّاً لك ألهذا جمعتنا!" فنزلت السورة. والملفت أن القرآن تحدى أبا لهب أن يُسلم ليُكذب القرآن، فلو أسلم لقال الناس: القرآن كذب عليه. لكنه لم يُسلم حتى مات، فكان عدم إسلامه نفسه دليلاً على صدق النبوة.',
    insight_en: 'Ibn Kathir narrates the occasion of revelation: when the Prophet climbed Safa and warned the Quraysh, Abu Lahab retorted: "May you perish! Is this why you gathered us?" So the surah was revealed. Remarkably, the Quran implicitly challenged Abu Lahab to convert to disprove the Quran — had he converted, people would say the Quran lied about him. But he never converted until death, making his very refusal proof of the prophecy\'s truth.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 32,
    verse_ref: '9:40',
    verse_ar: 'إِلَّا تَنصُرُوهُ فَقَدْ نَصَرَهُ اللَّهُ إِذْ أَخْرَجَهُ الَّذِينَ كَفَرُوا ثَانِيَ اثْنَيْنِ إِذْ هُمَا فِي الْغَارِ',
    topic_ar: 'النبي وأبو بكر في الغار — لماذا "لا تحزن"؟',
    topic_en: 'The Prophet and Abu Bakr in the cave — why "do not grieve"?',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'يبيّن ابن كثير أن أبا بكر لم يكن خائفاً على نفسه بل على النبي. ولذلك قال النبي "لا تحزن" وليس "لا تخف". الحزن على الآخرين أرفع من الخوف على النفس. وقوله "إن الله معنا" بضمير الجمع يشمل أبا بكر في المعية الإلهية، وهذا أعلى تكريم له. السياق التاريخي يكشف أن اختيار الألفاظ مرتبط بالحالة النفسية الدقيقة للمخاطب.',
    insight_en: 'Ibn Kathir explains that Abu Bakr was not afraid for himself but for the Prophet. Thus the Prophet said "do not grieve" not "do not fear." Grief for others is nobler than fear for oneself. Saying "Allah is with us" with the plural pronoun includes Abu Bakr in the divine companionship — the highest honor for him. The historical context reveals that word choice is tied to the precise psychological state of the addressee.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 33,
    verse_ref: '66:1',
    verse_ar: 'يَا أَيُّهَا النَّبِيُّ لِمَ تُحَرِّمُ مَا أَحَلَّ اللَّهُ لَكَ ۖ تَبْتَغِي مَرْضَاتَ أَزْوَاجِكَ',
    topic_ar: 'الله يعاتب النبي — الشفافية المطلقة',
    topic_en: 'Allah rebukes the Prophet — absolute transparency',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'يروي الطبري أن هذه الآية نزلت حين حرّم النبي على نفسه شيئاً حلالاً إرضاءً لبعض أزواجه. وفي هذا دليل على صدق الوحي: لو كان النبي هو مؤلف القرآن لما وضع فيه عتاباً لنفسه أمام الناس جميعاً. هذا العتاب الإلهي العلني يثبت أن القرآن ليس من عند محمد، إذ لا يعقل أن يعاتب المرء نفسه في كتاب يؤلفه لإقناع الناس.',
    insight_en: 'Al-Tabari narrates that this verse was revealed when the Prophet forbade himself something permissible to please some of his wives. This is evidence of the revelation\'s authenticity: had the Prophet authored the Quran, he would not have included a public rebuke of himself before all people. This public divine reproach proves the Quran is not from Muhammad — it is inconceivable that someone would rebuke himself in a book he authored to convince others.',
    scholar_ar: 'الطبري',
    scholar_en: 'Al-Tabari',
    source_ar: 'جامع البيان عن تأويل آي القرآن',
    source_en: 'Jami\' Al-Bayan',
    source_type: 'tafsir'
  },
  {
    id: 34,
    verse_ref: '80:1',
    verse_ar: 'عَبَسَ وَتَوَلَّىٰ ۝ أَن جَاءَهُ الْأَعْمَىٰ',
    topic_ar: 'عتاب النبي بسبب الأعمى — لماذا الغائب لا المخاطب؟',
    topic_en: 'Rebuking the Prophet for the blind man — why third person?',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'يلاحظ الشعراوي أن الله قال "عبس وتولّى" بصيغة الغائب ولم يقل "عبستَ وتولّيتَ" بصيغة المخاطب. هذا تلطّف إلهي مع النبي في العتاب: ذكره بضمير الغيبة تأدباً ورفقاً، كأنه يتحدث عن شخص آخر. ثم إن سبب النزول يكشف قيمة إسلامية عظيمة: الناس سواء عند الله، والأعمى الفقير عبد الله بن أم مكتوم أولى من صناديد قريش.',
    insight_en: 'Al-Sha\'rawi observes that Allah said "He frowned and turned away" in the third person, not "You frowned and turned away" in the second person. This is divine gentleness in rebuke: referring to the Prophet in third person out of courtesy and kindness, as if speaking about someone else. The occasion of revelation further reveals a great Islamic value: all people are equal before God, and the blind, poor Abdullah ibn Umm Maktum takes priority over the chiefs of Quraysh.',
    scholar_ar: 'الشعراوي',
    scholar_en: 'Al-Sha\'rawi',
    source_ar: 'خواطر الشعراوي',
    source_en: 'Al-Sha\'rawi\'s Reflections',
    source_type: 'tafsir'
  },
  {
    id: 35,
    verse_ref: '33:37',
    verse_ar: 'وَتُخْفِي فِي نَفْسِكَ مَا اللَّهُ مُبْدِيهِ وَتَخْشَى النَّاسَ وَاللَّهُ أَحَقُّ أَن تَخْشَاهُ',
    topic_ar: '"تخفي في نفسك ما الله مبديه" — شفافية لا مثيل لها',
    topic_en: '"You concealed within yourself that which Allah was to disclose"',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'تروي عائشة رضي الله عنها أنه لو كان النبي كاتماً شيئاً من الوحي لكتم هذه الآية. فيها يكشف الله ما في نفس النبي ويعاتبه على خشية الناس. هذا أقوى دليل على أمانة النقل: النبي بلّغ آية تعرّيه أمام الناس. وكما يقول ابن كثير: أي عاقل يضع في كتابه ما يفضحه إلا أن يكون صادقاً في أن هذا ليس كتابه بل وحي ربه.',
    insight_en: 'Aisha narrated that if the Prophet were to conceal anything from revelation, he would have concealed this verse. In it, Allah reveals what was in the Prophet\'s heart and rebukes him for fearing people. This is the strongest evidence of faithful transmission: the Prophet delivered a verse that exposed him before all people. As Ibn Kathir notes: what rational person would include in his own book something that embarrasses him, unless he was truthful that it was not his book but his Lord\'s revelation?',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 36,
    verse_ref: '30:2',
    verse_ar: 'غُلِبَتِ الرُّومُ ۝ فِي أَدْنَى الْأَرْضِ وَهُم مِّن بَعْدِ غَلَبِهِمْ سَيَغْلِبُونَ',
    topic_ar: '"أدنى الأرض" — أخفض نقطة على وجه الأرض',
    topic_en: '"The lowest land" — the lowest point on Earth',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'يذكر الطبري أن "أدنى الأرض" تعني أقرب أرض الروم للعرب. لكن "أدنى" في العربية تحتمل أيضاً "أخفض". وقد وقعت المعركة بين الروم والفرس قرب البحر الميت الذي هو فعلاً أخفض نقطة على سطح الأرض (حوالي 430 متراً تحت سطح البحر). والقرآن تنبأ أيضاً بانتصار الروم في بضع سنين — وهو ما تحقق بالفعل بعد سبع سنوات.',
    insight_en: 'Al-Tabari states that "adna al-ard" means the nearest Roman land to the Arabs. But "adna" in Arabic also means "lowest." The battle between Rome and Persia occurred near the Dead Sea, which is indeed the lowest point on Earth (approximately 430 meters below sea level). The Quran also prophesied Rome\'s victory within a few years — which was fulfilled exactly seven years later.',
    scholar_ar: 'الطبري',
    scholar_en: 'Al-Tabari',
    source_ar: 'جامع البيان عن تأويل آي القرآن',
    source_en: 'Jami\' Al-Bayan',
    source_type: 'tafsir'
  },
  {
    id: 37,
    verse_ref: '105:1',
    verse_ar: 'أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ',
    topic_ar: 'عام الفيل — لماذا ذكرها القرآن بعد 40 سنة؟',
    topic_en: 'Year of the Elephant — why mention it 40 years later?',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'يبيّن سيد قطب أن سورة الفيل نزلت في مكة أي بعد نحو 40 سنة من الحادثة. القرآن يخاطب قريشاً: "ألم تر" — أي هذه حقيقة تعرفونها ورأيتم آثارها. كان الهدف تذكير قريش بأن الله الذي حمى الكعبة من أبرهة هو نفسه الذي أرسل محمداً. فكيف تحاربون من أرسله حامي البيت؟ السياق التاريخي يحوّل القصة من خبر ماضٍ إلى حجة حاضرة.',
    insight_en: 'Sayyid Qutb explains that Surah Al-Fil was revealed in Mecca, approximately 40 years after the event. The Quran addresses Quraysh: "Have you not seen" — meaning this is a reality you know and whose traces you witnessed. The purpose was reminding Quraysh that the God who protected the Ka\'ba from Abraha is the same God who sent Muhammad. How then do you fight against the one sent by the Protector of the House? Historical context transforms the story from past news into a present argument.',
    scholar_ar: 'سيد قطب',
    scholar_en: 'Sayyid Qutb',
    source_ar: 'في ظلال القرآن',
    source_en: 'In the Shade of the Quran',
    source_type: 'tafsir'
  },
  {
    id: 38,
    verse_ref: '48:27',
    verse_ar: 'لَّقَدْ صَدَقَ اللَّهُ رَسُولَهُ الرُّؤْيَا بِالْحَقِّ ۖ لَتَدْخُلُنَّ الْمَسْجِدَ الْحَرَامَ إِن شَاءَ اللَّهُ آمِنِينَ',
    topic_ar: 'صلح الحديبية — الهزيمة التي كانت نصراً',
    topic_en: 'Treaty of Hudaybiyyah — the defeat that was a victory',
    cat: 'historical',
    cat_ar: 'سياق تاريخي',
    insight_ar: 'يروي ابن كثير أن الصحابة حزنوا عند صلح الحديبية ظنّاً منهم أنه هزيمة. لكن القرآن سمّاه "فتحاً مبيناً" في أول سورة الفتح. وتحققت رؤيا النبي بدخول مكة في العام التالي. الدرس العميق: ما يبدو هزيمة قد يكون أعظم انتصار. الصلح أتاح للمسلمين نشر الإسلام بالسلم فدخل فيه أضعاف من دخل فيه بالحرب.',
    insight_en: 'Ibn Kathir narrates that the Companions were saddened by the Hudaybiyyah treaty, thinking it a defeat. But the Quran called it "a clear victory" at the start of Surah Al-Fath. The Prophet\'s vision of entering Mecca was fulfilled the following year. The deep lesson: what appears as defeat may be the greatest victory. The treaty allowed Muslims to spread Islam peacefully, and more people embraced it during the peace than during all prior wars combined.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },

  // ═══════════════════════════════════════════════════════════════
  // RHETORICAL (بلاغة قرآنية) — Rhetorical devices and literary beauty
  // ═══════════════════════════════════════════════════════════════

  {
    id: 39,
    verse_ref: '101:1',
    verse_ar: 'الْقَارِعَةُ ۝ مَا الْقَارِعَةُ ۝ وَمَا أَدْرَاكَ مَا الْقَارِعَةُ',
    topic_ar: 'أسلوب التهويل — "ما أدراك"',
    topic_en: 'The technique of magnification — "What will make you know?"',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يحلل السامرائي أسلوب "ما أدراك" الذي يتكرر في القرآن ويلاحظ قاعدة دقيقة: "ما أدراك" تأتي لما لا يعلمه أحد (كأهوال القيامة)، بينما "ما يدريك" بصيغة المضارع تأتي لما قد يقع في المستقبل (كالساعة). فالماضي في "أدراك" يقطع بعدم العلم، والمضارع في "يدريك" يبقي احتمال العلم مفتوحاً. هذا التمييز لم يلتفت إليه كثير من الدارسين.',
    insight_en: 'Al-Samarrai analyzes the recurring "what will make you know" and discovers a precise rule: "ma adraka" (past tense) is used for things no one can know (like the horrors of Judgment Day), while "ma yudrika" (present tense) is used for future possibilities (like the Hour). The past tense in "adraka" definitively negates knowledge, while the present in "yudrika" leaves the possibility open. This distinction has been overlooked by many scholars.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'التعبير القرآني',
    source_en: 'Quranic Expression',
    source_type: 'book'
  },
  {
    id: 40,
    verse_ref: '2:74',
    verse_ar: 'وَإِنَّ مِنَ الْحِجَارَةِ لَمَا يَتَفَجَّرُ مِنْهُ الْأَنْهَارُ ۚ وَإِنَّ مِنْهَا لَمَا يَشَّقَّقُ فَيَخْرُجُ مِنْهُ الْمَاءُ ۚ وَإِنَّ مِنْهَا لَمَا يَهْبِطُ مِنْ خَشْيَةِ اللَّهِ',
    topic_ar: 'تدرّج بلاغي: تفجّر، تشقّق، هبوط',
    topic_en: 'Rhetorical gradation: gushing, splitting, falling',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يلاحظ الزمخشري تدرجاً بلاغياً عجيباً: بدأ بالحجارة التي تتفجر منها الأنهار (أعلى درجة)، ثم التي تتشقق فيخرج منها الماء (درجة وسطى)، ثم التي تهبط من خشية الله (أدنى حركة). والمفارقة أن قلوب بني إسرائيل أقسى من هذه الحجارة كلها — فالحجارة تتأثر على تفاوتها، لكن تلك القلوب لا تتأثر البتة. التدرج يبني الحجة قبل أن يصل إلى المقارنة الصاعقة.',
    insight_en: 'Al-Zamakhshari notices a remarkable rhetorical gradation: starting with stones from which rivers gush (highest degree), then those that split and water flows (middle degree), then those that fall from fear of God (lowest motion). The irony is that the hearts of the Children of Israel are harder than all these stones — the stones respond to varying degrees, but those hearts do not respond at all. The gradation builds the argument before delivering the devastating comparison.',
    scholar_ar: 'الزمخشري',
    scholar_en: 'Al-Zamakhshari',
    source_ar: 'الكشاف عن حقائق غوامض التنزيل',
    source_en: 'Al-Kashshaf',
    source_type: 'tafsir'
  },
  {
    id: 41,
    verse_ref: '22:73',
    verse_ar: 'إِنَّ الَّذِينَ تَدْعُونَ مِن دُونِ اللَّهِ لَن يَخْلُقُوا ذُبَابًا وَلَوِ اجْتَمَعُوا لَهُ ۖ وَإِن يَسْلُبْهُمُ الذُّبَابُ شَيْئًا لَّا يَسْتَنقِذُوهُ مِنْهُ',
    topic_ar: 'التحدي بالذبابة — أسلوب التصغير',
    topic_en: 'The fly challenge — the technique of diminution',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يحلل ابن عاشور بلاغة هذه الآية: التحدي مزدوج ومتصاعد. أولاً: لا يستطيعون خلق ذبابة (أحقر المخلوقات). ثانياً والأعجب: لو سلبهم الذباب شيئاً لا يستطيعون استرداده. فالأصنام أعجز من الذبابة نفسها — لا يخلقونها ولا يغلبونها. وهذا أقوى أساليب التصغير: جعل المعبود أدنى من أحقر مخلوق، ثم أدنى من قدرة استرداد ما سلبه ذلك المخلوق الحقير.',
    insight_en: 'Ibn Ashur analyzes the rhetoric: the challenge is dual and escalating. First: they cannot create a fly (the lowliest creature). Second, more astonishing: if a fly snatched something from them, they could not retrieve it. The idols are weaker than the fly itself — they cannot create it nor overpower it. This is the most powerful diminution technique: making the object of worship lower than the most insignificant creature, then even lower than the ability to retrieve what that insignificant creature snatched.',
    scholar_ar: 'ابن عاشور',
    scholar_en: 'Ibn Ashur',
    source_ar: 'التحرير والتنوير',
    source_en: 'Al-Tahrir wa Al-Tanwir',
    source_type: 'tafsir'
  },
  {
    id: 42,
    verse_ref: '69:1',
    verse_ar: 'الْحَاقَّةُ ۝ مَا الْحَاقَّةُ ۝ وَمَا أَدْرَاكَ مَا الْحَاقَّةُ',
    topic_ar: 'تكرار الاسم ثلاثاً — أسلوب التعظيم',
    topic_en: 'Repeating the name thrice — the technique of magnification',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يبيّن السعدي أن تكرار "الحاقة" ثلاث مرات في ثلاث آيات متتالية يخلق تصاعداً دراماتيكياً: المرة الأولى تُلقي الاسم، والثانية تسأل عن ماهيته (تشويق)، والثالثة تؤكد أنه فوق إدراكك (تعظيم). هذا البناء الثلاثي يشبه ثلاث طرقات على الباب: كل طرقة أقوى من سابقتها. وهو يهيّئ السامع نفسياً قبل أن يسمع تفاصيل اليوم العظيم.',
    insight_en: 'Al-Sa\'di explains that repeating "Al-Haqqah" three times in three consecutive verses creates dramatic escalation: the first time introduces the name, the second asks about its nature (creating suspense), and the third confirms it is beyond comprehension (magnification). This threefold structure is like three knocks on a door, each louder than the last. It psychologically prepares the listener before they hear the details of the Great Day.',
    scholar_ar: 'السعدي',
    scholar_en: 'Al-Sa\'di',
    source_ar: 'تيسير الكريم الرحمن في تفسير كلام المنان',
    source_en: 'Taysir Al-Karim Al-Rahman',
    source_type: 'tafsir'
  },
  {
    id: 43,
    verse_ref: '27:44',
    verse_ar: 'قِيلَ لَهَا ادْخُلِي الصَّرْحَ ۖ فَلَمَّا رَأَتْهُ حَسِبَتْهُ لُجَّةً وَكَشَفَتْ عَن سَاقَيْهَا',
    topic_ar: 'قصر سليمان الزجاجي — إيجاز مذهل',
    topic_en: 'Solomon\'s glass palace — stunning conciseness',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يعجب الزمخشري من الإيجاز في وصف مشهد بلقيس: في جملة واحدة وصف القرآن القصر (الصرح)، وأرضيته الزجاجية الشفافة فوق الماء، وردة فعل بلقيس (حسبته لجة)، وفعلها (كشفت عن ساقيها)، وذكاء سليمان في تصميم هذا الاختبار. لو كتبها كاتب بشري لاحتاج صفحات. هذا الإيجاز يعطي القارئ المشهد كاملاً ويترك خياله يرسم التفاصيل.',
    insight_en: 'Al-Zamakhshari marvels at the conciseness in describing Bilqis\'s scene: in a single sentence, the Quran described the palace (sarh), its transparent glass floor over water, Bilqis\'s reaction (she thought it was a pool), her action (she uncovered her legs), and Solomon\'s cleverness in designing this test. A human writer would need pages. This conciseness gives the reader the complete scene while leaving their imagination to paint the details.',
    scholar_ar: 'الزمخشري',
    scholar_en: 'Al-Zamakhshari',
    source_ar: 'الكشاف عن حقائق غوامض التنزيل',
    source_en: 'Al-Kashshaf',
    source_type: 'tafsir'
  },
  {
    id: 44,
    verse_ref: '79:27',
    verse_ar: 'أَأَنتُمْ أَشَدُّ خَلْقًا أَمِ السَّمَاءُ ۚ بَنَاهَا',
    topic_ar: 'الاستفهام الإنكاري — إلزام بلا جدال',
    topic_en: 'The rhetorical question — compelling without argument',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يبيّن السعدي أن هذا الاستفهام يُلزم المنكرين من أنفسهم: إذا كنتم تقرّون أن الله خلق السماء — وهي أعظم وأعقد — فكيف يعجز عن إعادة خلقكم وأنتم أبسط؟ الاستفهام هنا لا يحتاج جواباً لأن الجواب بديهي. وهذا من أقوى أساليب الإقناع: أن تجعل الخصم يجيب نفسه بنفسه فيكون قد ألزم نفسه بالحجة.',
    insight_en: 'Al-Sa\'di explains that this rhetorical question compels the deniers to answer from within themselves: if you acknowledge that Allah created the heavens — which are far greater and more complex — then how could He be incapable of recreating you, who are simpler? The question needs no answer because the answer is self-evident. This is one of the most powerful persuasion techniques: making the opponent answer themselves, thereby binding themselves with the argument.',
    scholar_ar: 'السعدي',
    scholar_en: 'Al-Sa\'di',
    source_ar: 'تيسير الكريم الرحمن في تفسير كلام المنان',
    source_en: 'Taysir Al-Karim Al-Rahman',
    source_type: 'tafsir'
  },
  {
    id: 45,
    verse_ref: '37:102',
    verse_ar: 'قَالَ يَا بُنَيَّ إِنِّي أَرَىٰ فِي الْمَنَامِ أَنِّي أَذْبَحُكَ فَانظُرْ مَاذَا تَرَىٰ ۚ قَالَ يَا أَبَتِ افْعَلْ مَا تُؤْمَرُ',
    topic_ar: 'الحوار بين إبراهيم وابنه — بلاغة الحذف',
    topic_en: 'The dialogue between Ibrahim and his son — eloquence of omission',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يلاحظ ابن عاشور أن القرآن حذف مشهد الذبح نفسه وانتقل مباشرة من الحوار إلى الفداء: "فلما أسلما... وناديناه أن يا إبراهيم قد صدقت الرؤيا". هذا الحذف أبلغ من الذكر لأن المشهد أعظم من أن تصفه الكلمات. وإبراهيم قال "أرى في المنام" ولم يقل "أُمرت" — أي أعطى ابنه فرصة التفكير ولم يفرض عليه. وابنه قال "ستجدني إن شاء الله من الصابرين" — علّق صبره على مشيئة الله تواضعاً.',
    insight_en: 'Ibn Ashur notes that the Quran omits the actual sacrifice scene, jumping from dialogue to ransom: "When they had both submitted... We called to him: O Ibrahim, you have fulfilled the vision." This omission is more eloquent than description because the scene is too great for words. Ibrahim said "I see in a dream" rather than "I am commanded" — giving his son room to think. And his son said "you will find me, God willing, among the patient" — attributing his patience to God\'s will out of humility.',
    scholar_ar: 'ابن عاشور',
    scholar_en: 'Ibn Ashur',
    source_ar: 'التحرير والتنوير',
    source_en: 'Al-Tahrir wa Al-Tanwir',
    source_type: 'tafsir'
  },
  {
    id: 46,
    verse_ref: '12:84',
    verse_ar: 'وَتَوَلَّىٰ عَنْهُمْ وَقَالَ يَا أَسَفَىٰ عَلَىٰ يُوسُفَ وَابْيَضَّتْ عَيْنَاهُ مِنَ الْحُزْنِ فَهُوَ كَظِيمٌ',
    topic_ar: 'يعقوب يبكي على يوسف بعد عقود — لماذا الألف في "أسفى"؟',
    topic_en: 'Ya\'qub weeps for Yusuf after decades — why the alif in "asafa"?',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يحلل السامرائي النداء "يا أسفى": ألف المد في "أسفى" تطيل الصوت كتطويل البكاء والنواح. ولم يقل "يا حزني" بل "يا أسفي" — والأسف أعمق من الحزن لأنه حزن مخلوط بالندم. ثم قال "على يوسف" ولم يقل "على أبنائي" — أي رغم فقده لبنيامين أيضاً إلا أن الجرح الأول (يوسف) لم يندمل. هذا رسم نفسي للأبوة لم يتجاوزه أدب بشري.',
    insight_en: 'Al-Samarrai analyzes the cry "ya asafa": the elongated alif in "asafa" stretches the sound like extended weeping. He did not say "ya huzni" (my grief) but "ya asafi" (my sorrow) — asaf is deeper than huzn because it is grief mixed with regret. Then he said "over Yusuf" not "over my sons" — meaning despite also losing Binyamin, the first wound (Yusuf) never healed. This is a psychological portrait of fatherhood that no human literature has surpassed.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'لمسات بيانية في نصوص من التنزيل',
    source_en: 'Linguistic Touches in Quranic Texts',
    source_type: 'book'
  },
  {
    id: 47,
    verse_ref: '14:37',
    verse_ar: 'رَّبَّنَا إِنِّي أَسْكَنتُ مِن ذُرِّيَّتِي بِوَادٍ غَيْرِ ذِي زَرْعٍ عِندَ بَيْتِكَ الْمُحَرَّمِ',
    topic_ar: '"من ذريتي" بـ"من" التبعيضية — دقة مذهلة',
    topic_en: '"Some of my offspring" with partitive "min" — stunning precision',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يلاحظ السامرائي أن إبراهيم قال "من ذريتي" بـ"من" التبعيضية ولم يقل "ذريتي". لأنه أسكن إسماعيل وأمه فقط (بعض ذريته) وليس كل ذريته. ولو قال "ذريتي" لشمل إسحاق وهو لم يكن في مكة. هذه الدقة في حرف واحد (من) تدل على أن كل حرف في القرآن محسوب. وكلمة "أسكنت" تعني الإقامة الدائمة لا الزيارة المؤقتة.',
    insight_en: 'Al-Samarrai observes that Ibrahim said "min dhurriyyati" (some of my offspring) with the partitive "min," not "dhurriyyati" (my offspring). Because he settled only Isma\'il and his mother (some of his offspring), not all of them. Had he said "my offspring" it would include Ishaq, who was not in Mecca. This precision in a single letter (min) indicates that every letter in the Quran is deliberate. And "askuntu" (I settled) implies permanent residence, not a temporary visit.',
    scholar_ar: 'فاضل السامرائي',
    scholar_en: 'Dr. Fadel Al-Samarrai',
    source_ar: 'لمسات بيانية في نصوص من التنزيل',
    source_en: 'Linguistic Touches in Quranic Texts',
    source_type: 'book'
  },
  {
    id: 48,
    verse_ref: '76:1',
    verse_ar: 'هَلْ أَتَىٰ عَلَى الْإِنسَانِ حِينٌ مِّنَ الدَّهْرِ لَمْ يَكُن شَيْئًا مَّذْكُورًا',
    topic_ar: '"لم يكن شيئاً مذكوراً" — نفي الذكر لا الوجود',
    topic_en: '"He was not a thing mentioned" — denying mention, not existence',
    cat: 'rhetorical',
    cat_ar: 'بلاغة قرآنية',
    insight_ar: 'يدقق ابن عاشور في العبارة: لم يقل "لم يكن شيئاً" بل "لم يكن شيئاً مذكوراً". الفرق عميق: الإنسان كان موجوداً كعناصر في التراب والماء، لكنه لم يكن شيئاً يُذكر أو يُعرف أو يُسمّى. فالنفي منصبّ على "الذكر" لا على "الوجود". هذا تفريق فلسفي دقيق بين الوجود المادي والوجود المعنوي، في خمس كلمات فقط.',
    insight_en: 'Ibn Ashur examines the phrasing closely: it did not say "he was not a thing" but "he was not a thing mentioned." The difference is profound: the human existed as elements in soil and water, but was not a thing that could be mentioned, known, or named. The negation targets "being mentioned," not "existing." This is a precise philosophical distinction between material existence and meaningful existence, in only five words.',
    scholar_ar: 'ابن عاشور',
    scholar_en: 'Ibn Ashur',
    source_ar: 'التحرير والتنوير',
    source_en: 'Al-Tahrir wa Al-Tanwir',
    source_type: 'tafsir'
  },

  // ═══════════════════════════════════════════════════════════════
  // THEOLOGICAL (عقيدة) — Core theological concepts
  // ═══════════════════════════════════════════════════════════════

  {
    id: 49,
    verse_ref: '112:1',
    verse_ar: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
    topic_ar: 'لماذا "أحد" وليس "واحد"؟',
    topic_en: 'Why "Ahad" and not "Wahid"?',
    cat: 'theological',
    cat_ar: 'عقيدة',
    insight_ar: 'يفرّق السعدي بين "أحد" و"واحد": "واحد" تعني واحداً في العدد ويمكن أن يكون له ثانٍ، أما "أحد" فتنفي أي مشابهة أو مماثلة. فالله ليس واحداً عددياً فقط بل هو أحد في ذاته وصفاته — لا يشبهه شيء ولا يماثله شيء. و"الصمد" تعني الذي يقصده كل شيء في حوائجه ولا يحتاج هو لأحد. في أربع آيات قصيرة اختصر القرآن عقيدة التوحيد كاملة.',
    insight_en: 'Al-Sa\'di distinguishes between "Ahad" and "Wahid": "Wahid" means one in number and could theoretically have a second, but "Ahad" negates any resemblance or likeness. Allah is not merely numerically one but is uniquely singular in His essence and attributes — nothing resembles or parallels Him. "Al-Samad" means the One whom all creation turns to in need while He needs no one. In four short verses, the Quran encapsulated the entire creed of monotheism.',
    scholar_ar: 'السعدي',
    scholar_en: 'Al-Sa\'di',
    source_ar: 'تيسير الكريم الرحمن في تفسير كلام المنان',
    source_en: 'Taysir Al-Karim Al-Rahman',
    source_type: 'tafsir'
  },
  {
    id: 50,
    verse_ref: '42:11',
    verse_ar: 'لَيْسَ كَمِثْلِهِ شَيْءٌ ۖ وَهُوَ السَّمِيعُ الْبَصِيرُ',
    topic_ar: '"ليس كمثله" — لماذا لم يقل "ليس مثله"؟',
    topic_en: '"Nothing is like His likeness" — why not "nothing is like Him"?',
    cat: 'theological',
    cat_ar: 'عقيدة',
    insight_ar: 'يحلل الزمخشري "ليس كمثله شيء": ظاهرها نفي المثل عن المثل، لكن المعنى أعمق — هي نفي مضاعف. الكاف الزائدة بلاغياً تؤكد النفي تأكيداً مطلقاً: ليس له مثل حتى يكون لذلك المثل شبيه. وهذا أبلغ من "ليس مثله شيء" لأنه ينفي وجود المثل من الأصل. ثم ختم بـ"وهو السميع البصير" ليثبت أن التنزيه لا يعني التعطيل: ينفي المشابهة ويثبت الصفات.',
    insight_en: 'Al-Zamakhshari analyzes "laysa kamithlihi shay\'": its surface meaning negates likeness of a likeness, but the deeper meaning is a doubled negation. The extra "ka" (like) emphatically confirms the negation: He has no likeness for that likeness to even have a resemblance. This is more powerful than "nothing is like Him" because it negates the very existence of a likeness from the start. Then it closes with "He is the All-Hearing, All-Seeing" to affirm that transcendence does not mean negation of attributes: it negates resemblance while affirming attributes.',
    scholar_ar: 'الزمخشري',
    scholar_en: 'Al-Zamakhshari',
    source_ar: 'الكشاف عن حقائق غوامض التنزيل',
    source_en: 'Al-Kashshaf',
    source_type: 'tafsir'
  },
  {
    id: 51,
    verse_ref: '67:2',
    verse_ar: 'الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا',
    topic_ar: 'لماذا "أحسن" عملاً وليس "أكثر"؟',
    topic_en: 'Why "best" in deeds and not "most"?',
    cat: 'theological',
    cat_ar: 'عقيدة',
    insight_ar: 'يلاحظ الشعراوي أن الله قال "أحسن عملاً" ولم يقل "أكثر عملاً". المعيار عند الله ليس الكمّ بل الكيف. صلاتان بخشوع خير من مئة بلا قلب. وقدّم "الموت" على "الحياة" لأن تذكّر الموت هو الذي يدفع إلى إحسان العمل. من يعلم أنه سيموت يحسن عمله، ومن ينسى الموت يهمل. فترتيب اللفظ يعكس ترتيب الدافع: الموت يدفع إلى إتقان الحياة.',
    insight_en: 'Al-Sha\'rawi observes that Allah said "best in deeds" not "most in deeds." God\'s standard is quality, not quantity. Two prayers with mindfulness are better than a hundred without heart. And "death" precedes "life" because remembering death is what drives excellence in deeds. One who knows they will die perfects their work; one who forgets death becomes negligent. The word order reflects the order of motivation: death drives the perfection of life.',
    scholar_ar: 'الشعراوي',
    scholar_en: 'Al-Sha\'rawi',
    source_ar: 'خواطر الشعراوي',
    source_en: 'Al-Sha\'rawi\'s Reflections',
    source_type: 'tafsir'
  },
  {
    id: 52,
    verse_ref: '50:16',
    verse_ar: 'وَلَقَدْ خَلَقْنَا الْإِنسَانَ وَنَعْلَمُ مَا تُوَسْوِسُ بِهِ نَفْسُهُ ۖ وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ',
    topic_ar: '"أقرب من حبل الوريد" — القرب الإلهي',
    topic_en: '"Closer than the jugular vein" — divine closeness',
    cat: 'theological',
    cat_ar: 'عقيدة',
    insight_ar: 'يتأمل سيد قطب في هذه الصورة: حبل الوريد داخل الإنسان، فالله أقرب إليك من شيء في داخلك أنت. وسبق ذلك بـ"نعلم ما توسوس به نفسه" — أي يعلم حتى ما لم تقله وما لم تفعله، يعلم الخاطرة قبل أن تصبح فكرة. هذا القرب ليس مكانياً بل علمي وإحاطي. والوريد اختير لأنه يحمل الدم — أساس الحياة — فالله أقرب إليك من أساس حياتك.',
    insight_en: 'Sayyid Qutb reflects on this image: the jugular vein is inside you, so Allah is closer than something within your own self. This is preceded by "We know what his soul whispers" — meaning He knows even what you did not say or do, knowing the thought before it becomes an idea. This closeness is not spatial but of knowledge and encompassment. The vein was chosen because it carries blood — the basis of life — so Allah is closer to you than the very basis of your life.',
    scholar_ar: 'سيد قطب',
    scholar_en: 'Sayyid Qutb',
    source_ar: 'في ظلال القرآن',
    source_en: 'In the Shade of the Quran',
    source_type: 'tafsir'
  },
  {
    id: 53,
    verse_ref: '6:103',
    verse_ar: 'لَّا تُدْرِكُهُ الْأَبْصَارُ وَهُوَ يُدْرِكُ الْأَبْصَارَ ۖ وَهُوَ اللَّطِيفُ الْخَبِيرُ',
    topic_ar: '"لا تدركه الأبصار" — نفي الإدراك لا الرؤية',
    topic_en: '"Vision cannot encompass Him" — negating comprehension not sight',
    cat: 'theological',
    cat_ar: 'عقيدة',
    insight_ar: 'يفرّق ابن كثير بين "الرؤية" و"الإدراك": الآية تنفي الإدراك (الإحاطة الكاملة) لا مجرد الرؤية. فالله يُرى في الآخرة كما ثبت في الأحاديث، لكنه لا يُدرك — أي لا تحيط به الأبصار إحاطة كاملة. كما أنك ترى السماء لكنك لا تدركها كلها. ختم بـ"اللطيف الخبير": اللطيف يدل على أنه يدرك الدقائق التي لا تراها أبصارنا — فهو يرانا ولا نحيط به.',
    insight_en: 'Ibn Kathir distinguishes between "seeing" and "comprehending": the verse negates comprehension (complete encompassment), not mere sight. Allah can be seen in the Hereafter as established in the hadith, but cannot be encompassed — meaning vision cannot fully contain Him. Just as you see the sky but cannot encompass all of it. It closes with "the Subtle, the Expert": Al-Latif indicates He perceives the minutiae invisible to our eyes — He sees us while we cannot encompass Him.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 54,
    verse_ref: '2:286',
    verse_ar: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
    topic_ar: '"وُسعها" وليس "طاقتها" — الفرق الدقيق',
    topic_en: '"Its capacity" not "its maximum" — the subtle difference',
    cat: 'theological',
    cat_ar: 'عقيدة',
    insight_ar: 'يبيّن الشعراوي الفرق بين "الوُسع" و"الطاقة": الطاقة هي أقصى ما يتحمله الإنسان، أما الوُسع فهو ما يسعه بيسر ورحابة. فالله لا يكلّف الإنسان حتى أقصى طاقته بل في حدود ما يسعه براحة. وهذا أرحم: فلو قال "طاقتها" لكان التكليف حتى الحد الأقصى. لكن "وسعها" تعني أن بين التكليف وبين أقصى الطاقة هامشاً مريحاً. رحمة مبثوثة في كلمة واحدة.',
    insight_en: 'Al-Sha\'rawi distinguishes between "wus\'aha" (capacity) and "taqataha" (maximum ability): taqah is the absolute maximum a person can bear, while wus\' is what one can do with ease and spaciousness. Allah does not burden a soul even to its maximum but within what it can handle comfortably. This is more merciful: had it said "taqataha," the obligation would extend to the absolute limit. But "wus\'aha" means there is a comfortable margin between the obligation and the maximum. Mercy embedded in a single word.',
    scholar_ar: 'الشعراوي',
    scholar_en: 'Al-Sha\'rawi',
    source_ar: 'خواطر الشعراوي',
    source_en: 'Al-Sha\'rawi\'s Reflections',
    source_type: 'tafsir'
  },
  {
    id: 55,
    verse_ref: '57:3',
    verse_ar: 'هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ',
    topic_ar: 'أربع صفات تحيط بكل شيء',
    topic_en: 'Four attributes that encompass everything',
    cat: 'theological',
    cat_ar: 'عقيدة',
    insight_ar: 'يتأمل ابن القيم (كما ينقل ابن كثير) في هذه الصفات الأربع فيجد أنها تحيط بالزمان والمكان: "الأول" أي ليس قبله شيء (بداية الزمان)، "الآخر" أي ليس بعده شيء (نهاية الزمان)، "الظاهر" أي ليس فوقه شيء (ظاهر المكان)، "الباطن" أي ليس دونه شيء (باطن المكان). فأي اتجاه اتجهت فيه — ماضياً أو مستقبلاً، ظاهراً أو باطناً — تجد الله.',
    insight_en: 'Ibn Al-Qayyim (as cited by Ibn Kathir) reflects on these four attributes and finds they encompass all time and space: "The First" — nothing before Him (beginning of time), "The Last" — nothing after Him (end of time), "The Manifest" — nothing above Him (outer space), "The Hidden" — nothing closer than Him (inner space). Whichever direction you turn — past or future, outer or inner — you find Allah.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },

  // ═══════════════════════════════════════════════════════════════
  // ETHICAL (أخلاق وتشريع) — Ethics, law, and social guidance
  // ═══════════════════════════════════════════════════════════════

  {
    id: 56,
    verse_ref: '5:32',
    verse_ar: 'مَن قَتَلَ نَفْسًا بِغَيْرِ نَفْسٍ أَوْ فَسَادٍ فِي الْأَرْضِ فَكَأَنَّمَا قَتَلَ النَّاسَ جَمِيعًا وَمَنْ أَحْيَاهَا فَكَأَنَّمَا أَحْيَا النَّاسَ جَمِيعًا',
    topic_ar: 'قتل نفس واحدة = قتل الناس جميعاً — لماذا؟',
    topic_en: 'Killing one soul = killing all humanity — why?',
    cat: 'ethical',
    cat_ar: 'أخلاق وتشريع',
    insight_ar: 'يشرح القرطبي المنطق: من يستبيح قتل نفس بريئة فقد استباح مبدأ القتل ذاته، ومن استباح المبدأ فلا فرق عنده بين واحد وألف. فالجريمة ليست في العدد بل في انتهاك حرمة الحياة. والمقابل "من أحياها" يشمل كل إنقاذ: إطعام جائع، علاج مريض، عفو عن قاتل. هذا التأسيس يجعل قيمة الإنسان مطلقة وغير قابلة للتجزئة — وهو أساس حقوق الإنسان في أعمق صوره.',
    insight_en: 'Al-Qurtubi explains the logic: whoever permits themselves to kill an innocent soul has permitted the principle of killing itself, and whoever permits the principle sees no difference between one and a thousand. The crime is not in numbers but in violating the sanctity of life. The counterpart "whoever saves one" includes all forms of rescue: feeding the hungry, treating the sick, pardoning a killer. This foundation makes human value absolute and indivisible — the deepest form of human rights.',
    scholar_ar: 'القرطبي',
    scholar_en: 'Al-Qurtubi',
    source_ar: 'الجامع لأحكام القرآن',
    source_en: 'Al-Jami\' li Ahkam Al-Quran',
    source_type: 'tafsir'
  },
  {
    id: 57,
    verse_ref: '4:135',
    verse_ar: 'يَا أَيُّهَا الَّذِينَ آمَنُوا كُونُوا قَوَّامِينَ بِالْقِسْطِ شُهَدَاءَ لِلَّهِ وَلَوْ عَلَىٰ أَنفُسِكُمْ أَوِ الْوَالِدَيْنِ وَالْأَقْرَبِينَ',
    topic_ar: 'العدل حتى ضد النفس — أساس القضاء المستقل',
    topic_en: 'Justice even against yourself — foundation of judicial independence',
    cat: 'ethical',
    cat_ar: 'أخلاق وتشريع',
    insight_ar: 'يبيّن ابن كثير أن هذه الآية أصّلت مبدأ العدالة المطلقة: أن تشهد بالحق حتى لو كان ضدك أنت أو والديك أو أقربائك. وترتيب الآية بليغ: بدأ بالأنفس (الأصعب) ثم الوالدين ثم الأقربين. لأن من تغلّب على هوى نفسه سهل عليه ما بعده. هذا المبدأ سبق نظام الإقرارات القضائية وشهادات تضارب المصالح بأربعة عشر قرناً.',
    insight_en: 'Ibn Kathir explains that this verse established the principle of absolute justice: bearing witness to truth even if it is against yourself, your parents, or your relatives. The verse\'s order is eloquent: starting with the self (hardest), then parents, then relatives. Because whoever overcomes self-interest finds the rest easier. This principle preceded judicial disclosure systems and conflict of interest declarations by fourteen centuries.',
    scholar_ar: 'ابن كثير',
    scholar_en: 'Ibn Kathir',
    source_ar: 'تفسير القرآن العظيم',
    source_en: 'Tafsir Al-Quran Al-Azim',
    source_type: 'tafsir'
  },
  {
    id: 58,
    verse_ref: '49:13',
    verse_ar: 'يَا أَيُّهَا النَّاسُ إِنَّا خَلَقْنَاكُم مِّن ذَكَرٍ وَأُنثَىٰ وَجَعَلْنَاكُمْ شُعُوبًا وَقَبَائِلَ لِتَعَارَفُوا ۚ إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ',
    topic_ar: '"لتعارفوا" — الاختلاف للتعارف لا للتناحر',
    topic_en: '"That you may know one another" — diversity for connection not conflict',
    cat: 'ethical',
    cat_ar: 'أخلاق وتشريع',
    insight_ar: 'يبيّن سيد قطب أن الآية بدأت بتوحيد الأصل "من ذكر وأنثى" — لنفي أي تفوق عرقي. ثم جعل الاختلاف (شعوب وقبائل) وسيلة للتعارف لا للتفاخر. و"لتعارفوا" من المعرفة والعرفان: أي لتتبادلوا المعرفة والخير. ثم ختم بالمعيار الحقيقي: التقوى. في آية واحدة هدم القرآن العنصرية والطبقية والقومية ووضع معياراً واحداً: العمل الصالح. لم تصل أي حضارة لهذا المبدأ إلا مؤخراً.',
    insight_en: 'Sayyid Qutb explains that the verse begins by unifying the origin "from a male and female" — negating any racial superiority. Then it makes diversity (peoples and tribes) a means for knowing each other, not for boasting. "Li ta\'arafu" derives from knowledge and gratitude: meaning to exchange knowledge and goodness. It closes with the real standard: God-consciousness. In one verse, the Quran demolished racism, classism, and nationalism, establishing one criterion: righteous deeds. No other civilization reached this principle until recently.',
    scholar_ar: 'سيد قطب',
    scholar_en: 'Sayyid Qutb',
    source_ar: 'في ظلال القرآن',
    source_en: 'In the Shade of the Quran',
    source_type: 'tafsir'
  },
  {
    id: 59,
    verse_ref: '31:18',
    verse_ar: 'وَلَا تُصَعِّرْ خَدَّكَ لِلنَّاسِ وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا ۖ إِنَّ اللَّهَ لَا يُحِبُّ كُلَّ مُخْتَالٍ فَخُورٍ',
    topic_ar: '"لا تصعّر خدك" — أدق وصف للتكبر',
    topic_en: '"Do not turn your cheek" — the most precise description of arrogance',
    cat: 'ethical',
    cat_ar: 'أخلاق وتشريع',
    insight_ar: 'يبيّن القرطبي أن "تصعّر خدك" من الصَّعَر وهو داء يصيب الإبل فيلوي عنقها. فالمتكبر كالبعير المريض — يلوي وجهه عن الناس كأن النظر إليهم يؤذيه. هذا التشبيه يجعل الكبر مرضاً لا فضيلة. والنهي جاء في سياق وصايا لقمان لابنه — أي تربية الأطفال على التواضع. ولاحظ أنه نهى عن أبسط حركة (لوي الخد) ليشمل ما فوقها من باب أولى.',
    insight_en: 'Al-Qurtubi explains that "tusa\'\'ir khaddaka" (turn your cheek) comes from sa\'ar, a disease that strikes camels causing their necks to twist. The arrogant person is like a diseased camel — twisting their face away from people as if looking at them is painful. This comparison makes arrogance a disease, not a virtue. The prohibition comes within Luqman\'s advice to his son — teaching children humility. Note it forbids the simplest gesture (turning the cheek) to encompass everything greater by logical priority.',
    scholar_ar: 'القرطبي',
    scholar_en: 'Al-Qurtubi',
    source_ar: 'الجامع لأحكام القرآن',
    source_en: 'Al-Jami\' li Ahkam Al-Quran',
    source_type: 'tafsir'
  },
  {
    id: 60,
    verse_ref: '16:90',
    verse_ar: 'إِنَّ اللَّهَ يَأْمُرُ بِالْعَدْلِ وَالْإِحْسَانِ وَإِيتَاءِ ذِي الْقُرْبَىٰ وَيَنْهَىٰ عَنِ الْفَحْشَاءِ وَالْمُنكَرِ وَالْبَغْيِ',
    topic_ar: 'أجمع آية في القرآن للخير والشر',
    topic_en: 'The most comprehensive verse of good and evil in the Quran',
    cat: 'ethical',
    cat_ar: 'أخلاق وتشريع',
    insight_ar: 'يروي القرطبي أن ابن مسعود قال: "أجمع آية في القرآن للخير والشر هذه الآية." فيها ثلاثة أوامر: العدل (الحد الأدنى)، والإحسان (ما فوق العدل)، وإيتاء ذي القربى (التكافل). وثلاثة نواهٍ: الفحشاء (المعاصي الكبرى)، والمنكر (ما أنكره الشرع والعقل)، والبغي (الظلم والعدوان). في سطر واحد رسم القرآن خارطة الأخلاق البشرية كاملة: ثلاثة افعل وثلاثة لا تفعل.',
    insight_en: 'Al-Qurtubi narrates that Ibn Mas\'ud said: "The most comprehensive verse in the Quran for good and evil is this verse." It contains three commands: justice (the minimum), ihsan/excellence (beyond justice), and giving to relatives (social solidarity). And three prohibitions: immorality (major sins), wrongdoing (what religion and reason reject), and transgression (oppression and aggression). In one line, the Quran drew the complete map of human ethics: three do\'s and three don\'ts.',
    scholar_ar: 'القرطبي',
    scholar_en: 'Al-Qurtubi',
    source_ar: 'الجامع لأحكام القرآن',
    source_en: 'Al-Jami\' li Ahkam Al-Quran',
    source_type: 'tafsir'
  }
];

// ═══════════════════════════════════════════════════════════════
// Category definitions for UI rendering
// ═══════════════════════════════════════════════════════════════
const TAFSIR_CATEGORIES = {
  wisdom:      { ar: 'حكمة إلهية',     en: 'Divine Wisdom',     icon: '🌟', color: '#D4AF37' },
  linguistic:  { ar: 'إعجاز لغوي',     en: 'Linguistic Miracle', icon: '📖', color: '#2E86AB' },
  scientific:  { ar: 'إشارات علمية',    en: 'Scientific Signs',   icon: '🔬', color: '#28A745' },
  historical:  { ar: 'سياق تاريخي',     en: 'Historical Context',  icon: '📜', color: '#8B4513' },
  rhetorical:  { ar: 'بلاغة قرآنية',    en: 'Quranic Rhetoric',   icon: '✨', color: '#6F42C1' },
  theological: { ar: 'عقيدة',           en: 'Theology',           icon: '🕌', color: '#17A2B8' },
  ethical:     { ar: 'أخلاق وتشريع',    en: 'Ethics & Law',       icon: '⚖️', color: '#DC3545' }
};

// ═══════════════════════════════════════════════════════════════
// Scholar definitions for UI rendering
// ═══════════════════════════════════════════════════════════════
const TAFSIR_SCHOLARS = {
  'فاضل السامرائي':  { en: 'Dr. Fadel Al-Samarrai', era: 'modern',    specialty: 'بلاغة وتعبير قرآني' },
  'ابن كثير':        { en: 'Ibn Kathir',             era: 'classical', specialty: 'تفسير بالمأثور' },
  'الطبري':          { en: 'Al-Tabari',              era: 'classical', specialty: 'تفسير جامع' },
  'القرطبي':         { en: 'Al-Qurtubi',             era: 'classical', specialty: 'أحكام القرآن' },
  'السعدي':          { en: 'Al-Sa\'di',              era: 'modern',    specialty: 'تفسير ميسّر' },
  'ابن عاشور':       { en: 'Ibn Ashur',              era: 'modern',    specialty: 'تحرير وتنوير' },
  'الشعراوي':        { en: 'Al-Sha\'rawi',           era: 'modern',    specialty: 'خواطر إيمانية' },
  'الزمخشري':        { en: 'Al-Zamakhshari',         era: 'classical', specialty: 'بلاغة وكشاف' },
  'سيد قطب':         { en: 'Sayyid Qutb',            era: 'modern',    specialty: 'ظلال القرآن' }
};
