const QURAN_STORIES = [
  // ═══════════════════════════════════════════════════════════════
  // PROPHETS (25)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 1,
    ar: "قصة آدم عليه السلام",
    en: "Story of Adam",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "خلق الله آدم من طين وعلّمه الأسماء كلها وأمر الملائكة بالسجود له، فسجدوا إلا إبليس. أسكنه الجنة ثم أهبطه إلى الأرض خليفةً بعد أن أكل من الشجرة.",
    desc_en: "God created Adam from clay, taught him all names, and commanded the angels to prostrate. He dwelt in Paradise then was sent to Earth as a vicegerent after eating from the forbidden tree.",
    refs: ["2:30-39", "7:11-25", "15:26-44", "17:61-65", "18:50", "20:115-124", "38:71-85"],
    figures_ar: "آدم، حواء، إبليس",
    figures_en: "Adam, Eve (Hawwa), Iblis (Satan)",
    primary: 2
  },
  {
    id: 2,
    ar: "قصة إدريس عليه السلام",
    en: "Story of Idris (Enoch)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "نبي صدّيق رفعه الله مكاناً علياً. يُذكر في القرآن بالثناء على صبره وصدقه.",
    desc_en: "A truthful prophet whom God raised to a lofty station. The Quran praises his patience and righteousness.",
    refs: ["19:56-57", "21:85-86"],
    figures_ar: "إدريس",
    figures_en: "Idris (Enoch)",
    primary: 19
  },
  {
    id: 3,
    ar: "قصة نوح عليه السلام",
    en: "Story of Nuh (Noah)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "دعا قومه تسعمائة وخمسين عاماً فلم يؤمن إلا قليل. أمره الله ببناء السفينة فنجا بالمؤمنين وغرق الكافرون ومنهم ابنه.",
    desc_en: "He called his people for 950 years but few believed. God commanded him to build the Ark; the believers were saved while the disbelievers, including his own son, drowned in the Great Flood.",
    refs: ["7:59-64", "10:71-73", "11:25-49", "23:23-30", "26:105-122", "29:14-15", "37:75-82", "54:9-17", "71:1-28"],
    figures_ar: "نوح، ابن نوح",
    figures_en: "Nuh (Noah), Son of Nuh",
    primary: 71
  },
  {
    id: 4,
    ar: "قصة هود عليه السلام",
    en: "Story of Hud",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أُرسل إلى قوم عاد الذين تفاخروا بقوتهم وبنيانهم. كذّبوه فأهلكهم الله بريح صرصر عاتية استمرت سبع ليالٍ وثمانية أيام.",
    desc_en: "Sent to the people of 'Ad who boasted of their strength and monuments. They rejected him, so God destroyed them with a furious wind lasting seven nights and eight days.",
    refs: ["7:65-72", "11:50-60", "23:31-41", "26:123-140", "41:15-16", "46:21-26", "54:18-22", "69:6-8"],
    figures_ar: "هود",
    figures_en: "Hud",
    primary: 11
  },
  {
    id: 5,
    ar: "قصة صالح عليه السلام",
    en: "Story of Salih",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أُرسل إلى ثمود وآتاهم الله الناقة آية. نهاهم عن عقرها فعقروها، فأخذتهم الصيحة وأُبيدوا.",
    desc_en: "Sent to Thamud with a miraculous she-camel as a sign. He warned them not to harm her, but they hamstrung her, and God destroyed them with a mighty blast.",
    refs: ["7:73-79", "11:61-68", "15:80-84", "26:141-159", "27:45-53", "54:23-32", "91:11-15"],
    figures_ar: "صالح",
    figures_en: "Salih",
    primary: 11
  },
  {
    id: 6,
    ar: "قصة إبراهيم عليه السلام",
    en: "Story of Ibrahim (Abraham)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "خليل الله الذي حطّم الأصنام وناظر قومه ونمرود في التوحيد. ألقوه في النار فجعلها الله عليه برداً وسلاماً. بنى الكعبة مع إسماعيل وابتُلي بذبح ابنه ففداه الله.",
    desc_en: "The Friend of God who smashed idols and debated his people and Nimrod about monotheism. Thrown into fire, God made it cool and safe. He built the Ka'ba with Ismail and was tested with the sacrifice of his son.",
    refs: ["2:124-141", "2:258-260", "6:74-83", "9:114", "11:69-76", "14:35-41", "15:51-60", "19:41-50", "21:51-73", "22:26-27", "26:69-104", "29:16-27", "37:83-113", "43:26-28", "51:24-37", "60:4"],
    figures_ar: "إبراهيم، سارة، هاجر، نمرود",
    figures_en: "Ibrahim (Abraham), Sarah, Hajar (Hagar), Nimrod",
    primary: 21
  },
  {
    id: 7,
    ar: "قصة لوط عليه السلام",
    en: "Story of Lut (Lot)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أُرسل إلى أهل سدوم الذين أتوا الفاحشة. أنذرهم فأصرّوا، فأرسل الله الملائكة لإنجائه وأهلكهم بحجارة من سجّيل.",
    desc_en: "Sent to the people of Sodom who committed grave immorality. He warned them but they persisted, so God sent angels to rescue him and destroyed the cities with stones of baked clay.",
    refs: ["7:80-84", "11:77-83", "15:57-77", "21:74-75", "26:160-175", "27:54-58", "29:28-35", "37:133-138", "54:33-40"],
    figures_ar: "لوط، امرأة لوط",
    figures_en: "Lut (Lot), Wife of Lut",
    primary: 11
  },
  {
    id: 8,
    ar: "قصة إسماعيل عليه السلام",
    en: "Story of Ismail (Ishmael)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "ابن إبراهيم الذي صبر على الذبح حتى فداه الله بكبش عظيم. شارك أباه في بناء الكعبة المشرّفة وكان صادق الوعد.",
    desc_en: "Son of Ibrahim who patiently submitted to the sacrifice before God ransomed him with a great ram. He helped his father build the Ka'ba and was known for keeping his promises.",
    refs: ["2:125-129", "2:133", "2:136", "6:86", "14:39", "19:54-55", "21:85", "37:100-107", "38:48"],
    figures_ar: "إسماعيل، إبراهيم",
    figures_en: "Ismail (Ishmael), Ibrahim (Abraham)",
    primary: 37
  },
  {
    id: 9,
    ar: "قصة إسحاق عليه السلام",
    en: "Story of Ishaq (Isaac)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "بُشّر به إبراهيم وسارة على كبرهما. كان نبياً من الصالحين وأباً ليعقوب.",
    desc_en: "Ibrahim and Sarah were given glad tidings of his birth in their old age. He was a righteous prophet and father of Yaqub (Jacob).",
    refs: ["2:133", "2:136", "6:84", "11:71-73", "12:6", "14:39", "19:49", "21:72", "29:27", "37:112-113", "38:45-47"],
    figures_ar: "إسحاق، إبراهيم، سارة",
    figures_en: "Ishaq (Isaac), Ibrahim (Abraham), Sarah",
    primary: 37
  },
  {
    id: 10,
    ar: "قصة يعقوب عليه السلام",
    en: "Story of Yaqub (Jacob)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "ابن إسحاق وأبو يوسف. ابتُلي بفقد ابنه يوسف وابيضّت عيناه من الحزن ثم ردّ الله إليه بصره عند لقاء يوسف.",
    desc_en: "Son of Ishaq and father of Yusuf. He was tested with the loss of his son Yusuf, wept until he lost his sight, then God restored it upon their reunion.",
    refs: ["2:132-133", "2:136", "6:84", "12:4-18", "12:63-100", "19:49", "21:72"],
    figures_ar: "يعقوب، يوسف",
    figures_en: "Yaqub (Jacob), Yusuf (Joseph)",
    primary: 12
  },
  {
    id: 11,
    ar: "قصة يوسف عليه السلام",
    en: "Story of Yusuf (Joseph)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أحسن القصص: ألقاه إخوته في الجُبّ حسداً، فبِيع عبداً في مصر. سُجن ظلماً ثم صار عزيز مصر بتأويله رؤيا الملك، والتقى بأبيه وإخوته وسامحهم.",
    desc_en: "The best of stories: his brothers cast him into a well out of jealousy. Sold into slavery in Egypt, unjustly imprisoned, he rose to become Egypt's treasurer by interpreting the king's dream. He reunited with and forgave his family.",
    refs: ["12:1-111"],
    figures_ar: "يوسف، يعقوب، إخوة يوسف، زليخا، الملك",
    figures_en: "Yusuf (Joseph), Yaqub (Jacob), Brothers of Yusuf, Zulaykha, The King",
    primary: 12
  },
  {
    id: 12,
    ar: "قصة أيوب عليه السلام",
    en: "Story of Ayyub (Job)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "ابتُلي بفقد ماله وأهله وبالمرض فصبر صبراً عظيماً. نادى ربه فكشف ضرّه وآتاه أهله ومثلهم معهم رحمةً.",
    desc_en: "Tested with the loss of his wealth, family, and health, he showed exemplary patience. He called upon God, who removed his affliction and restored his family twofold.",
    refs: ["4:163", "6:84", "21:83-84", "38:41-44"],
    figures_ar: "أيوب",
    figures_en: "Ayyub (Job)",
    primary: 38
  },
  {
    id: 13,
    ar: "قصة شعيب عليه السلام",
    en: "Story of Shu'ayb",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أُرسل إلى أهل مدين الذين كانوا يطفّفون الكيل والميزان ويقطعون السبيل. كذّبوه فأخذتهم الرجفة.",
    desc_en: "Sent to the people of Madyan who cheated in weights and measures and blocked the way. They rejected him, so God seized them with an earthquake.",
    refs: ["7:85-93", "11:84-95", "26:176-191", "29:36-37"],
    figures_ar: "شعيب",
    figures_en: "Shu'ayb (Jethro)",
    primary: 11
  },
  {
    id: 14,
    ar: "قصة موسى عليه السلام",
    en: "Story of Musa (Moses)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أكثر الأنبياء ذكراً في القرآن. أُلقي في اليمّ رضيعاً فالتقطه آل فرعون. كلّمه الله عند الطور وأرسله بالآيات إلى فرعون. أنجى بني إسرائيل وفلق البحر وتلقّى التوراة.",
    desc_en: "The most frequently mentioned prophet in the Quran. Cast into the river as an infant, raised in Pharaoh's palace, God spoke to him at Mount Tur. He was sent with signs to Pharaoh, led the Exodus, parted the sea, and received the Torah.",
    refs: ["2:49-74", "7:103-174", "10:75-92", "11:96-99", "17:101-104", "18:60-82", "20:9-99", "26:10-69", "27:7-14", "28:1-46", "40:23-46", "43:46-56", "44:17-33", "51:38-40", "79:15-26"],
    figures_ar: "موسى، فرعون، هارون، آسية، أم موسى",
    figures_en: "Musa (Moses), Pharaoh, Harun (Aaron), Asiya, Mother of Musa",
    primary: 28
  },
  {
    id: 15,
    ar: "قصة هارون عليه السلام",
    en: "Story of Harun (Aaron)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أخو موسى ووزيره. سأل موسى ربه أن يشدّ أزره بأخيه هارون فكان معه في مواجهة فرعون. استخلفه موسى في قومه حين ذهب لميقات ربه.",
    desc_en: "Brother and minister of Musa. Musa asked God to strengthen him through Harun, who stood with him against Pharaoh. He was left in charge of the Israelites during Musa's absence on Mount Sinai.",
    refs: ["2:248", "4:163", "6:84", "7:142", "7:150-151", "10:75", "19:53", "20:29-36", "20:90-94", "25:35", "26:13", "37:114-120"],
    figures_ar: "هارون، موسى",
    figures_en: "Harun (Aaron), Musa (Moses)",
    primary: 20
  },
  {
    id: 16,
    ar: "قصة ذي الكفل عليه السلام",
    en: "Story of Dhul-Kifl",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "ذُكر مع الصابرين ومن الأخيار. قيل إنه تكفّل بأمر قومه بعد نبي فوفّى بما التزم.",
    desc_en: "Mentioned among the patient and the righteous. Scholars suggest he took charge of guiding his people after a prophet and fulfilled his pledge faithfully.",
    refs: ["21:85-86", "38:48"],
    figures_ar: "ذو الكفل",
    figures_en: "Dhul-Kifl",
    primary: 21
  },
  {
    id: 17,
    ar: "قصة داود عليه السلام",
    en: "Story of Dawud (David)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "آتاه الله الملك والحكمة وألان له الحديد وسخّر معه الجبال والطير يسبّحن. قتل جالوت وهو فتى وأُنزل عليه الزبور.",
    desc_en: "God gave him kingship and wisdom, softened iron for him, and made the mountains and birds glorify Him alongside him. He slew Goliath as a youth and received the Psalms (Zabur).",
    refs: ["2:249-252", "4:163", "5:78", "6:84", "17:55", "21:78-80", "27:15-16", "34:10-11", "38:17-26"],
    figures_ar: "داود، جالوت",
    figures_en: "Dawud (David), Jalut (Goliath)",
    primary: 38
  },
  {
    id: 18,
    ar: "قصة سليمان عليه السلام",
    en: "Story of Sulayman (Solomon)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "ورث داود وسُخّر له الريح والجن وعُلّم منطق الطير. بلغه خبر ملكة سبأ فدعاها للإيمان فأسلمت.",
    desc_en: "He inherited Dawud's kingdom and was granted command over wind, jinn, and the language of birds. He summoned the Queen of Sheba to faith and she submitted to God.",
    refs: ["2:102", "6:84", "21:78-82", "27:15-44", "34:12-14", "38:30-40"],
    figures_ar: "سليمان، بلقيس، الهدهد",
    figures_en: "Sulayman (Solomon), Bilqis (Queen of Sheba), The Hoopoe",
    primary: 27
  },
  {
    id: 19,
    ar: "قصة إلياس عليه السلام",
    en: "Story of Ilyas (Elijah)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "أُرسل إلى قومه الذين عبدوا بعلاً فدعاهم إلى التوحيد. كذّبوه إلا قليلاً من المخلصين.",
    desc_en: "Sent to his people who worshipped Ba'l (Baal), he called them to pure monotheism. They rejected him except for a few sincere believers.",
    refs: ["6:85", "37:123-132"],
    figures_ar: "إلياس",
    figures_en: "Ilyas (Elijah)",
    primary: 37
  },
  {
    id: 20,
    ar: "قصة اليسع عليه السلام",
    en: "Story of Al-Yasa (Elisha)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "نبي فُضّل على العالمين وذُكر مع الأخيار. اختاره الله واجتباه من بين عباده.",
    desc_en: "A prophet favored above many, mentioned among the righteous and the chosen. God selected and guided him.",
    refs: ["6:86", "38:48"],
    figures_ar: "اليسع",
    figures_en: "Al-Yasa (Elisha)",
    primary: 6
  },
  {
    id: 21,
    ar: "قصة يونس عليه السلام",
    en: "Story of Yunus (Jonah)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "ذهب مغاضباً قومه فركب السفينة فالتقمه الحوت. سبّح الله في الظلمات فنجّاه. عاد إلى قومه فآمنوا جميعاً.",
    desc_en: "He departed in anger from his people, boarded a ship, and was swallowed by a whale. He glorified God in the depths of darkness and was delivered. His people then believed en masse.",
    refs: ["4:163", "6:86", "10:98", "21:87-88", "37:139-148", "68:48-50"],
    figures_ar: "يونس",
    figures_en: "Yunus (Jonah)",
    primary: 37
  },
  {
    id: 22,
    ar: "قصة زكريا عليه السلام",
    en: "Story of Zakariya (Zechariah)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "كفل مريم ووجد عندها رزقاً من الله. دعا ربه أن يهبه ولياً فبُشّر بيحيى رغم كبره وعقم زوجته.",
    desc_en: "He was guardian of Maryam and found sustenance miraculously provided for her. He prayed for an heir and was granted Yahya despite his old age and his wife's barrenness.",
    refs: ["3:37-41", "6:85", "19:2-11", "21:89-90"],
    figures_ar: "زكريا، مريم",
    figures_en: "Zakariya (Zechariah), Maryam (Mary)",
    primary: 19
  },
  {
    id: 23,
    ar: "قصة يحيى عليه السلام",
    en: "Story of Yahya (John the Baptist)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "سمّاه الله ولم يجعل له من قبل سمياً. أُوتي الحكم صبياً وكان حصوراً تقياً باراً بوالديه.",
    desc_en: "Named by God with a name never given before. He was granted wisdom as a child, was chaste, pious, and dutiful to his parents.",
    refs: ["3:38-41", "6:85", "19:7-15", "21:89-90"],
    figures_ar: "يحيى، زكريا",
    figures_en: "Yahya (John the Baptist), Zakariya (Zechariah)",
    primary: 19
  },
  {
    id: 24,
    ar: "قصة عيسى عليه السلام",
    en: "Story of Isa (Jesus)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "كلمة الله ألقاها إلى مريم وروح منه. وُلد من غير أب وتكلّم في المهد. أيّده الله بالمعجزات: إبراء الأكمه والأبرص وإحياء الموتى. رفعه الله إليه.",
    desc_en: "The Word of God and a spirit from Him, born to Maryam without a father. He spoke in the cradle and was supported with miracles: healing the blind and lepers, raising the dead. God raised him up to Himself.",
    refs: ["2:87", "2:253", "3:42-63", "4:156-159", "4:171-172", "5:46", "5:110-120", "19:16-40", "21:91", "23:50", "33:7", "42:13", "43:57-65", "57:27", "61:6", "61:14"],
    figures_ar: "عيسى، مريم، الحواريون",
    figures_en: "Isa (Jesus), Maryam (Mary), The Disciples (Hawariyyun)",
    primary: 3
  },
  {
    id: 25,
    ar: "قصة محمد صلى الله عليه وسلم",
    en: "Story of Muhammad (peace be upon him)",
    cat: "prophet",
    cat_ar: "أنبياء",
    desc_ar: "خاتم الأنبياء والمرسلين. أُنزل عليه القرآن في مكة والمدينة. هاجر من مكة وأقام دولة الإسلام. ذُكرت سيرته في آيات كثيرة من أحداث بدر وأحد والخندق وصلح الحديبية وفتح مكة.",
    desc_en: "The Seal of the Prophets. The Quran was revealed to him in Mecca and Medina. He migrated from Mecca and established the Muslim community. His biography is woven throughout the Quran including Badr, Uhud, the Trench, Hudaybiyyah, and the Conquest of Mecca.",
    refs: ["3:144", "8:1-75", "9:40", "9:128", "17:1", "33:21", "33:40", "33:56", "36:1-12", "47:2", "48:1-29", "53:1-18", "62:2", "93:1-11", "94:1-8"],
    figures_ar: "محمد، خديجة، أبو بكر، عائشة",
    figures_en: "Muhammad, Khadijah, Abu Bakr, Aisha",
    primary: 48
  },

  // ═══════════════════════════════════════════════════════════════
  // NATIONS & PEOPLES (11)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 26,
    ar: "قوم عاد",
    en: "People of 'Ad",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "قوم عملاقة سكنوا الأحقاف في جنوب الجزيرة العربية وبنوا إرَم ذات العماد. كفروا وتجبّروا فأهلكهم الله بريح صرصر عاتية.",
    desc_en: "A mighty people who lived in al-Ahqaf (southern Arabia) and built Iram of the Pillars. They were arrogant and disbelieved, so God annihilated them with a furious howling wind.",
    refs: ["7:65-72", "11:50-60", "26:123-140", "41:15-16", "46:21-26", "51:41-42", "54:18-22", "69:6-8", "89:6-8"],
    figures_ar: "هود، عاد",
    figures_en: "Hud, People of 'Ad",
    primary: 69
  },
  {
    id: 27,
    ar: "قوم ثمود",
    en: "People of Thamud",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "نحتوا البيوت في الجبال بالحِجر. أُرسل إليهم صالح بالناقة آية فعقروها، فأخذتهم الصيحة والرجفة.",
    desc_en: "They carved dwellings into the mountains at al-Hijr. God sent Salih with a she-camel as a sign, but they hamstrung her and were seized by a thunderous blast.",
    refs: ["7:73-79", "11:61-68", "15:80-84", "17:59", "26:141-159", "27:45-53", "41:17", "51:43-45", "54:23-32", "69:4-5", "85:17-18", "89:9-13", "91:11-15"],
    figures_ar: "صالح، ثمود",
    figures_en: "Salih, People of Thamud",
    primary: 91
  },
  {
    id: 28,
    ar: "أهل مدين",
    en: "People of Madyan",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "قوم شعيب الذين كانوا يُنقصون المكيال والميزان ويفسدون في الأرض. كذّبوا شعيباً فأخذتهم الرجفة والظُّلّة.",
    desc_en: "Shu'ayb's people who cheated in weights and measures and spread corruption. They rejected him and were struck by earthquake and the shadow of a scorching cloud.",
    refs: ["7:85-93", "9:70", "11:84-95", "20:40", "22:44", "26:176-191", "28:22-28", "29:36-37"],
    figures_ar: "شعيب، مدين",
    figures_en: "Shu'ayb, People of Madyan",
    primary: 11
  },
  {
    id: 29,
    ar: "قوم لوط",
    en: "People of Lut",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "سكان سدوم وعمورة الذين أتوا الفاحشة واعتدوا على ضيوف لوط. قلب الله عليهم ديارهم وأمطرهم حجارة من سجّيل.",
    desc_en: "Inhabitants of Sodom and Gomorrah who committed grave immorality and assaulted Lut's guests. God overturned their cities and rained upon them stones of baked clay.",
    refs: ["7:80-84", "11:77-83", "15:57-77", "26:160-175", "27:54-58", "29:28-35", "37:133-138", "51:31-37", "54:33-40"],
    figures_ar: "لوط، امرأة لوط",
    figures_en: "Lut, Wife of Lut",
    primary: 15
  },
  {
    id: 30,
    ar: "قوم نوح",
    en: "People of Nuh",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "أول قوم أشركوا بالله بعد آدم. دعاهم نوح قروناً طويلة فاستكبروا وسخروا منه حتى أغرقهم الله بالطوفان.",
    desc_en: "The first people to practice polytheism after Adam. Nuh called them for centuries but they mocked him and were arrogant, until God drowned them in the Great Flood.",
    refs: ["7:59-64", "10:71-73", "11:25-49", "23:23-30", "25:37", "26:105-122", "29:14-15", "37:75-82", "54:9-17", "71:1-28"],
    figures_ar: "نوح، ابن نوح",
    figures_en: "Nuh (Noah), Son of Nuh",
    primary: 71
  },
  {
    id: 31,
    ar: "آل فرعون",
    en: "People of Pharaoh",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "فرعون وملؤه الذين استعبدوا بني إسرائيل وادّعى فرعون الربوبية. أرسل الله إليهم موسى بتسع آيات بيّنات فأصرّوا، فأغرقهم الله في البحر.",
    desc_en: "Pharaoh and his establishment who enslaved the Children of Israel. Pharaoh claimed divinity. God sent Musa with nine clear signs, but they persisted, and God drowned them in the sea.",
    refs: ["2:49-50", "7:103-141", "8:52-54", "10:75-92", "11:96-99", "20:24-79", "26:10-68", "28:1-42", "40:23-46", "43:46-56", "44:17-33", "51:38-40", "79:15-26"],
    figures_ar: "فرعون، هامان، موسى، آسية",
    figures_en: "Pharaoh, Haman, Musa, Asiya",
    primary: 7
  },
  {
    id: 32,
    ar: "بنو إسرائيل",
    en: "Children of Israel",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "ذرية يعقوب الذين أنجاهم الله من فرعون وآتاهم الكتاب والنبوة. ابتُلوا بالتيه أربعين سنة وكثرت فيهم المعاصي مع ما أنعم الله عليهم.",
    desc_en: "Descendants of Yaqub whom God saved from Pharaoh and granted scripture and prophethood. They wandered the desert for forty years and were repeatedly tested despite God's immense blessings.",
    refs: ["2:40-74", "2:83-93", "2:122", "2:211", "2:246-252", "5:12-26", "5:70-78", "7:138-171", "10:90-93", "17:2-8", "17:101-104", "20:80-98", "26:59-67", "44:30-33", "45:16-17"],
    figures_ar: "بنو إسرائيل، موسى، هارون",
    figures_en: "Children of Israel, Musa, Harun",
    primary: 2
  },
  {
    id: 33,
    ar: "أهل سبأ",
    en: "People of Saba (Sheba)",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "سكنوا اليمن وكانت لهم جنّتان عن يمين وشمال ونعمة عظيمة. أعرضوا عن شكر الله فأرسل عليهم سيل العرم وبدّل جنتيهم.",
    desc_en: "They lived in Yemen with two gardens and great prosperity. They turned away from gratitude, so God sent the flood of the dam (Sayl al-'Arim) and replaced their gardens with bitter fruit.",
    refs: ["27:22-44", "34:15-21"],
    figures_ar: "ملكة سبأ (بلقيس)، سليمان",
    figures_en: "Queen of Sheba (Bilqis), Sulayman",
    primary: 34
  },
  {
    id: 34,
    ar: "أصحاب الفيل",
    en: "People of the Elephant",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "جيش أبرهة الحبشي الذي جاء بالفيلة لهدم الكعبة. أرسل الله عليهم طيراً أبابيل ترميهم بحجارة من سجّيل فجعلهم كعصف مأكول.",
    desc_en: "The Abyssinian army of Abraha that marched with elephants to destroy the Ka'ba. God sent flocks of birds pelting them with stones of baked clay, leaving them like devoured stalks.",
    refs: ["105:1-5"],
    figures_ar: "أبرهة",
    figures_en: "Abraha",
    primary: 105
  },
  {
    id: 35,
    ar: "قوم تبّع",
    en: "People of Tubba'",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "ملوك حمير في اليمن. ذُكروا في القرآن تحذيراً فقد كانوا أشدّ قوة ثم أُهلكوا لتكذيبهم.",
    desc_en: "The Himyarite kings of Yemen mentioned as a warning. They were mightier than the Quraysh yet were destroyed for their denial.",
    refs: ["44:37", "50:14"],
    figures_ar: "تبّع",
    figures_en: "Tubba'",
    primary: 44
  },
  {
    id: 36,
    ar: "أصحاب الأخدود",
    en: "People of the Ditch (Ukhdud)",
    cat: "nation",
    cat_ar: "أمم وأقوام",
    desc_ar: "ملك ظالم حفر أخدوداً وأوقد فيه النار وألقى فيه المؤمنين لأنهم رفضوا ترك إيمانهم. لعنهم الله وتوعّدهم بعذاب جهنم.",
    desc_en: "A tyrant king dug trenches filled with fire and cast in the believers who refused to renounce their faith. God cursed the perpetrators and promised them the punishment of Hell.",
    refs: ["85:1-11"],
    figures_ar: "المؤمنون، الملك الظالم",
    figures_en: "The Believers, The Tyrannical King",
    primary: 85
  },

  // ═══════════════════════════════════════════════════════════════
  // EVENTS (20)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 37,
    ar: "خلق السماوات والأرض",
    en: "Creation of the Universe",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "خلق الله السماوات والأرض في ستة أيام. كانتا رتقاً ففتقهما وجعل من الماء كل شيء حي وأقام السماء بغير عمد.",
    desc_en: "God created the heavens and earth in six periods. They were a joined entity which He split apart, made every living thing from water, and raised the sky without pillars.",
    refs: ["2:29", "6:1", "7:54", "10:3", "11:7", "13:2", "21:30-33", "25:59", "32:4", "41:9-12", "50:38", "51:47-48", "57:4", "65:12", "67:3-4", "71:15-16", "79:27-33"],
    figures_ar: "",
    figures_en: "",
    primary: 41
  },
  {
    id: 38,
    ar: "خلق آدم",
    en: "Creation of Adam",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "خلق الله آدم من صلصال من حمأ مسنون ونفخ فيه من روحه وعلّمه الأسماء كلها. أمر الملائكة بالسجود فسجدوا إلا إبليس أبى واستكبر.",
    desc_en: "God created Adam from sounding clay of altered dark mud, breathed His spirit into him, and taught him all the names. He commanded the angels to prostrate; all did except Iblis who refused out of arrogance.",
    refs: ["2:30-34", "7:11-12", "15:26-31", "17:61", "18:50", "20:115-116", "23:12-14", "32:7-9", "38:71-76", "55:14", "76:1"],
    figures_ar: "آدم، الملائكة، إبليس",
    figures_en: "Adam, The Angels, Iblis",
    primary: 15
  },
  {
    id: 39,
    ar: "قصة هابيل وقابيل",
    en: "Cain and Abel (Habil and Qabil)",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "قدّم ابنا آدم قرباناً فتُقبّل من أحدهما ولم يُتقبّل من الآخر. قتل قابيل أخاه هابيل حسداً فكان من الخاسرين وعلّمه الغراب كيف يواري سوأة أخيه.",
    desc_en: "Two sons of Adam each offered a sacrifice; one was accepted and the other was not. Cain killed Abel out of jealousy and a crow showed him how to bury the body - the first murder in history.",
    refs: ["5:27-31"],
    figures_ar: "هابيل، قابيل",
    figures_en: "Habil (Abel), Qabil (Cain)",
    primary: 5
  },
  {
    id: 40,
    ar: "الطوفان العظيم",
    en: "The Great Flood",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "فار التنور وفُتحت أبواب السماء بماء منهمر فغرقت الأرض. نجا نوح ومن آمن معه في السفينة واستوت على الجودي.",
    desc_en: "The oven gushed forth and the gates of heaven opened with torrential rain, flooding the earth. Nuh and the believers were saved in the Ark, which came to rest on Mount Judi.",
    refs: ["7:59-64", "11:36-48", "23:27-30", "26:117-122", "29:14-15", "37:75-82", "54:9-17", "69:11-12", "71:25-28"],
    figures_ar: "نوح، ابن نوح",
    figures_en: "Nuh, Son of Nuh",
    primary: 11
  },
  {
    id: 41,
    ar: "هلاك سدوم",
    en: "Destruction of Sodom",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "جاءت الملائكة لوطاً في صورة ضيوف حسان. حاول قومه الاعتداء عليهم فأعمى الله أبصارهم ثم قلب المدينة وأمطرها حجارة من سجّيل.",
    desc_en: "Angels came to Lut disguised as handsome guests. His people tried to assault them, so God blinded them, then overturned the city and rained upon it stones of baked clay.",
    refs: ["11:77-83", "15:57-77", "26:160-175", "29:31-35", "37:133-138", "51:31-37", "54:33-39"],
    figures_ar: "لوط، الملائكة",
    figures_en: "Lut, The Angels",
    primary: 11
  },
  {
    id: 42,
    ar: "بناء الكعبة",
    en: "Building of the Ka'ba",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "رفع إبراهيم وإسماعيل القواعد من البيت الحرام وطهّراه ودعوا الله أن يتقبّل منهما ويجعل ذريتهما مسلمة.",
    desc_en: "Ibrahim and Ismail raised the foundations of the Sacred House, purified it, and prayed to God to accept their work and make their descendants a nation submitting to Him.",
    refs: ["2:125-129", "3:96-97", "14:35-37", "22:26-29"],
    figures_ar: "إبراهيم، إسماعيل",
    figures_en: "Ibrahim, Ismail",
    primary: 2
  },
  {
    id: 43,
    ar: "ذبح إبراهيم لابنه",
    en: "Sacrifice of Ibrahim",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "رأى إبراهيم في المنام أنه يذبح ابنه. عرض الأمر على ابنه فأسلما لأمر الله. فلمّا تلّه للجبين فداه الله بذبح عظيم.",
    desc_en: "Ibrahim saw in a dream that he was sacrificing his son. They both submitted to God's command, and as he laid his son down, God ransomed him with a great sacrifice.",
    refs: ["37:100-111"],
    figures_ar: "إبراهيم، إسماعيل",
    figures_en: "Ibrahim, Ismail",
    primary: 37
  },
  {
    id: 44,
    ar: "الخروج من مصر",
    en: "The Exodus",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "أمر الله موسى أن يخرج ببني إسرائيل ليلاً من مصر فتبعهم فرعون وجنوده حتى أدركوهم عند البحر.",
    desc_en: "God commanded Musa to lead the Children of Israel out of Egypt by night. Pharaoh and his armies pursued them until they reached the sea.",
    refs: ["7:137-141", "10:90", "20:77-79", "26:52-67", "44:23-24"],
    figures_ar: "موسى، فرعون، بنو إسرائيل",
    figures_en: "Musa, Pharaoh, Children of Israel",
    primary: 26
  },
  {
    id: 45,
    ar: "فلق البحر",
    en: "Parting of the Sea",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "أوحى الله إلى موسى أن يضرب البحر بعصاه فانفلق كل فرق كالطود العظيم. عبر بنو إسرائيل وأغرق الله فرعون وجنوده.",
    desc_en: "God revealed to Musa to strike the sea with his staff. It split, each part like a towering mountain. The Israelites crossed safely while Pharaoh and his army drowned.",
    refs: ["2:50", "7:136-138", "10:90-92", "20:77-78", "26:63-67", "44:24-29"],
    figures_ar: "موسى، فرعون",
    figures_en: "Musa, Pharaoh",
    primary: 26
  },
  {
    id: 46,
    ar: "عبادة العجل",
    en: "The Golden Calf",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "غاب موسى أربعين ليلة لميقات ربه فصنع السامري عجلاً من الحليّ له خوار. عبده بنو إسرائيل فغضب موسى وأحرق العجل ونسفه.",
    desc_en: "During Musa's forty-night absence on Mount Sinai, al-Samiri fashioned a calf from gold ornaments that made a lowing sound. The Israelites worshipped it, and upon return, Musa burned and destroyed the idol.",
    refs: ["2:51-54", "2:92-93", "4:153", "7:148-156", "20:83-98"],
    figures_ar: "موسى، هارون، السامري",
    figures_en: "Musa, Harun, Al-Samiri",
    primary: 20
  },
  {
    id: 47,
    ar: "موسى والخضر",
    en: "Musa Meets al-Khidr",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "رحل موسى مع فتاه ليلقى عبداً صالحاً آتاه الله علماً لدنياً. صحبه فرأى منه أفعالاً عجيبة: خرق السفينة وقتل الغلام وبناء الجدار، ثم بيّن له حكمتها.",
    desc_en: "Musa traveled with his servant to meet a righteous servant granted special knowledge by God. He witnessed three puzzling acts - damaging a ship, killing a boy, and repairing a wall - then the servant revealed the divine wisdom behind each.",
    refs: ["18:60-82"],
    figures_ar: "موسى، الخضر، فتى موسى",
    figures_en: "Musa, Al-Khidr, Servant of Musa",
    primary: 18
  },
  {
    id: 48,
    ar: "داود وجالوت",
    en: "David and Goliath",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "بعث الله طالوت ملكاً لبني إسرائيل. خرجوا لقتال جالوت فقتله داود وهو فتى وآتاه الله الملك والحكمة.",
    desc_en: "God appointed Talut (Saul) as king of Israel. They marched against Goliath's army, and the young Dawud slew Jalut. God then granted Dawud kingship and wisdom.",
    refs: ["2:246-252"],
    figures_ar: "داود، جالوت، طالوت",
    figures_en: "Dawud (David), Jalut (Goliath), Talut (Saul)",
    primary: 2
  },
  {
    id: 49,
    ar: "ملكة سبأ وسليمان",
    en: "Queen of Sheba and Solomon",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "أخبر الهدهد سليمان بملكة تعبد الشمس. أرسل إليها كتاباً فجاءت وأُحضر عرشها في لمح البصر. دخلت الصرح فحسبته لجّة فأسلمت لله.",
    desc_en: "The hoopoe informed Sulayman of a queen who worshipped the sun. He sent her a letter; she came and her throne was brought in the blink of an eye. She entered the crystal palace, mistook it for water, and submitted to God.",
    refs: ["27:15-44"],
    figures_ar: "سليمان، بلقيس، الهدهد",
    figures_en: "Sulayman, Bilqis (Queen of Sheba), The Hoopoe",
    primary: 27
  },
  {
    id: 50,
    ar: "ميلاد عيسى",
    en: "Birth of Isa (Jesus)",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "أرسل الله جبريل إلى مريم فنفخ فيها فحملت بعيسى بلا أب. وضعته تحت النخلة وهزّتها فتساقط عليها الرطب. حملته إلى قومها فتكلّم في المهد مدافعاً عنها.",
    desc_en: "God sent Jibril to Maryam and she conceived Isa without a father. She gave birth under a palm tree which showered dates upon her. She brought the baby to her people and he spoke from the cradle in her defense.",
    refs: ["3:42-49", "19:16-33", "21:91", "23:50", "66:12"],
    figures_ar: "عيسى، مريم، جبريل",
    figures_en: "Isa (Jesus), Maryam (Mary), Jibril (Gabriel)",
    primary: 19
  },
  {
    id: 51,
    ar: "الإسراء والمعراج",
    en: "The Night Journey and Ascension (Isra & Mi'raj)",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "أسرى الله بنبيه محمد ليلاً من المسجد الحرام إلى المسجد الأقصى ثم عُرج به إلى السماوات العُلا حيث رأى من آيات ربه الكبرى.",
    desc_en: "God transported Prophet Muhammad by night from the Sacred Mosque to the Farthest Mosque, then ascended him through the heavens where he witnessed the greatest signs of his Lord.",
    refs: ["17:1", "53:1-18"],
    figures_ar: "محمد، جبريل",
    figures_en: "Muhammad, Jibril (Gabriel)",
    primary: 17
  },
  {
    id: 52,
    ar: "غزوة بدر",
    en: "Battle of Badr",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "أول معركة فاصلة في الإسلام. نصر الله المسلمين وهم قلة على قريش بألف من الملائكة مردفين يوم الفرقان.",
    desc_en: "The first decisive battle in Islam. God granted victory to the outnumbered Muslims over Quraysh, reinforcing them with a thousand angels on the Day of Criterion.",
    refs: ["3:13", "3:123-127", "8:1-19", "8:41-48", "8:65-75"],
    figures_ar: "محمد، المسلمون، قريش",
    figures_en: "Muhammad, The Muslims, Quraysh",
    primary: 8
  },
  {
    id: 53,
    ar: "غزوة أحد",
    en: "Battle of Uhud",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "خرج المسلمون لملاقاة قريش عند جبل أحد. تراجع الرماة عن مواقعهم فانقلبت المعركة وأُصيب النبي. عاتبهم الله ثم عفا عنهم.",
    desc_en: "The Muslims faced Quraysh at Mount Uhud. Archers abandoned their posts, turning the tide. The Prophet was injured. God admonished then forgave them.",
    refs: ["3:121-179"],
    figures_ar: "محمد، المسلمون، قريش",
    figures_en: "Muhammad, The Muslims, Quraysh",
    primary: 3
  },
  {
    id: 54,
    ar: "غزوة الخندق (الأحزاب)",
    en: "Battle of the Trench (Al-Ahzab)",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "تحزّبت القبائل على المدينة فحفر المسلمون خندقاً. أرسل الله ريحاً وجنوداً لم يروها فانهزم الأحزاب بلا قتال.",
    desc_en: "A coalition of tribes besieged Medina, so the Muslims dug a trench. God sent wind and unseen forces that routed the confederates without battle.",
    refs: ["33:9-27"],
    figures_ar: "محمد، المسلمون، الأحزاب",
    figures_en: "Muhammad, The Muslims, The Confederates",
    primary: 33
  },
  {
    id: 55,
    ar: "صلح الحديبية",
    en: "Treaty of Hudaybiyyah",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "خرج المسلمون معتمرين فصدّتهم قريش. عقد النبي صلحاً مع قريش بدا ظاهره ضرراً لكنه كان فتحاً مبيناً فتح الطريق لفتح مكة.",
    desc_en: "The Muslims set out for Umrah but Quraysh blocked them. The Prophet signed a treaty that seemed disadvantageous but was declared a manifest victory, paving the way for the Conquest of Mecca.",
    refs: ["48:1-29"],
    figures_ar: "محمد، قريش",
    figures_en: "Muhammad, Quraysh",
    primary: 48
  },
  {
    id: 56,
    ar: "فتح مكة",
    en: "Conquest of Mecca",
    cat: "event",
    cat_ar: "أحداث",
    desc_ar: "دخل النبي مكة فاتحاً بعشرة آلاف مقاتل دون قتال يُذكر. طهّر الكعبة من الأصنام وعفا عن أهل مكة.",
    desc_en: "The Prophet entered Mecca victoriously with ten thousand fighters and virtually no bloodshed. He purified the Ka'ba of idols and pardoned the people of Mecca.",
    refs: ["48:18-28", "110:1-3"],
    figures_ar: "محمد",
    figures_en: "Muhammad",
    primary: 110
  },

  // ═══════════════════════════════════════════════════════════════
  // PARABLES (8)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 57,
    ar: "أصحاب الكهف",
    en: "People of the Cave",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "فتية آمنوا بربهم ففرّوا بدينهم إلى كهف فأنامهم الله ثلاثمائة سنة وازدادوا تسعاً ثم بعثهم آيةً للناس.",
    desc_en: "Young men who believed in their Lord and fled to a cave to protect their faith. God made them sleep for 309 years then awakened them as a sign for mankind.",
    refs: ["18:9-26"],
    figures_ar: "أصحاب الكهف، الرقيم",
    figures_en: "Sleepers of the Cave, Al-Raqim",
    primary: 18
  },
  {
    id: 58,
    ar: "صاحب الجنتين",
    en: "Owner of Two Gardens",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "رجل أعطاه الله جنتين من أعناب فتكبّر وظنّ أنها لن تبيد. حاوره صاحبه المؤمن فلم يرتدع فأحاط الله بثمره وأصبح يقلّب كفّيه ندماً.",
    desc_en: "A man blessed with two lush gardens became arrogant and thought they would never perish. His believing companion warned him, but he dismissed it. God destroyed his gardens and he was left wringing his hands in regret.",
    refs: ["18:32-44"],
    figures_ar: "صاحب الجنتين، صاحبه المؤمن",
    figures_en: "Owner of Two Gardens, His Believing Companion",
    primary: 18
  },
  {
    id: 59,
    ar: "ذو القرنين",
    en: "Dhul-Qarnayn",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "ملك صالح مكّن الله له في الأرض. بلغ مغرب الشمس ومطلعها وبنى سدّاً من حديد ونحاس ليمنع يأجوج ومأجوج من الإفساد.",
    desc_en: "A righteous king whom God empowered across the earth. He traveled to the far west and east, and built a barrier of iron and copper to hold back Gog and Magog from spreading corruption.",
    refs: ["18:83-101"],
    figures_ar: "ذو القرنين، يأجوج ومأجوج",
    figures_en: "Dhul-Qarnayn, Gog and Magog (Ya'juj and Ma'juj)",
    primary: 18
  },
  {
    id: 60,
    ar: "وصايا لقمان",
    en: "Luqman's Advice",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "آتى الله لقمان الحكمة فوعظ ابنه بالتوحيد والصلاة والأمر بالمعروف والنهي عن المنكر والصبر والتواضع وخفض الصوت.",
    desc_en: "God granted Luqman wisdom, and he counselled his son on monotheism, prayer, enjoining good, forbidding evil, patience, humility, and lowering one's voice.",
    refs: ["31:12-19"],
    figures_ar: "لقمان، ابنه",
    figures_en: "Luqman, His Son",
    primary: 31
  },
  {
    id: 61,
    ar: "أصحاب الجنة (سورة القلم)",
    en: "People of the Garden (Surah Al-Qalam)",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "أصحاب بستان أقسموا ليقطعنّ ثمره دون أن يُطعموا المساكين. فطاف عليها بلاء من ربهم وهم نائمون فأصبحت كالصريم.",
    desc_en: "Owners of a garden swore to harvest it at dawn without feeding the poor. God sent a calamity upon it while they slept, reducing it to barren wasteland.",
    refs: ["68:17-33"],
    figures_ar: "أصحاب الجنة",
    figures_en: "People of the Garden",
    primary: 68
  },
  {
    id: 62,
    ar: "بقرة بني إسرائيل",
    en: "The Cow of Bani Israel",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "أمر الله بني إسرائيل بذبح بقرة لكشف قاتل. تعنّتوا في الأسئلة فشُدّد عليهم. ذبحوها وضربوا الميت ببعضها فأحياه الله وأخبرهم بالقاتل.",
    desc_en: "God commanded the Israelites to slaughter a cow to reveal a murderer. They kept asking nitpicking questions, making it harder on themselves. They struck the dead man with part of the cow and God brought him to life to identify his killer.",
    refs: ["2:67-73"],
    figures_ar: "بنو إسرائيل، موسى",
    figures_en: "Children of Israel, Musa",
    primary: 2
  },
  {
    id: 63,
    ar: "عُزير",
    en: "Uzair (Ezra) - Resurrection after a Hundred Years",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "مرّ على قرية خاوية فتساءل كيف يُحييها الله بعد موتها. فأماته الله مائة عام ثم بعثه وأراه كيف أحيا طعامه وحماره آية على البعث.",
    desc_en: "A man passed by a ruined town and wondered how God could restore it. God caused him to die for a hundred years then raised him, showing him how his food and donkey were revived as proof of resurrection.",
    refs: ["2:259", "9:30"],
    figures_ar: "عُزير",
    figures_en: "Uzair (Ezra)",
    primary: 2
  },
  {
    id: 64,
    ar: "مثل العنكبوت",
    en: "The Spider's Web",
    cat: "parable",
    cat_ar: "أمثال وعبر",
    desc_ar: "ضرب الله مثل الذين اتخذوا أولياء من دون الله كمثل العنكبوت اتخذت بيتاً، وإن أوهن البيوت لبيت العنكبوت.",
    desc_en: "God likened those who take protectors other than Him to a spider spinning a web - and the flimsiest of all dwellings is the spider's web.",
    refs: ["29:41"],
    figures_ar: "",
    figures_en: "",
    primary: 29
  },

  // ═══════════════════════════════════════════════════════════════
  // HISTORICAL FIGURES (5)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 65,
    ar: "مريم بنت عمران",
    en: "Maryam (Mary, daughter of Imran)",
    cat: "figure",
    cat_ar: "شخصيات تاريخية",
    desc_ar: "المرأة الوحيدة المسمّاة في القرآن. اصطفاها الله وطهّرها على نساء العالمين. نذرتها أمها لله وكفلها زكريا وحملت بعيسى بلا أب.",
    desc_en: "The only woman named in the Quran. God chose and purified her above all women. Her mother dedicated her to God's service, Zakariya was her guardian, and she conceived Isa without a father.",
    refs: ["3:33-47", "4:156", "4:171", "5:17", "5:75", "5:116", "19:16-34", "21:91", "23:50", "66:12"],
    figures_ar: "مريم، عمران، زكريا، عيسى",
    figures_en: "Maryam, Imran, Zakariya, Isa",
    primary: 19
  },
  {
    id: 66,
    ar: "قارون",
    en: "Qarun (Korah)",
    cat: "figure",
    cat_ar: "شخصيات تاريخية",
    desc_ar: "كان من قوم موسى فبغى عليهم. آتاه الله من الكنوز ما إنّ مفاتحه لتنوء بالعصبة فتكبّر. خسف الله به وبداره الأرض.",
    desc_en: "A man from Musa's people who was given such treasure that its keys alone burdened a group of strong men. He became arrogant, so God caused the earth to swallow him and his dwelling.",
    refs: ["28:76-82", "29:39", "40:24"],
    figures_ar: "قارون",
    figures_en: "Qarun (Korah)",
    primary: 28
  },
  {
    id: 67,
    ar: "هامان",
    en: "Haman",
    cat: "figure",
    cat_ar: "شخصيات تاريخية",
    desc_ar: "وزير فرعون الذي أمره ببناء صرح عالٍ ليطّلع إلى إله موسى. كان شريكاً في الظلم والطغيان وأُهلك مع فرعون.",
    desc_en: "Pharaoh's minister who was ordered to build a lofty tower to reach Musa's God. He was a partner in tyranny and oppression and was destroyed alongside Pharaoh.",
    refs: ["28:6", "28:8", "28:38", "29:39", "40:24", "40:36-37"],
    figures_ar: "هامان، فرعون",
    figures_en: "Haman, Pharaoh",
    primary: 28
  },
  {
    id: 68,
    ar: "جالوت",
    en: "Jalut (Goliath)",
    cat: "figure",
    cat_ar: "شخصيات تاريخية",
    desc_ar: "جبّار عظيم قاد جيشاً ضد بني إسرائيل. قتله داود وهو فتى صغير بإذن الله، وكان في ذلك آية على أنّ النصر بالإيمان لا بالعدد.",
    desc_en: "A mighty warrior who led an army against the Children of Israel. The young Dawud slew him by God's leave - a sign that victory comes through faith, not numbers.",
    refs: ["2:249-251"],
    figures_ar: "جالوت، داود، طالوت",
    figures_en: "Jalut (Goliath), Dawud (David), Talut (Saul)",
    primary: 2
  },
  {
    id: 69,
    ar: "طالوت",
    en: "Talut (Saul)",
    cat: "figure",
    cat_ar: "شخصيات تاريخية",
    desc_ar: "ملك اختاره الله لبني إسرائيل رغم اعتراضهم لأنه لم يكن غنياً. اختبر جنوده بنهر فلم يصبر أكثرهم. قاد المؤمنين الصابرين لقتال جالوت ونصرهم الله.",
    desc_en: "A king chosen by God for the Israelites despite their objection that he lacked wealth. He tested his soldiers at a river - most failed. He led the steadfast believers against Goliath and God granted them victory.",
    refs: ["2:247-249"],
    figures_ar: "طالوت، داود، جالوت",
    figures_en: "Talut (Saul), Dawud (David), Jalut (Goliath)",
    primary: 2
  }
];
