// History Claims: popular claims that a verse matches the ancient record, checked one by one.
// Verse text is NOT stored here. Cards read it live from corpus.js (QURAN_VERSES) and translation_en.js (QURAN_EN) by key.
// Years are numbers (negative = BCE). lost = last year the record could be read (null = never lost before the revelation).
// verdict: 'holds' | 'partial' | 'weak' (how well the claim as stated survives the evidence). card_* is the one-line answer on the index.
// region: 'egypt' | 'arabia' | 'neareast'. To add a claim, add an entry with the same shape.
// videos: where the claim circulates (YouTube id, t = start in seconds, short: true for a Short). Each was checked against its transcript.
// diff_*: how the videos tell it differently from the summary. acc_*: replaces the timeline sentence when there is no written record.

const QURAN_HISTORY_INTRO = {
  en: "Short videos often say a verse matches something only an archaeologist could know. We take those claims one at a time: what the ancient record really says, whether anyone in 7th-century Arabia could have read it, and what the other side argues.",
  ar: "كثيرًا ما تقول المقاطع القصيرة إن آيةً ما توافق أمرًا لا يعرفه إلا علماء الآثار. نأخذ هنا هذه المزاعم واحدًا واحدًا: ما يقوله الأثر القديم فعلًا، وهل كان في وسع أحدٍ في جزيرة العرب في القرن السابع أن يقرأه، وما حجة الطرف الآخر."
};

const QURAN_HISTORY = [
  {
    id: 'weep', region: 'egypt', verdict: 'partial', featured: true,
    card_en: "Partly. The Egyptian line is real and the verse answers it, but the short overstates how long it was lost, and Arabs had the phrase too.",
    card_ar: "جزئيًا. العبارة المصرية ثابتة والآية تردّ عليها، لكن المقطع يبالغ في مدة ضياعها، والعرب عرفوا العبارة كذلك.",
    tag_en: 'Viral short', tag_ar: 'مقطع منتشر',
    title_en: 'The sky did not weep for them', title_ar: 'فما بكت عليهم السماء',
    short_en: 'Sky did not weep', short_ar: 'لم تبكِ السماء',
    refs: ['44:29'],
    quote_en: 'The sky weeps for thee; the earth trembles for thee.',
    quote_ar: 'السماء تبكي عليك، والأرض ترتجف لك.',
    quote_lab_en: 'Pyramid Texts, Utterance 553', quote_lab_ar: 'نصوص الأهرام، التعويذة ٥٥٣',
    quote_note_en: 'Said to the dead king. Carved inside royal pyramids about 2300 BCE.',
    quote_note_ar: 'خطابٌ للملك الميت، نُقش داخل أهرام الملوك نحو سنة ٢٣٠٠ قبل الميلاد.',
    claim_en: "Ancient Egyptian royal texts said the sky and the earth weep when a king dies. The verse says they did not weep for Pharaoh's people. The claim adds that nobody could read those texts until the 19th century.",
    claim_ar: "كانت نصوص الملوك في مصر القديمة تقول إن السماء والأرض تبكيان إذا مات الملك، والآية تنفي هذا البكاء عن قوم فرعون. ويضيف أصحاب هذا الطرح أن أحدًا لم يكن يقدر على قراءة تلك النصوص حتى القرن التاسع عشر.",
    record_en: "The Pyramid Texts, Utterance 553, say to the dead king: \"The sky weeps for thee; the earth trembles for thee.\" These texts were carved inside royal pyramids of the late Old Kingdom, around 2300 BCE, and copied into later tombs for centuries. The pyramid walls themselves were seen again only in 1880, when Gaston Maspero opened the pyramids at Saqqara.",
    record_ar: "تخاطب «نصوص الأهرام» الملكَ الميت في التعويذة ٥٥٣ بقولها: «السماء تبكي عليك، والأرض ترتجف لك». وقد نُقشت هذه النصوص داخل أهرام الملوك في أواخر الدولة القديمة نحو سنة ٢٣٠٠ قبل الميلاد، وظلّت تُنسخ في المقابر قرونًا بعد ذلك. ولم تُرَ جدران الأهرام نفسها من جديد إلا سنة ١٨٨٠، حين فتح غاستون ماسبيرو أهرام سقارة.",
    check_en: "The match is real. \"The sky weeps for thee\" is a genuine Egyptian royal formula, and the verse withholds exactly that honour from the people whose religion claimed it. The short overstates the gap, though. It says the knowledge went dark in the 6th century BCE. In fact priests were still carving hieroglyphs at Philae in 394 CE, and the temple there was only closed in the 530s. Even so, the script was dead well before the revelation. Nobody could read it until Champollion in 1822, and these texts were not found until 1880.",
    check_ar: "التطابق حقيقي، فعبارة «السماء تبكي عليك» صيغةٌ ملكية مصرية ثابتة، والآية تنفي هذا التكريم عن القوم الذين كانت ديانتهم تدّعيه لملوكهم. غير أن المقطع يبالغ في طول الفجوة، إذ يقول إن هذا العلم انطمس منذ القرن السادس قبل الميلاد، والصحيح أن الكهنة ظلّوا ينقشون الهيروغليفية في فيلة حتى سنة ٣٩٤ للميلاد، وأن معبدها لم يُغلق إلا في ثلاثينيات القرن السادس. ومع ذلك كان الخطّ قد مات قبل نزول الوحي بزمن، ولم يقرأه أحدٌ حتى فكّ شامبليون رموزه سنة ١٨٢٢، ولم يُعثر على هذه النصوص إلا سنة ١٨٨٠.",
    counter_en: "Al-Zamakhshari (d. 1144) and al-Qurtubi (d. 1273) both record that Arabs honoured a great man's death by saying \"the sky and the earth wept for him\". So the phrase had a way into Arabic that did not pass through Egypt. The poems they quote as proof come from after the Quran, though, so how old that Arabic idiom really is stays an open question.",
    counter_ar: "ينقل الزمخشري (ت ٥٣٨ هـ) والقرطبي (ت ٦٧١ هـ) أن العرب كانت تقول إذا مات فيهم السيد: «بكت عليه السماء والأرض». فللعبارة طريقٌ إلى العربية لا يمرّ بمصر. لكن الأبيات التي يستشهدان بها لشعراء جاؤوا بعد نزول القرآن، فيبقى قِدَم هذا التعبير عند العرب سؤالًا مفتوحًا.",
    reading_en: "Ali and Ibn Abbas explained the verse this way: when a believer dies, his place of prayer on earth and the gate in the sky through which his deeds rose both weep for him. Pharaoh's people left neither behind.",
    reading_ar: "فسّرها عليٌّ وابن عباس بأن المؤمن إذا مات بكى عليه مُصلّاه من الأرض ومَصعدُ عمله من السماء، وقوم فرعون لم يتركوا هذا ولا ذاك.",
    written: -2300, written_en: 'Pyramid Texts carved', written_ar: 'نقش نصوص الأهرام',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1880, recovered_en: 'Pyramid Texts found at Saqqara', recovered_ar: 'العثور على نصوص الأهرام في سقارة',
    videos: [
      {id: '9APrP0cw6_A', short: true, by: 'itachii', title: "The Quran Described Pharaoh's Weeping THOUSANDS of Years Later, Hieroglyphics Confirm It"},
      {id: 'c2ovILc_sKY', t: 20, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"},
      {id: 'OKTS73lNwGU', t: 720, by: 'Purpose of Visit', title: '5 Miracles of the Quran in Ancient Egyptian Inscriptions'}],
    diff_en: "The short says \"neither the heavens nor the stars\" wept; the verse says the heaven and the earth. It also says hieroglyphs were lost from the 6th century BCE. The longer videos quote the Egyptian line in different translations, and one credits it to the Book of the Dead. It is from the Pyramid Texts.",
    diff_ar: "يقول المقطع القصير إن «السماوات والنجوم» لم تبكِ، والآية تقول السماء والأرض. ويقول إن الهيروغليفية ضاعت منذ القرن السادس قبل الميلاد. والمقاطع الأطول تنقل العبارة المصرية بترجماتٍ مختلفة، وأحدها ينسبها إلى «كتاب الموتى»، وهي من نصوص الأهرام.",
    source_en: "Pyramid Texts, Utterance 553, §1365 (S. A. B. Mercer translation, 1952). G. Maspero, excavations at Saqqara (1880 to 1881). Graffito of Esmet-Akhom, Philae, 24 August 394 CE. Tafsir of al-Zamakhshari (al-Kashshaf), al-Qurtubi and Ibn Kathir on 44:29.",
    source_ar: "نصوص الأهرام، التعويذة ٥٥٣، الفقرة ١٣٦٥ (ترجمة صموئيل ميرسر، ١٩٥٢). غاستون ماسبيرو، حفائر سقارة (١٨٨٠ إلى ١٨٨١). نقش إسمت-أخوم في فيلة، ٢٤ أغسطس ٣٩٤م. تفسير الزمخشري (الكشاف) والقرطبي وابن كثير للآية ٤٤:٢٩."
  },
  {
    id: 'king', region: 'egypt', verdict: 'holds', live: 'kingPharaoh',
    card_en: "Yes. \"Pharaoh\" never appears in Joseph's story, and Egypt only gave its king that title later.",
    card_ar: "نعم. لا يرد «فرعون» في قصة يوسف قط، ومصر لم تلقّب ملكها بهذا اللقب إلا لاحقًا.",
    title_en: 'A king for Joseph, a Pharaoh for Moses', title_ar: 'ملكٌ في قصة يوسف، وفرعونُ في قصة موسى',
    short_en: 'King vs Pharaoh', short_ar: 'الملك وفرعون',
    refs: ['12:43'], also: ['12:50', '12:54', '12:72', '12:76'],
    claim_en: "The Bible calls Egypt's ruler \"Pharaoh\" in Joseph's story and in Moses' story alike. The Quran calls Joseph's ruler \"the king\" and keeps \"Pharaoh\" for Moses' time, and the Egyptians only started calling their king \"Pharaoh\" later.",
    claim_ar: "تسمّي التوراة حاكم مصر «فرعون» في قصة يوسف وفي قصة موسى معًا، أما القرآن فيسمّي حاكم يوسف «الملك» ويحتفظ بلقب «فرعون» لعهد موسى. ويُقال إن المصريين لم يطلقوا لقب «فرعون» على ملكهم إلا في عصرٍ لاحق.",
    record_en: "Per-aa, \"great house\", meant the royal palace for most of Egyptian history. The first confirmed use of the word for the king himself is in a letter to Akhenaten (reigned about 1353 to 1336 BCE), possibly a century earlier under Thutmose III. It was first joined to a king's name as a title under Siamun, in the 10th century BCE.",
    record_ar: "كانت كلمة «پر-عا» ومعناها «البيت العظيم» تدلّ على القصر الملكي في معظم تاريخ مصر. وأقدم استعمالٍ مؤكد لها في الدلالة على الملك نفسه رسالةٌ إلى أخناتون (حكم نحو ١٣٥٣ إلى ١٣٣٦ قبل الميلاد)، وربما سبق ذلك بقرنٍ في عهد تحتمس الثالث. أما اقترانها باسم الملك لقبًا فأول ما ظهر في عهد سيامون في القرن العاشر قبل الميلاد.",
    check_en: "The Quran side is airtight, and the counts on this card are live from the corpus. The history side holds too: the title really did arrive late. What nobody can check is when Joseph lived. If his story is set before the 14th century BCE, the Quran's word choice fits the record and the Bible's does not.",
    check_ar: "جانب القرآن محسوم، والأعداد في هذه البطاقة تُحسب لحظيًا من المدونة. وجانب التاريخ صحيحٌ كذلك، فاللقب ظهر متأخرًا فعلًا. أما ما لا سبيل إلى التحقق منه فهو زمن يوسف، فإن كانت قصته قبل القرن الرابع عشر قبل الميلاد وافق لفظُ القرآن ما في الآثار، وخالفه لفظُ التوراة.",
    counter_en: "No Egyptian record names Joseph, so the argument rests on an assumed date. And \"king\" is the ordinary Arabic word for any ruler; choosing it is not, on its own, proof of special knowledge.",
    counter_ar: "لا يذكر أيُّ أثرٍ مصري يوسفَ باسمه، فالحجة قائمةٌ على تاريخٍ مفترض. ثم إن «الملك» هو اللفظ العربي المعتاد لكل حاكم، واختياره وحده لا يكفي دليلًا على علمٍ خاص.",
    written: -1350, written_en: '"Pharaoh" first used for the king', written_ar: 'أول إطلاق «فرعون» على الملك',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    videos: [
      {id: '9t1YWohFxWk', t: 0, by: 'THINK Muslim', title: 'King VS Pharaoh | Miracle of Quran'},
      {id: 'c2ovILc_sKY', t: 110, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The videos date Joseph to about the 17th century BCE, which is what makes the argument work. That date is an estimate, not a record.",
    diff_ar: "تؤرّخ المقاطع يوسف بنحو القرن السابع عشر قبل الميلاد، وعلى هذا التاريخ يقوم الاستدلال. وهو تقديرٌ لا أثرٌ مدوَّن.",
    source_en: "Title history of per-aa: Amarna-period letter to Akhenaten; Year 17 of Siamun. Counts: Quranic Arabic Corpus lemmas, computed in your browser.",
    source_ar: "تاريخ لقب «پر-عا»: رسالة من عصر العمارنة إلى أخناتون، والسنة السابعة عشرة من حكم سيامون. الأعداد: جذوع المدونة الصرفية للقرآن، محسوبة في متصفحك."
  },
  {
    id: 'tower', region: 'egypt', verdict: 'partial',
    card_en: "Partly. Egypt's kings were said to climb to the sky, as the verse has Pharaoh try. But a brick tower to heaven also recalls Babel.",
    card_ar: "جزئيًا. كانت نصوص مصر تصف ملوكها صاعدين إلى السماء، وهو ما يطلبه فرعون في الآية. لكن برجًا من الآجرّ يبلغ السماء يذكّر ببرج بابل أيضًا.",
    title_en: "Pharaoh's tower to the heavens", title_ar: 'صرح فرعون إلى السماوات',
    short_en: "Pharaoh's tower", short_ar: 'صرح فرعون',
    refs: ['40:36', '40:37'], also: ['28:38'],
    quote_en: 'A stairway to the sky is set up for me, that I may ascend on it to the sky.',
    quote_ar: 'نُصب لي سُلَّمٌ إلى السماء لأصعد عليه إلى السماء.',
    claim_en: "Pharaoh orders Haman to build him a tower so that he can reach \"the ways of the heavens\" and look at the God of Moses. The claim: this echoes a real Egyptian belief, written in the Pyramid Texts, that the king rises to the sky, and nobody could read those texts in the 7th century.",
    claim_ar: "يأمر فرعونُ هامانَ أن يبني له صرحًا لعلّه يبلغ «أسباب السماوات» فيطّلع إلى إله موسى. ويُقال إن في هذا صدًى لعقيدةٍ مصرية حقيقية مدوّنة في نصوص الأهرام، هي أن الملك يصعد إلى السماء، وإن أحدًا لم يكن يقرأ تلك النصوص في القرن السابع.",
    record_en: "The Pyramid Texts are full of the king's climb to the sky: by stairway, by ladder, by ramp, on wings. Utterance 267, carved for King Unas about 2350 BCE, says a stairway to the sky is set up for him. Royal builders used the same language: Bakenkhonsu, chief of works under Ramesses II, boasts on his statue of obelisks that reached to the sky.",
    record_ar: "تمتلئ نصوص الأهرام بصعود الملك إلى السماء: على دَرَج، وعلى سُلَّم، وعلى منحدر، وبأجنحة. وتقول التعويذة ٢٦٧، المنقوشة للملك أوناس نحو سنة ٢٣٥٠ قبل الميلاد، إن سُلَّمًا إلى السماء نُصب له. واستعمل بنّاؤو الملوك اللغة نفسها، فباكنخونسو، رئيس الأشغال في عهد رمسيس الثاني، يفخر على تمثاله بمسلّاتٍ بلغت السماء.",
    check_en: "The Egyptian idea is real and the verse fits it: the king wants a way up to the sky. But the verse is about a living king building in baked clay to look for God, and the Egyptian texts are about a dead king's soul. The match is in the theme, not in the detail.",
    check_ar: "الفكرة المصرية ثابتة والآية توافقها، فالملك يريد طريقًا إلى السماء. غير أن الآية تتحدث عن ملكٍ حيٍّ يبني بالطين المحروق ليطّلع إلى الإله، والنصوص المصرية تتحدث عن روح ملكٍ ميت. فالتوافق في المعنى العام لا في التفصيل.",
    counter_en: "A tower of baked brick built to reach heaven is the story of Babel in Genesis 11, set in Mesopotamia. Critics say the Quran has moved that story to Egypt, whose great monuments were of stone.",
    counter_ar: "برجٌ من الآجرّ المحروق يُبنى ليبلغ السماء هو قصة برج بابل في الإصحاح الحادي عشر من سفر التكوين، وموضعها بلاد الرافدين. ويقول النقّاد إن القرآن نقل تلك القصة إلى مصر، وعمائرُ مصر الكبرى كانت من الحجر.",
    videos: [{id: 'c2ovILc_sKY', t: 1470, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The video goes a step further and says the tower is not a literal tower at all, only a symbol of this belief. The verse itself speaks of baked clay and a building.",
    diff_ar: "يذهب المقطع أبعد من ذلك، فيقول إن الصرح ليس بناءً حقيقيًا بل رمزٌ لهذه العقيدة. والآية نفسها تذكر الطين المحروق والبناء.",
    written: -2350, written_en: 'Pyramid Texts carved for King Unas', written_ar: 'نقش نصوص الأهرام للملك أوناس',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1880, recovered_en: 'Pyramid Texts found at Saqqara', recovered_ar: 'العثور على نصوص الأهرام في سقارة',
    source_en: "Pyramid Texts, Utterance 267, §365 (R. O. Faulkner translation, 1969). Block statue of Bakenkhonsu, Staatliches Museum Ägyptischer Kunst, Munich. Genesis 11:3-4.",
    source_ar: "نصوص الأهرام، التعويذة ٢٦٧، الفقرة ٣٦٥ (ترجمة ريموند فوكنر، ١٩٦٩). تمثال باكنخونسو المكعّب، متحف الفن المصري في ميونخ. سفر التكوين ١١:٣-٤."
  },
  {
    id: 'god', region: 'egypt', verdict: 'holds',
    card_en: "Yes. Ramesses II had himself carved as a god receiving offerings. The Bible's prophets already knew Pharaoh spoke that way.",
    card_ar: "نعم. أمر رمسيس الثاني بنقش نفسه إلهًا تُقدَّم له القرابين. وفي سفر حزقيال من قبلُ أن فرعون كان يقول مثل هذا.",
    title_en: 'The Pharaoh who called himself a god', title_ar: 'فرعون الذي ادّعى الألوهية',
    short_en: 'Pharaoh as god', short_ar: 'ادّعاء الألوهية',
    refs: ['28:38'], also: ['79:24', '26:29'],
    claim_en: "In the Quran, Pharaoh tells his court \"I know of no god for you but me\" and \"I am your lord, most high\". The Bible's Exodus story never has him say this. The claim: archaeology proves it, because Ramesses II had himself worshipped as a god.",
    claim_ar: "في القرآن يقول فرعون لملئه: «ما علمتُ لكم من إلهٍ غيري» و«أنا ربُّكم الأعلى». وقصة الخروج في التوراة لا تنسب إليه هذا القول. ويُقال إن علم الآثار أثبته، لأن رمسيس الثاني جعل الناس يعبدونه إلهًا.",
    record_en: "At Abu Simbel, carved for Ramesses II about 1250 BCE, the king sits in the sanctuary as one of four gods, and a wall relief shows him making offerings to his own divine image. Egyptian kings had carried the title \"son of Ra\" for more than a thousand years before him.",
    record_ar: "في معبد أبو سمبل، المنحوت لرمسيس الثاني نحو سنة ١٢٥٠ قبل الميلاد، يجلس الملك في قدس الأقداس واحدًا من أربعة آلهة، ويصوّره نقشٌ على الجدار وهو يقدّم القرابين لصورته الإلهية. وقد حمل ملوك مصر لقب «ابن رع» أكثر من ألف عامٍ قبله.",
    check_en: "The carvings are real and they say what the verse says: this king presented himself as a god. It was not lost knowledge, though. The prophet Ezekiel has Pharaoh boast \"My Nile is my own; I made it\", and early rabbis listed Pharaoh among the kings who called themselves gods.",
    check_ar: "النقوش ثابتة وهي تقول ما تقوله الآية: هذا الملك قدّم نفسه إلهًا. لكن هذا لم يكن علمًا ضائعًا، ففي سفر حزقيال يتبجّح فرعون قائلًا: «نهري لي، وأنا عملتُه لنفسي»، وعدّ أحبار اليهود الأوائل فرعونَ بين الملوك الذين ادّعوا الألوهية.",
    counter_en: "In Egyptian belief every king was divine by office. It was the normal language of the throne, not one man's boast. And nothing identifies Ramesses II as the Pharaoh of Moses.",
    counter_ar: "في عقيدة المصريين كان كل ملكٍ إلهيًّا بحكم منصبه، فتلك لغة العرش المعتادة لا تبجُّح رجلٍ بعينه. ولا شيء يثبت أن رمسيس الثاني هو فرعون موسى.",
    videos: [{id: 'c2ovILc_sKY', t: 895, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The video says archaeology has proven that the Pharaoh of Moses made himself a god. What it shows is that Ramesses II did. Whether he was that Pharaoh is a separate question.",
    diff_ar: "يقول المقطع إن علم الآثار أثبت أن فرعون موسى ألّه نفسه. والذي تثبته الآثار أن رمسيس الثاني فعل ذلك، أما كونه فرعونَ موسى فمسألةٌ أخرى.",
    written: -1250, written_en: 'Abu Simbel carved for Ramesses II', written_ar: 'نحت معبد أبو سمبل لرمسيس الثاني',
    lost: null, recovered: null,
    source_en: "Great Temple of Abu Simbel, sanctuary statues and hall reliefs. Ezekiel 29:3. Mekhilta de-Rabbi Ishmael on Exodus 15:11.",
    source_ar: "المعبد الكبير في أبو سمبل، تماثيل قدس الأقداس ونقوش القاعة. سفر حزقيال ٢٩:٣. مخيلتا الحاخام إسماعيل على سفر الخروج ١٥:١١."
  },
  {
    id: 'stake', region: 'egypt', verdict: 'holds',
    card_en: "Yes. Egypt put men to the stake long before Rome. So did its neighbours.",
    card_ar: "نعم. عرفت مصر القتل على الخشب قبل روما بزمنٍ طويل، وعرفه جيرانها أيضًا.",
    title_en: "Pharaoh's threat to crucify", title_ar: 'وعيد فرعون بالصلب',
    short_en: 'Stake punishment', short_ar: 'عقوبة الصلب',
    refs: ['20:71'], also: ['7:124', '26:49'],
    claim_en: "Critics call Pharaoh's threat an anachronism, since crucifixion is known as a Persian and Roman punishment from centuries after Moses. The reply: Egypt was already putting condemned men on stakes, so the threat fits its own time.",
    claim_ar: "يعدّ بعض النقّاد وعيد فرعون خطأً تاريخيًا، لأن الصلب عُرف عقوبةً فارسية ورومانية بعد موسى بقرون. والجواب أن مصر كانت تشدّ المحكوم عليهم إلى الخشب قبل ذلك، فالوعيد يناسب زمنه.",
    record_en: "A victory stela of Merneptah at Amada in Nubia (reigned about 1213 to 1203 BCE) reports that Libyan prisoners were \"put to the stake\" south of Memphis. Older still, Papyrus Boulaq 18 (about 1750 BCE) speaks of a man \"put on the stake\", and oaths in the tomb-robbery papyri name the stake as the penalty for lying.",
    record_ar: "تذكر لوحة نصرٍ للملك مرنبتاح في عمدا ببلاد النوبة (حكم نحو ١٢١٣ إلى ١٢٠٣ قبل الميلاد) أن أسرى من الليبيين «وُضعوا على الخشب» جنوب منف. وأقدم من ذلك برديةُ بولاق ١٨ (نحو سنة ١٧٥٠ قبل الميلاد) التي تذكر رجلًا «وُضع على الخشب»، وأيمانُ برديات سرقة المقابر تجعل الخشبَ عقوبةَ الكاذب.",
    check_en: "The Arabic verb ṣallaba means to fix someone to wood; it does not have to mean the Roman cross. Read that way, the threat matches a punishment Egypt is known to have used, and the anachronism charge loses most of its force.",
    check_ar: "الفعل «صَلَّبَ» في العربية معناه شدُّ الإنسان إلى الخشب، ولا يلزم منه الصليب الروماني بهيئته المعروفة. وبهذا المعنى يتّفق الوعيد مع عقوبةٍ ثابتة في مصر القديمة، ويفقد اعتراض «الخطأ التاريخي» معظم قوته.",
    counter_en: "Death on a stake was common across the ancient Near East; Assyrian palace reliefs show it too. So the verse matches a general practice of the age, not a detail that only Egypt could supply.",
    counter_ar: "كان القتل على الخشب شائعًا في الشرق الأدنى القديم كله، ونقوش القصور الآشورية تصوّره أيضًا. فالآية توافق ممارسةً عامة في ذلك العصر، لا تفصيلًا تنفرد به مصر.",
    written: -1208, written_en: "Merneptah's Amada stela", written_ar: 'لوحة مرنبتاح في عمدا',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    videos: [
      {id: 'c2ovILc_sKY', t: 385, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The video also cites Pharaoh's threat to cut off hands and feet, and sets it beside a New Kingdom court papyrus that records noses and ears cut off as punishment.",
    diff_ar: "يستشهد المقطع كذلك بوعيد فرعون بقطع الأيدي والأرجل، ويقرنه ببرديةٍ قضائية من الدولة الحديثة تسجّل جدع الأنوف والآذان عقوبةً.",
    source_en: "Amada stela of Merneptah (Libyan war). Papyrus Boulaq 18. Abbott Papyrus, British Museum. Assyrian impalement scenes: Lachish reliefs, palace of Sennacherib, Nineveh.",
    source_ar: "لوحة مرنبتاح في عمدا (حرب الليبيين). بردية بولاق ١٨. بردية أبوت، المتحف البريطاني. مشاهد الخوزقة الآشورية: نقوش لخيش في قصر سنحاريب بنينوى."
  },
  {
    id: 'haman', region: 'egypt', verdict: 'weak',
    card_en: "No. The hieroglyph proof does not stand: the reading is uncertain and the name is built on a god's name.",
    card_ar: "لا. دليل الهيروغليفية لا يصمد، فالقراءة غير مؤكدة والاسم مبنيٌّ على اسم إله.",
    title_en: "Haman at Pharaoh's court", title_ar: 'هامان في بلاط فرعون',
    short_en: "Haman's name", short_ar: 'اسم هامان',
    refs: ['28:38'], also: ['40:36', '28:6'],
    claim_en: "Critics say the Quran moved Haman from Persia, where the Book of Esther places him, into Egypt. Maurice Bucaille replied that a hieroglyphic name, \"Hmn-h\", belonging to an overseer of quarry workers, proves there was an Egyptian Haman. A second version says \"Haman\" is the title of Bakenkhonsu, high priest of Amun and chief of works under Ramesses II.",
    claim_ar: "يقول بعض النقّاد إن القرآن نقل هامان من فارس، حيث يضعه سفر أستير، إلى مصر. وردّ موريس بوكاي بأن اسمًا هيروغليفيًا يُقرأ «حمن-ح» لرئيسٍ لعمّال المحاجر يثبت وجود هامان مصري. وفي روايةٍ ثانية أن «هامان» هو لقب باكنخونسو، كبير كهنة آمون ورئيس الأشغال في عهد رمسيس الثاني.",
    record_en: "The name is on a New Kingdom door jamb now in the Kunsthistorisches Museum, Vienna. Hermann Ranke's dictionary of Egyptian personal names (1935) lists it as \"Hmn-h(?)\", flags the last sign as uncertain, and suggests it is short for Hemen-hotep, \"the god Hemen is content\".",
    record_ar: "الاسم منقوشٌ على عضادة بابٍ من الدولة الحديثة محفوظةٍ اليوم في متحف تاريخ الفن في فيينا. ويورده معجم هرمان رانكه للأسماء المصرية (١٩٣٥) بصيغة «حمن-ح(؟)»، فيضع علامة شكٍّ على الحرف الأخير، ويرجّح أنه اختصارٌ لاسم «حمن-حتب» أي «الإله حمن راضٍ».",
    check_en: "Bucaille's reading does not survive. The name is uncertain, it is built on a god's name rather than a job title, and nothing ties it to Moses' time. Egyptian records neither confirm nor rule out a Haman: most officials of any reign are simply unknown to us. The second version fares no better. The high priest's title is hem-netjer tepy en Amun, \"first servant of the god, of Amun\"; turning that into \"Haman\" means dropping the middle of it, and every high priest of Amun held the same title.",
    check_ar: "قراءة بوكاي لا تصمد، فالاسم غير مؤكد، وهو مبنيٌّ على اسم إلهٍ لا على لقب وظيفة، ولا شيء يربطه بعصر موسى. والآثار المصرية لا تثبت هامان ولا تنفيه، فأكثر رجال الدولة في أي عهدٍ مجهولون لنا. والرواية الثانية ليست أحسن حالًا، فلقب كبير الكهنة هو «حم نثر تبي إن آمون» أي «خادم الإله الأول لآمون»، وردُّه إلى «هامان» يقتضي إسقاط وسطه، وكل كبار كهنة آمون حملوا اللقب نفسه.",
    counter_en: "The Quran never says its Haman is the man in Esther. Two people sharing a name a thousand years apart is not a contradiction, so the critics' charge is weaker than it sounds as well.",
    counter_ar: "لا يقول القرآن إن هامان هذا هو نفسه هامان سفر أستير، واشتراك رجلين في اسمٍ واحد بينهما ألف عام ليس تناقضًا. فاعتراض النقّاد أضعف مما يبدو كذلك.",
    written: -1300, written_en: 'Door jamb carved (New Kingdom)', written_ar: 'نقش عضادة الباب (الدولة الحديثة)',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    videos: [
      {id: 'OKTS73lNwGU', t: 250, by: 'Purpose of Visit', title: '5 Miracles of the Quran in Ancient Egyptian Inscriptions'},
      {id: '27MSQQ61ti4', t: 0, by: 'Sense Islam', title: 'Ancient Hieroglyphs Reveals Mystery Behind Quran'},
      {id: 'c2ovILc_sKY', t: 1470, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "There are two versions. Most videos use the hieroglyphic name from Ranke's dictionary and call him head of the quarry workers. The longer video instead says Haman is the title of Bakenkhonsu.",
    diff_ar: "للمزعم روايتان. أكثر المقاطع تعتمد الاسم الهيروغليفي من معجم رانكه وتجعله رئيس عمّال المحاجر. أما المقطع الأطول فيقول إن هامان لقبُ باكنخونسو.",
    source_en: "H. Ranke, Die ägyptischen Personennamen, vol. 1 (1935). W. Wreszinski, Aegyptische Inschriften aus dem K.K. Hof Museum in Wien (1906). M. Bucaille, Moses and Pharaoh (1994).",
    source_ar: "هرمان رانكه، الأسماء الشخصية المصرية، المجلد الأول (١٩٣٥). فالتر فريشينسكي، النقوش المصرية في متحف البلاط في فيينا (١٩٠٦). موريس بوكاي، موسى وفرعون (١٩٩٤)."
  },
  {
    id: 'body', region: 'egypt', verdict: 'weak',
    card_en: "Not as told. Every pharaoh was mummified, the mummy the videos show is that of a man of about ninety, and no record names the Pharaoh of the Exodus.",
    card_ar: "ليس كما يُروى. كل الفراعنة حُنّطوا، والمومياء التي تعرضها المقاطع لرجلٍ في نحو التسعين، ولا أثر يسمّي فرعون الخروج.",
    title_en: '"This day We save your body"', title_ar: '«فاليوم ننجّيك ببدنك»',
    short_en: "Pharaoh's body", short_ar: 'بدن فرعون',
    refs: ['10:92'],
    claim_en: "The verse promises that Pharaoh's body would be kept as a sign for later generations. Most videos point to the mummy of Ramesses II, found in 1881 after three thousand years in a hidden cache, and say the French doctor Maurice Bucaille proved from it that the king drowned.",
    claim_ar: "تعِد الآية بأن يبقى بدن فرعون آيةً لمن بعده. وأكثر المقاطع تشير إلى مومياء رمسيس الثاني، التي عُثر عليها سنة ١٨٨١ بعد ثلاثة آلاف عامٍ في خبيئةٍ سرّية، وتقول إن الطبيب الفرنسي موريس بوكاي أثبت منها أن الملك مات غرقًا.",
    record_en: "Ramesses II died about 1213 BCE. Priests moved his mummy to a secret cache around 1000 BCE to save it from tomb robbers, and it was found at Deir el-Bahari in 1881. It was examined in Cairo in 1975 and treated in Paris in 1976. The mummy of his son Merneptah, the king Bucaille actually argued for, was found in another tomb in 1898.",
    record_ar: "تُوفي رمسيس الثاني نحو سنة ١٢١٣ قبل الميلاد. ونقل الكهنة موميائه إلى خبيئةٍ سرّية نحو سنة ١٠٠٠ قبل الميلاد لحمايتها من لصوص المقابر، وعُثر عليها في الدير البحري سنة ١٨٨١. وفُحصت في القاهرة سنة ١٩٧٥ وعولجت في باريس سنة ١٩٧٦. أما مومياء ابنه مرنبتاح، وهو الملك الذي رجّحه بوكاي فعلًا، فعُثر عليها في مقبرةٍ أخرى سنة ١٨٩٨.",
    check_en: "The verse fits any Pharaoh, because every king was mummified, and no Egyptian record identifies the Pharaoh of the Exodus. Ramesses II's mummy is that of a man of about ninety with severe arthritis. The early commentators read the verse differently: the drowned body was cast onto the shore so the Israelites could see with their own eyes that he was dead.",
    check_ar: "الآية تصدق على أي فرعون، فكل الملوك حُنّطوا، ولا يحدّد أيُّ أثرٍ مصري فرعونَ الخروج. ومومياء رمسيس الثاني لرجلٍ في نحو التسعين مصابٍ بالتهابٍ شديد في المفاصل. وقد فهم المفسرون الأوائل الآية على وجهٍ آخر: أن البحر ألقى جثته على الساحل ليرى بنو إسرائيل بأعينهم أنه هلك.",
    counter_en: "Every mummy contains salt, because embalmers dried bodies with natron, so salt proves nothing about the sea. And Merneptah's own victory stela, from his fifth year, already names Israel as a people in Canaan, which sits badly with him being the king they fled from.",
    counter_ar: "في كل مومياء ملح، لأن المحنّطين كانوا يجفّفون الأجساد بالنطرون، فالملح لا يدلّ على البحر. ثم إن لوحة نصر مرنبتاح نفسه، من سنته الخامسة، تذكر «إسرائيل» قومًا في أرض كنعان، وهذا لا يستقيم مع كونه الملك الذي فرّوا منه.",
    videos: [
      {id: 'OKTS73lNwGU', t: 515, by: 'Purpose of Visit', title: '5 Miracles of the Quran in Ancient Egyptian Inscriptions'},
      {id: 'c2ovILc_sKY', t: 960, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The videos name Ramesses II; Bucaille himself argued for Merneptah. One video says the mummy was flown to France in 1874. It went to Paris in 1976.",
    diff_ar: "تسمّي المقاطع رمسيس الثاني، أما بوكاي نفسه فرجّح مرنبتاح. ويقول أحدها إن المومياء نُقلت جوًّا إلى فرنسا سنة ١٨٧٤، والصحيح أنها ذهبت إلى باريس سنة ١٩٧٦.",
    written: -1213, written_en: 'Ramesses II dies and is buried', written_ar: 'وفاة رمسيس الثاني ودفنه',
    lost: -1000, lost_en: 'Royal mummies hidden in a secret cache', lost_ar: 'إخفاء المومياوات الملكية في خبيئةٍ سرّية',
    recovered: 1881, recovered_en: 'The royal cache is found at Deir el-Bahari', recovered_ar: 'العثور على الخبيئة الملكية في الدير البحري',
    source_en: "M. Bucaille, Mummies of the Pharaohs: Modern Medical Investigations (1990). Royal cache TT320, Deir el-Bahari (1881). V. Loret, discovery of KV35 (1898). Merneptah Stele, Egyptian Museum, Cairo.",
    source_ar: "موريس بوكاي، مومياوات الفراعنة: فحوص طبية حديثة (١٩٩٠). الخبيئة الملكية TT320 في الدير البحري (١٨٨١). فيكتور لوريه، اكتشاف المقبرة KV35 (١٨٩٨). لوحة مرنبتاح، المتحف المصري بالقاهرة."
  },
  {
    id: 'reign', region: 'egypt', verdict: 'partial',
    card_en: "Partly. The Quran does read as one Pharaoh, and Ramesses II did reign 66 years. No Egyptian record ties him to Moses.",
    card_ar: "جزئيًا. القرآن يُفهم منه فعلًا أنه فرعونٌ واحد، ورمسيس الثاني حكم ستةً وستين عامًا. لكن لا أثر مصري يربطه بموسى.",
    title_en: 'One Pharaoh, from the cradle to the sea', title_ar: 'فرعونٌ واحد من المهد إلى البحر',
    short_en: 'One long reign', short_ar: 'حكمٌ طويل واحد',
    refs: ['26:18'], also: ['28:14', '28:27'],
    claim_en: "The Bible has two Pharaohs in Moses' life: one dies while Moses is away in Midian. In the Quran, Pharaoh says to the grown Moses \"Did we not raise you among us as a child?\", so it is the same king throughout. The claim: only Ramesses II, who reigned 66 years, fits.",
    claim_ar: "في التوراة فرعونان في حياة موسى، يموت أحدهما وموسى في مدين. وفي القرآن يقول فرعون لموسى وقد كبر: «ألم نُربِّك فينا وليدًا؟»، فهو الملك نفسه من البداية إلى النهاية. ويُقال إن هذا لا ينطبق إلا على رمسيس الثاني الذي حكم ستةً وستين عامًا.",
    record_en: "Ramesses II ruled from about 1279 to 1213 BCE, one of the longest reigns in Egyptian history. The Merneptah Stele, about 1208 BCE, already names Israel as a people in Canaan, so an Exodus under a later king is hard to fit.",
    record_ar: "حكم رمسيس الثاني من نحو سنة ١٢٧٩ إلى ١٢١٣ قبل الميلاد، وهو من أطول العهود في تاريخ مصر. ولوحة مرنبتاح، نحو سنة ١٢٠٨ قبل الميلاد، تذكر «إسرائيل» قومًا في أرض كنعان، فيصعب أن يكون الخروج في عهد ملكٍ بعده.",
    check_en: "As a reading of the text, it holds: the Quran never mentions a change of king. The 66 years are a fact too. The rest is inference. The video's ages (maturity at forty, then eight to ten years in Midian) come from joining separate verses, and Egypt's own records say nothing of Moses or an Exodus.",
    check_ar: "هذا صحيحٌ من جهة النص، فالقرآن لا يذكر تبدُّل الملك. والستة والستون عامًا حقيقةٌ كذلك. وما عدا ذلك استنتاج، فالأعمار التي يبني عليها المقطع (بلوغ الأشدّ في الأربعين ثم ثماني سنين إلى عشر في مدين) مأخوذةٌ من جمع آياتٍ متفرقة، وسجلات مصر نفسها لا تذكر موسى ولا الخروج.",
    counter_en: "The length of this reign was never lost: the Egyptian priest Manetho's king list, kept in Greek and quoted by Josephus, gives this king 66 years. And his mummy is that of a man of about ninety with severe arthritis, which sits badly with a king leading a chariot chase.",
    counter_ar: "طول هذا العهد لم يكن علمًا ضائعًا، فقائمة الملوك التي وضعها الكاهن المصري مانيتون، وحُفظت باليونانية ونقلها يوسيفوس، تعطي هذا الملك ستةً وستين عامًا. ثم إن موميائه لرجلٍ في نحو التسعين مصابٍ بالتهابٍ شديد في المفاصل، وهذا لا يستقيم مع ملكٍ يقود مطاردةً بالمركبات.",
    videos: [{id: 'c2ovILc_sKY', t: 600, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The video presents Ramesses II as settled. Egyptologists have no agreed Pharaoh of the Exodus, and many doubt the event can be dated at all.",
    diff_ar: "يعرض المقطع رمسيس الثاني كأنه أمرٌ محسوم. وعلماء المصريات لا يتفقون على فرعونٍ للخروج، وكثيرٌ منهم يشكّ في إمكان تأريخ الحدث أصلًا.",
    written: -1279, written_en: 'Ramesses II takes the throne', written_ar: 'اعتلاء رمسيس الثاني العرش',
    lost: null, recovered: null,
    source_en: "K. A. Kitchen, Pharaoh Triumphant: The Life and Times of Ramesses II (1982). Manetho, quoted in Josephus, Against Apion 1.97. Merneptah Stele, Egyptian Museum, Cairo. Exodus 2:23.",
    source_ar: "كينيث كيتشن، فرعون المنتصر: حياة رمسيس الثاني وعصره (١٩٨٢). مانيتون، نقلًا عن يوسيفوس، ضدّ أبيون ١.٩٧. لوحة مرنبتاح، المتحف المصري بالقاهرة. سفر الخروج ٢:٢٣."
  },
  {
    id: 'band', region: 'egypt', verdict: 'holds',
    card_en: "Yes, as far as the evidence goes. Nothing in Egypt or Sinai shows millions on the move, and the Quran's Pharaoh calls them few.",
    card_ar: "نعم، بقدر ما تسمح به الأدلة. لا شيء في مصر ولا في سيناء يدلّ على خروج ملايين، وفرعون في القرآن يصفهم بالقلّة.",
    title_en: '"A small band", not six hundred thousand', title_ar: '«شرذمةٌ قليلون» لا ستمئة ألف',
    short_en: 'A small band', short_ar: 'شرذمة قليلون',
    refs: ['26:54'], also: ['26:52', '26:53'],
    claim_en: "The Bible counts about 600,000 Israelite men leaving Egypt, which means two million people or more. In the Quran, Pharaoh calls them \"a small band\". The claim: the Quran's picture is the one that fits history.",
    claim_ar: "تعدّ التوراة نحو ستمئة ألف رجلٍ من بني إسرائيل خرجوا من مصر، أي مليوني إنسانٍ أو أكثر. وفي القرآن يسمّيهم فرعون «شرذمةً قليلين». ويُقال إن صورة القرآن هي التي توافق التاريخ.",
    record_en: "There is no Egyptian record of the Exodus at all. Egypt's whole population at the time is estimated at about three million, and decades of surveys in Sinai have found no trace of a host of that size.",
    record_ar: "لا يوجد في آثار مصر ذكرٌ للخروج أصلًا. ويُقدَّر سكان مصر كلها يومئذٍ بنحو ثلاثة ملايين، ولم تجد المسوح الأثرية في سيناء، على مدى عقود، أثرًا لجمعٍ بهذا الحجم.",
    check_en: "On the numbers, the Quran's wording is the one that is easy to square with the evidence. Many Bible scholars agree that 600,000 cannot be literal, and some read the Hebrew word for \"thousand\" as \"clan\" or \"troop\", which brings the total down to a few thousand.",
    check_ar: "من جهة الأعداد، لفظ القرآن هو الأيسر توفيقًا مع الأدلة. وكثيرٌ من دارسي التوراة يرون أن الستمئة ألف ليست عددًا حرفيًا، وبعضهم يقرأ الكلمة العبرية «ألف» بمعنى «عشيرة» أو «فرقة»، فينزل المجموع إلى بضعة آلاف.",
    counter_en: "The verse is Pharaoh's own speech as he rallies his army, the kind of thing a king says about an enemy. It is not a census. And a small group leaving Egypt is just the sort of event that would leave no record, so the silence cannot confirm it either.",
    counter_ar: "الآية كلام فرعون نفسه وهو يحشد جنده، وهو ما يقوله ملكٌ عن عدوّه، وليست إحصاءً. ثم إن خروج جماعةٍ صغيرة من مصر حدثٌ لا يترك أثرًا بطبيعته، فالصمت لا يثبته كذلك.",
    videos: [{id: 'c2ovILc_sKY', t: 240, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The video argues from two details inside the Bible itself (two midwives for a whole nation, and the fear of wild animals), not from archaeology.",
    diff_ar: "يحتجّ المقطع بتفصيلين من داخل التوراة نفسها (قابلتان لأمةٍ كاملة، والخوف من وحوش البرّ)، لا بعلم الآثار.",
    written: null, lost: null, recovered: null,
    acc_en: 'There is no ancient record to date here. The comparison is between two scriptures, and the ground itself has stayed silent.',
    acc_ar: 'لا أثر قديم هنا يُؤرَّخ. المقارنة بين كتابين، والأرض نفسها بقيت صامتة.',
    source_en: "Exodus 12:37; Numbers 1:46. W. M. F. Petrie, Researches in Sinai (1906), on \"thousand\" as \"clan\". K. W. Butzer, Early Hydraulic Civilization in Egypt (1976), on population.",
    source_ar: "سفر الخروج ١٢:٣٧، وسفر العدد ١:٤٦. فلندرز بيتري، أبحاث في سيناء (١٩٠٦)، عن قراءة «ألف» بمعنى «عشيرة». كارل بوتزر، الحضارة المائية المبكرة في مصر (١٩٧٦)، عن عدد السكان."
  },
  {
    id: 'silver', region: 'egypt', verdict: 'partial',
    card_en: "Partly. Egypt did price goods in set units of silver long before coins. It struck no coins until many centuries after Joseph.",
    card_ar: "جزئيًا. كانت مصر تسعّر البضائع بوحداتٍ محددة من الفضة قبل النقود بزمنٍ طويل. لكنها لم تسكّ نقودًا إلا بعد يوسف بقرونٍ كثيرة.",
    title_en: 'Joseph, sold for a few counted silver pieces', title_ar: 'دراهم معدودة ثمنًا ليوسف',
    short_en: 'Counted silver', short_ar: 'دراهم معدودة',
    refs: ['12:20'], also: ['12:21'],
    claim_en: "The verse says Joseph was sold \"for a low price, a few counted dirhams\". Critics call that an anachronism, since coins did not exist yet. The claim: Egypt already used standard pieces of silver, so the verse is right, and it even shows that minting is older than the Greeks.",
    claim_ar: "تقول الآية إن يوسف بِيع «بثمنٍ بخسٍ دراهمَ معدودة». ويعدّ النقّاد ذلك خطأً تاريخيًا، لأن النقود لم تكن قد وُجدت. والردّ أن مصر كانت تتعامل بقطعٍ قياسية من الفضة، فالآية صحيحة، بل هي تدلّ على أن سكّ النقود أقدم من اليونان.",
    record_en: "Egyptian accounts from the Old Kingdom onward price goods in a unit called the shat, one twelfth of a deben of metal. A market scene in a tomb at Saqqara, about 2400 BCE, shows cloth sold for shat. No shat piece has ever been found, so it may have been a unit of account only. Egypt struck its first coins in the 4th century BCE.",
    record_ar: "تسعّر حسابات المصريين منذ الدولة القديمة البضائعَ بوحدةٍ تُسمّى «شات»، وهي جزءٌ من اثني عشر جزءًا من «الدِّبن»، وهو وزنٌ من المعدن. ويصوّر مشهدُ سوقٍ في مقبرةٍ بسقارة، نحو سنة ٢٤٠٠ قبل الميلاد، قماشًا يُباع بالشات. ولم يُعثر قط على قطعة شات، فربما كانت وحدة حسابٍ فحسب. أما أول نقودٍ سكّتها مصر ففي القرن الرابع قبل الميلاد.",
    check_en: "Paying a set amount of silver was normal in Egypt, so the verse describes something real. But \"dirham\" was simply the Arabic word of the Prophet's day for a silver piece, and the verse does not need coins to be true. The stronger half of the claim, that Egypt minted money before the Greeks, is not supported.",
    check_ar: "دفعُ مقدارٍ محدد من الفضة كان أمرًا معتادًا في مصر، فالآية تصف شيئًا حقيقيًا. لكن «الدرهم» هو ببساطة اللفظ العربي في زمن النبي ﷺ لقطعة الفضة، والآية لا تحتاج إلى نقودٍ مسكوكة لتصحّ. أما الشقّ الأقوى من المزعم، وهو أن مصر سكّت النقود قبل اليونان، فلا دليل عليه.",
    counter_en: "The Bible tells the same sale: twenty pieces of silver (Genesis 37:28). So the detail was already in an older book, and it is not a new piece of knowledge.",
    counter_ar: "التوراة تروي البيعَ نفسه بعشرين قطعةً من الفضة (التكوين ٣٧:٢٨). فالتفصيل موجودٌ في كتابٍ أقدم، وليس علمًا جديدًا.",
    videos: [{id: 'c2ovILc_sKY', t: 1260, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "The video says the Bible places the sale outside Egypt, so the Quran could not have copied it. In both books Joseph passes first to a caravan and then to an Egyptian buyer.",
    diff_ar: "يقول المقطع إن التوراة تجعل البيع خارج مصر، فلا يمكن أن يكون القرآن نقل عنها. وفي الكتابين ينتقل يوسف أولًا إلى قافلة ثم إلى مشترٍ مصري.",
    written: -2400, written_en: 'Prices in shat in a Saqqara tomb', written_ar: 'أسعارٌ بالشات في مقبرةٍ بسقارة',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    source_en: "Tomb of Niankhkhnum and Khnumhotep, Saqqara (market scene). Rhind Mathematical Papyrus. Genesis 37:28.",
    source_ar: "مقبرة ني عنخ خنوم وخنوم حتب في سقارة (مشهد السوق). بردية ريند الرياضية. سفر التكوين ٣٧:٢٨."
  },
  {
    id: 'ipuwer', region: 'egypt', verdict: 'weak',
    card_en: "No. The poem laments a society falling apart, and it was composed centuries before any date given for Moses.",
    card_ar: "لا. القصيدة مرثيةٌ لمجتمعٍ ينهار، وقد أُلّفت قبل أي تاريخٍ يُقترح لموسى بقرون.",
    title_en: 'The Ipuwer Papyrus and the plagues', title_ar: 'بردية إيبوور وآيات العذاب',
    short_en: 'Ipuwer Papyrus', short_ar: 'بردية إيبوور',
    refs: ['7:133'], also: ['7:130'],
    quote_en: 'The river is blood.',
    quote_ar: 'النهر دم.',
    claim_en: "The Quran lists the punishments sent on Pharaoh's people: flood, locusts, lice, frogs and blood. The claim: an Egyptian eyewitness, Ipuwer, wrote the same disasters down in a papyrus now in a Dutch museum.",
    claim_ar: "يعدّد القرآن ما أُرسل على قوم فرعون: الطوفان والجراد والقُمَّل والضفادع والدم. ويُقال إن شاهدَ عيانٍ مصريًّا اسمه إيبوور دوّن الكوارث نفسها في برديةٍ محفوظة اليوم في متحفٍ هولندي.",
    record_en: "The papyrus is in Leiden, bought in 1828 and translated by Alan Gardiner in 1909. It is a long poem in which a sage laments that Egypt has been turned upside down: the river is blood, grain has perished, servants own what their masters had. The surviving copy dates to about 1250 BCE. The poem itself was composed no earlier than the late Twelfth Dynasty, around 1800 BCE.",
    record_ar: "البردية في لايدن، اشتُريت سنة ١٨٢٨ وترجمها ألن غاردنر سنة ١٩٠٩. وهي قصيدةٌ طويلة يرثي فيها حكيمٌ مصرَ وقد انقلبت رأسًا على عقب: النهر دم، والغلال هلكت، والخدم ملكوا ما كان لسادتهم. والنسخة الباقية تعود إلى نحو سنة ١٢٥٠ قبل الميلاد. أما القصيدة نفسها فلم تُؤلَّف قبل أواخر الأسرة الثانية عشرة، نحو سنة ١٨٠٠ قبل الميلاد.",
    check_en: "A few lines do sound like the plagues. Read whole, though, the poem is about the collapse of order, not about a prophet or a people leaving. It complains that foreigners are pouring into Egypt, the opposite of an Exodus, and it was composed centuries before any date proposed for Moses. Egyptologists read it as literature, not as a report.",
    check_ar: "بضعة أسطرٍ منها تشبه آيات العذاب فعلًا. لكن القصيدة إذا قُرئت كاملةً تتحدث عن انهيار النظام، لا عن نبيٍّ ولا عن قومٍ يخرجون. وهي تشكو من تدفّق الأجانب إلى مصر، وهذا عكس الخروج، وقد أُلّفت قبل أي تاريخٍ يُقترح لموسى بقرون. وعلماء المصريات يقرؤونها أدبًا لا تقريرًا.",
    counter_en: "Supporters point out that the only copy we have was written in the age of Ramesses II, and that \"the river is blood\" is too close to dismiss. One of the videos uses it more carefully, only to show that a red Nile was a known event.",
    counter_ar: "يشير المؤيدون إلى أن النسخة الوحيدة الباقية كُتبت في عصر رمسيس الثاني، وأن عبارة «النهر دم» أقرب من أن تُهمل. ويستعملها أحد المقاطع بحذرٍ أكبر، ليدلّ فقط على أن احمرار النيل كان حدثًا معروفًا.",
    videos: [
      {id: 'OKTS73lNwGU', t: 350, by: 'Purpose of Visit', title: '5 Miracles of the Quran in Ancient Egyptian Inscriptions'},
      {id: 'SG_3cI8j95A', t: 330, by: 'Towards Eternity', title: 'Prophet Moses (pbuh) and Pharaoh in Historical Sources! New Discoveries Prove The Qur\'an!'},
      {id: 'c2ovILc_sKY', t: 1085, by: 'ManyProphetsOneMessage', title: "The Qur'an and the Secrets of Egypt"}],
    diff_en: "One video says the papyrus was dug up in the early 1900s and dates from the reign of Ramesses II. It was bought by the Leiden museum in 1828, and only this copy is from that age. The third video makes the smaller claim.",
    diff_ar: "يقول أحد المقاطع إن البردية استُخرجت في مطلع القرن العشرين وإنها من عهد رمسيس الثاني. والصحيح أن متحف لايدن اشتراها سنة ١٨٢٨، وأن هذه النسخة وحدها من ذلك العصر. والمقطع الثالث يكتفي بالدعوى الأصغر.",
    written: -1250, written_en: 'The surviving copy is written', written_ar: 'كتابة النسخة الباقية',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1909, recovered_en: 'Gardiner publishes a translation', recovered_ar: 'غاردنر ينشر ترجمتها',
    source_en: "Papyrus Leiden I 344 recto. A. H. Gardiner, The Admonitions of an Egyptian Sage (1909). M. Lichtheim, Ancient Egyptian Literature, vol. 1 (1973).",
    source_ar: "بردية لايدن I 344، الوجه. ألن غاردنر، نصائح حكيمٍ مصري (١٩٠٩). مريم ليشتهايم، الأدب المصري القديم، المجلد الأول (١٩٧٣)."
  },
  {
    id: 'letter', region: 'egypt', verdict: 'weak',
    card_en: "No. The two scribes are real, but their papyri are school exercises, and no Egyptian text reports a king drowning.",
    card_ar: "لا. الكاتبان حقيقيان، لكن بردياتهما تمارين مدرسية، ولا يوجد نصٌّ مصري يروي غرق ملك.",
    title_en: 'A palace letter about the drowning', title_ar: 'رسالةٌ من القصر عن الغرق',
    short_en: 'The drowning letter', short_ar: 'رسالة الغرق',
    refs: ['10:90'], also: ['2:50', '26:66'],
    claim_en: "Several videos read out a letter from a papyrus in the British Museum. A palace official, Amenamoni, tells the scribe Pentaur of \"the disaster of drowning in the waves\" and the death of \"the king of the East and the West\". The claim: Egypt recorded Pharaoh's drowning.",
    claim_ar: "تقرأ مقاطعُ عدّة رسالةً من برديةٍ في المتحف البريطاني، يخبر فيها موظفٌ في القصر اسمه «أمينامونِي» الكاتبَ «بنتاؤر» بـ«كارثة الغرق في الأمواج» وبموت «ملك المشرق والمغرب». ويُقال إن مصر دوّنت غرق فرعون.",
    record_en: "The names belong to two known scribes: Amenemone, chief bookkeeper of Pharaoh's treasury (the \"White House\"), and his pupil Pentaweret. Pentaweret's manuscripts, the Sallier papyri, are in the British Museum. They are collections of model letters and poems that trainee scribes copied out, written in the reign of Merneptah, about 1204 BCE.",
    record_ar: "الاسمان لكاتبين معروفين: آمون إم إيني، كبير أمناء سجلات خزانة فرعون («البيت الأبيض»)، وتلميذه بنتاورت. ومخطوطات بنتاورت، وهي برديات ساليه، محفوظةٌ في المتحف البريطاني. وهي مجموعات من رسائل وقصائد نموذجية كان الكتبة المتدرّبون ينسخونها، وقد كُتبت في عهد مرنبتاح نحو سنة ١٢٠٤ قبل الميلاد.",
    check_en: "The videos never name the papyrus, the translator or the year, and we could not trace the quoted words to any modern edition. The papyri these scribes left are practice texts, and the scholars who edited them read them as school exercises. A Victorian clergyman, D. I. Heath, did publish them in 1855 as \"The Exodus Papyri\", when the script was barely understood. The drowning reading most likely comes from that time.",
    check_ar: "لا تذكر المقاطع اسم البردية ولا المترجم ولا السنة، ولم نستطع ردَّ العبارات المقتبسة إلى أي طبعةٍ حديثة. والبرديات التي تركها هذان الكاتبان نصوصٌ للتمرين، والعلماء الذين حقّقوها قرؤوها تمارينَ مدرسية. وكان قسٌّ من العصر الفكتوري، هو د. إ. هيث، قد نشرها سنة ١٨٥٥ بعنوان «برديات الخروج»، يوم كان الخطّ لا يكاد يُفهم. والأرجح أن قراءة «الغرق» من ذلك الزمن.",
    counter_en: "Supporters say Egypt never recorded its defeats, so a private letter is exactly where such news would slip out. That would be a fair point if the letter could be produced. Until someone names the papyrus and the line, there is nothing to check.",
    counter_ar: "يقول المؤيدون إن مصر لم تكن تدوّن هزائمها، فالرسالة الخاصة هي الموضع الذي يتسرّب منه خبرٌ كهذا. وهذا اعتراضٌ وجيه لو أمكن إبراز الرسالة. وإلى أن يسمّي أحدٌ البردية والسطر، فلا شيء يُفحص.",
    videos: [
      {id: 'OKTS73lNwGU', t: 455, by: 'Purpose of Visit', title: '5 Miracles of the Quran in Ancient Egyptian Inscriptions'},
      {id: 'SG_3cI8j95A', t: 545, by: 'Towards Eternity', title: 'Prophet Moses (pbuh) and Pharaoh in Historical Sources! New Discoveries Prove The Qur\'an!'}],
    diff_en: "The videos give no papyrus number. Printed versions of the claim call it \"papyrus 6\" and spell the names Amenamoni and Penterhor.",
    diff_ar: "لا تذكر المقاطع رقمًا للبردية. والصيغ المكتوبة من المزعم تسمّيها «البردية ٦».",
    written: -1204, written_en: 'Pentaweret copies his model letters', written_ar: 'بنتاورت ينسخ رسائله النموذجية',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    source_en: "Papyrus Sallier I, British Museum EA 10185. A. H. Gardiner, Late-Egyptian Miscellanies (1937). R. A. Caminos, Late-Egyptian Miscellanies (1954). D. I. Heath, The Exodus Papyri (1855).",
    source_ar: "بردية ساليه الأولى، المتحف البريطاني EA 10185. ألن غاردنر، منوّعات مصرية متأخرة (١٩٣٧). ريكاردو كامينوس، منوّعات مصرية متأخرة (١٩٥٤). د. إ. هيث، برديات الخروج (١٨٥٥)."
  },
  {
    id: 'wheels', region: 'egypt', verdict: 'weak',
    card_en: "No. The photos come from one amateur diver in 1978. No wheel has ever been raised, dated or published.",
    card_ar: "لا. الصور مصدرها غوّاصٌ هاوٍ واحد سنة ١٩٧٨. ولم تُنتشل عجلةٌ قط، ولم تُؤرَّخ، ولم تُنشر.",
    title_en: 'Chariot wheels on the floor of the Red Sea', title_ar: 'عجلات المركبات في قاع البحر الأحمر',
    short_en: 'Chariot wheels', short_ar: 'عجلات المركبات',
    refs: ['26:65', '26:66'], also: ['10:90', '20:78'],
    claim_en: "Divers have found Pharaoh's army in the Gulf of Aqaba: coral-covered chariot wheels with four, six and eight spokes, bones of horses and men, even a gilded wheel. The claim: the sea crossing is proven.",
    claim_ar: "عثر الغوّاصون على جيش فرعون في خليج العقبة: عجلات مركباتٍ يكسوها المرجان، منها ذات الأضلاع الأربعة والستة والثمانية، وعظام خيلٍ وبشر، بل عجلةٌ مذهّبة. ويُقال إن عبور البحر ثبت بذلك.",
    record_en: "The story began with Ron Wyatt, an American nurse and amateur explorer, who dived off Nuweiba in 1978 and showed photographs of wheel-shaped objects. No object was recovered for study, and nothing was published in an archaeological journal.",
    record_ar: "بدأت القصة مع رون وايات، وهو ممرّضٌ أمريكي ومستكشفٌ هاوٍ، غاص قبالة نويبع سنة ١٩٧٨ وعرض صورًا لأجسامٍ على هيئة عجلات. ولم يُنتشل شيءٌ للدراسة، ولم يُنشر شيءٌ في مجلةٍ أثرية.",
    check_en: "There is no find to examine. Corals in that sea often grow as flat plates on a stalk, which look like a wheel on an axle. Later \"news\" stories of an army on the seabed trace back to a satire site and to edited images. Belief in the crossing does not depend on this. The photographs simply are not evidence.",
    check_ar: "لا يوجد أثرٌ يُفحص. والمرجان في ذلك البحر ينمو كثيرًا على هيئة صفائح مسطّحة فوق ساق، فتشبه عجلةً على محور. و«الأخبار» اللاحقة عن جيشٍ في قاع البحر مردُّها إلى موقعٍ ساخر وصورٍ معدَّلة. والإيمان بالعبور لا يتوقف على هذا، لكن الصور ببساطة ليست دليلًا.",
    counter_en: "Supporters reply that the law forbids removing antiquities, so the wheels had to be left where they lay. But a find can be surveyed, sampled and dated without being removed, and in more than forty years none of that has been done.",
    counter_ar: "يردّ المؤيدون بأن القانون يمنع إخراج الآثار، فكان لا بدّ من ترك العجلات في مكانها. لكن الأثر يُمسح وتؤخذ منه عيّنات ويُؤرَّخ من غير أن يُنقل، ولم يحدث شيءٌ من ذلك في أكثر من أربعين عامًا.",
    videos: [
      {id: 'klpW-owgGOk', t: 0, by: 'Ambrose Discovery', title: "Divers Discovered Pharaoh's Army Beneath the Red Sea"},
      {id: '9-zDjvT_XC8', t: 0, by: 'Origins Explained', title: "Did Salvage Divers Find Pharaoh's Chariot Wheel in the Red Sea?", n_en: 'examines the claim', n_ar: 'يفحص المزعم'}],
    diff_en: "The first video describes a robot survey and a whole field of wheels as fact. It names no expedition, date or publication.",
    diff_ar: "يصف المقطع الأول مسحًا بالروبوت وحقلًا كاملًا من العجلات كأنه حقيقة. ولا يسمّي بعثةً ولا تاريخًا ولا نشرًا علميًا.",
    written: null, lost: null, recovered: 1978, recovered_en: "Wyatt's dive off Nuweiba", recovered_ar: 'غوص وايت قبالة نويبع',
    acc_en: "Not a written record: a diver's report from 1978. Nothing has been raised or dated since.",
    acc_ar: 'ليس نصًّا مكتوبًا، بل روايةُ غوّاصٍ من سنة ١٩٧٨. ولم يُنتشل شيءٌ ولم يُؤرَّخ منذ ذلك الحين.',
    source_en: "Wyatt Archaeological Research, claims from 1978 onward. Fact-checks of the 2014 \"Egyptian army found\" story, which began on a satire site.",
    source_ar: "مؤسسة وايات للأبحاث الأثرية، مزاعمها منذ سنة ١٩٧٨. تدقيقات خبر «العثور على الجيش المصري» سنة ٢٠١٤، وقد بدأ في موقعٍ ساخر."
  },
  {
    id: 'famine', region: 'egypt', verdict: 'weak',
    card_en: "No. The stone does tell of a seven-year famine, but it was carved more than two thousand years after the king it names.",
    card_ar: "لا. اللوحة تروي فعلًا مجاعةً دامت سبع سنين، لكنها نُقشت بعد الملك الذي تذكره بأكثر من ألفي عام.",
    title_en: 'Seven lean years on the Famine Stela', title_ar: 'سبعٌ شِداد على لوحة المجاعة',
    short_en: 'Famine Stela', short_ar: 'لوحة المجاعة',
    refs: ['12:47', '12:48'],
    claim_en: "Joseph foretells seven good years and then seven hard ones. The claim: a hieroglyphic inscription on Sehel Island records that very seven-year famine, with a wise adviser who saves Egypt.",
    claim_ar: "يخبر يوسف بسبع سنين خِصبٍ تليها سبعٌ شِداد. ويُقال إن نقشًا هيروغليفيًا في جزيرة سهيل يسجّل تلك المجاعة نفسها، ومعها مستشارٌ حكيم ينقذ مصر.",
    record_en: "The Famine Stela, found by Charles Wilbour in 1889, is cut into a granite boulder at Sehel near Aswan. It says the Nile failed for seven years under King Djoser (about 2670 BCE), until his adviser Imhotep learned that the god Khnum must be honoured. The carving itself is Ptolemaic, probably from the reign of Ptolemy V (205 to 180 BCE).",
    record_ar: "لوحة المجاعة، التي عثر عليها تشارلز ويلبور سنة ١٨٨٩، منقوشةٌ على صخرةٍ من الغرانيت في جزيرة سهيل قرب أسوان. وتقول إن النيل لم يفِض سبع سنين في عهد الملك زوسر (نحو سنة ٢٦٧٠ قبل الميلاد)، حتى علم مستشاره إمحوتب أن الإله خنوم يجب أن يُكرَّم. أما النقش نفسه فبطلمي، والأرجح أنه من عهد بطليموس الخامس (٢٠٥ إلى ١٨٠ قبل الميلاد).",
    check_en: "The stone is real and the seven years are in it. But it was carved more than two thousand years after Djoser, most likely by the priests of Khnum to back their claim to land and revenue. Djoser also lived many centuries before any date given for Joseph. A seven-year famine was a common story pattern across the ancient Near East.",
    check_ar: "اللوحة حقيقية والسنون السبع فيها. لكنها نُقشت بعد زوسر بأكثر من ألفي عام، والأرجح أن كهنة خنوم وضعوها ليثبتوا حقّهم في الأرض والخراج. وزوسر نفسه عاش قبل أي تاريخٍ يُقترح ليوسف بقرونٍ كثيرة. والمجاعة ذات السنين السبع نمطٌ قصصي شائع في الشرق الأدنى القديم.",
    counter_en: "For some, the pattern itself is the point: Egypt remembered that the Nile could fail for seven years and that a wise official could save the country. That makes Joseph's story at home in Egypt, even if this stone is not about him.",
    counter_ar: "يرى بعضهم أن النمط نفسه هو المقصود: مصر كانت تذكر أن النيل قد يخذلها سبع سنين وأن موظفًا حكيمًا قد ينقذ البلاد. فقصة يوسف مألوفةٌ في مصر، وإن لم تكن هذه اللوحة عنه.",
    videos: [{id: 'GCRyLOgykyI', t: 60, by: 'Ancient Sites Girl', title: 'Proof of 7 Years of Famine in Ancient Egypt? FAMINE STELA'}],
    diff_en: "This video shows the stone and reads out the text. It concludes, as scholars do, that the priests of Khnum wrote it.",
    diff_ar: "يعرض هذا المقطع الصخرة ويقرأ نصّها، وينتهي كما ينتهي العلماء إلى أن كهنة خنوم هم من كتبوه.",
    written: -190, written_en: 'Stela carved under Ptolemy V', written_ar: 'نقش اللوحة في عهد بطليموس الخامس',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1889, recovered_en: 'Wilbour finds the stela', recovered_ar: 'ويلبور يعثر على اللوحة',
    source_en: "Famine Stela, Sehel Island. M. Lichtheim, Ancient Egyptian Literature, vol. 3 (1980). Genesis 41.",
    source_ar: "لوحة المجاعة، جزيرة سهيل. مريم ليشتهايم، الأدب المصري القديم، المجلد الثالث (١٩٨٠). سفر التكوين ٤١."
  },
  {
    id: 'thamud', region: 'arabia', verdict: 'holds',
    card_en: "Yes. Thamud are in Assyrian, Greek and Roman records. Arabs already knew of them.",
    card_ar: "نعم. ثمود في سجلات الآشوريين واليونان والرومان، والعرب كانوا يعرفونهم.",
    title_en: 'Thamud, who carved homes from rock', title_ar: 'ثمود الذين جابوا الصخر',
    short_en: 'Thamud', short_ar: 'ثمود',
    refs: ['7:74'], also: ['15:82', '89:9'],
    claim_en: "The Quran's Thamud, who carved houses out of the mountains, were a real people, and Assyrian records prove it.",
    claim_ar: "ثمود الذين نحتوا من الجبال بيوتًا شعبٌ حقيقي، وفي سجلات الآشوريين ما يثبت ذلك.",
    record_en: "The annals of Sargon II (reigned 722 to 705 BCE) list the \"Tamudi\" among desert Arabs he claims to have defeated. Greek writers from the 2nd century BCE place the Thamudeni in north-west Arabia, and a temple at Ruwafa was built around 165 to 169 CE by \"the tribal unit of Thamud\".",
    record_ar: "تذكر حوليات سرجون الثاني (حكم ٧٢٢ إلى ٧٠٥ قبل الميلاد) قبيلة «تمودي» بين عرب البادية الذين يزعم أنه هزمهم. ويضع الكتّاب اليونان منذ القرن الثاني قبل الميلاد «الثموديين» في شمال غرب الجزيرة، وقد بنت «جماعة ثمود» معبد الرُّوافة نحو سنة ١٦٥ إلى ١٦٩ للميلاد.",
    check_en: "Thamud are real and well attested. But they were never a secret in Arabia: pre-Islamic poets already spoke of them as a vanished tribe, and the Prophet passed the ruins of al-Hijr on the road to Tabuk. One correction to the usual picture: the grand rock-cut facades at Hegra are mostly Nabataean tombs from the 1st century CE.",
    check_ar: "ثمود شعبٌ حقيقي ثابتٌ في الآثار، لكنه لم يكن سرًّا عند العرب، فشعراء الجاهلية ذكروهم قومًا بائدين، ومرّ النبي ﷺ بديار الحِجر في طريقه إلى تبوك. ويحتاج التصوّر الشائع إلى تصحيحٍ واحد: فالواجهات المنحوتة الشهيرة في الحِجر مقابرُ نبطية في معظمها، من القرن الأول للميلاد.",
    counter_en: "The name Thamud still appears in Roman army lists of the 5th century CE, as cavalry units in Egypt and Palestine. That makes it hard to pin the destruction the Quran describes to a single date.",
    counter_ar: "يظهر اسم ثمود في قوائم الجيش الروماني في القرن الخامس للميلاد، فِرَقًا من الفرسان في مصر وفلسطين. وهذا يجعل تحديد زمن الهلاك الذي يصفه القرآن بتاريخٍ واحد أمرًا عسيرًا.",
    written: -715, written_en: "Sargon II's annals", written_ar: 'حوليات سرجون الثاني',
    lost: null, recovered: 1857, recovered_en: 'Assyrian cuneiform deciphered', recovered_ar: 'فكّ رموز المسمارية الآشورية',
    videos: [
      {id: 'z-mXik85lTc', t: 120, by: 'Omni-Islam', title: "The Thamud of Mada'in Salih: What Archaeology Actually Found"}],
    diff_en: "This video makes the same case from the Assyrian, Greek and Roman sources, and also says the great tombs are Nabataean.",
    diff_ar: "يعرض هذا المقطع الحجّة نفسها من المصادر الآشورية واليونانية والرومانية، ويقول كذلك إن المقابر الكبرى نبطية.",
    source_en: "Annals of Sargon II, Dur-Sharrukin (Khorsabad). Diodorus Siculus, Library of History, book 3. Ruwafa inscription (Greek and Nabataean). Notitia Dignitatum.",
    source_ar: "حوليات سرجون الثاني، دور شروكين (خورسباد). ديودور الصقلي، المكتبة التاريخية، الكتاب الثالث. نقش الرُّوافة (يوناني ونبطي). سجلّ المناصب الروماني «نوتيتيا ديغنيتاتوم»."
  },
  {
    id: 'iram', region: 'arabia', verdict: 'weak',
    card_en: "No. A real fort was found at Shisr, but its own excavator did not call it Iram.",
    card_ar: "لا. عُثر في الشِّصر على حصنٍ حقيقي، لكن المنقّب نفسه لم يقل إنه إرم.",
    title_en: 'Iram of the pillars', title_ar: 'إرم ذات العماد',
    short_en: 'Iram', short_ar: 'إرم',
    refs: ['89:6', '89:7', '89:8'],
    claim_en: "In 1992 a team using NASA radar images found Ubar, the \"Atlantis of the Sands\", in Oman, and it was identified as Iram of the pillars.",
    claim_ar: "في سنة ١٩٩٢ عثر فريقٌ استعان بصور رادار من وكالة ناسا على «أوبار»، المسمّاة «أطلانطس الرمال»، في عُمان، وقيل إنها إرم ذات العماد.",
    record_en: "The team, including filmmaker Nicholas Clapp and archaeologist Juris Zarins, followed old caravan tracks to Shisr, an oasis about 170 km north of Salalah, and excavated a fortified site on the frankincense trade route.",
    record_ar: "تتبّع الفريق، ومنه المخرج نيكولاس كلاب والآثاري يوريس زارينز، آثار طرق القوافل القديمة حتى واحة الشِّصر، على نحو ١٧٠ كيلومترًا شمال صلالة، وكشف عن موقعٍ محصّن على طريق تجارة اللبان.",
    check_en: "The find is real; the identification is not. Zarins argued that Ubar named a region and a people, not one town, and most scholars read Shisr as a caravan station rather than a lost city. Iram was never hidden knowledge either: Arab tradition told of 'Ad and Iram long before any satellite.",
    check_ar: "الاكتشاف حقيقي، أما نسبته إلى إرم فلا. فقد رأى زارينز أن «أوبار» اسمٌ لإقليمٍ وقوم لا لمدينةٍ واحدة، ويرى أكثر الباحثين في الشِّصر محطةً للقوافل لا مدينةً مفقودة. ولم تكن إرم علمًا خفيًّا أصلًا، فأخبار عادٍ وإرم حاضرةٌ في تراث العرب قبل الأقمار الصناعية بقرون.",
    counter_en: "Supporters point out that part of the fort collapsed into a sinkhole under its well, which fits the legend of a city swallowed by the sand. A collapse fits a ruin, but it does not tell you its name.",
    counter_ar: "يشير المؤيدون إلى أن جزءًا من الحصن انهار في تجويفٍ أرضي تحت بئره، وهذا يوافق أسطورة المدينة التي ابتلعتها الرمال. لكن الانهيار يصف خرابًا، ولا يخبرك باسمه.",
    written: null, lost: null, recovered: 1992, recovered_en: 'Shisr excavated', recovered_ar: 'التنقيب في الشِّصر',
    videos: [
      {id: 'NeKgfyN106I', t: 0, by: 'M07RYD', title: 'The Lost City of Iram of the Pillars Only Mentioned in Quran'}],
    diff_en: "The video says the city was found with the help of a map by Ptolemy, and that its pillars prove it is Iram. The dig found the towers of a fort. It found no inscription naming the place.",
    diff_ar: "يقول المقطع إن المدينة عُثر عليها بمعونة خريطةٍ لبطليموس، وإن أعمدتها تثبت أنها إرم. والتنقيب كشف عن أبراج حصن، ولم يكشف عن نقشٍ يسمّي المكان.",
    source_en: "N. Clapp, The Road to Ubar (1998). J. Zarins, The Land of Incense (2001).",
    source_ar: "نيكولاس كلاب، الطريق إلى أوبار (١٩٩٨). يوريس زارينز، أرض اللبان (٢٠٠١)."
  },
  {
    id: 'ebla', region: 'neareast', verdict: 'weak',
    card_en: "No. The first readings of those names were withdrawn or rejected by the scholars who publish the tablets.",
    card_ar: "لا. القراءات الأولى لتلك الأسماء سحبها أصحابها أو ردّها العلماء الذين ينشرون الألواح.",
    title_en: 'Iram and Sodom on the Ebla tablets', title_ar: 'إرم وسدوم في ألواح إبلا',
    short_en: 'Ebla tablets', short_ar: 'ألواح إبلا',
    refs: ['89:7'], also: ['11:82', '15:74'],
    claim_en: "In 1975 thousands of clay tablets were found at Ebla in Syria, written about 2350 BCE. The claim: they name Sodom, Gomorrah and Iram, cities otherwise known only from scripture, and even the names of prophets.",
    claim_ar: "في سنة ١٩٧٥ عُثر في إبلا بسورية على آلاف الألواح الطينية المكتوبة نحو سنة ٢٣٥٠ قبل الميلاد. ويُقال إنها تذكر سدوم وعمورة وإرم، وهي مدنٌ لا تُعرف إلا من الكتب المقدسة، بل تذكر أسماء أنبياء.",
    record_en: "The archive is real: thousands of tablets and fragments from the palace of Ebla, burned around 2300 BCE and found by an Italian team in 1974 and 1975. In 1976 the first epigrapher, Giovanni Pettinato, announced that he had read Sodom and Gomorrah in them. A 1978 magazine report added Iram to the list.",
    record_ar: "الأرشيف حقيقي: آلاف الألواح والكِسَر من قصر إبلا الذي احترق نحو سنة ٢٣٠٠ قبل الميلاد، وعثرت عليها بعثةٌ إيطالية سنتي ١٩٧٤ و١٩٧٥. وفي سنة ١٩٧٦ أعلن عالم النقوش الأول في البعثة، جوفاني بتيناتو، أنه قرأ فيها سدوم وعمورة. ثم أضاف تقريرٌ صحفي سنة ١٩٧٨ إرمَ إلى القائمة.",
    check_en: "Those readings did not last. Alfonso Archi, who took over the tablets, rejected the Sodom reading in 1979 and 1981, and Pettinato withdrew part of his own. The editors of the tablets now say they contain no places or people from scripture. We could find no published tablet that names Iram.",
    check_ar: "لم تصمد تلك القراءات. فألفونسو أركي، الذي تولّى الألواح بعده، ردّ قراءة «سدوم» سنتي ١٩٧٩ و١٩٨١، وسحب بتيناتو جزءًا من قراءاته. ومحقّقو الألواح يقولون اليوم إنها لا تذكر أماكن ولا أشخاصًا من الكتب المقدسة. ولم نجد لوحًا منشورًا يذكر إرم.",
    counter_en: "Ebla's personal names do include forms like Ishmael and Abram, which shows such names were ordinary in ancient Syria. That is real, but it is evidence about a family of languages, not about the prophets themselves.",
    counter_ar: "في أسماء الأشخاص بإبلا صيغٌ مثل إسماعيل وأبرام فعلًا، وهذا يدلّ على أن هذه الأسماء كانت مألوفةً في سورية القديمة. وهو أمرٌ ثابت، لكنه دليلٌ على أسرةٍ لغوية، لا على الأنبياء أنفسهم.",
    videos: [{id: 'baEfquwukks', t: 332, by: 'Harun Yahya English', title: 'The Prophet Whose Name Appears on the Ebla Tablets', n_en: 'Turkish audio', n_ar: 'بالتركية'}],
    diff_en: "The video is in Turkish. It presents the first readings from the 1970s as fact.",
    diff_ar: "المقطع بالتركية، ويعرض قراءات السبعينيات الأولى كأنها حقائق.",
    written: -2350, written_en: "Ebla's archive is written", written_ar: 'كتابة أرشيف إبلا',
    lost: -2300, lost_en: 'Ebla burns and the archive is buried', lost_ar: 'احتراق إبلا ودفن الأرشيف',
    recovered: 1975, recovered_en: 'The archive is excavated', recovered_ar: 'التنقيب عن الأرشيف',
    source_en: "G. Pettinato, The Archives of Ebla (1981). A. Archi, \"The Epigraphic Evidence from Ebla and the Old Testament\", Biblica 60 (1979). H. La Fay, \"Ebla: Splendor of an Unknown Empire\", National Geographic, December 1978.",
    source_ar: "جوفاني بتيناتو، أرشيفات إبلا (١٩٨١). ألفونسو أركي، «الشواهد النقشية من إبلا والعهد القديم»، مجلة بيبليكا ٦٠ (١٩٧٩). هوارد لا فاي، «إبلا: بهاء إمبراطوريةٍ مجهولة»، ناشيونال جيوغرافيك، ديسمبر ١٩٧٨."
  },
  {
    id: 'dam', region: 'arabia', verdict: 'holds',
    card_en: "Yes. The dam's own inscriptions record its breaches, and Arabia remembered it.",
    card_ar: "نعم. نقوش السدّ نفسه تسجّل ثُلماته، وكانت العرب تذكره.",
    title_en: 'The flood of the dam at Saba', title_ar: 'سيل العرم',
    short_en: 'Marib dam', short_ar: 'سدّ مأرب',
    refs: ['34:16'], also: ['34:15'],
    claim_en: "The \"flood of al-'Arim\" that ruined Saba's two gardens is the failure of the great Marib dam, and the dam's own inscriptions record it.",
    claim_ar: "«سيل العرم» الذي أهلك جنّتَي سبأ هو انهيار سدّ مأرب العظيم، ونقوش السدّ نفسها تشهد بذلك.",
    record_en: "Sabaic inscriptions at Marib record two breaches repaired in 454 and 455 CE under King Shurihbi'il Ya'fur, and another sealed in 547 under Abraha, told in his 136-line inscription of 548 CE (CIH 541). The dam was overtopped again in about 570 or 575 CE and never repaired.",
    record_ar: "تسجّل النقوش السبئية في مأرب ثُلمتين رُمّمتا سنتي ٤٥٤ و٤٥٥ للميلاد في عهد الملك شُرَحبئيل يَعفُر، وثُلمةً ثالثة سُدّت سنة ٥٤٧ في عهد أبرهة، يرويها نقشه الطويل (CIH 541) المؤرخ سنة ٥٤٨ في مئةٍ وستةٍ وثلاثين سطرًا. ثم طغى الماء على السدّ مرةً أخرى نحو سنة ٥٧٠ أو ٥٧٥، ولم يُرمَّم بعدها.",
    check_en: "The dam, its breaches and its end are recorded in stone, so the match is solid. It is also history the first listeners could know for themselves: the final collapse was within living memory, and the musnad script was still written in Yemen. This one is a true match, not hidden knowledge.",
    check_ar: "السدّ وثُلماته ونهايته مسجّلةٌ على الحجر، فالتطابق متين. وهو كذلك تاريخٌ كان في متناول السامعين الأوائل، فالانهيار الأخير وقع في حياة بعضهم، وخطّ المسند كان لا يزال يُكتب في اليمن. فهذا تطابقٌ صحيح، لا علمٌ محجوب.",
    counter_en: "Which breach the verse means is debated. Some historians link it to an earlier break, around 145 BCE, rather than to the final collapse.",
    counter_ar: "يختلف المؤرخون في الثُّلمة المقصودة، فبعضهم يربط الآية بانهيارٍ أقدم وقع نحو سنة ١٤٥ قبل الميلاد، لا بالانهيار الأخير.",
    written: 454, written_en: 'First dated breach inscription', written_ar: 'أول نقشٍ مؤرخ لثُلمة السدّ',
    lost: null, recovered: 1841, recovered_en: 'Sabaic script deciphered', recovered_ar: 'فكّ رموز خطّ المسند',
    videos: [
      {id: '8B56bt_VkX8', t: 0, by: 'The Hijazi', title: 'Why Did Allah Destroy the Nation of Saba? | Quran Stories'}],
    diff_en: "This video tells the story as tradition has it, including the creature that gnawed at the dam. It does not discuss the inscriptions.",
    diff_ar: "يروي هذا المقطع القصة كما في الروايات، ومنها الدابّة التي نخرت السدّ. ولا يتناول النقوش.",
    source_en: "CIH 540 (Shurihbi'il Ya'fur) and CIH 541 (Abraha, 548 CE), Great Dam of Marib. E. Rödiger and W. Gesenius, decipherment of the South Arabian script (1841).",
    source_ar: "النقشان CIH 540 (شرحبئيل يعفر) وCIH 541 (أبرهة، ٥٤٨م)، سدّ مأرب العظيم. إميل رودِيغر وفيلهلم غيزينيوس، فكّ رموز خطّ المسند (١٨٤١)."
  },
  {
    id: 'elephant', region: 'arabia', verdict: 'holds',
    card_en: "Yes. Abraha's own inscriptions record his march into Arabia. The date is the open question.",
    card_ar: "نعم. نقوش أبرهة نفسه تسجّل حملته على الجزيرة، والسؤال المفتوح هو التاريخ.",
    title_en: 'Abraha and the Year of the Elephant', title_ar: 'أبرهة وعام الفيل',
    short_en: "Abraha's army", short_ar: 'جيش أبرهة',
    refs: ['105:1'], also: ['105:2', '105:3', '105:4', '105:5'],
    claim_en: "The army of Surah al-Fil belonged to Abraha, the Christian ruler of Yemen, and his campaigns into Arabia are carved in his own inscriptions.",
    claim_ar: "جيش أصحاب الفيل هو جيش أبرهة، حاكم اليمن النصراني، وحملاته على جزيرة العرب مسجّلةٌ في نقوشه هو.",
    record_en: "Abraha ruled the Himyarite kingdom from about 533 CE. His Murayghan inscription (Ry 506), dated 552 CE, records a campaign into central Arabia against the tribes of Ma'add.",
    record_ar: "حكم أبرهة مملكة حِميَر منذ نحو سنة ٥٣٣ للميلاد. ويسجّل نقش مُرَيغان (Ry 506) المؤرخ سنة ٥٥٢ حملةً له على وسط الجزيرة ضدّ قبائل مَعَدّ.",
    check_en: "Abraha is one of the best-documented rulers of pre-Islamic Arabia, so the surah names a real king with a real record of marching north. Its first listeners did not need an archive: many of them had grown up with the story.",
    check_ar: "أبرهة من أوفر حكّام الجزيرة قبل الإسلام حظًّا من التوثيق، فالسورة تذكر ملكًا حقيقيًا ثبتت حملاته شمالًا. ولم يكن السامعون الأوائل بحاجةٍ إلى أرشيف، فكثيرٌ منهم نشأ على هذه القصة.",
    counter_en: "Tradition puts the Year of the Elephant at about 570 CE, the year of the Prophet's birth, but Abraha's dated inscriptions stop in the 550s and he probably died before 560. Historians still argue over which should move, the date or the campaign.",
    counter_ar: "تجعل الروايةُ عامَ الفيل نحو سنة ٥٧٠ للميلاد، عامَ مولد النبي ﷺ، لكن نقوش أبرهة المؤرخة تتوقف في خمسينيات القرن السادس، والأرجح أنه مات قبل سنة ٥٦٠. ولا يزال المؤرخون مختلفين في أيّهما يُعدَّل: التاريخ أم الحملة.",
    written: 552, written_en: 'Murayghan inscription (Ry 506)', written_ar: 'نقش مريغان (Ry 506)',
    lost: null, recovered: 1841, recovered_en: 'Sabaic script deciphered', recovered_ar: 'فكّ رموز خطّ المسند',
    videos: [
      {id: 'Y_tU8A2MVXg', t: 140, by: 'DawahBook TV', title: 'The Year of the Elephant: The Army That Tried to Destroy the Kaaba'}],
    diff_en: "This video says it plainly: the inscription confirms Abraha and his campaigns in Arabia, not the attack on the Kaaba itself.",
    diff_ar: "يقولها هذا المقطع صريحةً: النقش يثبت أبرهة وحملاته في الجزيرة، لا الهجوم على الكعبة نفسه.",
    source_en: "Murayghan inscription Ry 506 (552 CE). C. J. Robin, studies of Abraha's reign and the campaign of the elephant.",
    source_ar: "نقش مريغان Ry 506 (٥٥٢م). كريستيان روبان، دراساته عن حكم أبرهة وحملة الفيل."
  },
  {
    id: 'romans', region: 'neareast', verdict: 'holds',
    card_en: "Yes. Heraclius turned the war around within the years the verses give.",
    card_ar: "نعم. قلب هرقل مجرى الحرب في المدة التي حدّدتها الآيات.",
    title_en: '"The Romans have been defeated"', title_ar: '«غُلِبت الروم»',
    short_en: "Rome's comeback", short_ar: 'غلبة الروم',
    refs: ['30:2', '30:3', '30:4'],
    claim_en: "Revealed after Persia crushed the Byzantines, the verses predict a Byzantine comeback within \"a few years\" (bid' sinin, three to nine). Some add that \"adna al-ard\" means \"the lowest land\": the Dead Sea basin, the lowest point on Earth.",
    claim_ar: "نزلت الآيات بعد أن سحق الفرسُ الروم، وفيها نبوءةٌ بأن الروم سيَغلبون «في بضع سنين»، والبضع ما بين الثلاث والتسع. ويضيف بعضهم أن «أدنى الأرض» معناها أخفض بقعةٍ على وجه الأرض، أي حوض البحر الميت.",
    record_en: "Persia captured Jerusalem in 614 CE. Emperor Heraclius won his first major victory over the Persians in 622 and broke their army near Nineveh in December 627; peace followed in 628.",
    record_ar: "استولى الفرس على بيت المقدس سنة ٦١٤ للميلاد. ثم أحرز الإمبراطور هرقل أول نصرٍ كبير عليهم سنة ٦٢٢، وحطّم جيشهم قرب نينوى في ديسمبر ٦٢٧، وعُقد الصلح سنة ٦٢٨.",
    check_en: "The reversal happened, and inside the window the verses give, if they came down around 614 to 616 CE as tradition holds. The \"lowest land\" reading is modern, though. The early commentators read adna as \"nearest\": the lands closest to Arabia.",
    check_ar: "وقع الانقلاب فعلًا، وفي المدة التي تحدّدها الآيات، إن صحّ أنها نزلت نحو سنة ٦١٤ إلى ٦١٦ كما تقول الرواية. أما تفسير «أدنى الأرض» بأخفضها فحديث، إذ فهمها المفسرون الأوائل بمعنى «أقربها»، أي أقرب الأرض إلى بلاد العرب.",
    counter_en: "The date of the verses comes from the same tradition that reports the prophecy coming true, so the timing cannot be checked against an independent source.",
    counter_ar: "تاريخ نزول الآيات مأخوذٌ من الرواية نفسها التي تروي تحقّق النبوءة، فلا سبيل إلى التحقق من التوقيت بمصدرٍ مستقل.",
    written: 614, written_en: 'Persians take Jerusalem', written_ar: 'الفرس يأخذون بيت المقدس',
    lost: null, recovered: null,
    videos: [
      {id: '29cN6q3Of3c', t: 180, by: 'Towards Eternity', title: "Quran's 2 Shocking Prophecies Came True! Confessions of Non-Muslim Historians"},
      {id: 'LFpFGaxSOEw', t: 140, by: 'The Last Dialogue', title: 'Miracle Of Surah Rum: Romans Victory & Lowest Place On Earth'}],
    diff_en: "The second video itself says the early commentators read the word as \"nearest\", and offers \"lowest\" as an added meaning. It dates Badr to 623 and the conquest of Mecca to 628. They were in 624 and 630.",
    diff_ar: "يقول المقطع الثاني نفسه إن المفسرين الأوائل فهموا الكلمة بمعنى «أقرب»، ويعرض «أخفض» معنًى إضافيًا. ويؤرّخ بدرًا بسنة ٦٢٣ وفتح مكة بسنة ٦٢٨، والصحيح ٦٢٤ و٦٣٠.",
    source_en: "Chronicon Paschale; Theophanes, Chronographia. Tafsir al-Tabari on 30:2-4.",
    source_ar: "التاريخ الفصحي (Chronicon Paschale)، وحوليات ثيوفانيس. تفسير الطبري للآيات ٣٠:٢-٤."
  },
  {
    id: 'judi', region: 'neareast', verdict: 'holds',
    card_en: "Yes. Al-Judi matches the older Mesopotamian and Aramaic tradition, which was still alive.",
    card_ar: "نعم. الجوديّ يوافق التقليد الرافديني والآرامي الأقدم، وكان لا يزال حيًّا.",
    title_en: 'The ark comes to rest on al-Judi', title_ar: 'واستوت على الجوديّ',
    short_en: 'Ark on al-Judi', short_ar: 'سفينة نوح',
    refs: ['11:44'],
    claim_en: "The Bible lands the ark on \"the mountains of Ararat\". The Quran names al-Judi instead, and that choice matches an older tradition.",
    claim_ar: "ترسو السفينة في التوراة على «جبال أراراط»، أما القرآن فيسمّي «الجوديّ»، وهذا الاختيار يوافق تقليدًا أقدم.",
    record_en: "Berossus, a Babylonian priest of the 3rd century BCE quoted by Josephus, said remains of the vessel survived \"at the mountain of the Cordyaeans\". The Aramaic Jewish translations of Genesis (the Targums, Onkelos among them) say \"the mountains of Qardu\". That is the old Gordyene district, where Mount Cudi stands in south-east Turkey.",
    record_ar: "قال بيروسوس، الكاهن البابلي في القرن الثالث قبل الميلاد، فيما ينقله عنه يوسيفوس، إن بقايا السفينة باقيةٌ «عند جبل الكَرْدويين». وتقول الترجمات الآرامية اليهودية لسفر التكوين، ومنها ترجمة أونقيلوس، «جبال قَرْدو». وتلك هي ناحية «قردو» القديمة التي يقوم فيها جبل الجودي في جنوب شرق تركيا.",
    check_en: "The Quran sides with the older Mesopotamian and Aramaic tradition, not with the Ararat one most Bible readers know. That tradition was alive among Syriac Christians and Jews in the 7th century, so this is agreement with an existing source, not hidden knowledge. Classical Muslim geographers such as Yaqut place al-Judi above Jazirat Ibn 'Umar, today's Cizre, on the same range.",
    check_ar: "يقف القرآن مع التقليد الرافديني والآرامي الأقدم، لا مع «أراراط» الذي يعرفه أكثر قرّاء التوراة. وكان ذلك التقليد حيًّا عند السريان واليهود في القرن السابع، فهذا توافقٌ مع مصدرٍ قائم، لا علمٌ محجوب. ويضع الجغرافيون المسلمون، كياقوت، الجوديَّ مطلًّا على جزيرة ابن عمر، وهي مدينة جزرة التركية اليوم، في السلسلة نفسها.",
    counter_en: "Ararat is also the old name of the kingdom of Urartu, a wide highland region bordering these mountains. So the Bible and the Quran may not disagree at all.",
    counter_ar: "«أراراط» هو أيضًا الاسم القديم لمملكة أورارطو، وهي إقليمٌ جبلي واسع يتاخم هذه الجبال، فقد لا يكون بين التوراة والقرآن خلافٌ أصلًا.",
    written: -290, written_en: 'Berossus writes his history', written_ar: 'بيروسوس يكتب تاريخه',
    lost: null, recovered: null,
    videos: [
      {id: 'D3fBhRpy1tk', t: 480, by: 'Islamic Guidance', title: "Landing Site Of Noah's Ark, Judi Or Ararat?"}],
    diff_en: "This video compares the two mountains. The separate claim that the Ark itself has been found is checked under \"Noah's Ark found at Durupinar\".",
    diff_ar: "يقارن هذا المقطع بين الجبلين. أما المزعم الآخر، وهو أن السفينة نفسها عُثر عليها، ففحصه تحت عنوان «سفينة نوح في موقع دوروبينار».",
    source_en: "Josephus, Antiquities of the Jews 1.3.6 (quoting Berossus). Targum Onkelos, Genesis 8:4. Yaqut al-Hamawi, Mu'jam al-Buldan, entry al-Judi.",
    source_ar: "يوسيفوس، آثار اليهود ١.٣.٦ (نقلًا عن بيروسوس). ترجوم أونقيلوس، التكوين ٨:٤. ياقوت الحموي، معجم البلدان، مادة «الجودي»."
  },
  {
    id: 'ark', region: 'neareast', verdict: 'weak',
    card_en: "No. Geologists who drilled the boat shape found natural rock, and it lies about 280 km from the mountain tradition calls Judi.",
    card_ar: "لا. الجيولوجيون الذين حفروا في الشكل وجدوا صخرًا طبيعيًا، وهو يبعد نحو ٢٨٠ كيلومترًا عن الجبل الذي تسمّيه الرواية الجوديّ.",
    title_en: "Noah's Ark found at Durupinar", title_ar: 'سفينة نوح في موقع دوروبينار',
    short_en: 'Durupinar "ark"', short_ar: 'موقع دوروبينار',
    refs: ['11:44'], also: ['54:13', '54:15'],
    claim_en: "A boat-shaped outline in eastern Turkey, first seen in air photographs in 1959, is said to be the Ark: the right length, with radar showing beams and decks, metal rivets in the soil and anchor stones nearby. The claim: it lies on Mount Judi, exactly where the Quran says.",
    claim_ar: "شكلٌ على هيئة سفينة في شرق تركيا، ظهر أول مرة في صورٍ جوية سنة ١٩٥٩، يُقال إنه السفينة: بالطول الصحيح، والرادار يُظهر فيه عوارض وطوابق، وفي التربة مسامير معدنية، وبالقرب منه أحجار مراسٍ. ويُقال إنه على جبل الجوديّ، حيث ذكر القرآن تمامًا.",
    record_en: "The outline is real. Captain Ilhan Durupinar spotted it in survey photographs in 1959. It is a 164-metre mound of iron-rich rock on the slopes of Mount Tendurek, near the village of Uzengili, about 30 km south of Mount Ararat. Ron Wyatt and David Fasold promoted it as the Ark from the 1970s.",
    record_ar: "الشكل حقيقي. رصده النقيب إلهان دوروبينار في صور المسح الجوي سنة ١٩٥٩. وهو تلٌّ طوله ١٦٤ مترًا من صخرٍ غنيٍّ بالحديد على سفوح جبل تندورك، قرب قرية أوزنغيلي، على نحو ٣٠ كيلومترًا جنوب جبل أرارات. وروّج له رون وايات وديفيد فاسولد سفينةً لنوح منذ السبعينيات.",
    check_en: "Fasold later changed his mind. After drilling at the site, he and the geologist Lorence Collins published a study in 1996 that found a natural formation: folded rock shaped by a landslide, with the \"rivets\" being lumps of iron ore. The mountain that Muslim geographers and local tradition call Judi stands near Cizre, about 280 km to the south-west. So the shape is neither a ship nor on that mountain.",
    check_ar: "غيّر فاسولد رأيه بعد ذلك. فبعد الحفر في الموقع نشر مع الجيولوجي لورنس كولينز دراسةً سنة ١٩٩٦ انتهت إلى أنه تكوينٌ طبيعي: صخرٌ مطويٌّ شكّله انزلاقٌ أرضي، و«المسامير» كتلٌ من خام الحديد. أما الجبل الذي يسمّيه الجغرافيون المسلمون وأهل المنطقة الجوديَّ فيقع قرب جزيرة ابن عمر، على نحو ٢٨٠ كيلومترًا إلى الجنوب الغربي. فالشكل ليس سفينةً، وليس على ذلك الجبل.",
    counter_en: "Recent radar surveys report straight lines and right angles under the soil, and a Turkish and American team is still studying the site. Radar shows shapes, not timber. Until something is dug up and dated, the 1996 finding stands.",
    counter_ar: "تتحدث مسوحٌ راداريةٌ حديثة عن خطوطٍ مستقيمة وزوايا قائمة تحت التربة، وما زال فريقٌ تركي أمريكي يدرس الموقع. والرادار يُظهر أشكالًا لا أخشابًا. وإلى أن يُستخرج شيءٌ ويُؤرَّخ، تبقى نتيجة سنة ١٩٩٦ قائمة.",
    videos: [
      {id: 'YN4XnfV3wBM', t: 0, by: 'ISLAMICA', title: "Is This The Real Location of Noah's Ark?"},
      {id: '_5xQt6HbBxI', t: 0, by: 'Dark Era Docs', title: 'The Quran is Right: We Found The Ark On Mount Judi'}],
    diff_en: "One video says Mount Ararat is 20 miles from Mount Judi. That is the distance from Ararat to this site. The Judi of tradition is far to the south-west.",
    diff_ar: "يقول أحد المقطعين إن جبل أرارات يبعد عشرين ميلًا عن الجوديّ. وهذه هي المسافة بين أرارات وهذا الموقع. أما الجوديّ في الرواية فبعيدٌ في الجنوب الغربي.",
    written: null, lost: null, recovered: 1959, recovered_en: 'First seen in air photographs', recovered_ar: 'ظهوره أول مرة في الصور الجوية',
    acc_en: 'Not a written record: a rock formation, first photographed in 1959 and drilled in the 1990s.',
    acc_ar: 'ليس نصًّا مكتوبًا، بل تكوينٌ صخري صُوّر أول مرة سنة ١٩٥٩ وحُفر فيه في التسعينيات.',
    source_en: "L. G. Collins and D. F. Fasold, \"Bogus 'Noah's Ark' from Turkey Exposed as a Common Geologic Structure\", Journal of Geoscience Education 44 (1996).",
    source_ar: "لورنس كولينز وديفيد فاسولد، «سفينة نوح الزائفة في تركيا: تكوينٌ جيولوجي مألوف»، مجلة تعليم علوم الأرض ٤٤ (١٩٩٦)."
  }
];
