// History Claims: popular claims that a verse matches the ancient record, checked one by one.
// Verse text is NOT stored here. Cards read it live from corpus.js (QURAN_VERSES) and translation_en.js (QURAN_EN) by key.
// Years are numbers (negative = BCE). lost = last year the record could be read (null = never lost before the revelation).
// verdict: 'holds' | 'partial' | 'weak' (how well the claim as stated survives the evidence). card_* is the one-line answer on the index.
// region: 'egypt' | 'arabia' | 'neareast'. To add a claim, append an entry with the same shape.

const QURAN_HISTORY_INTRO = {
  en: "Short videos often say a verse matches something only an archaeologist could know. We take those claims one at a time: what the ancient record really says, whether anyone in 7th-century Arabia could have read it, and what the other side argues.",
  ar: "كثيرًا ما تقول المقاطع القصيرة إن آيةً ما توافق أمرًا لا يعرفه إلا علماء الآثار. نأخذ هنا هذه المزاعم واحدًا واحدًا: ما يقوله الأثر القديم فعلًا، وهل كان في وسع أحدٍ في جزيرة العرب في القرن السابع أن يقرأه، وما حجة الطرف الآخر."
};

const QURAN_HISTORY = [
  {
    id: 'weep', region: 'egypt', verdict: 'partial', featured: true,
    card_en: "Partly. The Egyptian line is real and the verse answers it, but the short overstates how long it was lost, and Arabs had the phrase too.",
    card_ar: "جزئيًا. العبارة المصرية ثابتة والآية تردّ عليها، لكن المقطع يبالغ في مدة ضياعها، والعرب عرفوا العبارة كذلك.",
    tag_en: 'Viral short', tag_ar: 'مقطع منتشر',
    title_en: 'The sky did not weep for them', title_ar: 'فما بكت عليهم السماء',
    short_en: 'Sky did not weep', short_ar: 'لم تبكِ السماء',
    refs: ['44:29'],
    quote_en: 'The sky weeps for thee; the earth trembles for thee.',
    quote_ar: 'السماء تبكي عليك، والأرض ترتجف لك.',
    quote_lab_en: 'Pyramid Texts, Utterance 553', quote_lab_ar: 'نصوص الأهرام، التعويذة ٥٥٣',
    quote_note_en: 'Said to the dead king. Carved inside royal pyramids about 2300 BCE.',
    quote_note_ar: 'خطابٌ للملك الميت، نُقش داخل أهرام الملوك نحو سنة ٢٣٠٠ قبل الميلاد.',
    claim_en: "Ancient Egyptian royal texts said the sky and the earth weep when a king dies. The verse says they did not weep for Pharaoh's people. The claim adds that nobody could read those texts until the 19th century.",
    claim_ar: "كانت نصوص الملوك في مصر القديمة تقول إن السماء والأرض تبكيان إذا مات الملك، والآية تنفي هذا البكاء عن قوم فرعون. ويضيف أصحاب هذا الطرح أن أحدًا لم يكن يقدر على قراءة تلك النصوص حتى القرن التاسع عشر.",
    record_en: "The Pyramid Texts, Utterance 553, say to the dead king: \"The sky weeps for thee; the earth trembles for thee.\" These texts were carved inside royal pyramids of the late Old Kingdom, around 2300 BCE, and copied into later tombs for centuries. The pyramid walls themselves were seen again only in 1880, when Gaston Maspero opened the pyramids at Saqqara.",
    record_ar: "تخاطب «نصوص الأهرام» الملكَ الميت في التعويذة ٥٥٣ بقولها: «السماء تبكي عليك، والأرض ترتجف لك». وقد نُقشت هذه النصوص داخل أهرام الملوك في أواخر الدولة القديمة نحو سنة ٢٣٠٠ قبل الميلاد، وظلّت تُنسخ في المقابر قرونًا بعد ذلك. ولم تُرَ جدران الأهرام نفسها من جديد إلا سنة ١٨٨٠، حين فتح غاستون ماسبيرو أهرام سقارة.",
    check_en: "The match is real. \"The sky weeps for thee\" is a genuine Egyptian royal formula, and the verse withholds exactly that honour from the people whose religion claimed it. The short overstates the gap, though. It says the knowledge went dark in the 6th century BCE. In fact priests were still carving hieroglyphs at Philae in 394 CE, and the temple there was only closed in the 530s. Even so, the script was dead well before the revelation. Nobody could read it until Champollion in 1822, and these texts were not found until 1880.",
    check_ar: "التطابق حقيقي، فعبارة «السماء تبكي عليك» صيغةٌ ملكية مصرية ثابتة، والآية تنفي هذا التكريم عن القوم الذين كانت ديانتهم تدّعيه لملوكهم. غير أن المقطع يبالغ في طول الفجوة، إذ يقول إن هذا العلم انطمس منذ القرن السادس قبل الميلاد، والصحيح أن الكهنة ظلّوا ينقشون الهيروغليفية في فيلة حتى سنة ٣٩٤ للميلاد، وأن معبدها لم يُغلق إلا في ثلاثينيات القرن السادس. ومع ذلك كان الخطّ قد مات قبل نزول الوحي بزمن، ولم يقرأه أحدٌ حتى فكّ شامبليون رموزه سنة ١٨٢٢، ولم يُعثر على هذه النصوص إلا سنة ١٨٨٠.",
    counter_en: "Al-Zamakhshari (d. 1144) and al-Qurtubi (d. 1273) both record that Arabs honoured a great man's death by saying \"the sky and the earth wept for him\". So the phrase had a way into Arabic that did not pass through Egypt. The poems they quote as proof come from after the Quran, though, so how old that Arabic idiom really is stays an open question.",
    counter_ar: "ينقل الزمخشري (ت ٥٣٨ هـ) والقرطبي (ت ٦٧١ هـ) أن العرب كانت تقول إذا مات فيهم السيد: «بكت عليه السماء والأرض». فللعبارة طريقٌ إلى العربية لا يمرّ بمصر. لكن الأبيات التي يستشهدان بها لشعراء جاؤوا بعد نزول القرآن، فيبقى قِدَم هذا التعبير عند العرب سؤالًا مفتوحًا.",
    reading_en: "Ali and Ibn Abbas explained the verse this way: when a believer dies, his place of prayer on earth and the gate in the sky through which his deeds rose both weep for him. Pharaoh's people left neither behind.",
    reading_ar: "فسّرها عليٌّ وابن عباس بأن المؤمن إذا مات بكى عليه مُصلّاه من الأرض ومَصعدُ عمله من السماء، وقوم فرعون لم يتركوا هذا ولا ذاك.",
    written: -2300, written_en: 'Pyramid Texts carved', written_ar: 'نقش نصوص الأهرام',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1880, recovered_en: 'Pyramid Texts found at Saqqara', recovered_ar: 'العثور على نصوص الأهرام في سقارة',
    source_en: "Pyramid Texts, Utterance 553, §1365 (S. A. B. Mercer translation, 1952). G. Maspero, excavations at Saqqara (1880 to 1881). Graffito of Esmet-Akhom, Philae, 24 August 394 CE. Tafsir of al-Zamakhshari (al-Kashshaf), al-Qurtubi and Ibn Kathir on 44:29.",
    source_ar: "نصوص الأهرام، التعويذة ٥٥٣، الفقرة ١٣٦٥ (ترجمة صموئيل ميرسر، ١٩٥٢). غاستون ماسبيرو، حفائر سقارة (١٨٨٠ إلى ١٨٨١). نقش إسمت-أخوم في فيلة، ٢٤ أغسطس ٣٩٤م. تفسير الزمخشري (الكشاف) والقرطبي وابن كثير للآية ٤٤:٢٩."
  },
  {
    id: 'king', region: 'egypt', verdict: 'holds', live: 'kingPharaoh',
    card_en: "Yes. \"Pharaoh\" never appears in Joseph's story, and Egypt only gave its king that title later.",
    card_ar: "نعم. لا يرد «فرعون» في قصة يوسف قط، ومصر لم تلقّب ملكها بهذا اللقب إلا لاحقًا.",
    title_en: 'A king for Joseph, a Pharaoh for Moses', title_ar: 'ملكٌ في قصة يوسف، وفرعونُ في قصة موسى',
    short_en: 'King vs Pharaoh', short_ar: 'الملك وفرعون',
    refs: ['12:43'], also: ['12:50', '12:54', '12:72', '12:76'],
    claim_en: "The Bible calls Egypt's ruler \"Pharaoh\" in Joseph's story and in Moses' story alike. The Quran calls Joseph's ruler \"the king\" and keeps \"Pharaoh\" for Moses' time, and the Egyptians only started calling their king \"Pharaoh\" later.",
    claim_ar: "تسمّي التوراة حاكم مصر «فرعون» في قصة يوسف وفي قصة موسى معًا، أما القرآن فيسمّي حاكم يوسف «الملك» ويحتفظ بلقب «فرعون» لعهد موسى. ويُقال إن المصريين لم يطلقوا لقب «فرعون» على ملكهم إلا في عصرٍ لاحق.",
    record_en: "Per-aa, \"great house\", meant the royal palace for most of Egyptian history. The first confirmed use of the word for the king himself is in a letter to Akhenaten (reigned about 1353 to 1336 BCE), possibly a century earlier under Thutmose III. It was first joined to a king's name as a title under Siamun, in the 10th century BCE.",
    record_ar: "كانت كلمة «پر-عا» ومعناها «البيت العظيم» تدلّ على القصر الملكي في معظم تاريخ مصر. وأقدم استعمالٍ مؤكد لها في الدلالة على الملك نفسه رسالةٌ إلى أخناتون (حكم نحو ١٣٥٣ إلى ١٣٣٦ قبل الميلاد)، وربما سبق ذلك بقرنٍ في عهد تحتمس الثالث. أما اقترانها باسم الملك لقبًا فأول ما ظهر في عهد سيامون في القرن العاشر قبل الميلاد.",
    check_en: "The Quran side is airtight, and the counts on this card are live from the corpus. The history side holds too: the title really did arrive late. What nobody can check is when Joseph lived. If his story is set before the 14th century BCE, the Quran's word choice fits the record and the Bible's does not.",
    check_ar: "جانب القرآن محسوم، والأعداد في هذه البطاقة تُحسب لحظيًا من المدونة. وجانب التاريخ صحيحٌ كذلك، فاللقب ظهر متأخرًا فعلًا. أما ما لا سبيل إلى التحقق منه فهو زمن يوسف، فإن كانت قصته قبل القرن الرابع عشر قبل الميلاد وافق لفظُ القرآن ما في الآثار، وخالفه لفظُ التوراة.",
    counter_en: "No Egyptian record names Joseph, so the argument rests on an assumed date. And \"king\" is the ordinary Arabic word for any ruler; choosing it is not, on its own, proof of special knowledge.",
    counter_ar: "لا يذكر أيُّ أثرٍ مصري يوسفَ باسمه، فالحجة قائمةٌ على تاريخٍ مفترض. ثم إن «الملك» هو اللفظ العربي المعتاد لكل حاكم، واختياره وحده لا يكفي دليلًا على علمٍ خاص.",
    written: -1350, written_en: '"Pharaoh" first used for the king', written_ar: 'أول إطلاق «فرعون» على الملك',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    source_en: "Title history of per-aa: Amarna-period letter to Akhenaten; Year 17 of Siamun. Counts: Quranic Arabic Corpus lemmas, computed in your browser.",
    source_ar: "تاريخ لقب «پر-عا»: رسالة من عصر العمارنة إلى أخناتون، والسنة السابعة عشرة من حكم سيامون. الأعداد: جذوع المدونة الصرفية للقرآن، محسوبة في متصفحك."
  },
  {
    id: 'stake', region: 'egypt', verdict: 'holds',
    card_en: "Yes. Egypt put men to the stake long before Rome. So did its neighbours.",
    card_ar: "نعم. عرفت مصر القتل على الخشب قبل روما بزمنٍ طويل، وعرفه جيرانها أيضًا.",
    title_en: "Pharaoh's threat to crucify", title_ar: 'وعيد فرعون بالصلب',
    short_en: 'Stake punishment', short_ar: 'عقوبة الصلب',
    refs: ['20:71'], also: ['7:124', '26:49'],
    claim_en: "Critics call Pharaoh's threat an anachronism, since crucifixion is known as a Persian and Roman punishment from centuries after Moses. The reply: Egypt was already putting condemned men on stakes, so the threat fits its own time.",
    claim_ar: "يعدّ بعض النقّاد وعيد فرعون خطأً تاريخيًا، لأن الصلب عُرف عقوبةً فارسية ورومانية بعد موسى بقرون. والجواب أن مصر كانت تشدّ المحكوم عليهم إلى الخشب قبل ذلك، فالوعيد يناسب زمنه.",
    record_en: "A victory stela of Merneptah at Amada in Nubia (reigned about 1213 to 1203 BCE) reports that Libyan prisoners were \"put to the stake\" south of Memphis. Death on a wooden stake also appears in earlier New Kingdom texts.",
    record_ar: "تذكر لوحة نصرٍ للملك مرنبتاح في عمدا ببلاد النوبة (حكم نحو ١٢١٣ إلى ١٢٠٣ قبل الميلاد) أن أسرى من الليبيين «وُضعوا على الخشب» جنوب منف. والقتل على الخشب واردٌ كذلك في نصوصٍ أقدم من عصر الدولة الحديثة.",
    check_en: "The Arabic verb ṣallaba means to fix someone to wood; it does not have to mean the Roman cross. Read that way, the threat matches a punishment Egypt is known to have used, and the anachronism charge loses most of its force.",
    check_ar: "الفعل «صَلَّبَ» في العربية معناه شدُّ الإنسان إلى الخشب، ولا يلزم منه الصليب الروماني بهيئته المعروفة. وبهذا المعنى يتّفق الوعيد مع عقوبةٍ ثابتة في مصر القديمة، ويفقد اعتراض «الخطأ التاريخي» معظم قوته.",
    counter_en: "Death on a stake was common across the ancient Near East; Assyrian palace reliefs show it too. So the verse matches a general practice of the age, not a detail that only Egypt could supply.",
    counter_ar: "كان القتل على الخشب شائعًا في الشرق الأدنى القديم كله، ونقوش القصور الآشورية تصوّره أيضًا. فالآية توافق ممارسةً عامة في ذلك العصر، لا تفصيلًا تنفرد به مصر.",
    written: -1208, written_en: "Merneptah's Amada stela", written_ar: 'لوحة مرنبتاح في عمدا',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    source_en: "Amada stela of Merneptah (Libyan war). Assyrian impalement scenes: Lachish reliefs, palace of Sennacherib, Nineveh.",
    source_ar: "لوحة مرنبتاح في عمدا (حرب الليبيين). مشاهد الخوزقة الآشورية: نقوش لخيش في قصر سنحاريب بنينوى."
  },
  {
    id: 'haman', region: 'egypt', verdict: 'weak',
    card_en: "No. The hieroglyph proof does not stand: the reading is uncertain and the name is built on a god's name.",
    card_ar: "لا. دليل الهيروغليفية لا يصمد، فالقراءة غير مؤكدة والاسم مبنيٌّ على اسم إله.",
    title_en: "Haman at Pharaoh's court", title_ar: 'هامان في بلاط فرعون',
    short_en: "Haman's name", short_ar: 'اسم هامان',
    refs: ['28:38'], also: ['40:36', '28:6'],
    claim_en: "Critics say the Quran moved Haman from Persia, where the Book of Esther places him, into Egypt. Maurice Bucaille replied that a hieroglyphic name, \"Hmn-h\", belonging to an overseer of quarry workers, proves there was an Egyptian Haman.",
    claim_ar: "يقول بعض النقّاد إن القرآن نقل هامان من فارس، حيث يضعه سفر أستير، إلى مصر. وردّ موريس بوكاي بأن اسمًا هيروغليفيًا يُقرأ «حمن-ح» لرئيسٍ لعمّال المحاجر يثبت وجود هامان مصري.",
    record_en: "The name is on a New Kingdom door jamb now in the Kunsthistorisches Museum, Vienna. Hermann Ranke's dictionary of Egyptian personal names (1935) lists it as \"Hmn-h(?)\", flags the last sign as uncertain, and suggests it is short for Hemen-hotep, \"the god Hemen is content\".",
    record_ar: "الاسم منقوشٌ على عضادة بابٍ من الدولة الحديثة محفوظةٍ اليوم في متحف تاريخ الفن في فيينا. ويورده معجم هرمان رانكه للأسماء المصرية (١٩٣٥) بصيغة «حمن-ح(؟)»، فيضع علامة شكٍّ على الحرف الأخير، ويرجّح أنه اختصارٌ لاسم «حمن-حتب» أي «الإله حمن راضٍ».",
    check_en: "Bucaille's reading does not survive. The name is uncertain, it is built on a god's name rather than a job title, and nothing ties it to Moses' time. Egyptian records neither confirm nor rule out a Haman: most officials of any reign are simply unknown to us.",
    check_ar: "قراءة بوكاي لا تصمد، فالاسم غير مؤكد، وهو مبنيٌّ على اسم إلهٍ لا على لقب وظيفة، ولا شيء يربطه بعصر موسى. والآثار المصرية لا تثبت هامان ولا تنفيه، فأكثر رجال الدولة في أي عهدٍ مجهولون لنا.",
    counter_en: "The Quran never says its Haman is the man in Esther. Two people sharing a name a thousand years apart is not a contradiction, so the critics' charge is weaker than it sounds as well.",
    counter_ar: "لا يقول القرآن إن هامان هذا هو نفسه هامان سفر أستير، واشتراك رجلين في اسمٍ واحد بينهما ألف عام ليس تناقضًا. فاعتراض النقّاد أضعف مما يبدو كذلك.",
    written: -1300, written_en: 'Door jamb carved (New Kingdom)', written_ar: 'نقش عضادة الباب (الدولة الحديثة)',
    lost: 394, lost_en: 'Last dated hieroglyphic inscription, Philae', lost_ar: 'آخر نقشٍ هيروغليفي مؤرخ، فيلة',
    recovered: 1822, recovered_en: 'Champollion deciphers hieroglyphs', recovered_ar: 'شامبليون يفكّ رموز الهيروغليفية',
    source_en: "H. Ranke, Die ägyptischen Personennamen, vol. 1 (1935). W. Wreszinski, Aegyptische Inschriften aus dem K.K. Hof Museum in Wien (1906). M. Bucaille, Moses and Pharaoh (1994).",
    source_ar: "هرمان رانكه، الأسماء الشخصية المصرية، المجلد الأول (١٩٣٥). فالتر فريشينسكي، النقوش المصرية في متحف البلاط في فيينا (١٩٠٦). موريس بوكاي، موسى وفرعون (١٩٩٤)."
  },
  {
    id: 'body', region: 'egypt', verdict: 'weak',
    card_en: "Not as told. Every pharaoh was mummified, every mummy holds salt, and no record names the Pharaoh of the Exodus.",
    card_ar: "ليس كما يُروى. كل الفراعنة حُنّطوا، وفي كل مومياء ملح، ولا أثر يسمّي فرعون الخروج.",
    title_en: '"This day We save your body"', title_ar: '«فاليوم ننجّيك ببدنك»',
    short_en: "Pharaoh's body", short_ar: 'بدن فرعون',
    refs: ['10:92'],
    claim_en: "The verse promises that Pharaoh's body would be kept as a sign for later generations. Maurice Bucaille named Merneptah as the Pharaoh of the Exodus, examined his mummy, and said the salt in it and its injuries point to drowning.",
    claim_ar: "تعِد الآية بأن يبقى بدن فرعون آيةً لمن بعده. وقد جعل موريس بوكاي مرنبتاحَ فرعونَ الخروج، وفحص موميائه، وقال إن ما فيها من ملحٍ وإصابات يدلّ على الغرق.",
    record_en: "Merneptah's mummy was found in tomb KV35 in 1898; his father Ramesses II, the other usual candidate, was found in the Deir el-Bahari royal cache in 1881. Bucaille examined the royal mummies in Cairo in 1975.",
    record_ar: "عُثر على مومياء مرنبتاح في المقبرة KV35 سنة ١٨٩٨، وعلى مومياء أبيه رمسيس الثاني، المرشح الآخر المعتاد، في خبيئة الدير البحري سنة ١٨٨١. وفحص بوكاي المومياوات الملكية في القاهرة سنة ١٩٧٥.",
    check_en: "The verse fits any Pharaoh, because every king was mummified, and no Egyptian record identifies the Pharaoh of the Exodus. The early commentators read it differently: the drowned body was cast onto the shore so the Israelites could see with their own eyes that he was dead.",
    check_ar: "الآية تصدق على أي فرعون، فكل الملوك حُنّطوا، ولا يحدّد أيُّ أثرٍ مصري فرعونَ الخروج. وقد فهمها المفسرون الأوائل على وجهٍ آخر: أن البحر ألقى جثته على الساحل ليرى بنو إسرائيل بأعينهم أنه هلك.",
    counter_en: "Every mummy contains salt, because embalmers dried bodies with natron. And Merneptah's own victory stela, from his fifth year, already names Israel as a people in Canaan, which sits badly with him being the king they fled from.",
    counter_ar: "في كل مومياء ملح، لأن المحنّطين كانوا يجفّفون الأجساد بالنطرون. ثم إن لوحة نصر مرنبتاح نفسه، من سنته الخامسة، تذكر «إسرائيل» قومًا في أرض كنعان، وهذا لا يستقيم مع كونه الملك الذي فرّوا منه.",
    written: -1203, written_en: 'Merneptah dies and is buried', written_ar: 'وفاة مرنبتاح ودفنه',
    lost: -1000, lost_en: 'Royal mummies hidden in secret caches', lost_ar: 'إخفاء المومياوات الملكية في خبايا سرّية',
    recovered: 1898, recovered_en: "Merneptah's mummy found in KV35", recovered_ar: 'العثور على مومياء مرنبتاح في KV35',
    source_en: "M. Bucaille, Mummies of the Pharaohs: Modern Medical Investigations (1990). V. Loret, discovery of KV35 (1898). Merneptah Stele, Egyptian Museum, Cairo.",
    source_ar: "موريس بوكاي، مومياوات الفراعنة: فحوص طبية حديثة (١٩٩٠). فيكتور لوريه، اكتشاف المقبرة KV35 (١٨٩٨). لوحة مرنبتاح، المتحف المصري بالقاهرة."
  },
  {
    id: 'thamud', region: 'arabia', verdict: 'holds',
    card_en: "Yes. Thamud are in Assyrian, Greek and Roman records. Arabs already knew of them.",
    card_ar: "نعم. ثمود في سجلات الآشوريين واليونان والرومان، والعرب كانوا يعرفونهم.",
    title_en: 'Thamud, who carved homes from rock', title_ar: 'ثمود الذين جابوا الصخر',
    short_en: 'Thamud', short_ar: 'ثمود',
    refs: ['7:74'], also: ['15:82', '89:9'],
    claim_en: "The Quran's Thamud, who carved houses out of the mountains, were a real people, and Assyrian records prove it.",
    claim_ar: "ثمود الذين نحتوا من الجبال بيوتًا شعبٌ حقيقي، وفي سجلات الآشوريين ما يثبت ذلك.",
    record_en: "The annals of Sargon II (reigned 722 to 705 BCE) list the \"Tamudi\" among desert Arabs he claims to have defeated. Greek writers from the 2nd century BCE place the Thamudeni in north-west Arabia, and a temple at Ruwafa was built around 165 to 169 CE by \"the tribal unit of Thamud\".",
    record_ar: "تذكر حوليات سرجون الثاني (حكم ٧٢٢ إلى ٧٠٥ قبل الميلاد) قبيلة «تمودي» بين عرب البادية الذين يزعم أنه هزمهم. ويضع الكتّاب اليونان منذ القرن الثاني قبل الميلاد «الثموديين» في شمال غرب الجزيرة، وقد بنت «جماعة ثمود» معبد الرُّوافة نحو سنة ١٦٥ إلى ١٦٩ للميلاد.",
    check_en: "Thamud are real and well attested. But they were never a secret in Arabia: pre-Islamic poets already spoke of them as a vanished tribe, and the Prophet passed the ruins of al-Hijr on the road to Tabuk. One correction to the usual picture: the grand rock-cut facades at Hegra are mostly Nabataean tombs from the 1st century CE.",
    check_ar: "ثمود شعبٌ حقيقي ثابتٌ في الآثار، لكنه لم يكن سرًّا عند العرب، فشعراء الجاهلية ذكروهم قومًا بائدين، ومرّ النبي ﷺ بديار الحِجر في طريقه إلى تبوك. ويحتاج التصوّر الشائع إلى تصحيحٍ واحد: فالواجهات المنحوتة الشهيرة في الحِجر مقابرُ نبطية في معظمها، من القرن الأول للميلاد.",
    counter_en: "The name Thamud still appears in Roman army lists of the 5th century CE, as cavalry units in Egypt and Palestine. That makes it hard to pin the destruction the Quran describes to a single date.",
    counter_ar: "يظهر اسم ثمود في قوائم الجيش الروماني في القرن الخامس للميلاد، فِرَقًا من الفرسان في مصر وفلسطين. وهذا يجعل تحديد زمن الهلاك الذي يصفه القرآن بتاريخٍ واحد أمرًا عسيرًا.",
    written: -715, written_en: "Sargon II's annals", written_ar: 'حوليات سرجون الثاني',
    lost: null, recovered: 1857, recovered_en: 'Assyrian cuneiform deciphered', recovered_ar: 'فكّ رموز المسمارية الآشورية',
    source_en: "Annals of Sargon II, Dur-Sharrukin (Khorsabad). Diodorus Siculus, Library of History, book 3. Ruwafa inscription (Greek and Nabataean). Notitia Dignitatum.",
    source_ar: "حوليات سرجون الثاني، دور شروكين (خورسباد). ديودور الصقلي، المكتبة التاريخية، الكتاب الثالث. نقش الرُّوافة (يوناني ونبطي). سجلّ المناصب الروماني «نوتيتيا ديغنيتاتوم»."
  },
  {
    id: 'iram', region: 'arabia', verdict: 'weak',
    card_en: "No. A real fort was found at Shisr, but its own excavator did not call it Iram.",
    card_ar: "لا. عُثر في الشِّصر على حصنٍ حقيقي، لكن المنقّب نفسه لم يقل إنه إرم.",
    title_en: 'Iram of the pillars', title_ar: 'إرم ذات العماد',
    short_en: 'Iram', short_ar: 'إرم',
    refs: ['89:6', '89:7', '89:8'],
    claim_en: "In 1992 a team using NASA radar images found Ubar, the \"Atlantis of the Sands\", in Oman, and it was identified as Iram of the pillars.",
    claim_ar: "في سنة ١٩٩٢ عثر فريقٌ استعان بصور رادار من وكالة ناسا على «أوبار»، «أطلانطس الرمال»، في عُمان، وقيل إنها إرم ذات العماد.",
    record_en: "The team, including filmmaker Nicholas Clapp and archaeologist Juris Zarins, followed old caravan tracks to Shisr, an oasis about 170 km north of Salalah, and excavated a fortified site on the frankincense trade route.",
    record_ar: "تتبّع الفريق، ومنه المخرج نيكولاس كلاب والآثاري يوريس زارينز، آثار طرق القوافل القديمة حتى واحة الشِّصر، على نحو ١٧٠ كيلومترًا شمال صلالة، وكشف عن موقعٍ محصّن على طريق تجارة اللبان.",
    check_en: "The find is real; the identification is not. Zarins argued that Ubar named a region and a people, not one town, and most scholars read Shisr as a caravan station rather than a lost city. Iram was never hidden knowledge either: Arab tradition told of 'Ad and Iram long before any satellite.",
    check_ar: "الاكتشاف حقيقي، أما نسبته إلى إرم فلا. فقد رأى زارينز أن «أوبار» اسمٌ لإقليمٍ وقوم لا لمدينةٍ واحدة، ويرى أكثر الباحثين في الشِّصر محطةً للقوافل لا مدينةً مفقودة. ولم تكن إرم علمًا خفيًّا أصلًا، فأخبار عادٍ وإرم حاضرةٌ في تراث العرب قبل الأقمار الصناعية بقرون.",
    counter_en: "Supporters point out that part of the fort collapsed into a sinkhole under its well, which fits the legend of a city swallowed by the sand. A collapse fits a ruin, but it does not tell you its name.",
    counter_ar: "يشير المؤيدون إلى أن جزءًا من الحصن انهار في تجويفٍ أرضي تحت بئره، وهذا يوافق أسطورة المدينة التي ابتلعتها الرمال. لكن الانهيار يصف خرابًا، ولا يخبرك باسمه.",
    written: null, lost: null, recovered: 1992, recovered_en: 'Shisr excavated', recovered_ar: 'التنقيب في الشِّصر',
    source_en: "N. Clapp, The Road to Ubar (1998). J. Zarins, The Land of Incense (2001).",
    source_ar: "نيكولاس كلاب، الطريق إلى أوبار (١٩٩٨). يوريس زارينز، أرض اللبان (٢٠٠١)."
  },
  {
    id: 'dam', region: 'arabia', verdict: 'holds',
    card_en: "Yes. The dam's own inscriptions record its breaches, and Arabia remembered it.",
    card_ar: "نعم. نقوش السدّ نفسه تسجّل ثُلماته، وكانت العرب تذكره.",
    title_en: 'The flood of the dam at Saba', title_ar: 'سيل العرم',
    short_en: 'Marib dam', short_ar: 'سدّ مأرب',
    refs: ['34:16'], also: ['34:15'],
    claim_en: "The \"flood of al-'Arim\" that ruined Saba's two gardens is the failure of the great Marib dam, and the dam's own inscriptions record it.",
    claim_ar: "«سيل العرم» الذي أهلك جنّتَي سبأ هو انهيار سدّ مأرب العظيم، ونقوش السدّ نفسها تشهد بذلك.",
    record_en: "Sabaic inscriptions at Marib record two breaches repaired in 454 and 455 CE under King Shurihbi'il Ya'fur, and another sealed in 547 under Abraha, told in his 136-line inscription of 548 CE (CIH 541). The dam was overtopped again in about 570 or 575 CE and never repaired.",
    record_ar: "تسجّل النقوش السبئية في مأرب ثُلمتين رُمّمتا سنتي ٤٥٤ و٤٥٥ للميلاد في عهد الملك شُرَحبئيل يَعفُر، وثُلمةً ثالثة سُدّت سنة ٥٤٧ في عهد أبرهة، يرويها نقشه الطويل (CIH 541) المؤرخ سنة ٥٤٨ في مئةٍ وستةٍ وثلاثين سطرًا. ثم طغى الماء على السدّ مرةً أخرى نحو سنة ٥٧٠ أو ٥٧٥، ولم يُرمَّم بعدها.",
    check_en: "The dam, its breaches and its end are recorded in stone, so the match is solid. It is also history the first listeners could know for themselves: the final collapse was within living memory, and the musnad script was still written in Yemen. This one is a true match, not hidden knowledge.",
    check_ar: "السدّ وثُلماته ونهايته مسجّلةٌ على الحجر، فالتطابق متين. وهو كذلك تاريخٌ كان في متناول السامعين الأوائل، فالانهيار الأخير وقع في حياة بعضهم، وخطّ المسند كان لا يزال يُكتب في اليمن. فهذا تطابقٌ صحيح، لا علمٌ محجوب.",
    counter_en: "Which breach the verse means is debated. Some historians link it to an earlier break, around 145 BCE, rather than to the final collapse.",
    counter_ar: "يختلف المؤرخون في الثُّلمة المقصودة، فبعضهم يربط الآية بانهيارٍ أقدم وقع نحو سنة ١٤٥ قبل الميلاد، لا بالانهيار الأخير.",
    written: 454, written_en: 'First dated breach inscription', written_ar: 'أول نقشٍ مؤرخ لثُلمة السدّ',
    lost: null, recovered: 1841, recovered_en: 'Sabaic script deciphered', recovered_ar: 'فكّ رموز خطّ المسند',
    source_en: "CIH 540 (Shurihbi'il Ya'fur) and CIH 541 (Abraha, 548 CE), Great Dam of Marib. E. Rödiger and W. Gesenius, decipherment of the South Arabian script (1841).",
    source_ar: "النقشان CIH 540 (شرحبئيل يعفر) وCIH 541 (أبرهة، ٥٤٨م)، سدّ مأرب العظيم. إميل رودِيغر وفيلهلم غيزينيوس، فكّ رموز خطّ المسند (١٨٤١)."
  },
  {
    id: 'elephant', region: 'arabia', verdict: 'holds',
    card_en: "Yes. Abraha's own inscriptions record his march into Arabia. The date is the open question.",
    card_ar: "نعم. نقوش أبرهة نفسه تسجّل حملته على الجزيرة، والسؤال المفتوح هو التاريخ.",
    title_en: 'Abraha and the Year of the Elephant', title_ar: 'أبرهة وعام الفيل',
    short_en: "Abraha's army", short_ar: 'جيش أبرهة',
    refs: ['105:1'], also: ['105:2', '105:3', '105:4', '105:5'],
    claim_en: "The army of Surah al-Fil belonged to Abraha, the Christian ruler of Yemen, and his campaigns into Arabia are carved in his own inscriptions.",
    claim_ar: "جيش أصحاب الفيل هو جيش أبرهة، حاكم اليمن النصراني، وحملاته على جزيرة العرب منقوشةٌ في نقوشه هو.",
    record_en: "Abraha ruled the Himyarite kingdom from about 533 CE. His Murayghan inscription (Ry 506), dated 552 CE, records a campaign into central Arabia against the tribes of Ma'add.",
    record_ar: "حكم أبرهة مملكة حِميَر منذ نحو سنة ٥٣٣ للميلاد. ويسجّل نقش مُرَيغان (Ry 506) المؤرخ سنة ٥٥٢ حملةً له على وسط الجزيرة ضدّ قبائل مَعَدّ.",
    check_en: "Abraha is one of the best-documented rulers of pre-Islamic Arabia, so the surah names a real king with a real record of marching north. Its first listeners did not need an archive: many of them had grown up with the story.",
    check_ar: "أبرهة من أوفر حكّام الجزيرة قبل الإسلام حظًّا من التوثيق، فالسورة تذكر ملكًا حقيقيًا ثبتت حملاته شمالًا. ولم يكن السامعون الأوائل بحاجةٍ إلى أرشيف، فكثيرٌ منهم نشأ على هذه القصة.",
    counter_en: "Tradition puts the Year of the Elephant at about 570 CE, the year of the Prophet's birth, but Abraha's dated inscriptions stop in the 550s and he probably died before 560. Historians still argue over which should move, the date or the campaign.",
    counter_ar: "تجعل الروايةُ عامَ الفيل نحو سنة ٥٧٠ للميلاد، عامَ مولد النبي ﷺ، لكن نقوش أبرهة المؤرخة تتوقف في خمسينيات القرن السادس، والأرجح أنه مات قبل سنة ٥٦٠. ولا يزال المؤرخون مختلفين في أيّهما يُعدَّل: التاريخ أم الحملة.",
    written: 552, written_en: 'Murayghan inscription (Ry 506)', written_ar: 'نقش مريغان (Ry 506)',
    lost: null, recovered: 1841, recovered_en: 'Sabaic script deciphered', recovered_ar: 'فكّ رموز خطّ المسند',
    source_en: "Murayghan inscription Ry 506 (552 CE). C. J. Robin, studies of Abraha's reign and the campaign of the elephant.",
    source_ar: "نقش مريغان Ry 506 (٥٥٢م). كريستيان روبان، دراساته عن حكم أبرهة وحملة الفيل."
  },
  {
    id: 'romans', region: 'neareast', verdict: 'holds',
    card_en: "Yes. Heraclius turned the war around within the years the verses give.",
    card_ar: "نعم. قلب هرقل مجرى الحرب في المدة التي حدّدتها الآيات.",
    title_en: '"The Romans have been defeated"', title_ar: '«غُلِبت الروم»',
    short_en: "Rome's comeback", short_ar: 'غلبة الروم',
    refs: ['30:2', '30:3', '30:4'],
    claim_en: "Revealed after Persia crushed the Byzantines, the verses predict a Byzantine comeback within \"a few years\" (bid' sinin, three to nine). Some add that \"adna al-ard\" means \"the lowest land\": the Dead Sea basin, the lowest point on Earth.",
    claim_ar: "نزلت الآيات بعد أن سحق الفرسُ الروم، وفيها نبوءةٌ بأن الروم سيَغلبون «في بضع سنين»، والبضع ما بين الثلاث والتسع. ويضيف بعضهم أن «أدنى الأرض» معناها أخفض بقعةٍ على وجه الأرض، أي حوض البحر الميت.",
    record_en: "Persia captured Jerusalem in 614 CE. Emperor Heraclius won his first major victory over the Persians in 622 and broke their army near Nineveh in December 627; peace followed in 628.",
    record_ar: "استولى الفرس على بيت المقدس سنة ٦١٤ للميلاد. ثم أحرز الإمبراطور هرقل أول نصرٍ كبير عليهم سنة ٦٢٢، وحطّم جيشهم قرب نينوى في ديسمبر ٦٢٧، وعُقد الصلح سنة ٦٢٨.",
    check_en: "The reversal happened, and inside the window the verses give, if they came down around 614 to 616 CE as tradition holds. The \"lowest land\" reading is modern, though. The early commentators read adna as \"nearest\": the lands closest to Arabia.",
    check_ar: "وقع الانقلاب فعلًا، وفي المدة التي تحدّدها الآيات، إن صحّ أنها نزلت نحو سنة ٦١٤ إلى ٦١٦ كما تقول الرواية. أما تفسير «أدنى الأرض» بأخفضها فحديث، إذ فهمها المفسرون الأوائل بمعنى «أقربها»، أي أقرب الأرض إلى بلاد العرب.",
    counter_en: "The date of the verses comes from the same tradition that reports the prophecy coming true, so the timing cannot be checked against an independent source.",
    counter_ar: "تاريخ نزول الآيات مأخوذٌ من الرواية نفسها التي تروي تحقّق النبوءة، فلا سبيل إلى التحقق من التوقيت بمصدرٍ مستقل.",
    written: 614, written_en: 'Persians take Jerusalem', written_ar: 'الفرس يأخذون بيت المقدس',
    lost: null, recovered: null,
    source_en: "Chronicon Paschale; Theophanes, Chronographia. Tafsir al-Tabari on 30:2-4.",
    source_ar: "التاريخ الفصحي (Chronicon Paschale)، وحوليات ثيوفانيس. تفسير الطبري للآيات ٣٠:٢-٤."
  },
  {
    id: 'judi', region: 'neareast', verdict: 'holds',
    card_en: "Yes. Al-Judi matches the older Mesopotamian and Aramaic tradition, which was still alive.",
    card_ar: "نعم. الجوديّ يوافق التقليد الرافديني والآرامي الأقدم، وكان لا يزال حيًّا.",
    title_en: 'The ark comes to rest on al-Judi', title_ar: 'واستوت على الجوديّ',
    short_en: 'Ark on al-Judi', short_ar: 'سفينة نوح',
    refs: ['11:44'],
    claim_en: "The Bible lands the ark on \"the mountains of Ararat\". The Quran names al-Judi instead, and that choice matches an older tradition.",
    claim_ar: "ترسو السفينة في التوراة على «جبال أراراط»، أما القرآن فيسمّي «الجوديّ»، وهذا الاختيار يوافق تقليدًا أقدم.",
    record_en: "Berossus, a Babylonian priest of the 3rd century BCE quoted by Josephus, said remains of the vessel survived \"at the mountain of the Cordyaeans\". The Aramaic Jewish translations of Genesis (the Targums, Onkelos among them) say \"the mountains of Qardu\". That is the old Gordyene district, where Mount Cudi stands in south-east Turkey.",
    record_ar: "قال بيروسوس، الكاهن البابلي في القرن الثالث قبل الميلاد، فيما ينقله عنه يوسيفوس، إن بقايا السفينة باقيةٌ «عند جبل الكَرْدويين». وتقول الترجمات الآرامية اليهودية لسفر التكوين، ومنها ترجمة أونقيلوس، «جبال قَرْدو». وتلك هي ناحية «قردو» القديمة التي يقوم فيها جبل الجودي في جنوب شرق تركيا.",
    check_en: "The Quran sides with the older Mesopotamian and Aramaic tradition, not with the Ararat one most Bible readers know. That tradition was alive among Syriac Christians and Jews in the 7th century, so this is agreement with an existing source, not hidden knowledge. Classical Muslim geographers such as Yaqut place al-Judi above Jazirat Ibn 'Umar, today's Cizre, on the same range.",
    check_ar: "يقف القرآن مع التقليد الرافديني والآرامي الأقدم، لا مع «أراراط» الذي يعرفه أكثر قرّاء التوراة. وكان ذلك التقليد حيًّا عند السريان واليهود في القرن السابع، فهذا توافقٌ مع مصدرٍ قائم، لا علمٌ محجوب. ويضع الجغرافيون المسلمون، كياقوت، الجوديَّ مطلًّا على جزيرة ابن عمر، وهي مدينة جزرة التركية اليوم، في السلسلة نفسها.",
    counter_en: "Ararat is also the old name of the kingdom of Urartu, a wide highland region bordering these mountains. So the Bible and the Quran may not disagree at all.",
    counter_ar: "«أراراط» هو أيضًا الاسم القديم لمملكة أورارطو، وهي إقليمٌ جبلي واسع يتاخم هذه الجبال، فقد لا يكون بين التوراة والقرآن خلافٌ أصلًا.",
    written: -290, written_en: 'Berossus writes his history', written_ar: 'بيروسوس يكتب تاريخه',
    lost: null, recovered: null,
    source_en: "Josephus, Antiquities of the Jews 1.3.6 (quoting Berossus). Targum Onkelos, Genesis 8:4. Yaqut al-Hamawi, Mu'jam al-Buldan, entry al-Judi.",
    source_ar: "يوسيفوس، آثار اليهود ١.٣.٦ (نقلًا عن بيروسوس). ترجوم أونقيلوس، التكوين ٨:٤. ياقوت الحموي، معجم البلدان، مادة «الجودي»."
  }
];
