// One interactive figure for each History Claim, keyed by the claim's id in quran_history.js.
// Every fact here comes from that claim's own checked text (record, check, counter, sources).
// Text is [English, Arabic]. Years: negative = BCE. A claim with no entry here gets a time spiral
// built from its written / lost / recovered years, so a new claim always has a figure.
//
// Figure types
//   duel   : the record and the verse, phrase by phrase. rel: same | flip | diff
//   era    : a time line with a marker the reader drags; the zone under the marker explains what follows.
//            win = a window [from, to] years after the marker (e.g. "three to nine years")
//   spiral : the centuries wound into a spiral; phases colour the stretches (gold | dim | teal)
//   map    : a sketch map of the region; sites and the distances between them
//   weigh  : the case for and against; each point placed on the scale tips it. w = 1 to 3
//   bars   : quantities on one scale, with readings to switch between
//   convert: solar years to lunar years
const QURAN_HISTORY_VIZ = {

weep: { type:"duel",
  title:["The honour, and the verse that withholds it", "التكريم، والآية التي تمنعه"],
  sub:["Point at a line of the record to see what answers it in the verse. Gold is a match, red a reversal, grey a difference.",
       "أشر إلى سطرٍ من الأثر لترى ما يقابله في الآية. الذهبي تطابق، والأحمر قلبٌ للمعنى، والرمادي اختلاف."],
  pairs:[
    { src:["Pyramid Texts, Utterance 553", "نصوص الأهرام، الفقرة ٥٥٣"], rec:["The sky weeps for thee", "السماء تبكي عليك"],
      ar:"فَمَا بَكَتْ عَلَيْهِمُ ٱلسَّمَآءُ", en:"the heaven wept not for them", rel:"flip",
      note:["The same royal honour, turned around: Egypt's texts give it to the dead king, the verse denies it to Pharaoh's people.",
            "التكريم الملكي نفسه مقلوبًا: تمنحه نصوص مصر للملك الميت، وتنفيه الآية عن قوم فرعون."] },
    { src:["Pyramid Texts, Utterance 553", "نصوص الأهرام، الفقرة ٥٥٣"], rec:["the earth trembles for thee", "والأرض ترتجف لك"],
      ar:"وَٱلْأَرْضُ", en:"and the earth", rel:"diff",
      note:["Both bring in the earth. In Egypt it trembles; in the verse, like the sky, it does not weep.",
            "كلاهما يذكر الأرض، لكنها في مصر ترتجف، وفي الآية لا تبكي كالسماء."] },
    { src:["Said to one king", "يقال لملكٍ واحد"], rec:["to the dead king alone", "للملك الميت وحده"],
      ar:"عَلَيْهِمُ", en:"for them: Pharaoh's people", rel:"diff",
      note:["The Egyptian line honours one king; the verse speaks of a whole people.",
            "السطر المصري يكرّم ملكًا واحدًا، والآية تتحدث عن قومٍ بأكملهم."] },
    { src:["Al-Zamakhshari, al-Qurtubi", "الزمخشري، القرطبي"], rec:["Arabs said 'the sky and the earth wept for him' of a great man", "كانت العرب تقول في موت العظيم: بكت عليه السماء والأرض"],
      ar:"فَمَا بَكَتْ عَلَيْهِمُ ٱلسَّمَآءُ وَٱلْأَرْضُ", en:"the heaven and the earth wept not", rel:"same",
      note:["The phrase had a way into Arabic that did not pass through Egypt, though the poems quoted for it come from after the Quran.",
            "كان للعبارة طريقٌ إلى العربية لا يمر بمصر، وإن كانت الأشعار المستشهد بها متأخرةً عن القرآن."] } ] },

king: { type:"era",
  title:["When did Joseph live?", "متى عاش يوسف؟"],
  sub:["Drag the marker to any date for Joseph. The bands show what the word per-aa, 'great house', meant at that time.",
       "اسحب العلامة إلى أي تاريخٍ تقترحه ليوسف. تُظهر الأشرطة ما كانت تعنيه كلمة «پر-عا»، أي «البيت العظيم»، في ذلك الزمن."],
  range:[-2000,-900], marker:{ y:-1650, min:-2000, max:-900, label:["Joseph?", "يوسف؟"] },
  zones:[
    { a:-2000, b:-1450, tone:"good", lab:["Per-aa means the palace", "«پر-عا» تعني القصر"],
      say:["Here the ruler is not yet called 'Pharaoh'. The Quran's 'the king' fits; the Bible's 'Pharaoh' does not.",
           "هنا لم يكن الحاكم يُسمّى «فرعون» بعد، فكلمة القرآن «الملك» تناسب، وكلمة التوراة «فرعون» لا تناسب."] },
    { a:-1450, b:-1350, tone:"mid", lab:["Possibly used for the king", "ربما استُعملت للملك"],
      say:["The word may already name the king under Thutmose III, but the first confirmed use is a little later.",
           "قد تكون الكلمة سمّت الملك منذ تحتمس الثالث، لكن أول استعمالٍ مؤكد يأتي بعد ذلك بقليل."] },
    { a:-1350, b:-970, tone:"bad", lab:["Used for the king himself", "تُستعمل للملك نفسه"],
      say:["By now 'Pharaoh' is a word for the king, first confirmed in a letter to Akhenaten. Calling Joseph's ruler 'Pharaoh' would fit too.",
           "صارت «فرعون» هنا اسمًا للملك، وأول تأكيدٍ لذلك رسالةٌ إلى إخناتون. فتسمية حاكم يوسف «فرعون» تناسب أيضًا."] },
    { a:-970, b:-900, tone:"bad", lab:["A title beside the king's name", "لقبٌ مع اسم الملك"],
      say:["Under Siamun, 'Pharaoh' is joined to a king's name as a title for the first time.",
           "في عهد سيامون اقترن لقب «فرعون» باسم الملك لأول مرة."] } ],
  events:[ { y:-1350, lab:["Letter to Akhenaten", "رسالة إلى إخناتون"] }, { y:-1250, lab:["Moses, as usually dated", "موسى، في التأريخ المعتاد"] } ],
  foot:["No Egyptian record names Joseph, so his date is an estimate. The videos place him in the 17th century BCE.",
        "لا يذكر أي أثرٍ مصري يوسف، فتاريخه تقدير. والمقاطع تضعه في القرن السابع عشر قبل الميلاد."] },

tower: { type:"duel",
  title:["A way up to the sky", "طريقٌ إلى السماء"],
  sub:["Point at a line of the record to see what answers it in the verses.", "أشر إلى سطرٍ من الأثر لترى ما يقابله في الآيات."],
  pairs:[
    { src:["Pyramid Texts, Utterance 267 (Unas)", "نصوص الأهرام، الفقرة ٢٦٧ (أوناس)"], rec:["A stairway to the sky is set up for me", "يُنصب لي سلّمٌ إلى السماء"],
      ar:"لَّعَلِّىٓ أَبْلُغُ ٱلْأَسْبَٰبَ أَسْبَٰبَ ٱلسَّمَٰوَٰتِ", en:"that haply I may reach the roads, the roads of the heavens", rel:"same",
      note:["The theme matches: a king who wants a way up to the sky.", "الموضوع متطابق: ملكٌ يريد طريقًا إلى السماء."] },
    { src:["Pyramid Texts", "نصوص الأهرام"], rec:["the climb of a dead king's soul", "صعود روح الملك الميت"],
      ar:"فَأَطَّلِعَ إِلَىٰٓ إِلَٰهِ مُوسَىٰ", en:"and may look upon the god of Moses", rel:"diff",
      note:["The Egyptian texts are about the dead; the verse is about a living king who wants to look for God.",
            "النصوص المصرية عن الموتى، والآية عن ملكٍ حي يريد أن يطّلع إلى الإله."] },
    { src:["Statue of Bakenkhonsu, chief of works", "تمثال باكنخونسو، رئيس الأشغال"], rec:["obelisks that reached to the sky", "مسلاتٌ بلغت السماء"],
      ar:"ٱبْنِ لِى صَرْحًا", en:"build for me a tower", rel:"same",
      note:["Royal builders spoke of their works reaching the sky.", "كان بنّاؤو الملوك يصفون أعمالهم بأنها تبلغ السماء."] },
    { src:["Genesis 11 (the critics' reading)", "سفر التكوين ١١ (قراءة المنتقدين)"], rec:["Babel: a tower of baked brick to reach heaven", "بابل: برجٌ من الآجر المشوي ليبلغ السماء"],
      ar:"فَأَوْقِدْ لِى يَٰهَٰمَٰنُ عَلَى ٱلطِّينِ", en:"kindle for me, O Haman, a fire to bake the mud", rel:"same",
      note:["Critics say baked brick belongs to Mesopotamia, and that Egypt's great monuments were of stone.",
            "يقول المنتقدون إن الآجر المشوي من بلاد الرافدين، وإن آثار مصر العظيمة من الحجر."] } ] },

god: { type:"duel",
  title:["A king who presented himself as a god", "ملكٌ قدّم نفسه إلهًا"],
  sub:["Point at a line of the record to see what answers it in the verses.", "أشر إلى سطرٍ من الأثر لترى ما يقابله في الآيات."],
  pairs:[
    { src:["Abu Simbel, sanctuary", "أبو سمبل، قدس الأقداس"], rec:["Ramesses II sits as one of four gods", "رمسيس الثاني جالسٌ إلهًا بين أربعة"],
      ar:"مَا عَلِمْتُ لَكُم مِّنْ إِلَٰهٍ غَيْرِى", en:"I know not that ye have a god other than me", rel:"same",
      note:["The carving and the verse say the same thing: this king presented himself as a god.", "النقش والآية يقولان الشيء نفسه: هذا الملك قدّم نفسه إلهًا."] },
    { src:["Abu Simbel, hall relief", "أبو سمبل، نقش القاعة"], rec:["the king makes offerings to his own divine image", "الملك يقدّم القرابين لصورته الإلهية"],
      ar:"أَنَا۠ رَبُّكُمُ ٱلْأَعْلَىٰ", en:"I am your Lord the Highest", rel:"same",
      note:["A king worshipping his own image is the boast of the verse made into stone.", "ملكٌ يعبد صورته هو تفاخر الآية منقوشًا في الحجر."] },
    { src:["Egyptian kingship", "الملكية المصرية"], rec:["every king was 'son of Ra', divine by office", "كل ملكٍ «ابن رع»، إلهٌ بحكم منصبه"],
      ar:"فَقَالَ أَنَا۠ رَبُّكُمُ ٱلْأَعْلَىٰ", en:"and proclaimed", rel:"diff",
      note:["In Egypt this was the normal language of the throne, not one man's boast.", "كانت هذه في مصر لغة العرش المعتادة، لا تفاخر رجلٍ واحد."] },
    { src:["Ezekiel 29:3", "حزقيال ٢٩:٣"], rec:["'My Nile is my own; I made it'", "«لي نهري وأنا عملته»"],
      ar:"مَا عَلِمْتُ لَكُم مِّنْ إِلَٰهٍ غَيْرِى", en:"no god for you but me", rel:"same",
      note:["Not lost knowledge: the Bible's prophets and the early rabbis already gave Pharaoh this boast.", "ليس علمًا ضائعًا: فقد نسب أنبياء التوراة والأحبار الأوائل إلى فرعون هذا التفاخر."] } ] },

stake: { type:"map",
  title:["Where the stake was used", "أين استُعمل الصلب على الخشب"],
  sub:["Point at a site to read what was found there. The practice spans the region, not Egypt alone.",
       "أشر إلى موقعٍ لتقرأ ما وُجد فيه. الممارسة تمتد في المنطقة كلها، لا في مصر وحدها."],
  box:[28,20,46,38],
  sites:[
    { lon:32.26, lat:22.72, k:"egypt", lab:["Amada", "عمدا"], say:["Merneptah's victory stela: Libyan prisoners 'put to the stake' south of Memphis.", "لوحة نصر مرنبتاح: أسرى ليبيون «وُضعوا على الخازوق» جنوب منف."] },
    { lon:31.25, lat:29.85, k:"egypt", lab:["Memphis", "منف"], say:["Where the Libyan prisoners were executed, by the Amada stela.", "حيث أُعدم الأسرى الليبيون بحسب لوحة عمدا."] },
    { lon:32.64, lat:25.70, k:"egypt", lab:["Thebes", "طيبة"], say:["Papyrus Boulaq 18 (about 1750 BCE) and the tomb-robbery oaths name the stake as a penalty.", "بردية بولاق ١٨ (نحو ١٧٥٠ ق.م.) وأيمان لصوص المقابر تذكر الخازوق عقوبةً."] },
    { lon:34.85, lat:31.56, k:"other", lab:["Lachish", "لخيش"], say:["Assyrian reliefs of the siege of Lachish show impalement.", "نقوش آشور لحصار لخيش تُظهر الإعدام على الخوازيق."] },
    { lon:43.15, lat:36.36, k:"other", lab:["Nineveh", "نينوى"], say:["The Lachish reliefs line Sennacherib's palace at Nineveh.", "نقوش لخيش تزيّن قصر سنحاريب في نينوى."] } ],
  foot:["The Arabic verb ṣallaba means to fix someone to wood; it need not mean the Roman cross. Gold: Egypt. Teal: elsewhere in the Near East.",
        "الفعل «صلّب» يعني التثبيت على الخشب، ولا يلزم منه الصليب الروماني. الذهبي: مصر. الفيروزي: سائر الشرق الأدنى."] },

haman: { type:"weigh",
  title:["Is there an Egyptian Haman?", "هل في مصر هامان؟"],
  sub:["Tap each point to place it on the scale. The weights are our reading of how much each one counts.",
       "انقر كل نقطةٍ لتضعها في الميزان. والأوزان قراءتنا لثقل كل واحدة."],
  forLab:["For an Egyptian Haman", "مع هامان مصري"], againstLab:["Against", "ضده"],
  items:[
    { side:"for", w:1, t:["A New Kingdom door jamb in Vienna carries a name read as 'Hmn-h'", "على عضادة بابٍ من الدولة الحديثة في فيينا اسمٌ قُرئ «حمن-ح»"] },
    { side:"for", w:1, t:["The Quran never says its Haman is the man in Esther; two people can share a name", "لا يقول القرآن إن هامانه هو هامان سفر أستير، وقد يشترك اثنان في اسم"] },
    { side:"against", w:2, t:["Ranke's dictionary marks the last sign as uncertain", "معجم رانكه يشير إلى أن العلامة الأخيرة غير مؤكدة"] },
    { side:"against", w:2, t:["The name is built on a god's name, likely Hemen-hotep, not a job title", "الاسم مبنيٌّ على اسم إله، والأرجح «حمن-حتب»، لا على وظيفة"] },
    { side:"against", w:2, t:["Nothing ties the name to Moses' time", "لا شيء يربط الاسم بزمن موسى"] },
    { side:"against", w:2, t:["The Bakenkhonsu version drops the middle of a title every high priest of Amun held", "رواية باكنخونسو تحذف وسط لقبٍ حمله كل كبار كهنة آمون"] } ] },

body: { type:"spiral",
  title:["Three thousand years of a body", "ثلاثة آلاف سنةٍ من عمر جسد"],
  sub:["Drag along the spiral, or press play. Each turn is five centuries.", "اسحب على اللولب أو شغّل العرض. كل دورةٍ خمسة قرون."],
  per:500,
  phases:[
    { a:-1213, b:-1000, tone:"gold", lab:["In his tomb", "في قبره"], say:["Ramesses II is buried in his own tomb.", "رمسيس الثاني مدفونٌ في قبره."] },
    { a:-1000, b:1881, tone:"dim", lab:["Hidden in a secret cache", "مخبّأ في خبيئةٍ سرية"], say:["Priests have moved the mummy to a hidden cache to save it from tomb robbers. Nobody knows where it is.", "نقل الكهنة المومياء إلى خبيئةٍ سرية لحمايتها من اللصوص، ولا أحد يعرف مكانها."] },
    { a:1881, b:2026, tone:"teal", lab:["Found and studied", "وُجدت ودُرست"], say:["Found at Deir el-Bahari in 1881. The mummy is that of a man of about ninety with severe arthritis.", "وُجدت في الدير البحري سنة ١٨٨١، وهي لرجلٍ في نحو التسعين مصابٍ بالتهاب مفاصل شديد."] } ],
  events:[ { y:-1213, lab:["Ramesses II dies", "وفاة رمسيس الثاني"] }, { y:-1000, lab:["Moved to the cache", "النقل إلى الخبيئة"] },
    { y:1881, lab:["The cache is found", "العثور على الخبيئة"] }, { y:1898, lab:["Merneptah's mummy found", "العثور على مومياء مرنبتاح"] }, { y:1976, lab:["Treated in Paris", "المعالجة في باريس"] } ],
  foot:["The verse speaks of the Pharaoh who drowned (10:90-92), but no record says which king he was, and every king was mummified. Bucaille himself argued for Merneptah, not Ramesses II.",
        "تتحدث الآية عن فرعون الذي غرق (١٠:٩٠-٩٢)، لكن لا أثر يذكر أيَّ ملكٍ كان، وكل الملوك حُنّطوا. وبوكاي نفسه رجّح مرنبتاح لا رمسيس الثاني."] },

reign: { type:"era",
  title:["Put the Exodus on the line", "ضع الخروج على خط الزمن"],
  sub:["Drag the marker to a date for the Exodus and see which king it falls under.", "اسحب العلامة إلى تاريخٍ للخروج لترى في عهد أي ملكٍ يقع."],
  range:[-1300,-1190], marker:{ y:-1240, min:-1300, max:-1190, label:["Exodus?", "الخروج؟"] },
  zones:[
    { a:-1300, b:-1279, tone:"mid", lab:["Before Ramesses II", "قبل رمسيس الثاني"], say:["An earlier king. The 66-year argument does not apply here.", "ملكٌ أسبق، فلا ينطبق هنا استدلال الستة والستين عامًا."] },
    { a:-1279, b:-1213, tone:"good", lab:["Ramesses II, 66 years", "رمسيس الثاني، ٦٦ عامًا"], say:["One king through Moses' whole life is possible: the reign is long enough. Egypt's records still say nothing of Moses.", "ملكٌ واحد طوال حياة موسى ممكن، فالحكم طويلٌ بما يكفي. لكن آثار مصر لا تذكر موسى."] },
    { a:-1213, b:-1208, tone:"mid", lab:["Merneptah, before his stele", "مرنبتاح، قبل لوحته"], say:["A new king, so not the one who raised Moses as a child.", "ملكٌ جديد، فليس هو من ربّى موسى طفلًا."] },
    { a:-1208, b:-1190, tone:"bad", lab:["After the Merneptah Stele", "بعد لوحة مرنبتاح"], say:["Too late: by now the stele already names Israel as a people in Canaan.", "متأخرٌ جدًا: فاللوحة تذكر إسرائيل شعبًا في كنعان قبل ذلك."] } ],
  events:[ { y:-1279, lab:["Ramesses II takes the throne", "رمسيس الثاني يعتلي العرش"] }, { y:-1213, lab:["He dies, about ninety", "يموت في نحو التسعين"] }, { y:-1208, lab:["Merneptah Stele", "لوحة مرنبتاح"] } ],
  foot:["Manetho's king list, quoted by Josephus, already gave this king 66 years, so the length of the reign was never lost.",
        "قائمة مانيتون، التي نقلها يوسيفوس، أعطت هذا الملك ٦٦ عامًا، فطول حكمه لم يضع قط."] },

band: { type:"bars",
  title:["How many left Egypt?", "كم عدد الذين خرجوا من مصر؟"],
  sub:["Switch between the two readings of the Hebrew word for 'thousand'. Every bar is on the same scale.",
       "بدّل بين قراءتي الكلمة العبرية «ألف». كل الأشرطة على مقياسٍ واحد."],
  modes:[
    { id:"lit", lab:["'Thousand' as a thousand", "«ألف» بمعنى ألف"],
      rows:[ { v:600000, lab:["Israelite men, Exodus 12:37", "رجال بني إسرائيل، الخروج ١٢:٣٧"], tone:"bad" },
             { v:2000000, lab:["With their families: two million or more", "مع عائلاتهم: مليونان أو أكثر"], tone:"bad" },
             { v:3000000, lab:["Egypt's whole population, estimated", "سكان مصر كلها، تقديرًا"], tone:"ref" } ],
      say:["Two million leaving would be most of a country of about three million, and Sinai surveys found no trace of such a host.",
           "خروج مليونين يعني معظم بلدٍ سكانه نحو ثلاثة ملايين، ولم تجد مسوح سيناء أثرًا لجمعٍ كهذا."] },
    { id:"clan", lab:["'Thousand' as a clan", "«ألف» بمعنى عشيرة"],
      rows:[ { v:5000, txt:["a few thousand", "بضعة آلاف"], lab:["Israelites, if the word means clan or troop", "بنو إسرائيل إن كانت الكلمة بمعنى عشيرة"], tone:"good" },
             { v:3000000, lab:["Egypt's whole population, estimated", "سكان مصر كلها، تقديرًا"], tone:"ref" } ],
      say:["Read as 'clan', the total falls to a few thousand: a band small enough for Pharaoh's 'little troop', and small enough to leave no record.",
           "إن قُرئت «عشيرة» نزل العدد إلى بضعة آلاف: جماعةٌ صغيرة تناسب «شرذمة قليلون»، وصغيرةٌ بما يكفي ألا تترك أثرًا."] } ],
  foot:["The verse is Pharaoh's own speech to his army, not a census.", "الآية كلام فرعون لجيشه، لا إحصاءٌ للسكان."] },

silver: { type:"era",
  title:["Counted silver, before coins", "فضةٌ معدودة قبل النقود"],
  sub:["Drag the marker to any date for Joseph's sale and see how a price was paid then.", "اسحب العلامة إلى أي تاريخٍ لبيع يوسف لترى كيف كان يُدفع الثمن حينها."],
  range:[-2600,700], marker:{ y:-1700, min:-2600, max:700, label:["Joseph sold?", "بيع يوسف؟"] },
  zones:[
    { a:-2600, b:-350, tone:"good", lab:["Prices in fixed units of metal", "أسعارٌ بوحداتٍ ثابتة من المعدن"], say:["No coins yet, but goods were priced in the shat, a twelfth of a deben of metal. A set amount of silver fits.", "لا نقود بعد، لكن السلع كانت تُسعّر بالشات، وهو جزءٌ من اثني عشر من الدبن. فمبلغٌ محدد من الفضة يناسب."] },
    { a:-350, b:700, tone:"mid", lab:["Egypt strikes coins", "مصر تسكّ النقود"], say:["Egypt has struck its own coins since the 4th century BCE.", "صارت مصر تسكّ نقودها منذ القرن الرابع قبل الميلاد."] } ],
  events:[ { y:-2400, lab:["Prices in shat, Saqqara tomb", "أسعارٌ بالشات، مقبرة سقارة"] }, { y:-350, lab:["First Egyptian coins", "أول نقودٍ مصرية"] }, { y:610, lab:["'Dirham': the Arabic word for a silver piece", "«درهم»: الكلمة العربية لقطعة الفضة"] } ],
  foot:["The Bible tells the same sale: twenty pieces of silver (Genesis 37:28). No shat piece has ever been found; it may have been a unit of account only.",
        "تروي التوراة البيع نفسه: عشرون من الفضة (التكوين ٣٧:٢٨). ولم يُعثر قط على قطعة شات، فلعلها كانت وحدة حسابٍ فقط."] },

ipuwer: { type:"duel",
  title:["A lament, read beside the plagues", "مرثيةٌ تُقرأ بجانب الآيات"],
  sub:["Point at a line of the papyrus to see what answers it in the verses.", "أشر إلى سطرٍ من البردية لترى ما يقابله في الآيات."],
  pairs:[
    { src:["Papyrus Leiden I 344", "بردية ليدن ١ ٣٤٤"], rec:["The river is blood", "النهر دم"],
      ar:"وَٱلدَّمَ", en:"and the blood", rel:"same",
      note:["The closest line, and the reason the papyrus is quoted at all. A red Nile was a known event.", "أقرب سطر، وهو سبب الاستشهاد بالبردية أصلًا. واحمرار النيل حدثٌ معروف."] },
    { src:["Papyrus Leiden I 344", "بردية ليدن ١ ٣٤٤"], rec:["foreigners are pouring into Egypt", "الأجانب يتدفقون إلى مصر"],
      ar:"أَنْ أَسْرِ بِعِبَادِىٓ", en:"take away My slaves by night", rel:"flip",
      note:["The poem complains of people coming in; the Exodus is a people going out.", "القصيدة تشكو من قومٍ يدخلون، والخروج قومٌ يغادرون."] },
    { src:["Papyrus Leiden I 344", "بردية ليدن ١ ٣٤٤"], rec:["servants own what their masters had", "الخدم يملكون ما كان لأسيادهم"],
      ar:"ءَايَٰتٍ مُّفَصَّلَٰتٍ", en:"a succession of clear signs", rel:"diff",
      note:["Read whole, the poem is about the collapse of order, not signs sent to a king.", "القصيدة في جملتها عن انهيار النظام، لا عن آياتٍ تُرسل إلى ملك."] },
    { src:["Date of composition", "تاريخ التأليف"], rec:["composed no earlier than about 1800 BCE", "أُلّفت في نحو ١٨٠٠ ق.م. أو بعده"],
      ar:"فَأَرْسَلْنَا عَلَيْهِمُ", en:"So We sent against them", rel:"diff",
      note:["Centuries before any date proposed for Moses. Only the surviving copy is from about 1250 BCE.", "قبل أي تاريخٍ مقترح لموسى بقرون، والنسخة الباقية وحدها من نحو ١٢٥٠ ق.م."] } ] },

letter: { type:"weigh",
  title:["Did a palace letter record the drowning?", "هل سجّلت رسالةٌ من القصر الغرق؟"],
  sub:["Tap each point to place it on the scale. The weights are our reading of how much each one counts.", "انقر كل نقطةٍ لتضعها في الميزان. والأوزان قراءتنا لثقل كل واحدة."],
  forLab:["For the letter", "مع الرسالة"], againstLab:["Against", "ضدها"],
  items:[
    { side:"for", w:1, t:["Amenemone and Pentaweret were real scribes", "أمنمؤوني وبنتاوور كاتبان حقيقيان"] },
    { side:"for", w:1, t:["Egypt rarely recorded its defeats, so a private letter is where news might slip out", "نادرًا ما سجّلت مصر هزائمها، فالرسالة الخاصة موضعٌ قد يتسرب منه الخبر"] },
    { side:"against", w:3, t:["No papyrus number, translator or year is ever given", "لا يُذكر رقم بردية ولا مترجم ولا سنة"] },
    { side:"against", w:2, t:["The quoted words trace to no modern edition", "الكلمات المنقولة لا أصل لها في أي طبعةٍ حديثة"] },
    { side:"against", w:2, t:["Their papyri are model letters copied out by trainee scribes", "برديّاتهما رسائل نموذجية ينسخها الكتبة المتدربون"] },
    { side:"against", w:1, t:["The reading most likely goes back to 'The Exodus Papyri' of 1855", "الأرجح أن القراءة ترجع إلى «برديات الخروج» سنة ١٨٥٥"] } ] },

wheels: { type:"weigh",
  title:["Chariot wheels on the seabed?", "عجلات عرباتٍ في قاع البحر؟"],
  sub:["Tap each point to place it on the scale. The weights are our reading of how much each one counts.", "انقر كل نقطةٍ لتضعها في الميزان. والأوزان قراءتنا لثقل كل واحدة."],
  forLab:["For the wheels", "مع العجلات"], againstLab:["Against", "ضدها"],
  items:[
    { side:"for", w:1, t:["Photographs of wheel-shaped objects off Nuweiba, 1978", "صورٌ لأجسامٍ تشبه العجلات قبالة نويبع، ١٩٧٨"] },
    { side:"for", w:1, t:["The law forbids removing antiquities from the site", "القانون يمنع نقل الآثار من موقعها"] },
    { side:"against", w:3, t:["No object was recovered for study or published", "لم يُستخرج أي جسمٍ للدراسة ولم يُنشر شيء"] },
    { side:"against", w:2, t:["Plate corals on a stalk look like a wheel on an axle", "المرجان الصفائحي على ساقٍ يشبه عجلةً على محور"] },
    { side:"against", w:2, t:["The 2014 'army found' story began on a satire site", "قصة «العثور على الجيش» سنة ٢٠١٤ بدأت في موقعٍ ساخر"] },
    { side:"against", w:2, t:["In over forty years, nothing has been surveyed, sampled or dated", "في أكثر من أربعين عامًا لم يُمسح شيء ولم تؤخذ عينة ولم يؤرَّخ"] } ] },

famine: { type:"spiral",
  title:["The gap between the story and the stone", "المسافة بين القصة والحجر"],
  sub:["Drag along the spiral, or press play. Each turn is five centuries.", "اسحب على اللولب أو شغّل العرض. كل دورةٍ خمسة قرون."],
  per:500,
  phases:[
    { a:-2670, b:-195, tone:"dim", lab:["The story's setting, not yet carved", "زمن القصة، ولم يُنقش بعد"], say:["King Djoser's reign is where the stela sets the famine. Nothing about it is carved yet.", "عهد الملك زوسر هو الزمن الذي تضع فيه اللوحة المجاعة، ولم يُنقش عنها شيء بعد."] },
    { a:-195, b:394, tone:"gold", lab:["Carved, and readable", "منقوشة ومقروءة"], say:["The priests of Khnum carve the stela under Ptolemy V, more than two thousand years after Djoser.", "ينقش كهنة خنوم اللوحة في عهد بطليموس الخامس، بعد زوسر بأكثر من ألفي عام."] },
    { a:394, b:1822, tone:"dim", lab:["Nobody can read it", "لا أحد يقرؤها"], say:["Hieroglyphs are dead. The stone stands on Sehel Island, unread.", "ماتت الهيروغليفية، والحجر قائمٌ في جزيرة سهيل لا يقرؤه أحد."] },
    { a:1822, b:2026, tone:"teal", lab:["Readable again", "مقروءةٌ من جديد"], say:["Champollion has deciphered the script; Wilbour finds the stela in 1889.", "فكّ شامبليون الخط، ووجد ويلبور اللوحة سنة ١٨٨٩."] } ],
  events:[ { y:-2670, lab:["Djoser, the story's king", "زوسر، ملك القصة"] }, { y:-195, lab:["Stela carved", "نقش اللوحة"] }, { y:394, lab:["Last hieroglyphs", "آخر نقشٍ هيروغليفي"] }, { y:1822, lab:["Decipherment", "فك الرموز"] }, { y:1889, lab:["Wilbour finds it", "ويلبور يجدها"] } ],
  foot:["Djoser lived centuries before any date given for Joseph, and a seven-year famine was a common story pattern across the Near East.",
        "عاش زوسر قبل أي تاريخٍ مقترح ليوسف بقرون، والمجاعة ذات السبع سنين نمطٌ قصصيٌّ شائع في الشرق الأدنى."] },

stele: { type:"duel",
  title:["What the video says, what the verses say", "ما يقوله المقطع، وما تقوله الآيات"],
  sub:["Point at a line on the left to see what answers it in the verses.", "أشر إلى سطرٍ على اليمين لترى ما يقابله في الآيات."],
  pairs:[
    { src:["The video", "المقطع"], rec:["Islam teaches the Israelites had no early history in the land", "الإسلام يعلّم أن بني إسرائيل لا تاريخ مبكرًا لهم في الأرض"],
      ar:"وَأَوْرَثْنَا ٱلْقَوْمَ ٱلَّذِينَ كَانُوا۟ يُسْتَضْعَفُونَ مَشَٰرِقَ ٱلْأَرْضِ وَمَغَٰرِبَهَا", en:"We caused the folk who were despised to inherit the eastern parts of the land and the western", rel:"flip",
      note:["The verse says the opposite of what the video says Islam teaches.", "الآية تقول عكس ما ينسبه المقطع إلى الإسلام."] },
    { src:["Merneptah Stele, about 1208 BCE", "لوحة مرنبتاح، نحو ١٢٠٨ ق.م."], rec:["'Israel is laid waste; its seed is no more'", "«إسرائيل خرب، ولم يعد له بذر»"],
      ar:"يَٰقَوْمِ ٱدْخُلُوا۟ ٱلْأَرْضَ ٱلْمُقَدَّسَةَ", en:"O my people! Go into the holy land", rel:"same",
      note:["A people called Israel in Canaan after Pharaoh: the stone and the verses agree.", "شعبٌ اسمه إسرائيل في كنعان بعد فرعون: الحجر والآيات متفقان."] },
    { src:["Merneptah Stele", "لوحة مرنبتاح"], rec:["names no Moses and no Exodus", "لا تذكر موسى ولا الخروج"],
      ar:"وَأَوْرَثْنَا", en:"We caused them to inherit", rel:"diff",
      note:["The stele proves a people called Israel was in Canaan, nothing more. It rules out an Exodus after 1208 BCE.", "اللوحة تثبت وجود شعبٍ اسمه إسرائيل في كنعان لا أكثر، وتستبعد خروجًا بعد ١٢٠٨ ق.م."] } ] },

samiri: { type:"spiral",
  title:["Moses, Samaria, and the Samaritans", "موسى والسامرة والسامريون"],
  sub:["Drag along the spiral, or press play. Each turn is three centuries.", "اسحب على اللولب أو شغّل العرض. كل دورةٍ ثلاثة قرون."],
  per:300,
  phases:[
    { a:-1250, b:-880, tone:"dim", lab:["No Samaria yet", "لا سامرة بعد"], say:["Moses is usually placed here. The city that gave the Samaritans their name does not exist yet.", "هنا يوضع موسى عادةً، والمدينة التي سُمّي بها السامريون لم توجد بعد."] },
    { a:-880, b:-722, tone:"gold", lab:["The city of Samaria", "مدينة السامرة"], say:["King Omri founds Samaria, named after Shemer, who sold him the hill.", "يؤسس الملك عُمري السامرة، وقد سُمّيت باسم شامر الذي باعه التل."] },
    { a:-722, b:2026, tone:"teal", lab:["The Samaritans as a people", "السامريون جماعةً"], say:["After the Assyrian conquest the Samaritans become a distinct community. Arabic writers such as al-Biruni call them al-Samira.", "بعد الغزو الآشوري صار السامريون جماعةً متميزة، وسمّاهم كتّاب العربية كالبيروني «السامرة»."] } ],
  events:[ { y:-1250, lab:["Moses, as usually dated", "موسى، في التأريخ المعتاد"] }, { y:-880, lab:["Samaria founded", "تأسيس السامرة"] }, { y:-722, lab:["Assyrian conquest", "الغزو الآشوري"] }, { y:1030, lab:["Al-Biruni", "البيروني"] } ],
  foot:["The Quran gives this man no biography, and the early commentators read the name as a clan or place name.",
        "لا يذكر القرآن سيرةً لهذا الرجل، وقرأ المفسرون الأوائل الاسم نسبةً إلى قبيلةٍ أو مكان."] },

thamud: { type:"map",
  title:["Thamud on the map", "ثمود على الخريطة"],
  sub:["Point at a site to read what was found there.", "أشر إلى موقعٍ لتقرأ ما وُجد فيه."],
  box:[33,22,46,38],
  sites:[
    { lon:37.95, lat:26.79, k:"site", lab:["Al-Hijr (Hegra)", "الحِجر"], say:["The ruins the Prophet passed on the road to Tabuk. The grand rock-cut facades are mostly Nabataean tombs of the 1st century CE.", "الأطلال التي مرّ بها النبي في طريقه إلى تبوك. والواجهات المنحوتة الكبرى أكثرها مقابر نبطية من القرن الأول الميلادي."] },
    { lon:35.75, lat:28.10, k:"site", lab:["Ruwafa", "الرُّوافة"], say:["A temple built around 165 to 169 CE by 'the tribal unit of Thamud'.", "معبدٌ بُني نحو ١٦٥ إلى ١٦٩م باسم «جماعة ثمود»."] },
    { lon:36.57, lat:28.38, k:"ref", lab:["Tabuk", "تبوك"], say:["The Prophet's campaign of Tabuk passed al-Hijr on the way.", "مرّت غزوة تبوك بالحِجر في طريقها."] },
    { lon:39.61, lat:24.47, k:"ref", lab:["Medina", "المدينة"], say:["Where the road to Tabuk began.", "حيث بدأ الطريق إلى تبوك."] },
    { lon:43.23, lat:36.51, k:"other", lab:["Khorsabad", "خرسباد"], say:["Sargon II's annals, found at his capital, list the 'Tamudi' among the desert Arabs he defeated.", "حوليات سرجون الثاني، التي وُجدت في عاصمته، تذكر «تامودي» بين عرب البادية الذين هزمهم."] } ],
  links:[ { a:3, b:0, lab:["the road to Tabuk", "طريق تبوك"] }, { a:0, b:2 } ],
  foot:["Thamud were never a secret in Arabia: pre-Islamic poets already spoke of them as a vanished tribe.",
        "لم تكن ثمود سرًّا في جزيرة العرب، فقد ذكرها شعراء الجاهلية قبيلةً بائدة."] },

iram: { type:"map",
  title:["The fort at Shisr", "حصن الشصر"],
  sub:["Point at a site to read what was found there.", "أشر إلى موقعٍ لتقرأ ما وُجد فيه."],
  box:[44,12,58,26],
  sites:[
    { lon:53.65, lat:18.25, k:"site", lab:["Shisr", "الشصر"], say:["A fortified caravan site on the frankincense route, excavated after 1992. No inscription names the place.", "موقعٌ محصّن للقوافل على طريق اللبان، نُقّب بعد ١٩٩٢، ولا نقش فيه يسمّي المكان."] },
    { lon:54.09, lat:17.02, k:"ref", lab:["Salalah", "صلالة"], say:["The coast of Dhofar, where the frankincense grew.", "ساحل ظفار، حيث ينبت اللبان."] },
    { lon:39.83, lat:21.42, k:"ref", lab:["Mecca", "مكة"], say:["For scale: Arab tradition told of 'Ad and Iram long before any satellite.", "للمقارنة: روى العرب خبر عادٍ وإرم قبل أي قمرٍ صناعي بزمن طويل."] } ],
  links:[ { a:0, b:1 } ],
  foot:["Juris Zarins argued that Ubar named a region and a people, not one town. Most scholars read Shisr as a caravan station.",
        "رأى يوريس زارينز أن «أوبار» اسم إقليمٍ وقوم لا اسم بلدةٍ واحدة، ويرى أكثر الباحثين الشصر محطة قوافل."] },

ebla: { type:"weigh",
  title:["Do the Ebla tablets name scripture's cities?", "هل تذكر ألواح إبلا مدن الكتب المقدسة؟"],
  sub:["Tap each point to place it on the scale. The weights are our reading of how much each one counts.", "انقر كل نقطةٍ لتضعها في الميزان. والأوزان قراءتنا لثقل كل واحدة."],
  forLab:["For the readings", "مع القراءات"], againstLab:["Against", "ضدها"],
  items:[
    { side:"for", w:1, t:["The archive is real: thousands of tablets from the palace of Ebla", "الأرشيف حقيقي: آلاف الألواح من قصر إبلا"] },
    { side:"for", w:1, t:["In 1976 the first epigrapher announced Sodom and Gomorrah", "سنة ١٩٧٦ أعلن أول قارئٍ للألواح أنه قرأ سدوم وعمورة"] },
    { side:"against", w:3, t:["Alfonso Archi, who took over the tablets, rejected the Sodom reading in 1979 and 1981", "رفض ألفونسو آركي، الذي تسلّم الألواح، قراءة سدوم سنتي ١٩٧٩ و١٩٨١"] },
    { side:"against", w:2, t:["Pettinato withdrew part of his own reading", "تراجع بيتيناتو عن جزءٍ من قراءته"] },
    { side:"against", w:2, t:["The tablets' editors say they contain no places or people from scripture", "يقول محررو الألواح إنها لا تحوي أماكن أو أشخاصًا من الكتب المقدسة"] },
    { side:"against", w:2, t:["No published tablet names Iram", "لا لوح منشور يذكر إرم"] } ] },

dam: { type:"era",
  title:["The dam, within living memory", "السد في ذاكرة الأحياء"],
  sub:["Drag the marker to a year and see the state of the Marib dam. The revelation begins in 610.", "اسحب العلامة إلى سنةٍ لترى حال سد مأرب. وبدأ الوحي سنة ٦١٠."],
  range:[420,640], marker:{ y:600, min:420, max:640, label:["Year", "السنة"] },
  zones:[
    { a:420, b:454, tone:"good", lab:["The dam stands", "السد قائم"], say:["The great dam waters Saba's two gardens.", "السد العظيم يسقي جنتي سبأ."] },
    { a:454, b:572, tone:"mid", lab:["Breaking and mended", "يتصدع ويُرمَّم"], say:["Breaches in 454 and 455 are repaired under Shurihbi'il Ya'fur; another is sealed in 547 under Abraha.", "صُدوعٌ سنتي ٤٥٤ و٤٥٥ رُمّمت في عهد شرحبيل يعفر، وسُدّ صدعٌ آخر سنة ٥٤٧ في عهد أبرهة."] },
    { a:572, b:640, tone:"bad", lab:["Overtopped, never repaired", "طغى عليه الماء ولم يُرمَّم"], say:["The dam failed in about 570 or 575 and was never repaired. In 610, anyone about forty or older had been alive when it happened.", "انهار السد نحو ٥٧٠ أو ٥٧٥ ولم يُرمَّم. ففي ٦١٠ كان كل من بلغ الأربعين أو جاوزها حيًّا يوم حدوثه."] } ],
  events:[ { y:454, lab:["Breach", "صدع"] }, { y:547, lab:["Sealed under Abraha", "سدّه في عهد أبرهة"] }, { y:572, lab:["Final failure, c. 570 to 575", "الانهيار الأخير، نحو ٥٧٠ إلى ٥٧٥"] }, { y:610, lab:["The revelation begins", "بدء الوحي"] } ],
  foot:["Which breach the verse means is debated; some historians link it to a break around 145 BCE.",
        "اختُلف في أي صدعٍ تقصده الآية، وبعض المؤرخين يربطها بصدعٍ نحو ١٤٥ ق.م."] },

elephant: { type:"era",
  title:["When did the elephant march?", "متى سار الفيل؟"],
  sub:["Drag the marker to a year for the campaign and compare it with Abraha's own dated record.", "اسحب العلامة إلى سنةٍ للحملة وقارنها بسجل أبرهة المؤرَّخ."],
  range:[525,580], marker:{ y:570, min:525, max:580, label:["The elephant?", "الفيل؟"] },
  zones:[
    { a:525, b:533, tone:"mid", lab:["Before Abraha rules", "قبل حكم أبرهة"], say:["Abraha does not yet rule the Himyarite kingdom.", "لم يكن أبرهة قد حكم مملكة حمير بعد."] },
    { a:533, b:553, tone:"good", lab:["Abraha's dated record", "سجل أبرهة المؤرَّخ"], say:["Inside his own record. The Murayghan inscription of 552 records a campaign into central Arabia.", "داخل سجله نفسه، ونقش مريغان سنة ٥٥٢ يسجل حملةً إلى وسط الجزيرة."] },
    { a:553, b:560, tone:"mid", lab:["After his last inscription", "بعد آخر نقوشه"], say:["His dated inscriptions have stopped, though he may still be alive.", "توقفت نقوشه المؤرخة، وإن كان قد يظل حيًا."] },
    { a:560, b:580, tone:"bad", lab:["Abraha probably dead", "الأرجح أن أبرهة مات"], say:["Tradition's date, about 570, the year of the Prophet's birth. Abraha probably died before 560, so historians argue over which should move: the date or the campaign.", "تاريخ الرواية نحو ٥٧٠، عام مولد النبي. والأرجح أن أبرهة مات قبل ٥٦٠، فيختلف المؤرخون: أيّهما يُعدَّل، التاريخ أم الحملة."] } ],
  events:[ { y:533, lab:["Abraha rules", "حكم أبرهة"] }, { y:548, lab:["Dam inscription", "نقش السد"] }, { y:552, lab:["Murayghan", "مريغان"] }, { y:570, lab:["Tradition's year", "عام الرواية"] } ],
  foot:["Abraha is one of the best-documented rulers of pre-Islamic Arabia. The surah's first listeners had grown up with the story.",
        "أبرهة من أوثق حكام الجزيرة قبل الإسلام توثيقًا، ونشأ أوائل من سمع السورة على هذه القصة."] },

trench: { type:"map",
  title:["Najran, and how near it was", "نجران، وكم كانت قريبة"],
  sub:["Point at a site to read what happened there.", "أشر إلى موقعٍ لتقرأ ما جرى فيه."],
  box:[36,13,50,34],
  sites:[
    { lon:44.13, lat:17.49, k:"site", lab:["Najran", "نجران"], say:["July 523: Dhu Nuwas's commanders burn the church and kill its people, and carve their boast in three inscriptions.", "يوليو ٥٢٣: قادة ذي نواس يحرقون الكنيسة ويقتلون أهلها، وينقشون تفاخرهم في ثلاثة نقوش."] },
    { lon:44.45, lat:31.88, k:"other", lab:["Al-Hira", "الحيرة"], say:["Bishop Simeon of Beth Arsham writes his account from here in 524.", "منها كتب الأسقف شمعون الأرشامي روايته سنة ٥٢٤."] },
    { lon:39.83, lat:21.42, k:"ref", lab:["Mecca", "مكة"], say:["A town that traded with Najran. The massacre came less than ninety years before the revelation.", "بلدةٌ تتاجر مع نجران، والمذبحة وقعت قبل الوحي بأقل من تسعين عامًا."] } ],
  links:[ { a:2, b:0 }, { a:1, b:0 } ],
  foot:["The surah names no place; tradition ties it to Najran. Some commentators read it as a scene of the Last Day.",
        "لا تسمّي السورة مكانًا، والرواية هي التي تربطها بنجران، وبعض المفسرين قرأها مشهدًا من يوم القيامة."] },

romans: { type:"era",
  title:["'Within a few years'", "«في بضع سنين»"],
  sub:["Drag the marker to the year the verses came down. The shaded window is bid' sinin, three to nine years after.",
       "اسحب العلامة إلى سنة نزول الآيات. والنافذة المظللة «بضع سنين»: من ثلاثٍ إلى تسعٍ بعدها."],
  range:[608,634], marker:{ y:615, min:613, max:618, label:["The verses", "نزول الآيات"] },
  win:{ from:3, to:9, lab:["bid' sinin", "بضع سنين"] },
  zones:[], events:[ { y:614, lab:["Persia takes Jerusalem", "الفرس يأخذون القدس"] }, { y:622, lab:["Heraclius's first major victory", "أول نصرٍ كبير لهرقل"] }, { y:627, lab:["Nineveh", "نينوى"] }, { y:628, lab:["Peace", "الصلح"] } ],
  foot:["The verses' date comes from the same tradition that reports the prophecy coming true, so the timing cannot be checked against an independent source.",
        "تاريخ الآيات مصدره الرواية نفسها التي تخبر بتحقق النبوءة، فلا يمكن التحقق من التوقيت بمصدرٍ مستقل."] },

judi: { type:"map",
  title:["Al-Judi and Ararat", "الجودي وأرارات"],
  sub:["Point at a site to read which tradition puts the ark there.", "أشر إلى موقعٍ لتقرأ أي روايةٍ تضع السفينة فيه."],
  box:[39,35,47,41],
  sites:[
    { lon:42.33, lat:37.37, k:"site", lab:["Mount Cudi (al-Judi)", "جبل الجودي"], say:["Above Cizre, in the old Gordyene district: the mountains of Qardu of the Aramaic Targums, and Berossus's 'mountain of the Cordyaeans'.", "فوق الجزيرة (جزيرة ابن عمر)، في إقليم كوردوئين القديم: «جبال قردو» في الترجمات الآرامية، و«جبل الكورديين» عند بيروسوس."] },
    { lon:44.30, lat:39.70, k:"other", lab:["Mount Ararat", "جبل أرارات"], say:["The 'mountains of Ararat' most Bible readers know. Ararat is also the old name of Urartu, a wide highland region.", "«جبال أراراط» التي يعرفها أكثر قرّاء التوراة. وأرارات أيضًا الاسم القديم لأورارتو، وهي بلادٌ جبلية واسعة."] },
    { lon:43.15, lat:36.36, k:"ref", lab:["Nineveh (Mosul)", "نينوى (الموصل)"], say:["For orientation, on the Tigris.", "للتوجيه، على دجلة."] } ],
  links:[ { a:0, b:1 } ],
  foot:["The Quran sides with the older Mesopotamian and Aramaic tradition, alive among Syriac Christians and Jews in the 7th century.",
        "يوافق القرآن الرواية الرافدية والآرامية الأقدم، وكانت حيّةً عند المسيحيين السريان واليهود في القرن السابع."] },

ark: { type:"map",
  title:["Where the 'ark' shape is", "أين يقع شكل «السفينة»"],
  sub:["Point at a site. The lines give the distances between them.", "أشر إلى موقع، والخطوط تُظهر المسافات بينها."],
  box:[40.5,36.3,46.5,40.6],
  sites:[
    { lon:44.23, lat:39.44, k:"site", lab:["Durupinar site", "موقع دوروپينار"], say:["A 164-metre mound of iron-rich rock near Uzengili. A 1996 study found a natural formation shaped by a landslide.", "ركامٌ صخري غني بالحديد طوله ١٦٤ مترًا قرب أوزنغيلي، ووجدت دراسة ١٩٩٦ أنه تكوينٌ طبيعي شكّله انزلاقٌ أرضي."] },
    { lon:44.30, lat:39.70, k:"other", lab:["Mount Ararat", "جبل أرارات"], say:["About 30 km north of the site.", "على نحو ٣٠ كم شمال الموقع."] },
    { lon:42.33, lat:37.37, k:"ref", lab:["Mount Cudi (al-Judi)", "جبل الجودي"], say:["The Judi of Muslim geographers and local tradition, near Cizre.", "جوديّ الجغرافيين المسلمين والرواية المحلية، قرب الجزيرة."] } ],
  links:[ { a:0, b:1 }, { a:0, b:2 } ],
  foot:["So the shape is neither a ship nor on the mountain the Quran's tradition names.", "فالشكل ليس سفينةً، ولا هو على الجبل الذي تسمّيه رواية القرآن."] },

sleepers: { type:"convert",
  title:["Three hundred years, and nine more", "ثلاث مئة سنين وازدادوا تسعًا"],
  sub:["Drag the years in the sun's calendar and watch the same span counted in moons.", "اسحب عدد السنين بتقويم الشمس، وانظر المدة نفسها بحساب القمر."],
  solar:300, solarLen:365.24, lunarLen:354.37,
  marks:[ { y:200, lab:["Some Christian tellings: about 200", "بعض الروايات المسيحية: نحو ٢٠٠"] }, { y:372, lab:["Others: 372", "روايات أخرى: ٣٧٢"] } ],
  foot:["The arithmetic holds, and it was not hidden: commentators such as Ibn Kathir already explained the nine as the lunar surplus.",
        "الحساب صحيح، ولم يكن خفيًا، فقد فسّر المفسرون كابن كثير التسع بزيادة السنين القمرية."] },

cyrus: { type:"weigh",
  title:["Is Dhul-Qarnayn Cyrus?", "هل ذو القرنين هو قورش؟"],
  sub:["Tap each point to place it on the scale. The weights are our reading of how much each one counts.", "انقر كل نقطةٍ لتضعها في الميزان. والأوزان قراءتنا لثقل كل واحدة."],
  forLab:["For Cyrus", "مع قورش"], againstLab:["Against", "ضده"],
  items:[
    { side:"for", w:1, t:["Isaiah 45 calls Cyrus God's anointed", "سفر إشعياء ٤٥ يسمّي قورش مسيح الرب"] },
    { side:"for", w:1, t:["Daniel's two-horned ram stands for the kings of Media and Persia", "كبش دانيال ذو القرنين يرمز إلى ملوك مادي وفارس"] },
    { side:"for", w:1, t:["A relief at Pasargadae shows a crown with ram's horns", "نقشٌ في باسارغاد يُظهر تاجًا بقرني كبش"] },
    { side:"for", w:1, t:["The Quran's just believer fits Cyrus better than the pagan Alexander", "المؤمن العادل في القرآن أقرب إلى قورش منه إلى الإسكندر الوثني"] },
    { side:"against", w:2, t:["No ancient text calls Cyrus two-horned", "لا نصّ قديمًا يصف قورش بذي القرنين"] },
    { side:"against", w:1, t:["Daniel's ram is a kingdom, not a man", "كبش دانيال مملكة لا رجل"] },
    { side:"against", w:1, t:["The Pasargadae figure is not labelled Cyrus", "صورة باسارغاد لا تحمل اسم قورش"] },
    { side:"against", w:3, t:["The Syriac Alexander Legend matches the surah's episodes in order", "أسطورة الإسكندر السريانية توافق مشاهد السورة بترتيبها"] },
    { side:"against", w:1, t:["The Cyrus reading dates from the 1930s; early commentators mostly said Alexander", "قراءة قورش ترجع إلى الثلاثينيات، وأكثر المفسرين الأوائل قالوا الإسكندر"] } ] },

sodom: { type:"weigh",
  title:["Was Sodom found, and its stones explained?", "هل وُجدت سدوم وفُسّرت حجارتها؟"],
  sub:["Tap each point to place it on the scale. The weights are our reading of how much each one counts.", "انقر كل نقطةٍ لتضعها في الميزان. والأوزان قراءتنا لثقل كل واحدة."],
  forLab:["For the claim", "مع المزعم"], againstLab:["Against", "ضده"],
  items:[
    { side:"for", w:1, t:["Tall el-Hammam is a Bronze Age city near the Dead Sea, destroyed about 1650 BCE", "تل الحمام مدينةٌ من العصر البرونزي قرب البحر الميت، دُمّرت نحو ١٦٥٠ ق.م."] },
    { side:"for", w:1, t:["Its melted material and high salt still need an explanation", "موادها المنصهرة وملوحتها العالية ما زالت تحتاج إلى تفسير"] },
    { side:"against", w:3, t:["The airburst paper was retracted on 24 April 2025", "سُحبت ورقة الانفجار الجوي في ٢٤ أبريل ٢٠٢٥"] },
    { side:"against", w:2, t:["Calling this site Sodom was a minority view even before", "تسمية هذا الموقع سدوم كانت رأي الأقلية حتى قبل ذلك"] },
    { side:"against", w:2, t:["The Quran never mentions a pillar of salt", "لا يذكر القرآن عمودًا من الملح"] } ] }
};
