// The site's explanations in layers, for the app's analysis pages (web/app.html reads window.DALEEL_EXPLAIN).
//   SCI:   each page's explanation for scientists, beside the plain one: purpose, data, method, result, limits
//          (and "also" for a second analysis on the same page). The switch above each box picks the layer.
//   GLOSS: the technical terms. Each opens as a card in four layers: in plain words, what it does here,
//          what it showed us, and for scientists; "page" is where the term is at work.
//   PCA:   the steps of the walk-through on the Clusters page.
// Every text is [English, Arabic]. In a text, [[key]] or [[key|shown words]] becomes a term you can open,
// and `...` is a formula (set left to right, also in Arabic).
// The numbers are the build's (data-build/pipeline); data-build/tests/test_methods.py pins the ones that
// the site does not show elsewhere.
window.DALEEL_EXPLAIN = (function () {
  'use strict';
  const SCI = {
    overview: {
      purpose: ['A census of the text: the counts every other page builds on.',
        'إحصاءٌ أساسيٌّ للنص: الأعداد التي تقوم عليها بقية الصفحات.'],
      data: ['The Quranic Arabic Corpus morphology, in Uthmani script with Kufan verse numbering: 130,030 morphological segments, grouped into 77,429 written words in 6,236 verses and 114 surahs. The build stops if any of these totals changes.',
        'المدوّنة الصرفية للقرآن الكريم (Quranic Arabic Corpus) بالرسم العثماني وعدّ الآي الكوفي: ١٣٠٬٠٣٠ مقطعًا صرفيًا تُجمع في ٧٧٬٤٢٩ كلمةً مكتوبة، في ٦٬٢٣٦ آية و١١٤ سورة. ويتوقف بناء البيانات إن تغيّر أيٌّ من هذه المجاميع.'],
      method: ['A word is a written word (the text between two spaces), rebuilt from its segments. Written forms are the different spellings after [[normalization]]; different words are the different [[lemma|lemmas]]; roots are the corpus\'s [[root|roots]].',
        'الكلمة هي الكلمة المكتوبة (ما بين مسافتين)، مُعادٌ بناؤها من مقاطعها. والصيغ المكتوبة هي الرسوم المختلفة بعد [[normalization|توحيد الرسم]]، والكلمات المختلفة هي [[lemma|المداخل المعجمية]] المختلفة، والجذور هي [[root|جذور]] المدوّنة.'],
      result: ['14,710 written forms, of which 8,619 occur only once ([[hapax]]); 4,771 lemmas; 1,651 roots. Surah length is very uneven: the median surah has 39 verses and 344 words, while the 16 longest hold 51% of all the words.',
        '١٤٬٧١٠ صيغةً مكتوبة، منها ٨٬٦١٩ ترد مرةً واحدة ([[hapax|كلماتٌ فريدة]])، و٤٬٧٧١ مدخلًا معجميًا، و١٬٦٥١ جذرًا. وأطوال السور متفاوتةٌ جدًّا: السورة الوسيطة فيها ٣٩ آية و٣٤٤ كلمة، بينما تضمّ أطول ١٦ سورةً ٥١٪ من الكلمات كلها.'],
      limits: ['Totals follow the corpus\'s conventions: how words are split (particles written joined to a word count with it), the verse numbering (Kufan, 6,236) and the Uthmani spelling. Other editions and counting schools give slightly different numbers.',
        'المجاميع تتبع أعراف المدوّنة: طريقة تقسيم الكلمات (الأدوات المتصلة بكلمةٍ تُعَدّ معها)، وعدّ الآي (الكوفي: ٦٬٢٣٦)، والرسم العثماني. وتعطي الطبعات ومذاهب العدّ الأخرى أعدادًا مختلفةً قليلًا.'] },

    word: {
      purpose: ['Rank the vocabulary by how often each word occurs, counting every form of a word together.',
        'ترتيب المفردات بحسب ورود كل كلمة، مع عدّ صيغ الكلمة الواحدة معًا.'],
      data: ['76,572 of the 77,429 words carry a [[lemma]]. The 857 without one are left out: mostly pronouns written on their own (هُوَ, هُمْ, نَحْنُ) and the disconnected letters (الٓمٓ, حمٓ).',
        'يحمل ٧٦٬٥٧٢ من الكلمات الـ٧٧٬٤٢٩ [[lemma|مدخلًا معجميًا]]. وتُستبعد ٨٥٧ كلمةً بلا مدخل: معظمها ضمائر منفصلة (هُوَ، هُمْ، نَحْنُ) والحروف المقطّعة (الٓمٓ، حمٓ).'],
      method: ['Each word counts once, under the lemma of its stem: the segment that has a root; failing that, the first noun or verb segment; failing that, the first segment with a lemma. So a word made only of particles (وَلَا, وَمَا, وَإِنْ) counts under و, which is why و leads the list.',
        'تُعَدّ كل كلمةٍ مرةً واحدة تحت مدخل جذعها: المقطع الذي له جذر، وإلا فأول مقطعٍ اسميٍّ أو فعلي، وإلا فأول مقطعٍ له مدخل. فالكلمة المؤلفة من أدواتٍ فقط (وَلَا، وَمَا، وَإِنْ) تُعَدّ تحت «و»، ولهذا تتصدّر «و» القائمة.'],
      result: ['و 2,943, مِن 2,871, اللَّه 2,699. The distribution is heavy-tailed, as [[zipf]] describes (log–log slope about −1.1): the 10 commonest lemmas cover 25% of the words, while 41% of the 4,771 lemmas occur only once.',
        '«و» ٢٬٩٤٣، و«مِن» ٢٬٨٧١، و«اللَّه» ٢٬٦٩٩. والتوزيع طويل الذيل كما يصفه [[zipf|قانون زيبف]] (الميل اللوغاريتمي نحو ‎−١٫١): أكثر ١٠ مداخل ورودًا تغطي ٢٥٪ من الكلمات، و٤١٪ من المداخل الـ٤٬٧٧١ لا ترد إلا مرةً واحدة.'],
      limits: ['Lemmas follow the corpus\'s annotation, which is disputed in places. A word with particles attached counts once, under its stem, so particles are undercounted as separate words.',
        'المداخل تتبع توسيم المدوّنة، وفي بعضه خلاف. والكلمة المتصلة بها أدواتٌ تُعَدّ مرةً واحدة تحت جذعها، فلا تُعَدّ الأدوات المتصلة كلماتٍ مستقلة.'] },

    letters: {
      purpose: ['How often each letter is written in the text.', 'كم مرةً يُكتب كل حرفٍ في النص.'],
      data: ['325,665 letters in the 77,429 written words.', '٣٢٥٬٦٦٥ حرفًا في الكلمات المكتوبة الـ٧٧٬٤٢٩.'],
      method: ['[[normalization|Normalized]] text: vowel marks removed, the alif forms أ إ آ ٱ counted as ا and ى as ي. 32 letter shapes are counted, with ة and the hamza forms ء ؤ ئ kept apart. The small (dagger) alif and other small marks are not counted.',
        'النص بعد [[normalization|توحيد الرسم]]: تُحذف الحركات، وتُعَدّ صور الألف أ إ آ ٱ ألفًا (ا) والألف المقصورة ى ياءً (ي). وتُعَدّ ٣٢ صورةً للحروف، مع فصل التاء المربوطة ة وصور الهمزة ء ؤ ئ. ولا تُعَدّ الألف الخنجرية ولا العلامات الصغيرة.'],
      result: ['ا 52,655 (16.2%), ل 38,102 (11.7%), ن 27,268 (8.4%).', 'ا ٥٢٬٦٥٥ (١٦٫٢٪)، ل ٣٨٬١٠٢ (١١٫٧٪)، ن ٢٧٬٢٦٨ (٨٫٤٪).'],
      limits: ['These are counts of the Uthmani spelling, which differs from modern spelling (السموت for السماوات), and they change with the normalization chosen.',
        'هذه أعداد الرسم العثماني، وهو يختلف عن الرسم الإملائي الحديث («السموت» مقابل «السماوات»)، وتتغير بتغيّر طريقة توحيد الرسم.'] },

    mecca: {
      purpose: ['Compare the length of verses in the surahs labelled Meccan with those labelled Medinan.',
        'مقارنة طول الآيات في السور الموسومة بالمكية بطولها في السور الموسومة بالمدنية.'],
      data: ['All 6,236 verses: 4,613 in 86 Meccan surahs and 1,623 in 28 Medinan surahs. The label is per surah, from the standard classification.',
        'الآيات الـ٦٬٢٣٦ كلها: ٤٬٦١٣ في ٨٦ سورةً مكية، و١٬٦٢٣ في ٢٨ سورةً مدنية. والوسم للسورة كلها، بحسب التصنيف المشهور.'],
      method: ['Verse length is its number of written words. This page describes the two groups; the test of the difference is on the Statistics page ([[ttest]]).',
        'طول الآية عدد كلماتها المكتوبة. وهذه الصفحة تصف المجموعتين، أما اختبار الفرق فعلى صفحة الإحصاء ([[ttest|اختبار t]]).'],
      result: ['Mean 10.28 against 18.48 words; median 8 against 16; standard deviation 7.4 against 11.7. Both are skewed to the right (1 to 78 words and 1 to 128).',
        'المتوسط ١٠٫٢٨ مقابل ١٨٫٤٨ كلمة، والوسيط ٨ مقابل ١٦، والانحراف المعياري ٧٫٤ مقابل ١١٫٧. والتوزيعان ملتويان نحو اليمين (من ١ إلى ٧٨ كلمة، ومن ١ إلى ١٢٨).'],
      limits: ['One label per surah: some surahs are said to include verses from the other period, and a few surahs\' labels are disputed.',
        'وسمٌ واحد لكل سورة: فبعض السور يُقال إن فيها آياتٍ من المرحلة الأخرى، وفي وسم بعض السور خلاف.'] },

    stats: {
      purpose: ['Test whether Medinan verses are longer than Meccan ones, and estimate by how much when other factors are held fixed.',
        'اختبار ما إذا كانت الآيات المدنية أطول من المكية، وتقدير مقدار ذلك مع تثبيت عوامل أخرى.'],
      data: ['The lengths of all 6,236 verses: 1,623 Medinan and 4,613 Meccan.', 'أطوال الآيات الـ٦٬٢٣٦ كلها: ١٬٦٢٣ مدنية و٤٬٦١٣ مكية.'],
      method: ['[[ttest|Welch\'s t-test]] (two-sided, unequal variances, α = 0.05) with a 95% [[ci|confidence interval]] for the difference of means, and the [[effect|effect size]]. Then [[ols|linear regression]] by least squares: `length = b0 + b1·surah no. + b2·Medinan + b3·verse no.`',
        '[[ttest|اختبار t لويلش]] (ثنائي الطرف، بتباينين غير متساويين، `α = 0.05`) مع [[ci|فترة ثقة]] ٩٥٪ للفرق بين المتوسطين، و[[effect|حجم الأثر]]. ثم [[ols|انحدارٌ خطي]] بالمربعات الصغرى: `length = b0 + b1·surah + b2·Medinan + b3·verse`'],
      result: ['A difference of 8.19 words: `t = 26.41`, `df = 2,089.6`, `p ≈ 7.5×10⁻¹³³`, 95% CI [7.59, 8.80], Cohen\'s `d ≈ 0.94` (a large effect). Regression: `R² = 0.267`; being Medinan adds 5.93 words with surah and verse number held fixed; −0.134 words per step in surah number; −0.006 per verse number.',
        'فرقٌ قدره ٨٫١٩ كلمة: `t = 26.41` و`df = 2,089.6` و`p ≈ 7.5×10⁻¹³³`، وفترة الثقة ٩٥٪ من ٧٫٥٩ إلى ٨٫٨٠، وحجم الأثر `d ≈ 0.94` (أثرٌ كبير). والانحدار: `R² = 0.267`، وكون السورة مدنيةً يضيف ٥٫٩٣ كلمة مع تثبيت رقم السورة ورقم الآية، و‎−٠٫١٣٤ كلمة لكل خطوةٍ في رقم السورة، و‎−٠٫٠٠٦ لكل رقم آية.'],
      limits: ['The test treats verses as independent, but verses of one surah resemble each other, so the p-value is too small and the interval too narrow; with a gap this large the conclusion still stands. Verse lengths are skewed counts, the regression\'s standard errors are not reported, and surah number is an order, not a measurement.',
        'يعامل الاختبار الآيات كأنها مستقلة، لكن آيات السورة الواحدة متشابهة، فالقيمة الاحتمالية أصغر مما ينبغي والفترة أضيق؛ ومع فرقٍ بهذا الحجم تبقى النتيجة قائمة. وأطوال الآيات أعدادٌ ملتوية التوزيع، ولا تُذكر الأخطاء المعيارية للانحدار، ورقم السورة ترتيبٌ لا قياس.'] },

    classifier: {
      purpose: ['Ask whether vocabulary alone predicts a surah\'s Meccan or Medinan label.', 'هل تكفي المفردات وحدها للتنبؤ بوسم السورة: مكية أم مدنية؟'],
      data: ['114 documents, one per surah, each the list of its words\' lemmas: 86 Meccan and 28 Medinan. Vocabulary: the 2,587 lemmas found in at least two surahs.',
        '١١٤ وثيقة، واحدةٌ لكل سورة، هي قائمة المداخل المعجمية لكلماتها: ٨٦ مكية و٢٨ مدنية. والمفردات: ٢٬٥٨٧ مدخلًا ورد في سورتين على الأقل.'],
      method: ['[[tfidf|TF-IDF]] features (scikit-learn defaults: smoothed idf, rows scaled to length 1) and [[logreg|logistic regression]] with an L2 penalty (C = 1). Each surah is predicted by [[cv|stratified 5-fold cross-validation]] (shuffled, seed 42), with a 0.5 threshold.',
        'خصائص [[tfidf|TF-IDF]] (بإعدادات scikit-learn الافتراضية: idf ممهّد، وكل صفٍّ مُطبَّعٌ إلى طول ١)، و[[logreg|انحدارٌ لوجستي]] بعقوبة L2 ‏(`C = 1`). ويُتنبّأ بكل سورةٍ عبر [[cv|التحقق المتقاطع الطبقي بخمس طيّات]] (مخلوطة، البذرة ٤٢) بعتبة ٠٫٥.'],
      result: ['Accuracy 0.851 against a majority [[baseline]] of 0.754; [[auc|ROC AUC]] 0.920. [[confusion|Confusion matrix]]: all 86 Meccan surahs right; 11 of 28 Medinan right (recall 0.39, precision 1.00). The largest Medinan weights are اللَّه, رَسُول, أَيّ, آلاء, آمَنَ; the largest Meccan ones قالَ, و, رَبّ, إِنّ (from a model fit on all 114).',
        'الدقة ٠٫٨٥١ مقابل [[baseline|خط أساس]] الفئة الغالبة ٠٫٧٥٤، و[[auc|المساحة تحت منحنى ROC]] ‏٠٫٩٢٠. و[[confusion|مصفوفة الالتباس]]: السور المكية الـ٨٦ كلها صحيحة، و١١ من ٢٨ مدنية (الاستدعاء ٠٫٣٩، والدقة الموجبة ١٫٠٠). وأكبر الأوزان نحو المدني: اللَّه، رَسُول، أَيّ، آلاء، آمَنَ؛ ونحو المكي: قالَ، و، رَبّ، إِنّ (من نموذجٍ دُرِّب على السور الـ١١٤ كلها).'],
      limits: ['A small, imbalanced sample: at 0.5 the model leans to Meccan. The AUC shows its ranking is good, so a lower threshold would find more Medinan surahs. The vocabulary and idf weights were fitted on all surahs before cross-validation (no labels used). Weights show association, not cause.',
        'عيّنةٌ صغيرة غير متوازنة: عند العتبة ٠٫٥ يميل النموذج إلى «مكية». والمساحة تحت المنحنى تدل على أن ترتيبه جيد، فعتبةٌ أدنى تكشف سورًا مدنيةً أكثر. وقد حُسبت المفردات وأوزان idf على السور كلها قبل التحقق المتقاطع (دون استعمال الوسوم). والأوزان تدل على اقترانٍ لا على سببية.'] },

    cluster: {
      purpose: ['Find groups of surahs with a similar shape without telling the computer the groups, and draw the surahs on a flat map.',
        'إيجاد مجموعاتٍ من السور المتشابهة في هيئتها دون إخبار الحاسوب بالمجموعات، ورسم السور على خريطةٍ مسطّحة.'],
      data: ['114 surahs × 4 measurements: words per verse, number of verses, number of words, and the Medinan label (1 or 0).',
        '١١٤ سورة × ٤ قياسات: الكلمات في الآية، وعدد الآيات، وعدد الكلمات، ووسم المدني (١ أو ٠).'],
      method: ['Each measurement is [[zscore|standardized]]. [[kmeans|k-means]] with K = 4 (10 random starts, seed 42) forms the groups; [[pca|PCA]] on the same four standardized measurements gives the map\'s two axes. The list below ranks surahs by the [[cosine|cosine similarity]] of their [[tfidf|TF-IDF]] lemma vectors.',
        'يُقيَّس كل قياسٍ [[zscore|بالدرجة المعيارية]]. ثم تكوّن [[kmeans|خوارزمية k-means]] المجموعات بـ`K = 4` (عشر بدايات عشوائية، البذرة ٤٢)، ويعطي [[pca|تحليل المكوّنات الرئيسية]] على القياسات الأربعة نفسها محورَي الخريطة. والقائمة أدناه ترتّب السور بحسب [[cosine|تشابه جيب التمام]] بين متجهات [[tfidf|TF-IDF]] لمداخلها.'],
      result: ['The first two components keep 60.1% and 29.9% of the variance (90.0% together). The first is overall size (all four measurements load positively); the second sets Medinan surahs with long verses against surahs with many verses. Groups: 53 short Meccan surahs (4.9 words a verse); 31 middle-length Meccan; 23 Medinan (all of them Medinan); 7 very long surahs (5 Medinan). Of K = 2 to 8, K = 4 has the highest mean silhouette (0.55). For 100 of the 114 surahs, the most similar surah by vocabulary has the same label.',
        'يحتفظ المكوّنان الأوّلان بـ٦٠٫١٪ و٢٩٫٩٪ من التباين (٩٠٫٠٪ معًا). الأول هو الحجم العام (القياسات الأربعة كلها موجبة التحميل)، والثاني يقابل بين السور المدنية الطويلة الآيات والسور الكثيرة الآيات. والمجموعات: ٥٣ سورةً مكيةً قصيرة (٤٫٩ كلمة في الآية)، و٣١ مكيةً متوسطة الطول، و٢٣ مدنية (كلها مدنية)، و٧ سورٍ طويلةٍ جدًّا (٥ منها مدنية). ومن `K = 2` إلى ٨ يبلغ متوسط معامل الصورة الظلية (silhouette) أعلاه عند `K = 4` ‏(٠٫٥٥). ولـ١٠٠ من السور الـ١١٤، أشبهُ سورةٍ بها في المفردات لها الوسم نفسه.'],
      limits: ['The Medinan label is one of the inputs, so the split by place is partly built in, not discovered. k-means favours compact groups of similar spread, and the few very long surahs pull hard on the standardized scale. The map is a projection: surahs close on it can differ in the 10% of the variance it leaves out.',
        'وسم المدني أحد المدخلات، فالتقسيم بحسب مكان النزول مبنيٌّ فيه جزئيًا لا مكتشَف. وk-means تفضّل مجموعاتٍ متراصّةً متقاربة الانتشار، والسور الطويلة القليلة تشدّ المقياس المعياري بقوة. والخريطة إسقاط: فالسور المتقاربة عليها قد تختلف في الـ١٠٪ من التباين التي تتركها.'] },

    coincidence: {
      purpose: ['Measure how easily a «meaningful» number is matched by some word\'s count: the base rate behind numerical claims.',
        'قياس سهولة أن يوافق رقمٌ «ذو دلالة» عددَ ورود كلمةٍ ما: المعدّل الأساسي الذي تقوم عليه المزاعم العددية.'],
      data: ['The frequencies of the 4,771 lemmas (76,572 words that carry a lemma).', 'تكرارات المداخل المعجمية الـ٤٬٧٧١ (٧٦٬٥٧٢ كلمةً تحمل مدخلًا).'],
      method: ['For each notable number n (7, 12, 19 … 365), count the lemmas that occur exactly n times, and within ±5 of n. It is a plain count over the real distribution, not a simulation, and no p-value is given: the distribution is heavy-tailed ([[zipf]]), and a fair null model would need a model of how the text was produced.',
        'لكل رقمٍ لافت n ‏(٧، ١٢، ١٩ … ٣٦٥) نعدّ المداخل التي ترد n مرةً تمامًا، والتي تقع في حدود ±٥ منه. إنه عدٌّ مباشر على التوزيع الحقيقي لا محاكاة، ولا تُعطى قيمةٌ احتمالية: فالتوزيع طويل الذيل ([[zipf|قانون زيبف]])، وفرضية عدمٍ منصفة تحتاج نموذجًا لكيفية نشوء النص.'],
      result: ['Exactly 7 times: 104 lemmas (2,126 within ±5); exactly 19: 14 (233 within ±5); exactly 88: 4; 365: none (1 within ±5). 41% of lemmas occur once and 82% fewer than 10 times, so small numbers are crowded and large ones rare.',
        '٧ مراتٍ تمامًا: ١٠٤ مداخل (٢٬١٢٦ في حدود ±٥)؛ و١٩ تمامًا: ١٤ (٢٣٣ في حدود ±٥)؛ و٨٨ تمامًا: ٤؛ و٣٦٥: لا شيء (واحدٌ في حدود ±٥). و٤١٪ من المداخل ترد مرةً واحدة و٨٢٪ أقل من ١٠ مرات، فالأرقام الصغيرة مزدحمة والكبيرة نادرة.'],
      also: ['Lower on the page, a [[montecarlo|Monte Carlo simulation]] of 1,000 memorisation journeys (seed 7): 9,060 lines; each day is missed with probability 0.15, otherwise `max(0, N(6.67, 2²))` new lines are learned. Days to finish: mean 1,600, [[percentile|P5–P95]] 1,565–1,633 (4.3–4.5 years).',
        'وفي أسفل الصفحة [[montecarlo|محاكاة مونت كارلو]] لألف رحلة حفظ (البذرة ٧): ٩٬٠٦٠ سطرًا؛ يفوت كلَّ يومٍ باحتمال ٠٫١٥، وإلا يُحفظ فيه `max(0, N(6.67, 2²))` سطرًا جديدًا. وأيام الختم: المتوسط ١٬٦٠٠، و[[percentile|المئين ٥–٩٥]] ‏١٬٥٦٥–١٬٦٣٣ (٤٫٣–٤٫٥ سنوات).'],
      limits: ['A match also depends on the counting rule (which forms, which spelling, which verses), which multiplies the chances ([[lookelsewhere]]). The landscape shows how common matches are; it does not test any one claim. In the simulation the band is narrow because independent day-to-day variation averages out over some 1,600 days; lasting changes of pace are not modelled.',
        'والتوافق يتوقف أيضًا على قاعدة العدّ (أيّ الصيغ، وأيّ رسم، وأيّ الآيات)، وهذا يضاعف الفرص ([[lookelsewhere|أثر البحث في كل مكان]]). فالمشهد يبيّن شيوع التوافقات ولا يختبر زعمًا بعينه. وفي المحاكاة يضيق النطاق لأن التفاوت اليومي المستقل يتلاشى على مدى ١٬٦٠٠ يومٍ تقريبًا، ولا يُنمذَج تغيّرٌ دائم في الوتيرة.'] },

    hifz: {
      purpose: ['Find the fastest daily memorisation plan that fits a time budget and keeps enough review.',
        'إيجاد أسرع خطة حفظٍ يومية تتسع لها الدقائق المتاحة مع مراجعةٍ كافية.'],
      data: ['9,060 lines (604 pages × 15 lines of the Madani mushaf). Assumed, not measured: 4 minutes to learn a new line, 0.5 minutes to review one, and at least 10 review lines for each new line.',
        '٩٬٠٦٠ سطرًا (٦٠٤ صفحات × ١٥ سطرًا في مصحف المدينة). ومفترَضٌ لا مَقيس: ٤ دقائق لحفظ السطر الجديد، ونصف دقيقة لمراجعة السطر، و١٠ أسطر مراجعةٍ على الأقل لكل سطرٍ جديد.'],
      method: ['[[lp|Linear programming]]: maximise N subject to `4N + 0.5R ≤ D`, `R ≥ 10N`, `N, R ≥ 0` (solved with HiGHS). The page re-solves in closed form as you move the slider: `N = D / (4 + 0.5·10) = D / 9`.',
        '[[lp|البرمجة الخطية]]: تعظيم N بشرط `4N + 0.5R ≤ D` و`R ≥ 10N` و`N, R ≥ 0` (بالحلّال HiGHS). وتعيد الصفحة الحلّ بصيغةٍ مغلقة كلما حرّكت المؤشر: `N = D / (4 + 0.5·10) = D / 9`'],
      result: ['At 60 minutes a day: 6.67 new and 66.7 review lines, 1,359 days (about 3.7 years). The [[shadow|shadow price]] of the time budget is 1/9 ≈ 0.111 new lines a day for each extra minute, the same at every budget because the model is linear.',
        'مع ٦٠ دقيقةً يوميًا: ٦٫٦٧ سطرًا جديدًا و٦٦٫٧ سطر مراجعة، و١٬٣٥٩ يومًا (نحو ٣٫٧ سنوات). و[[shadow|سعر الظل]] لقيد الوقت ١/٩ ≈ ٠٫١١١ سطرٍ جديدٍ يوميًا لكل دقيقةٍ زائدة، وهو ثابتٌ عند كل ميزانيةٍ لأن النموذج خطي.'],
      limits: ['The times and the review ratio are assumptions, and real memorising is not linear (fatigue, forgetting, harder pages). The Monte Carlo on the Coincidence page adds missed days and day-to-day variation.',
        'الأوقات ونسبة المراجعة افتراضات، والحفظ الحقيقي ليس خطيًا (التعب والنسيان وصعوبة بعض الصفحات). ومحاكاة مونت كارلو في صفحة المصادفات تضيف الأيام الفائتة والتفاوت اليومي.'] },

    dashboard: {
      purpose: ['Filter the surah table yourself and see the totals change.', 'رشِّح جدول السور بنفسك وشاهد المجاميع تتغيّر.'],
      data: ['The 114 surahs, with their verse and word counts and their Meccan or Medinan label.', 'السور الـ١١٤ بعدد آياتها وكلماتها ووسمها مكيةً أو مدنية.'],
      method: ['Filters by place and by a minimum number of verses. The totals, and words per verse as `total words ÷ total verses`, are recomputed from the surahs kept.',
        'ترشيحٌ بمكان النزول وبحدٍّ أدنى لعدد الآيات. وتُعاد المجاميع، والكلمات في الآية بوصفها `total words ÷ total verses`، من السور المُبقاة.'],
      result: ['All surahs: 6,236 verses, 77,429 words, 12.4 words a verse. Meccan only: 86 surahs, 10.3; Medinan only: 28 surahs, 18.5.',
        'كل السور: ٦٬٢٣٦ آية، و٧٧٬٤٢٩ كلمة، و١٢٫٤ كلمة في الآية. المكية وحدها: ٨٦ سورة و١٠٫٣؛ والمدنية وحدها: ٢٨ سورة و١٨٫٥.'],
      limits: ['Descriptive only: a difference you find by filtering is not tested here (see the Statistics page). The average is a ratio of totals, so long surahs weigh more; it is not the mean of the surahs\' own averages.',
        'وصفيٌّ فقط: الفرق الذي تجده بالترشيح لا يُختبر هنا (انظر صفحة الإحصاء). والمتوسط نسبةٌ بين مجموعين، فللسور الطويلة وزنٌ أكبر، وليس متوسطًا لمتوسطات السور.'] },

    emotion: {
      purpose: ['A rough profile of four themes (mercy, guidance, hope and warning) across the surahs.', 'صورةٌ تقريبية لأربعة معانٍ (الرحمة والهداية والأمل والتحذير) عبر السور.'],
      data: ['An English translation, verse by verse, prepared for the site\'s first version.', 'ترجمةٌ إنجليزية، آيةً آية، أُعدّت للنسخة الأولى من الموقع.'],
      method: ['[[lexicon|Word lists]]: each theme is a list of 17 to 20 English words (mercy: mercy, merciful, forgive, grace, peace…; warning: punishment, fire, hell, torment…; guidance: guide, path, truth, know, light, sign…; hope: paradise, garden, reward, glad, promise, good…). A verse scores the number of different list words it contains; scores are added up per surah.',
        '[[lexicon|قوائم كلمات]]: لكل معنى قائمةٌ من ١٧ إلى ٢٠ كلمةً إنجليزية (الرحمة: mercy وmerciful وforgive وgrace وpeace…؛ والتحذير: punishment وfire وhell وtorment…؛ والهداية: guide وpath وtruth وknow وlight وsign…؛ والأمل: paradise وgarden وreward وglad وpromise وgood…). ودرجة الآية عدد كلمات القائمة المختلفة التي فيها، وتُجمع الدرجات لكل سورة.'],
      result: ['Guidance 1,026, mercy 779, warning 710, hope 379.', 'الهداية ١٬٠٢٦، والرحمة ٧٧٩، والتحذير ٧١٠، والأمل ٣٧٩.'],
      limits: ['It depends on one translation and on the lists: no stemming («forgives» is missed), no negation, and common words (know, right, true, good) inflate some themes. The totals compare list hits, not meanings; read them as indicative.',
        'تتوقف النتائج على ترجمةٍ واحدة وعلى القوائم: فلا ردّ للكلمات إلى أصلها (تفوت «forgives»)، ولا مراعاة للنفي، وكلماتٌ شائعة (know وright وtrue وgood) تضخّم بعض المعاني. فالمجاميع تقارن مرات المطابقة لا المعاني، فاقرأها مؤشراتٍ تقريبية.'] },

    pronouns: {
      purpose: ['Count the forms in which God speaks or is spoken of: «We», «I» and «He».', 'عدّ الصيغ التي يتكلم بها الله أو يُتحدَّث بها عنه: «نحن» و«أنا» و«هو».'],
      data: ['«We» and «I»: the Arabic text of the site\'s first version, without vowel marks. «He»: the Quranic Arabic Corpus.',
        '«نحن» و«أنا»: النص العربي للنسخة الأولى من الموقع، بلا حركات. و«هو»: المدوّنة الصرفية للقرآن الكريم.'],
      method: ['Rules: «We» counts words that contain نحن or انا, or one of 16 first-person-plural verbs of divine action (أنزلنا، خلقنا، جعلنا، أرسلنا، أوحينا…); «I» counts words that are, or end in, إني or إنني; «He» counts every segment هو in the corpus.',
        'قواعد: «نحن» تعدّ الكلمات التي فيها «نحن» أو «انا»، أو أحد ١٦ فعلًا بصيغة المتكلمين في أفعال الله (أنزلنا، خلقنا، جعلنا، أرسلنا، أوحينا…)؛ و«أنا» تعدّ الكلمات التي هي «إني» أو «إنني» أو تنتهي بهما؛ و«هو» تعدّ كل مقطع «هو» في المدوّنة.'],
      result: ['«We» 681, «I» 167, «He» 481.', '«نحن» ٦٨١، و«أنا» ١٦٧، و«هو» ٤٨١.'],
      limits: ['These count forms, not references to God: people in the text also say «we» and «he». Without vowel marks, انا is both إنّا («indeed We») and أنا («I»), and it also matches inside other words; other first-person forms are missed. Read them as rough indicators.',
        'هذه أعداد صيغ لا إشاراتٍ إلى الله: ففي النص أناسٌ يقولون «نحن» و«هو» أيضًا. وبلا حركات تكون «انا» هي «إنّا» وهي «أنا»، وتطابق داخل كلماتٍ أخرى، وتفوت صيغٌ أخرى للمتكلم. فاقرأها مؤشراتٍ تقريبية.'] },

    science: {
      purpose: ['List verses often quoted when people discuss science and nature.', 'جمع آياتٍ يكثر الاستشهاد بها عند الحديث عن العلم والطبيعة.'],
      data: ['26 verses from 18 surahs, in 15 topics, chosen by hand for the site\'s first version.', '٢٦ آيةً من ١٨ سورة، في ١٥ موضوعًا، اختيرت يدويًا للنسخة الأولى من الموقع.'],
      method: ['A curated list, placed on the map of all verses in reading order. No statistics are computed.', 'قائمةٌ منتقاة، موضوعةٌ على خريطة الآيات كلها بترتيب القراءة. ولا تُحسب أي إحصاءات.'],
      limits: ['The selection reflects a popular way of reading these verses. Whether a verse anticipates a scientific finding is a matter of interpretation; the site does not test it.',
        'يعكس الانتقاء طريقةً شائعة في قراءة هذه الآيات. أما أن الآية تسبق كشفًا علميًا فمسألة تفسير، ولا يختبرها الموقع.'] },

    advanced: {
      purpose: ['See how the number of verses and the number of words relate across surahs.', 'رؤية العلاقة بين عدد الآيات وعدد الكلمات عبر السور.'],
      data: ['The 114 surahs.', 'السور الـ١١٤.'],
      method: ['A scatter plot on logarithmic axes, since both counts span two orders of magnitude (3 to 286 verses, 10 to 6,116 words).',
        'رسم انتشارٍ على محورين لوغاريتميين، لأن العددين يمتدان على مرتبتين عشريتين (من ٣ إلى ٢٨٦ آية، ومن ١٠ إلى ٦٬١١٦ كلمة).'],
      result: ['Strongly related: Pearson r = 0.88 on the counts, 0.92 on their logarithms. The log–log slope is 1.28: surahs with more verses also have longer verses. At the same number of verses, Medinan surahs sit higher.',
        'ارتباطٌ قوي: معامل بيرسون ٠٫٨٨ على الأعداد و٠٫٩٢ على لوغاريتماتها. وميل الخط اللوغاريتمي ١٫٢٨: فالسور الأكثر آياتٍ آياتها أطول أيضًا. وعند العدد نفسه من الآيات تقع السور المدنية أعلى.'],
      limits: ['A correlation across surahs, which differ in many ways at once; it describes, it does not explain.', 'ارتباطٌ عبر سورٍ تختلف في أمورٍ كثيرة معًا؛ فهو يصف ولا يفسّر.'] },

    search: {
      purpose: ['Find every verse where a word occurs.', 'إيجاد كل آيةٍ وردت فيها كلمة.'],
      data: ['The 77,429 words, each with its written form, [[lemma]] and [[root]].', 'الكلمات الـ٧٧٬٤٢٩، ولكلٍّ منها رسمها و[[lemma|مدخلها المعجمي]] و[[root|جذرها]].'],
      method: ['As written: the [[normalization|normalized]] query is found anywhere inside a word\'s normalized form. All forms: words whose lemma, without vowel marks, equals the query. Root: words whose root equals it.',
        'بالرسم: يُبحث عن النص [[normalization|الموحَّد الرسم]] في أي موضعٍ داخل رسم الكلمة الموحَّد. وبكل الصيغ: الكلمات التي يساوي مدخلها المعجمي، بلا حركات، نصَّ البحث. وبالجذر: الكلمات التي يساوي جذرها نصَّ البحث.'],
      limits: ['«As written» matches inside longer words, so short queries over-match. Without vowel marks, lemmas that share a spelling are found together (مَلَك angel, مُلْك dominion, مَلِك king); the hints under the box tell them apart.',
        '«بالرسم» يطابق داخل الكلمات الأطول، فالبحث القصير يطابق أكثر مما يُراد. وبلا حركات تُوجد المداخل المتفقة رسمًا معًا (مَلَك ومُلْك ومَلِك)، والتنبيهات تحت المربع تفصل بينها.'] },

    auditor: {
      purpose: ['Check popular numerical claims against the text.', 'التحقق من المزاعم العددية المتداولة بالرجوع إلى النص.'],
      data: ['The claims on this page; the Quranic Arabic Corpus.', 'المزاعم في هذه الصفحة؛ والمدوّنة الصرفية للقرآن الكريم.'],
      method: ['For each claim, the target [[lemma]] is the most frequent lemma whose unvowelled form matches the claimed word (this picks مَلَك, angel, over مُلْك, dominion). The count is every word with that lemma: singular, plural, with pronouns attached. Shown beside it: a narrower rule where a claim relies on one (such as the singular only), and a quick text search, to show how plain searching goes wrong.',
        'لكل زعمٍ يُختار [[lemma|المدخل المعجمي]] الأكثر ورودًا من المداخل التي يطابق رسمُها بلا حركات الكلمةَ المزعومة (فيُختار مَلَك لا مُلْك). والعدد كل كلمةٍ لها ذلك المدخل: مفردًا وجمعًا ومع الضمائر. وإلى جانبه قاعدةٌ أضيق حين يعتمد الزعم عليها (كالمفرد وحده)، وبحثٌ نصيٌّ سريع يبيّن كيف يخطئ البحث البسيط.'],
      result: ['Three claims hold exactly by lemma: angel 88, devil 88 and Hell 77. Others match only under a narrower rule, or not at all: يَوْم (day) is 475 in all forms and exactly 365 under the claim’s own singular rule.',
        'ثلاثة مزاعم تصحّ تمامًا بالمدخل المعجمي: الملائكة ٨٨، والشيطان ٨٨، وجهنم ٧٧. وغيرها لا يوافق إلا بقاعدةٍ أضيق أو لا يوافق أصلًا: «يَوْم» ٤٧٥ بكل صيغها، و٣٦٥ تمامًا بقاعدة المفرد التي يعدّ بها المزعم.'],
      limits: ['Every claim fixes its own way of counting, and a claim that holds under one convention and fails under another is not evidence either way. Borderline cases follow the corpus\'s tagging.',
        'كل زعمٍ يحدّد طريقته في العدّ، والزعم الذي يصحّ بطريقةٍ ويسقط بأخرى ليس دليلًا في أيّ الاتجاهين. والحالات الحدّية تتبع توسيم المدوّنة.'] },

    symmetry: {
      purpose: ['Test popular «balanced pairs»: two opposite words said to occur equally often.', 'اختبار «الأزواج المتوازنة» المتداولة: كلمتان متقابلتان يُقال إنهما وردتا بالعدد نفسه.'],
      method: ['Each word is counted as in the Claim Auditor (every form of its [[lemma]]); a pair is equal when the two counts match.', 'تُعَدّ كل كلمةٍ كما في مدقّق المزاعم (بكل صيغ [[lemma|مدخلها المعجمي]])، ويتساوى الزوج حين يتطابق العددان.'],
      result: ['Equal: angels and devils (88 each), Adam and Jesus (25 each). Not equal: man 29 against woman 26.',
        'متساوية: الملائكة والشياطين (٨٨ لكلٍّ منهما)، وآدم وعيسى (٢٥ لكلٍّ منهما). وغير متساوية: الرجل ٢٩ مقابل المرأة ٢٦.'],
      limits: ['With many candidate pairs and many ways of counting, some equal pairs are expected by chance (see the Coincidence page); only the pairs usually quoted are checked here.',
        'مع كثرة الأزواج الممكنة وطرق العدّ، يُتوقع تساوي بعضها مصادفةً (انظر صفحة المصادفات)، ولا يُفحص هنا إلا الأزواج المتداولة.'] },

    nlp: {
      purpose: ['Find the most frequent phrases.', 'إيجاد العبارات الأكثر ورودًا.'],
      data: ['[[normalization|Normalized]] written words, within each verse: a phrase never crosses from one verse into the next.', 'الكلمات المكتوبة بعد [[normalization|توحيد الرسم]]، داخل كل آية: فلا تعبر العبارة من آيةٍ إلى التي تليها.'],
      method: ['[[ngram|Bigram]] and trigram counts: every run of two or three neighbouring words. The cloud sizes the 40 commonest lemmas by the square root of their counts.',
        'عدّ [[ngram|الثنائيات]] والثلاثيات: كل تتابعٍ لكلمتين أو ثلاثٍ متجاورة. والسحابة تحجّم أكثر ٤٠ مدخلًا معجميًا بالجذر التربيعي لأعدادها.'],
      result: ['إن الله 257, الذين ءامنوا 184, في الارض 176, الذين كفروا 134, السموت والارض 133.', 'إن الله ٢٥٧، الذين ءامنوا ١٨٤، في الارض ١٧٦، الذين كفروا ١٣٤، السموت والارض ١٣٣.'],
      limits: ['Written forms, not lemmas: the same phrase with a prefix (والله, بالله) counts apart. These are raw frequencies, not association scores (such as PMI) that would discount phrases made of very common words.',
        'رسومٌ مكتوبة لا مداخل معجمية: فالعبارة نفسها مع سابقة («والله»، «بالله») تُعَدّ وحدها. وهذه تكراراتٌ خام لا مقاييس اقتران (مثل PMI) تُنقص وزن العبارات المؤلفة من كلماتٍ شائعةٍ جدًّا.'] },

    abjad: {
      purpose: ['Compute the abjad (ḥisāb al-jummal) value of a word.', 'حساب قيمة الكلمة بحساب الجُمَّل.'],
      method: ['Eastern (Mashriqi) abjad values, ا = 1 to غ = 1,000. Vowel marks are removed, أ إ آ ٱ count as ا (1), ى as ي (10) and ة as ه (5); ء ؤ ئ are not counted.',
        'قيم الجُمَّل المشرقية، من ا = ١ إلى غ = ١٬٠٠٠. تُحذف الحركات، وتُعَدّ أ إ آ ٱ ألفًا (١)، وى ياءً (١٠)، وة هاءً (٥)، ولا تُعَدّ ء ؤ ئ.'],
      limits: ['Conventions differ: the Maghribi order gives some letters other values, and ة and hamza are treated in several ways. A total is arithmetic, not evidence of meaning.',
        'الأعراف مختلفة: فالترتيب المغربي يعطي بعض الحروف قيمًا أخرى، وللتاء المربوطة والهمزة معاملاتٌ متعددة. والمجموع حسابٌ لا دليلٌ على معنى.'] },

    lettercount: {
      purpose: ['Show why the early letter counts of the Quran differ from each other and from a modern count, by counting one text under each rule.',
        'بيان سبب اختلاف الأعداد القديمة لحروف القرآن فيما بينها وعن العدّ الحديث، بعدّ نصٍّ واحد بكل قاعدة.'],
      data: ['The Quranic Arabic Corpus in Uthmani script: 325,665 letters (the letters of the Uthmani spelling; vowel marks, small signs and the tatweel left out), the count the Letters page uses. The early counts are from al-Qurtubi’s introduction to al-Jami li-Ahkam al-Quran.',
        'المدوّنة القرآنية العربية بالرسم العثماني: ٣٢٥٬٦٦٥ حرفًا (حروف الرسم العثماني، بلا حركاتٍ ولا علاماتٍ صغيرة ولا تطويل)، وهو العدد الذي تعتمده صفحة الحروف. والأعداد القديمة من مقدمة القرطبي في «الجامع لأحكام القرآن».'],
      method: ['Each word is read sign by sign. A written letter is one; under the rules, a shadda adds its letter again (22,678), a small alif not resting on ى adds an alif (6,652), the small waw and ya add a letter each (2,252), tanween adds a nun (8,893), the opening letters give way to their names (+135), and a standalone hamza ء is dropped (3,059). The Basmala adds 19 letters at 112 surah heads (2,128), and its own 3 doubled letters and small alif when those rules are on. The rules add exactly.',
        'تُقرأ كل كلمةٍ علامةً علامة. الحرف المكتوب واحد؛ وبالقواعد تضيف الشدّة حرفها مرةً ثانية (٢٢٬٦٧٨)، وتضيف الألف الصغيرة التي لا تقع على الياء ألفًا (٦٬٦٥٢)، وتضيف الواو والياء الصغيرتان حرفًا لكلٍّ منهما (٢٬٢٥٢)، ويضيف التنوين نونًا (٨٬٨٩٣)، وتحلّ أسماء الحروف المقطّعة محلّ رسمها (+١٣٥)، وتُحذف الهمزة المنفردة ء (٣٬٠٥٩). وتضيف البسملة ١٩ حرفًا في رأس ١١٢ سورة (٢٬١٢٨)، مع حروفها المشددة الثلاثة وألفها الصغيرة حين تُفعَّل تلك القواعد. والقواعد تُجمع جمعًا تامًّا.'],
      result: ['As printed 325,665; as first written (no hamza) 322,606, between Mujahid’s 321,180 and Ata’s 323,015; every letter read aloud 366,275. None of the 128 rule sets gives an early count exactly; the nearest are 274 from Ata’s and 202 from al-Himmani’s.',
        'كما في المصحف ٣٢٥٬٦٦٥؛ وكما كُتب أول مرة (بلا همزة) ٣٢٢٬٦٠٦، بين عدّ مجاهد ٣٢١٬١٨٠ وعدّ عطاء ٣٢٣٬٠١٥؛ وبكل حرفٍ يُقرأ ٣٦٦٬٢٧٥. ولا تعطي أيٌّ من مجموعات القواعد الـ١٢٨ عددًا قديمًا تمامًا، وأقربها على بُعد ٢٧٤ من عدّ عطاء و٢٠٢ من عدّ الحِمّاني.'],
      limits: ['The early counters’ rules and manuscripts are not known in detail, so a near fit shows how large each rule is, not how they counted. Pronunciation follows the Hafs reading as printed; assimilation (idgham) and the other recitation rules are not modelled.',
        'لا تُعرف قواعد العادّين الأوائل ولا مصاحفهم بالتفصيل، فالتوفيق القريب يدلّ على حجم أثر كل قاعدة لا على طريقتهم. والنطق هنا نطق رواية حفص كما في المصحف المطبوع، ولا يُحسب الإدغام ولا غيره من أحكام التلاوة.'] },

    wordcount: {
      purpose: ['Show why published word totals for the Quran differ, by counting one text under each rule people use.',
        'بيان سبب اختلاف الأعداد المنشورة لكلمات القرآن، بعدّ نصٍّ واحد بكل قاعدةٍ يعتمدها الناس.'],
      data: ['The Quranic Arabic Corpus morphology: 130,030 segments in 77,429 written words. The King Fahd Complex page layout of the Madinah mushaf (604 pages) gives the same 77,429 words in every one of the 6,236 verses. The figure 77,439 is from al-Qurtubi’s introduction to al-Jami li-Ahkam al-Quran, «in the saying of Ata ibn Yasar».',
        'المدوّنة الصرفية للقرآن الكريم (Quranic Arabic Corpus): ١٣٠٬٠٣٠ مقطعًا في ٧٧٬٤٢٩ كلمةً مكتوبة. ويعطي تخطيط صفحات مصحف المدينة من مجمّع الملك فهد (٦٠٤ صفحات) الكلمات الـ٧٧٬٤٢٩ نفسها في كل آيةٍ من الآيات الـ٦٬٢٣٦. أما ٧٧٬٤٣٩ فمن مقدمة القرطبي في «الجامع لأحكام القرآن»، «في قول عطاء بن يسار».'],
      method: ['Each rule is a class of corpus segments counted as words of their own: the joined vocative يا (361), the ها of attention before أنتم and هنا (8), the second noun of يبنؤم (1), two words written as one (562), joined particles (19,914), the article (8,377), attached pronouns (21,380, of them 208 understood but not written) and the other attached pieces (1,998). The classes do not overlap, so they add, and all of them together give the 130,030 segments. The Basmala adds 4 words at 112 surah heads (448); the opening letters can count as 30 words, as 78, or not at all.',
        'كل قاعدةٍ صنفٌ من مقاطع المدوّنة يُعدّ كلٌّ منها كلمةً مستقلة: «يا» الموصولة (٣٦١)، و«ها» التنبيه قبل أنتم وهنا (٨)، والاسم الثاني في يبنؤم (١)، والكلمتان المكتوبتان كلمةً واحدة (٥٦٢)، والحروف المتصلة (١٩٬٩١٤)، وأداة التعريف (٨٬٣٧٧)، والضمائر المتصلة (٢١٬٣٨٠، منها ٢٠٨ مقدّرة غير مكتوبة)، وسائر الأجزاء المتصلة (١٬٩٩٨). ولا تتداخل الأصناف، فتُجمع، ومجموعها كلها المقاطع الـ١٣٠٬٠٣٠. وتضيف البسملة ٤ كلماتٍ في رأس ١١٢ سورة (٤٤٨)، وتُعدّ الحروف المقطّعة ٣٠ كلمة، أو ٧٨، أو لا تُعدّ.'],
      result: ['As printed 77,429; in modern spelling 77,799; with every Basmala 77,877; every piece 130,030. None of the 1,536 combinations of these rules gives 77,439.',
        'كما في المصحف ٧٧٬٤٢٩، وبالإملاء الحديث ٧٧٬٧٩٩، ومع كل بسملة ٧٧٬٨٧٧، وبكل الأجزاء ١٣٠٬٠٣٠. ولا يعطي أيٌّ من التوافيق الـ١٬٥٣٦ لهذه القواعد ٧٧٬٤٣٩.'],
      limits: ['The rules behind 77,439 were not recorded, and it was counted on a hand-copied mushaf, so its 10-word difference cannot be traced word by word. The corpus’s segmentation is one linguistic analysis; another would split some words differently and move the larger totals.',
        'لم تُدوَّن قواعد عدّ ٧٧٬٤٣٩، وقد عُدّ على مصحفٍ منسوخٍ باليد، فلا يمكن تتبّع فرق الكلمات العشر كلمةً كلمة. وتقسيم المدوّنة تحليلٌ لغويٌّ واحد، وقد يقسم تحليلٌ آخر بعض الكلمات تقسيمًا مختلفًا فتتغير المجاميع الكبيرة.'] },

    n19: {
      purpose: ['Present the best-known claims that the number 19 structures the text (74:30).', 'عرض أشهر المزاعم بأن الرقم ١٩ يحكم بناء النص (المدثر: ٣٠).'],
      data: ['8 claims, with the arithmetic their sources give, collected for the site\'s first version.', '٨ مزاعم بالحساب الذي تذكره مصادرها، جُمعت للنسخة الأولى من الموقع.'],
      limits: ['Each claim fixes its own rule (which letters, whether the basmala counts, which spelling), chosen after looking at the text. Any count is a multiple of 19 about one time in 19 by chance, so with many rules and many counts some are bound to be ([[lookelsewhere]]).',
        'كل زعمٍ يحدّد قاعدته (أيّ الحروف، وهل تُعَدّ البسملة، وأيّ رسم)، وقد اختيرت بعد النظر في النص. وأيّ عددٍ يكون من مضاعفات ١٩ مصادفةً مرةً من كل ١٩ تقريبًا، فمع كثرة القواعد والأعداد لا بد أن يوافق بعضها ([[lookelsewhere|أثر البحث في كل مكان]]).'] },

    structural: {
      purpose: ['Record popular observations about how the text is arranged.', 'تسجيل ملاحظاتٍ متداولة عن ترتيب النص.'],
      method: ['Each one links a number in the text (a surah\'s position, a verse count, a word\'s position) to a fact outside it. None is tested.',
        'كلٌّ منها يربط رقمًا في النص (موضع سورة، أو عدد آيات، أو موضع كلمة) بحقيقةٍ خارجه. ولا يُختبر أيٌّ منها.'],
      limits: ['Chosen after the fact, from many possible numbers and facts ([[lookelsewhere]]). Check the outside facts too: iron\'s atomic number is 26 and its standard atomic weight 55.845; 57 is the mass number of one isotope, iron-57, about 2% of natural iron.',
        'اختيرت بعد وقوعها، من بين أرقامٍ وحقائق كثيرة ممكنة ([[lookelsewhere|أثر البحث في كل مكان]]). وتحقّق من الحقائق الخارجية أيضًا: العدد الذري للحديد ٢٦، ووزنه الذري المعياري ٥٥٫٨٤٥، أما ٥٧ فهو العدد الكتلي لأحد نظائره، الحديد-٥٧، ونسبته نحو ٢٪ من الحديد الطبيعي.'] },
  };

  const GLOSS = {
    pca: { name: ['PCA', 'تحليل المكوّنات الرئيسية'], full: ['Principal component analysis', 'تحليل المكوّنات الرئيسية (PCA)'], page: 'cluster',
      plain: ['A way to draw many measurements on a flat page. It finds the direction in which things differ most, then the next most at a right angle to it, and uses the two as the axes of a map, keeping as much of the differences as it can.',
        'طريقةٌ لرسم قياساتٍ كثيرة على صفحةٍ مسطّحة: تجد الاتجاه الذي تختلف فيه الأشياء أكثر ما تختلف، ثم الذي يليه عموديًا عليه، وتجعلهما محورَي خريطة، محتفظةً بأكبر قدرٍ من الفروق.'],
      here: ['Each surah has four measurements (verses, words, words per verse, Meccan or Medinan). PCA turns them into the two directions of the Clusters map.',
        'لكل سورةٍ أربعة قياسات (الآيات، والكلمات، والكلمات في الآية، ومكية أم مدنية)، ويحوّلها هذا التحليل إلى اتجاهَي خريطة العناقيد.'],
      found: ['Two directions keep 90% of the differences between surahs. The first (60%) is overall size: long surahs at one end, short ones at the other. The second (30%) sets Medinan surahs with long verses against surahs with many short verses.',
        'اتجاهان يحتفظان بـ٩٠٪ من الفروق بين السور. الأول (٦٠٪) هو الحجم العام: السور الطويلة في طرفٍ والقصيرة في الآخر. والثاني (٣٠٪) يقابل بين السور المدنية الطويلة الآيات والسور الكثيرة الآيات القصيرة.'],
      sci: ['Eigendecomposition of the correlation matrix of the standardized features (equivalently, SVD of the centred data). The components are its eigenvectors, each keeping `λᵢ / Σλ` of the variance: here 60.1, 29.9, 8.0 and 2.0%. Scores are `Z·vᵢ`; signs are arbitrary. Linear, and sensitive to scaling and outliers.',
        'تحليلٌ ذاتي لمصفوفة الارتباط بين الخصائص المقيَّسة (ويكافئ تحليل القيم المنفردة للبيانات المركَّزة). والمكوّنات متجهاتها الذاتية، ويحتفظ كلٌّ منها بنسبة `λᵢ / Σλ` من التباين: هنا ٦٠٫١ و٢٩٫٩ و٨٫٠ و٢٫٠٪. والدرجات `Z·vᵢ`، وإشاراتها اعتباطية. وهو خطيٌّ حسّاسٌ للمقياس وللقيم الشاذة.'] },
    kmeans: { name: ['k-means', 'k-means'], full: ['k-means clustering', 'التجميع بخوارزمية k-means'], page: 'cluster',
      plain: ['A way for a computer to sort things into k groups by itself: it places k centres, gives each item to its nearest centre, moves each centre to the middle of its group, and repeats until nothing changes.',
        'طريقةٌ يقسم بها الحاسوب الأشياء إلى k مجموعاتٍ وحده: يضع k مراكز، ويضمّ كل عنصرٍ إلى أقرب مركز، ثم ينقل كل مركزٍ إلى وسط مجموعته، ويكرر حتى لا يتغير شيء.'],
      here: ['It sorts the 114 surahs into 4 groups by their four measurements.', 'تقسم السور الـ١١٤ إلى ٤ مجموعاتٍ بحسب قياساتها الأربعة.'],
      found: ['Four groups: 53 short Meccan surahs, 31 middle-length Meccan ones, 23 Medinan ones, and 7 very long surahs (5 of them Medinan).',
        'أربع مجموعات: ٥٣ سورةً مكيةً قصيرة، و٣١ مكيةً متوسطة، و٢٣ مدنية، و٧ سورٍ طويلةٍ جدًّا (٥ منها مدنية).'],
      sci: ['Minimizes the within-cluster sum of squared Euclidean distances (Lloyd\'s algorithm, k-means++ starts; the best of 10, seed 42) on standardized features. K = 4 was set in advance; of K = 2 to 8 it also has the highest mean silhouette (0.55). Assumes roughly round clusters of similar spread.',
        'تقلّل مجموع مربعات المسافات الإقليدية داخل العناقيد (خوارزمية لويد ببدايات k-means++، وأفضل عشر محاولات، البذرة ٤٢) على خصائص مقيَّسة. وقد حُدّد `K = 4` مسبقًا، وهو أيضًا صاحب أعلى متوسطٍ لمعامل الصورة الظلية (٠٫٥٥) بين `K = 2` و٨. وتفترض عناقيد مستديرةً تقريبًا متقاربة الانتشار.'] },
    zscore: { name: ['standardized', 'التقييس'], full: ['Standard score (z-score)', 'الدرجة المعيارية (التقييس)'], page: 'cluster',
      plain: ['Putting measurements on the same scale: take away the average, then divide by the typical spread. 0 means average; +1 means one «typical step» above it.',
        'وضع القياسات على مقياسٍ واحد: نطرح المتوسط ثم نقسم على الانتشار المعتاد. فالصفر يعني المتوسط، و+١ يعني «خطوةً معتادة» فوقه.'],
      here: ['Verses (3 to 286), words (10 to 6,116) and words per verse are on very different scales; standardizing stops the biggest numbers from ruling the map and the groups.',
        'الآيات (٣ إلى ٢٨٦) والكلمات (١٠ إلى ٦٬١١٦) والكلمات في الآية على مقاييس مختلفةٍ جدًّا، والتقييس يمنع أكبر الأرقام من أن تتحكم في الخريطة والمجموعات.'],
      found: ['Al-Baqarah is 4.4 steps above average in verses and 5.9 in words, so the long surahs sit far out on the map.', 'البقرة فوق المتوسط بـ٤٫٤ خطوات في الآيات و٥٫٩ في الكلمات، ولذا تقع السور الطويلة بعيدًا على الخريطة.'],
      sci: ['`z = (x − x̄) / s`, with the population standard deviation (scikit-learn\'s StandardScaler). After it, PCA of the covariance matrix is PCA of the correlation matrix.',
        '`z = (x − x̄) / s` بالانحراف المعياري للمجتمع (StandardScaler في scikit-learn). وبعده يكون تحليل مصفوفة التغاير هو تحليل مصفوفة الارتباط.'] },
    logreg: { name: ['logistic regression', 'الانحدار اللوجستي'], full: ['Logistic regression', 'الانحدار اللوجستي'], page: 'classifier',
      plain: ['A model that turns evidence into a probability. Each word gets a weight; the weights of a surah\'s words are added up and turned into a chance, between 0 and 1, that the surah is Medinan.',
        'نموذجٌ يحوّل القرائن إلى احتمال: لكل كلمةٍ وزن، وتُجمع أوزان كلمات السورة وتتحول إلى احتمالٍ بين ٠ و١ أن تكون السورة مدنية.'],
      here: ['It reads each surah\'s words and says how likely the surah is to be Medinan; above 50% counts as a Medinan guess.', 'يقرأ كلمات كل سورة ويقدّر احتمال أن تكون مدنية، وما فوق ٥٠٪ يُعَدّ تخمينًا بأنها مدنية.'],
      found: ['It is right for 97 of the 114 surahs without seeing their labels. The strongest Medinan word is اللَّه (Allah); the strongest Meccan word is قالَ (he said).',
        'يصيب في ٩٧ من ١١٤ سورةً دون أن يرى وسمها. وأقوى كلمةٍ تدل على المدني «اللَّه»، وأقوى كلمةٍ تدل على المكي «قالَ».'],
      sci: ['`P(Medinan) = 1 / (1 + e^−(b₀ + w·x))`, fitted by maximum likelihood with an L2 penalty (C = 1, lbfgs). The weights act on TF-IDF features, so compare them by sign and rough size only.',
        '`P(Medinan) = 1 / (1 + e^−(b₀ + w·x))`، يُقدَّر بالإمكان الأعظم مع عقوبة L2 ‏(`C = 1`، lbfgs). والأوزان تعمل على خصائص TF-IDF، فقارنها بإشارتها ومقدارها التقريبي فقط.'] },
    tfidf: { name: ['TF-IDF', 'TF-IDF'], full: ['TF-IDF (term frequency × inverse document frequency)', 'TF-IDF (تكرار الكلمة × ندرتها في الوثائق)'], page: 'classifier',
      plain: ['A score for how characteristic a word is of a text: used often in it, but rarely in the others. Words that are common everywhere, like و, get little weight.',
        'درجةٌ تقيس مدى تميّز الكلمة لنصٍّ ما: كثيرة الورود فيه، نادرةٌ في غيره. والكلمات الشائعة في كل مكان، مثل «و»، تنال وزنًا ضئيلًا.'],
      here: ['Each surah becomes a list of 2,587 such scores, one for each word found in at least two surahs; the classifier and the similarity list use them.',
        'تصير كل سورةٍ قائمةً من ٢٬٥٨٧ درجة، واحدةٌ لكل كلمةٍ وردت في سورتين على الأقل، ويستعملها المصنِّف وقائمة التشابه.'],
      found: ['By these scores Al-Baqarah\'s closest surah is Aal-Imran (0.92), and for 100 of the 114 surahs the closest one has the same Meccan or Medinan label.',
        'بهذه الدرجات أقرب السور إلى البقرة آل عمران (٠٫٩٢)، ولـ١٠٠ من ١١٤ سورة تشترك أقرب سورةٍ إليها معها في الوسم مكيةً أو مدنية.'],
      sci: ['`tf · idf` with the smoothed `idf = ln((1 + n) / (1 + df)) + 1`, each row scaled to unit L2 length. The tokens are the words\' lemmas, with min_df = 2: 2,587 features from 4,771 lemmas.',
        '`tf · idf` مع `idf = ln((1 + n) / (1 + df)) + 1` الممهّد، ويُطبَّع كل صفٍّ إلى طول L2 يساوي ١. والوحدات هي المداخل المعجمية للكلمات مع `min_df = 2`: ‏٢٬٥٨٧ خاصيةً من ٤٬٧٧١ مدخلًا.'] },
    cv: { name: ['cross-validation', 'التحقق المتقاطع'], full: ['Cross-validation', 'التحقق المتقاطع'], page: 'classifier',
      plain: ['A fair test: hide some of the answers, let the model learn from the rest, check it on the hidden ones, and repeat until every item has been hidden once.',
        'اختبارٌ منصف: نُخفي بعض الأجوبة، ونترك النموذج يتعلم من الباقي، ثم نختبره على المخفي، ونكرر حتى يُخفى كل عنصرٍ مرة.'],
      here: ['The surahs are split into 5 parts; each part is predicted by a model trained on the other 4, so no surah is judged by a model that saw its label.',
        'تُقسم السور إلى ٥ أجزاء، ويُتنبّأ بكل جزءٍ بنموذجٍ دُرِّب على الأربعة الأخرى، فلا تُحكم سورةٌ بنموذجٍ رأى وسمها.'],
      found: ['Tested this way, the classifier is right for 85% of the surahs.', 'باختباره هكذا يصيب المصنِّف في ٨٥٪ من السور.'],
      sci: ['Stratified 5-fold (each fold keeps the class proportions), shuffled with seed 42. The out-of-fold probabilities from cross_val_predict are pooled for the accuracy, the AUC and the confusion matrix.',
        'خمس طيّاتٍ طبقية (تحفظ كل طيّةٍ نسب الفئتين)، مخلوطةٌ بالبذرة ٤٢. وتُجمع الاحتمالات خارج الطيّة من cross_val_predict لحساب الدقة والمساحة تحت المنحنى ومصفوفة الالتباس.'] },
    baseline: { name: ['baseline', 'خط الأساس'], full: ['Baseline (majority class)', 'خط الأساس (الفئة الغالبة)'], page: 'classifier',
      plain: ['The score you would get without any model: always guess the most common answer.', 'الدرجة التي تنالها بلا نموذج: أن تخمّن دائمًا الجواب الأكثر شيوعًا.'],
      here: ['75% of surahs are Meccan, so always saying «Meccan» is right 75% of the time. A model has to beat that to have learned anything.',
        '٧٥٪ من السور مكية، فقول «مكية» دائمًا يصيب في ٧٥٪ من المرات. وعلى النموذج أن يتجاوز ذلك ليكون قد تعلّم شيئًا.'],
      found: ['The classifier gets 85%, 10 points above it.', 'يبلغ المصنِّف ٨٥٪، أي فوقه بعشر نقاط.'],
      sci: ['Majority-class accuracy, `max(p, 1 − p)` = 86/114 = 0.754. Under class imbalance accuracy alone misleads; see the AUC and the confusion matrix.',
        'دقة الفئة الغالبة `max(p, 1 − p) = 86/114 = 0.754`. ومع عدم توازن الفئتين تُضلّل الدقة وحدها؛ فانظر المساحة تحت المنحنى ومصفوفة الالتباس.'] },
    auc: { name: ['AUC', 'المساحة تحت المنحنى'], full: ['AUC (area under the ROC curve)', 'المساحة تحت منحنى ROC (AUC)'], page: 'classifier',
      plain: ['How well a model ranks. Pick one Medinan and one Meccan surah at random: AUC is the chance that the model rates the Medinan one as more Medinan. 0.5 is guessing, 1 is perfect.',
        'مقياسٌ لجودة الترتيب: اختر سورةً مدنيةً وأخرى مكيةً عشوائيًا، فالمساحة هي احتمال أن يرى النموذج المدنية أقرب إلى المدني. ٠٫٥ تخمين، و١ إصابةٌ تامة.'],
      here: ['It measures the classifier\'s ranking, whatever cut-off is then used to make a guess.', 'تقيس ترتيب المصنِّف أيًّا كانت العتبة التي يُخمَّن بها بعد ذلك.'],
      found: ['0.92: in 92% of such pairs the Medinan surah gets the higher score.', '٠٫٩٢: في ٩٢٪ من هذه الأزواج تنال السورة المدنية الدرجة الأعلى.'],
      sci: ['The area under the ROC curve (true-positive rate against false-positive rate over all thresholds), equal to the Mann–Whitney U divided by `n₁·n₀`. It does not depend on the threshold or on the class balance.',
        'المساحة تحت منحنى ROC (معدل الإيجابيات الصحيحة مقابل معدل الإيجابيات الكاذبة عبر كل العتبات)، وتساوي إحصاءة مان–ويتني U مقسومةً على `n₁·n₀`، ولا تتوقف على العتبة ولا على توازن الفئتين.'] },
    confusion: { name: ['confusion matrix', 'مصفوفة الالتباس'], full: ['Confusion matrix', 'مصفوفة الالتباس'], page: 'classifier',
      plain: ['A 2 × 2 table of right and wrong guesses: what the answer really was, against what the model said.', 'جدولٌ ٢ × ٢ للإصابات والأخطاء: الجواب الحقيقي مقابل ما قاله النموذج.'],
      here: ['Rows: really Meccan, really Medinan. Columns: guessed Meccan, guessed Medinan.', 'الصفوف: مكية فعلًا ومدنية فعلًا. والأعمدة: خُمِّنت مكية وخُمِّنت مدنية.'],
      found: ['All 86 Meccan surahs right; 11 of the 28 Medinan right and 17 taken for Meccan. No Meccan surah was called Medinan.', 'السور المكية الـ٨٦ كلها صحيحة، و١١ من ٢٨ مدنية صحيحة و١٧ ظُنّت مكية. ولم تُعَدّ أي سورةٍ مكيةٍ مدنية.'],
      sci: ['TN 86, FP 0, FN 17, TP 11 (Medinan as positive): recall 0.39, precision 1.00, specificity 1.00. The errors fall on one side because a 0.5 threshold is cautious when one class is rare.',
        'TN ٨٦، وFP ٠، وFN ١٧، وTP ١١ (المدني هو الموجب): الاستدعاء ٠٫٣٩، والدقة الموجبة ١٫٠٠، والنوعية ١٫٠٠. وتقع الأخطاء في جهةٍ واحدة لأن عتبة ٠٫٥ حذرةٌ حين تندر إحدى الفئتين.'] },
    ttest: { name: ['t-test', 'اختبار t'], full: ['Welch\'s t-test', 'اختبار t لويلش'], page: 'stats',
      plain: ['A check of whether the gap between two groups\' averages is bigger than chance would easily produce, given how much the values vary inside each group.',
        'فحصٌ لما إذا كان الفرق بين متوسطَي مجموعتين أكبر مما تُنتجه المصادفة بسهولة، بالنظر إلى تفاوت القيم داخل كل مجموعة.'],
      here: ['It compares the average length of Medinan verses with that of Meccan verses.', 'يقارن متوسط طول الآيات المدنية بمتوسط طول المكية.'],
      found: ['The gap, 8.2 words, is 26 times its standard error: far beyond chance.', 'الفرق، ٨٫٢ كلمة، يبلغ ٢٦ ضعف خطئه المعياري: أبعد بكثيرٍ من المصادفة.'],
      sci: ['`t = (x̄₁ − x̄₂) / √(s₁²/n₁ + s₂²/n₂)`, with Welch–Satterthwaite degrees of freedom (2,089.6). It does not assume equal variances, but it does assume independent observations.',
        '`t = (x̄₁ − x̄₂) / √(s₁²/n₁ + s₂²/n₂)` بدرجات حرية ويلش–ساترثوايت (٢٬٠٨٩٫٦). لا يفترض تساوي التباينين، لكنه يفترض استقلال المشاهدات.'] },
    pvalue: { name: ['p-value', 'القيمة الاحتمالية'], full: ['p-value', 'القيمة الاحتمالية (p)'], page: 'stats',
      plain: ['If there were really no difference, how often would a gap at least this big turn up by chance? That chance is the p-value: the smaller it is, the harder the gap is to put down to luck.',
        'لو لم يكن هناك فرقٌ حقيقي، فكم مرةً يظهر فرقٌ بهذا الحجم أو أكبر مصادفة؟ هذا الاحتمال هو القيمة الاحتمالية: كلما صغرت صعُب ردّ الفرق إلى الحظ.'],
      here: ['For verse length p is about 7.5 × 10⁻¹³³: in practice, zero.', 'في طول الآيات تبلغ نحو `7.5 × 10⁻¹³³`: أي صفرًا عمليًا.'],
      found: ['The difference in length between Meccan and Medinan verses is not luck.', 'فالفرق في الطول بين الآيات المكية والمدنية ليس حظًّا.'],
      sci: ['`P(|T| ≥ |t| | H₀)` under the null hypothesis of equal means. It is not the probability that H₀ is true, and it does not measure size (see the effect size and the interval): with thousands of verses even a small gap gives a tiny p.',
        '`P(|T| ≥ |t| | H₀)` تحت فرضية العدم بتساوي المتوسطين. وليست احتمال صحة فرضية العدم، ولا تقيس الحجم (انظر حجم الأثر والفترة): فمع آلاف الآيات يعطي الفرق الصغير قيمةً ضئيلة.'] },
    ci: { name: ['confidence interval', 'فترة الثقة'], full: ['Confidence interval', 'فترة الثقة'], page: 'stats',
      plain: ['A range of believable values for the true difference, rather than a single number.', 'مدى من القيم المعقولة للفرق الحقيقي بدل رقمٍ واحد.'],
      here: ['Medinan verses are longer by 7.6 to 8.8 words (a 95% interval).', 'الآيات المدنية أطول بـ٧٫٦ إلى ٨٫٨ كلمات (فترة ٩٥٪).'],
      found: ['The whole range is far from zero, so the difference is real, and large.', 'المدى كله بعيدٌ عن الصفر، فالفرق حقيقيٌّ وكبير.'],
      sci: ['`(x̄₁ − x̄₂) ± t₀.₉₇₅,df · SE`. Under the model\'s assumptions, 95% of intervals built this way contain the true difference.', '`(x̄₁ − x̄₂) ± t₀.₉₇₅,df · SE`. وتحت افتراضات النموذج، تحوي ٩٥٪ من الفترات المبنية هكذا الفرقَ الحقيقي.'] },
    effect: { name: ['effect size', 'حجم الأثر'], full: ['Effect size (Cohen\'s d)', 'حجم الأثر (d لكوهين)'], page: 'stats',
      plain: ['How big a difference is, in units of the usual spread, rather than whether it is «significant».', 'مقدار الفرق بوحدات الانتشار المعتاد، لا مجرد كونه «دالًّا».'],
      here: ['The gap in verse length between Medinan and Meccan verses.', 'الفرق في طول الآية بين المدني والمكي.'],
      found: ['d ≈ 0.94: a large difference (0.8 and above is usually called large).', '`d ≈ 0.94`: فرقٌ كبير (يُعَدّ ٠٫٨ فما فوق كبيرًا عادةً).'],
      sci: ['Cohen\'s `d = (x̄₁ − x̄₂) / s_pooled` = 8.19 / 8.70.', 'حجم الأثر لكوهين: `d = (x̄₁ − x̄₂) / s_pooled = 8.19 / 8.70`'] },
    ols: { name: ['linear regression', 'الانحدار الخطي'], full: ['Linear regression (least squares)', 'الانحدار الخطي (المربعات الصغرى)'], page: 'stats',
      plain: ['Fits a straight-line rule that predicts one number from several others, and says how much each one adds when the others are held fixed.',
        'يطابق قاعدةً خطيةً تتنبأ برقمٍ من أرقامٍ أخرى، ويبيّن كم يضيف كلٌّ منها مع تثبيت البقية.'],
      here: ['It predicts a verse\'s length from its surah\'s number, whether the surah is Medinan, and the verse\'s number.', 'يتنبأ بطول الآية من رقم سورتها، وكونها مدنية، ورقم الآية.'],
      found: ['Being Medinan adds about 6 words even with the other two held fixed. The model explains 27% of the variation in verse length (R² = 0.27).',
        'كون السورة مدنيةً يضيف نحو ٦ كلمات حتى مع تثبيت الأمرين الآخرين. ويفسّر النموذج ٢٧٪ من التفاوت في طول الآيات (`R² = 0.27`).'],
      sci: ['Ordinary least squares: `ŷ = 15.70 − 0.134·surah + 5.93·Medinan − 0.006·verse`, `R² = 1 − SSres / SStot = 0.267`, n = 6,236.',
        'المربعات الصغرى العادية: `ŷ = 15.70 − 0.134·surah + 5.93·Medinan − 0.006·verse` و`R² = 1 − SSres / SStot = 0.267` و`n = 6,236`'] },
    montecarlo: { name: ['Monte Carlo', 'مونت كارلو'], full: ['Monte Carlo simulation', 'محاكاة مونت كارلو'], page: 'coincidence',
      plain: ['Instead of solving a hard question with a formula, let the computer play it out many times with chance built in, and look at the spread of the results.',
        'بدل حلّ مسألةٍ صعبة بمعادلة، نترك الحاسوب يمثّلها مراتٍ كثيرة مع عنصر المصادفة، ثم ننظر في انتشار النتائج.'],
      here: ['1,000 imaginary memorisation journeys, each with good days, bad days and missed days.', 'ألف رحلة حفظٍ افتراضية، في كلٍّ منها أيامٌ جيدة وأيامٌ ضعيفة وأيامٌ فائتة.'],
      found: ['Half finish within 1,600 days (4.4 years), and 90% between 1,565 and 1,633 days.', 'نصفها يختم في ١٬٦٠٠ يوم (٤٫٤ سنوات)، و٩٠٪ منها بين ١٬٥٦٥ و١٬٦٣٣ يومًا.'],
      sci: ['1,000 trials, seed 7: each day is missed with p = 0.15, otherwise `max(0, N(6.67, 2²))` new lines; stop at 9,060. Reported: P5, P50 and P95 of the days to finish.',
        'ألف محاولة بالبذرة ٧: يفوت كل يومٍ باحتمال ٠٫١٥، وإلا يُحفظ `max(0, N(6.67, 2²))` سطرًا، حتى ٩٬٠٦٠. وتُذكر المئينات ٥ و٥٠ و٩٥ لأيام الختم.'] },
    percentile: { name: ['percentile', 'المئين'], full: ['Percentile (P5, P50, P95)', 'المئين (٥، ٥٠، ٩٥)'], page: 'coincidence',
      plain: ['P95 is the value that 95% of the results fall below; P50 is the middle one (the median).', 'المئين ٩٥ هو القيمة التي تقع دونها ٩٥٪ من النتائج، والمئين ٥٠ هو الوسط (الوسيط).'],
      here: ['Used for the number of days a simulated journey takes to finish.', 'يُستعمل لعدد الأيام التي تستغرقها رحلة الحفظ المحاكاة.'],
      found: ['P5 1,565 days, P50 1,600, P95 1,633.', 'المئين ٥: ١٬٥٦٥ يومًا، و٥٠: ١٬٦٠٠، و٩٥: ١٬٦٣٣.'],
      sci: ['Empirical quantiles of the simulated distribution (linear interpolation, NumPy\'s default).', 'مئيناتٌ تجريبية للتوزيع المحاكى (بالاستكمال الخطي، الافتراضي في NumPy).'] },
    lookelsewhere: { name: ['look-elsewhere effect', 'أثر البحث في كل مكان'], full: ['The look-elsewhere effect (multiple comparisons)', 'أثر البحث في كل مكان (تعدّد المقارنات)'], page: 'coincidence',
      plain: ['Look in enough places and something surprising turns up somewhere by chance. A match found after trying many numbers, words and ways of counting is much weaker evidence than it seems.',
        'إن بحثت في أماكن كثيرة بما يكفي ظهر شيءٌ لافتٌ في مكانٍ ما مصادفة. فالتوافق الذي يُعثر عليه بعد تجريب أرقامٍ وكلماتٍ وطرق عدٍّ كثيرة دليلٌ أضعف بكثيرٍ مما يبدو.'],
      here: ['A numerical claim picks a word, a way of counting it and a number to match: many choices, so some matches are bound to appear.', 'الزعم العددي يختار كلمةً وطريقةً لعدّها ورقمًا يوافقه: اختياراتٌ كثيرة، فلا بد أن تظهر توافقات.'],
      found: ['14 different words occur exactly 19 times in the Quran, and 104 occur exactly 7 times.', '١٤ كلمةً مختلفة ترد في القرآن ١٩ مرةً تمامًا، و١٠٤ كلماتٍ ترد ٧ مراتٍ تمامًا.'],
      sci: ['The multiple-comparisons problem: with m independent chances at level α, the chance of at least one hit is `1 − (1 − α)^m`. A pattern chosen after seeing the data cannot be tested on the same data.',
        'مشكلة المقارنات المتعددة: مع m فرصةٍ مستقلة عند المستوى α يكون احتمال إصابةٍ واحدةٍ على الأقل `1 − (1 − α)^m`. والنمط المختار بعد رؤية البيانات لا يُختبر بالبيانات نفسها.'] },
    zipf: { name: ['Zipf\'s law', 'قانون زيبف'], full: ['Zipf\'s law', 'قانون زيبف'], page: 'word',
      plain: ['In any long text a few words are very common and most are rare: the second commonest word comes about half as often as the first, the third about a third as often, and so on.',
        'في كل نصٍّ طويل قليلٌ من الكلمات شائعٌ جدًّا وأكثرها نادر: الكلمة الثانية شيوعًا ترد نحو نصف ما ترد الأولى، والثالثة نحو ثلثها، وهكذا.'],
      here: ['It explains why a small count (like 7) is shared by many words and a large one (like 365) by very few.', 'يفسّر لماذا يشترك في العدد الصغير (مثل ٧) كلماتٌ كثيرة، وفي الكبير (مثل ٣٦٥) قليلٌ جدًّا.'],
      found: ['Among the Quran\'s 4,771 different words, the 10 commonest cover 25% of the text, and 41% occur only once.', 'من كلمات القرآن المختلفة الـ٤٬٧٧١، أكثر ١٠ كلماتٍ شيوعًا تغطي ٢٥٪ من النص، و٤١٪ منها لا ترد إلا مرةً واحدة.'],
      sci: ['`frequency ∝ rank^−s`. A least-squares fit on log–log axes, ranks 1 to 1,000 of the lemma frequencies, gives s ≈ 1.1.', '`frequency ∝ rank^−s`. ومطابقةٌ بالمربعات الصغرى على محورين لوغاريتميين، للرتب من ١ إلى ١٬٠٠٠ من تكرارات المداخل، تعطي `s ≈ 1.1`'] },
    lp: { name: ['linear programming', 'البرمجة الخطية'], full: ['Linear programming', 'البرمجة الخطية'], page: 'hifz',
      plain: ['A method for the best plan under limits: say what you want most, write the limits down as simple rules, and it finds the best plan that keeps all of them.',
        'طريقةٌ لأفضل خطةٍ ضمن قيود: تحدد ما تريده أكثر، وتكتب القيود قواعد بسيطة، فتجد أفضل خطةٍ تلتزم بها كلها.'],
      here: ['Goal: as many new lines a day as possible. Limits: your minutes a day, and enough review for each new line.', 'الهدف: أكبر عددٍ من الأسطر الجديدة يوميًا. والقيود: دقائقك في اليوم، ومراجعةٌ كافية لكل سطرٍ جديد.'],
      found: ['With 60 minutes a day: 6.7 new lines and 67 review lines, about 3.7 years to finish.', 'مع ٦٠ دقيقةً يوميًا: ٦٫٧ أسطر جديدة و٦٧ سطر مراجعة، ونحو ٣٫٧ سنوات للختم.'],
      sci: ['`max N  s.t.  4N + 0.5R ≤ D,  R ≥ 10N,  N, R ≥ 0` (HiGHS). The optimum is the vertex where both constraints bind: `N = D / 9`.', '`max N  s.t.  4N + 0.5R ≤ D,  R ≥ 10N,  N, R ≥ 0` ‏(HiGHS). والأمثل عند الرأس الذي يتحقق فيه القيدان معًا: `N = D / 9`'] },
    shadow: { name: ['shadow price', 'سعر الظل'], full: ['Shadow price', 'سعر الظل'], page: 'hifz',
      plain: ['How much better the best plan gets if one limit is loosened by one unit.', 'كم تتحسّن أفضل خطةٍ لو خُفِّف أحد القيود بوحدةٍ واحدة.'],
      here: ['What one more minute a day is worth, in new lines a day.', 'قيمة دقيقةٍ إضافية في اليوم، بالأسطر الجديدة يوميًا.'],
      found: ['0.11 new lines a day per extra minute: 9 extra minutes buy one more new line a day.', '٠٫١١ سطرٍ جديدٍ يوميًا لكل دقيقةٍ زائدة: فكل ٩ دقائق إضافية تشتري سطرًا جديدًا في اليوم.'],
      sci: ['The dual value (Lagrange multiplier) of the time constraint: `∂N*/∂D = 1 / (t_new + ρ·t_rev) = 1/9`, the same at every budget because the problem is linear.', 'القيمة الثنائية (مضروب لاغرانج) لقيد الوقت: `∂N*/∂D = 1 / (t_new + ρ·t_rev) = 1/9`، وهي ثابتةٌ عند كل ميزانية لأن المسألة خطية.'] },
    lemma: { name: ['lemma', 'المدخل المعجمي'], full: ['Lemma', 'المدخل المعجمي (lemma)'], page: 'word',
      plain: ['A word\'s dictionary form. يقول (he says), قالوا (they said) and قال (he said) share the lemma قالَ, so counting by lemma counts a word in all its forms.',
        'صورة الكلمة في المعجم: «يقول» و«قالوا» و«قال» مدخلها «قالَ»، فالعدّ بالمدخل يعدّ الكلمة بكل صيغها.'],
      here: ['The word counts, the word rankings and the Claim Auditor all count lemmas.', 'أعداد الكلمات وترتيبها ومدقّق المزاعم كلها تعدّ المداخل.'],
      found: ['77,429 words, 4,771 lemmas.', '٧٧٬٤٢٩ كلمة، و٤٬٧٧١ مدخلًا معجميًا.'],
      sci: ['From the Quranic Arabic Corpus annotation (its LEM feature); each written word takes the lemma of its stem segment. Lemmas keep their vowel marks, which keeps homographs apart: مَلَك (angel), مُلْك (dominion), مَلِك (king).',
        'من توسيم المدوّنة الصرفية (خاصية LEM)، وتأخذ كل كلمةٍ مكتوبة مدخل مقطعها الجذعي. وتحتفظ المداخل بحركاتها، فتبقى الكلمات المتفقة رسمًا منفصلة: مَلَك ومُلْك ومَلِك.'] },
    root: { name: ['root', 'الجذر'], full: ['Root', 'الجذر'], page: 'search',
      plain: ['The three (sometimes four) consonants a family of words grows from: ك ت ب gives كتاب (book), كاتب (writer), مكتوب (written).',
        'الحروف الثلاثة (وأحيانًا الأربعة) التي تتفرع منها أسرةٌ من الكلمات: ك ت ب تعطي كتاب وكاتب ومكتوب.'],
      here: ['The search can find every word that comes from one root.', 'يستطيع البحث إيجاد كل كلمةٍ من جذرٍ واحد.'],
      found: ['1,651 roots; 50,268 words carry one (most of the rest are particles and pronouns).', '١٬٦٥١ جذرًا، وتحمل جذرًا ٥٠٬٢٦٨ كلمة (وأكثر البقية أدواتٌ وضمائر).'],
      sci: ['The corpus\'s ROOT feature on the stem segment. Words without a root (particles, many pronouns, some proper nouns) are not counted.', 'خاصية ROOT في المقطع الجذعي من المدوّنة. ولا تُعَدّ الكلمات التي لا جذر لها (الأدوات، وكثيرٌ من الضمائر، وبعض الأعلام).'] },
    hapax: { name: ['hapax', 'كلمات فريدة'], full: ['Hapax legomenon', 'الكلمة الفريدة (hapax legomenon)'], page: 'overview',
      plain: ['A word form that occurs only once in a text.', 'صيغةُ كلمةٍ لا ترد في النص إلا مرةً واحدة.'],
      here: ['Counted among the written forms on the Overview.', 'تُعَدّ ضمن الصيغ المكتوبة في النظرة العامة.'],
      found: ['8,619 of the 14,710 written forms (59%) occur only once.', '٨٬٦١٩ من الصيغ المكتوبة الـ١٤٬٧١٠ (٥٩٪) لا ترد إلا مرةً واحدة.'],
      sci: ['Counted over normalized written forms, which include attached particles and pronouns; by lemma, 1,960 of the 4,771 (41%) occur once.', 'تُعَدّ على الصيغ المكتوبة الموحَّدة الرسم، وهي تشمل الأدوات والضمائر المتصلة؛ وبالمداخل المعجمية يرد ١٬٩٦٠ من ٤٬٧٧١ (٤١٪) مرةً واحدة.'] },
    normalization: { name: ['normalization', 'توحيد الرسم'], full: ['Text normalization', 'توحيد الرسم'], page: 'search',
      plain: ['Making different spellings of the same letters match: removing the vowel marks and treating أ, إ, آ and ٱ as ا.', 'جعل الرسوم المختلفة للحروف نفسها متطابقة: بحذف الحركات، وجعل أ وإ وآ وٱ ألفًا (ا).'],
      here: ['The search, the letter counts and the written forms all use normalized text.', 'البحث وعدّ الحروف والصيغ المكتوبة كلها تستعمل النص الموحَّد الرسم.'],
      found: ['It merges words that differ only in their vowels: مَلَك (angel) and مُلْك (dominion) both become ملك. Lemmas keep them apart.', 'يدمج الكلمات التي لا تختلف إلا في حركاتها: فمَلَك ومُلْك تصيران «ملك»، والمداخل المعجمية تفصل بينها.'],
      sci: ['Strips U+064B–065F, U+0670 (the dagger alif), U+0610–061A and U+06D6–06ED; maps ٱ آ أ إ → ا and ى → ي. The hamza letters ء ؤ ئ and ة are kept.', 'يحذف U+064B–065F وU+0670 (الألف الخنجرية) وU+0610–061A وU+06D6–06ED، ويحوّل ٱ آ أ إ إلى ا، وى إلى ي، ويُبقي ء ؤ ئ وة.'] },
    ngram: { name: ['bigram', 'الثنائية'], full: ['Bigram (n-gram)', 'الثنائية (n-gram)'], page: 'nlp',
      plain: ['Two words that come one after the other. Counting them finds a text\'s set phrases.', 'كلمتان تأتي إحداهما بعد الأخرى، وعدّها يكشف العبارات الثابتة في النص.'],
      here: ['The NLP page counts every pair (and every run of three) of neighbouring words within a verse.', 'تعدّ صفحة معالجة اللغة كل زوجٍ (وكل ثلاثٍ) من الكلمات المتجاورة داخل الآية.'],
      found: ['The commonest is إن الله (257 times), then الذين ءامنوا (184).', 'أكثرها ورودًا «إن الله» (٢٥٧ مرة)، ثم «الذين ءامنوا» (١٨٤).'],
      sci: ['Adjacent pairs of normalized written words, not crossing verse boundaries; raw counts, with no PMI or other association measure.', 'أزواجٌ متجاورة من الكلمات المكتوبة الموحَّدة الرسم لا تعبر حدود الآية؛ أعدادٌ خام بلا PMI أو مقياس اقترانٍ آخر.'] },
    cosine: { name: ['cosine similarity', 'تشابه جيب التمام'], full: ['Cosine similarity', 'تشابه جيب التمام'], page: 'cluster',
      plain: ['A score from 0 to 1 for how alike two texts are in the words they use and how much they use them.', 'درجةٌ من ٠ إلى ١ لمدى تشابه نصّين في الكلمات التي يستعملانها ومقدار استعمالها.'],
      here: ['The Clusters page lists each surah\'s five most similar surahs by vocabulary.', 'تعرض صفحة العناقيد أشبه خمس سورٍ بكل سورةٍ في مفرداتها.'],
      found: ['Al-Baqarah and Aal-Imran are the most alike pair (0.92); for 100 of the 114 surahs the most similar one has the same Meccan or Medinan label.', 'البقرة وآل عمران أشبه زوج (٠٫٩٢)، ولـ١٠٠ من ١١٤ سورة تشترك أشبه سورةٍ بها معها في الوسم مكيةً أو مدنية.'],
      sci: ['`cos θ = a·b / (‖a‖ ‖b‖)` between TF-IDF vectors; they have no negative entries, so it runs from 0 to 1.', '`cos θ = a·b / (‖a‖ ‖b‖)` بين متجهات TF-IDF، ولا قيم سالبة فيها، فتتراوح من ٠ إلى ١.'] },
    shuffle: { name: ['shuffle test', 'اختبار الخلط'], full: ['Shuffle test (permutation test)', 'اختبار الخلط (اختبار التبديل)'], page: 'd-rhyme',
      plain: ['To see whether a pattern could be chance, shuffle the thing being tested thousands of times (which verse has which ending, which places count as rhyme changes) and measure again each time. If the real text beats almost every shuffled copy, chance is a poor explanation.',
        'لتعرف هل النمط مصادفة، اخلط الشيء المختبَر آلاف المرات (أيّ آيةٍ لها أيّ خاتمة، وأيّ المواضع تُعَدّ تغيّرًا في الفاصلة) وأعد القياس في كل مرة. فإن تفوّق النص الحقيقي على كل النسخ المخلوطة تقريبًا كانت المصادفة تفسيرًا ضعيفًا.'],
      here: ['Every tested study in Discoveries compares the text with 285 to 10,000 shuffled versions of itself.', 'كل دراسةٍ مختبَرة في «اكتشافات» تقارن النص بما بين ٢٨٥ و١٠٬٠٠٠ نسخةٍ مخلوطةٍ منه.'],
      found: ['In the rhyme study none of 2,000 shuffles produced a gap as big as the real one; in the mirror study a quarter of the turned copies did as well as the real surah.',
        'في دراسة الفواصل لم تُنتج أيٌّ من ٢٬٠٠٠ خلطةٍ فرقًا بحجم الفرق الحقيقي، وفي دراسة التناظر بلغ ربع النسخ المُدارة ما بلغته السورة الحقيقية.'],
      sci: ['A permutation test: under the null hypothesis the labels are exchangeable, so the statistic\'s null distribution is estimated by recomputing it on B random permutations; `p = (#{null ≥ obs} + 1) / (B + 1)`. Restricting permutations to within groups (for example within surahs) conditions on group-level structure.',
        'اختبار التبديل: تحت فرضية العدم تكون الوسوم قابلةً للتبادل، فيُقدَّر توزيع الإحصاءة الصفري بإعادة حسابها على B تبديلًا عشوائيًّا، و`p = (#{null ≥ obs} + 1) / (B + 1)`. وحصر التبديل داخل مجموعات (داخل السور مثلًا) يثبّت البنية على مستوى المجموعة.'] },
    prereg: { name: ['pre-registration', 'التسجيل المسبق'], full: ['Pre-registration', 'التسجيل المسبق للدراسة'], page: 'discover',
      plain: ['Writing down, before looking at the results, exactly what will be tested, how, and what counts as a yes, and publishing it. It stops anyone from quietly picking, afterwards, whichever test looks best.',
        'أن تكتب قبل رؤية النتائج ما الذي سيُختبر بالضبط، وكيف، وما الذي يُعَدّ جوابًا بـ«نعم»، ثم تنشره. وهذا يمنع أيَّ أحدٍ من أن يختار بعد ذلك، في صمت، الاختبار الذي تبدو نتيجته أفضل.'],
      here: ['The nine Discoveries studies were written down and published in the project\'s public history before any was run; one change, found before running, is logged there with its reason, and so is an addendum on the mirror claims, written down before it was run.',
        'كُتبت دراسات «اكتشافات» التسع ونُشرت في السجل العام للمشروع قبل تشغيل أيٍّ منها، وتغييرٌ واحد اكتُشف قبل التشغيل مدوَّنٌ هناك مع سببه، وكذلك ملحقٌ عن ادعاءات التناظر كُتب قبل تشغيله.'],
      found: ['Three of the tests came out «does not hold», and they stay on the site.', 'خرجت ثلاثة اختبارات بـ«لم تثبت»، وتبقى في الموقع.'],
      sci: ['Guards against analytic flexibility (the «garden of forking paths», p-hacking, hypothesizing after the results are known). The commit\'s hash and timestamp make the plan\'s date checkable; deviations are logged; analyses added later are labelled exploratory and carry no verdict.',
        'يحمي من مرونة التحليل («حديقة المسارات المتشعبة»، والتلاعب بالقيمة الاحتمالية، وصوغ الفرضيات بعد معرفة النتائج). وبصمة الإيداع وتاريخه يجعلان تاريخ الخطة قابلًا للتحقق، والانحرافات مدوَّنة، وما أُضيف لاحقًا من تحليلات موسومٌ بالاستكشافي ولا حكم له.'] },
    multiple: { name: ['correcting for many tests', 'تصحيح تعدّد الاختبارات'], full: ['Multiple-testing correction (Holm, Benjamini–Hochberg)', 'تصحيح تعدّد الاختبارات (هولم، بنجاميني–هوخبرغ)'], page: 'd-companions',
      plain: ['Run many tests and some will pass by luck. A correction raises the bar for each test, so that the set of results as a whole stays trustworthy.', 'إن أجريت اختباراتٍ كثيرة نجح بعضها بالحظ. والتصحيح يرفع الحدّ لكل اختبار، كي تبقى النتائج في جملتها جديرةً بالثقة.'],
      here: ['The verse-endings study has two tests (Holm); the scan of long surahs tests 38 surahs, and the word-companions map 86,945 pairs (Benjamini–Hochberg).', 'في دراسة الخواتيم اختباران (هولم)، ومسح السور الطويلة يختبر ٣٨ سورة، وخريطة الكلمات المتصاحبة ٨٦٬٩٤٥ زوجًا (بنجاميني–هوخبرغ).'],
      found: ['Of 86,945 word pairs, 1,207 pass at a 1% false-discovery rate; in the scan of long surahs, the lowest p (0.024) does not survive.', 'من ٨٦٬٩٤٥ زوجًا يجتاز ١٬٢٠٧ عند معدّل اكتشافٍ كاذب ١٪، وفي مسح السور الطويلة لا تصمد أدنى قيمةٍ احتمالية (٠٫٠٢٤).'],
      sci: ['Holm: sort the m p-values, compare the i-th smallest with `α / (m − i + 1)` step-down; controls the family-wise error rate. Benjamini–Hochberg: reject the k smallest where k is the largest i with `p₍i₎ ≤ q · i / m`; controls the expected share of false discoveries at q (under independence or positive dependence).',
        'هولم: رتّب القيم الاحتمالية الـm وقارن أصغرها رقم i بـ`α / (m − i + 1)` تنازليًّا، فيضبط احتمال خطأٍ واحدٍ على الأقل. بنجاميني–هوخبرغ: ارفض أصغر k قيمةً حيث k أكبر i يحقق `p₍i₎ ≤ q · i / m`، فيضبط النسبة المتوقعة للاكتشافات الكاذبة عند q (مع الاستقلال أو الارتباط الموجب).'] },
    nmf: { name: ['NMF', 'NMF'], full: ['Non-negative matrix factorization (NMF)', 'تحليل المصفوفات غير السالبة (NMF)'], page: 'd-themes',
      plain: ['A way to find themes without telling the computer what they are: it looks for groups of words that tend to come together in the same verses, and describes each verse as a mix of those groups.',
        'طريقةٌ لإيجاد الموضوعات دون إخبار الحاسوب بها: تبحث عن مجموعاتٍ من الكلمات تميل إلى الاجتماع في الآيات نفسها، وتصف كل آيةٍ مزيجًا من تلك المجموعات.'],
      here: ['12 themes from the words of all 6,236 verses; each verse is coloured by its largest theme.', '١٢ موضوعًا من ألفاظ الآيات الـ٦٬٢٣٦ كلها، وكل آيةٍ ملوّنةٌ بأكبر موضوعاتها.'],
      found: ['Ten of the twelve themes come back each time the method starts afresh; the largest, believers and disbelievers and their reward, leads in 13% of verses.', 'عشرة من الاثني عشر تعود في كل مرةٍ تبدأ فيها الطريقة من جديد، وأكبرها «المؤمنون والكافرون وجزاؤهم» يتصدّر ١٣٪ من الآيات.'],
      sci: ['`X ≈ W H` with W, H ≥ 0, minimizing the Frobenius norm; X is the verse × lemma TF-IDF matrix, k = 12, nndsvda start. Stability: mean best-match cosine between the rows of H across 5 random restarts.',
        '`X ≈ W H` مع W وH غير سالبتين، بتقليل معيار فروبينيوس؛ وX مصفوفة TF-IDF للآيات × المداخل، و`k = 12` ببداية nndsvda. والثبات: متوسط أعلى تشابه جيب تمامٍ بين صفوف H عبر ٥ بداياتٍ عشوائية.'] },
    pmi: { name: ['PMI', 'PMI'], full: ['Pointwise mutual information (PMI)', 'المعلومات المتبادلة النقطية (PMI)'], page: 'd-companions',
      plain: ['How many times more often two words share a verse than they would if they were scattered at random. A PMI of 3 means 8 times more often (2 × 2 × 2).', 'كم مرةً تجتمع كلمتان في آيةٍ أكثر مما لو تبعثرتا عشوائيًّا. فـPMI يساوي ٣ يعني ٨ أضعاف (٢ × ٢ × ٢).'],
      here: ['The strength of each pair on the word-companions map.', 'قوة كل زوجٍ في خريطة الكلمات المتصاحبة.'],
      found: ['ليل and نهار (night and day) share 42 verses, about 70 times more than chance.', 'الليل والنهار يجتمعان في ٤٢ آية، أي نحو ٧٠ ضعف المصادفة.'],
      sci: ['`PMI = log₂(c · N / (n_a · n_b))`, with c the verses with both words, n_a and n_b the verses with each, N = 6,236. It favours rare pairs, so pairs are also filtered by a significance test and c ≥ 3.',
        '`PMI = log₂(c · N / (n_a · n_b))` حيث c الآيات التي تجمع الكلمتين، وn_a وn_b آيات كلٍّ منهما، و`N = 6,236`. وهو يحابي الأزواج النادرة، ولذا تُرشَّح الأزواج أيضًا باختبار دلالةٍ و`c ≥ 3`.'] },
    spearman: { name: ['rank correlation', 'ارتباط الرتب'], full: ['Spearman rank correlation (ρ)', 'معامل ارتباط الرتب لسبيرمان (ρ)'], page: 'd-chrono',
      plain: ['Whether two things rise together, using only their order: 1 means perfectly together, 0 no link, −1 one falls as the other rises.', 'هل يرتفع أمران معًا، بالاعتماد على ترتيبهما فقط: ١ يعني معًا تمامًا، و٠ لا علاقة، و−١ أحدهما ينخفض كلما ارتفع الآخر.'],
      here: ['The surahs\' traditional order of revelation against their average verse length.', 'ترتيب السور في النزول المأثور مقابل متوسط طول آياتها.'],
      found: ['ρ = 0.67: later surahs tend to have longer verses; 0.52 within the Meccan surahs alone.', '`ρ = 0.67`: السور المتأخرة أطول آياتٍ في الغالب، و٠٫٥٢ في السور المكية وحدها.'],
      sci: ['Pearson\'s correlation of the ranks; robust to outliers and to any monotone rescaling. Here p comes from 10,000 permutations of one variable (two-sided).', 'معامل بيرسون للرتب، لا يتأثر بالقيم الشاذة ولا بأي تحويلٍ رتيب. والقيمة الاحتمالية هنا من ١٠٬٠٠٠ تبديلٍ لأحد المتغيرين (من طرفين).'] },
    lexicon: { name: ['word lists', 'قوائم الكلمات'], full: ['Lexicon (word-list) method', 'طريقة المعجم (قوائم الكلمات)'], page: 'emotion',
      plain: ['Measuring a theme by counting words from a fixed list (for example mercy, forgive and peace for «mercy»).', 'قياس معنًى بعدّ كلماتٍ من قائمةٍ ثابتة (مثل mercy وforgive وpeace لمعنى «الرحمة»).'],
      here: ['The Emotion page counts four such lists in an English translation.', 'تعدّ صفحة البصمة العاطفية أربع قوائم كهذه في ترجمةٍ إنجليزية.'],
      found: ['Guidance words are counted most (1,026), then mercy (779), warning (710) and hope (379).', 'كلمات الهداية الأكثر عدًّا (١٬٠٢٦)، ثم الرحمة (٧٧٩)، والتحذير (٧١٠)، والأمل (٣٧٩).'],
      sci: ['Per verse, the number of distinct list words present (a set intersection on lower-case tokens), summed per surah; no stemming, negation or word-sense handling.', 'لكل آية: عدد كلمات القائمة المختلفة الموجودة فيها (تقاطع مجموعاتٍ على كلماتٍ بأحرفٍ صغيرة)، مجموعًا لكل سورة؛ بلا ردٍّ إلى الأصل ولا مراعاةٍ للنفي أو المعنى.'] },
  };

  // The Clusters page's walk-through: how four measurements become the map. Step 0 to 4; the page
  // opens on the last (the finished map). {K} is replaced with the share the line keeps.
  const PCA = [
    { title: ['Measure', 'القياس'],
      text: ['Every surah is described by four measurements. Here are two of them, the number of verses and the number of words, each put on the same scale, where 0 is the average surah. Each disc is one surah, made of its own verses.',
        'تُوصف كل سورةٍ بأربعة قياسات، وهنا اثنان منها: عدد الآيات وعدد الكلمات، وقد وُضع كلٌّ منهما على مقياسٍ واحد صفرُه السورة المتوسطة. وكل قرصٍ سورةٌ مصنوعةٌ من آياتها.'],
      sci: ['Axes: [[zscore|z-scores]] (population SD). Pearson r(verses, words) = 0.88.', 'المحوران: [[zscore|درجاتٌ معيارية]] (انحراف المجتمع). ومعامل الارتباط `r(verses, words) = 0.88`'],
      cap: ['Each disc is one surah: across, its number of verses; up, its number of words, both as standard scores. Gold: Meccan, green: Medinan.', 'كل قرصٍ سورةٌ واحدة: أفقيًا عدد آياتها، وعموديًا عدد كلماتها، وكلاهما بالدرجة المعيارية. الذهبي مكي والأخضر مدني.'] },
    { title: ['Find the widest direction', 'أوسع اتجاه'],
      text: ['Turn the line. Each tick on it is a surah\'s shadow, and the spread of the shadows is how much of the differences the line keeps: now {K}. PCA picks the direction where the spread is widest.',
        'أدِر الخط. كل علامةٍ عليه ظلُّ سورة، وانتشار الظلال هو ما يحتفظ به الخط من الفروق: الآن {K}. ويختار تحليل المكوّنات الرئيسية الاتجاه الذي يبلغ فيه الانتشار أقصاه.'],
      sci: ['Share kept at angle θ: `Var(z·u) / tr(C) = (1 + r·sin 2θ) / 2`, largest at 45° for two standardized measures: (1 + 0.88) / 2 = 94%.', 'النسبة المحفوظة عند الزاوية θ: `Var(z·u) / tr(C) = (1 + r·sin 2θ) / 2`، وأكبرها عند ٤٥° لقياسين مقيَّسين: `(1 + 0.88) / 2 = 94%`'],
      cap: ['The gold line is the direction being tried; the ticks on it are the surahs\' shadows.', 'الخط الذهبي هو الاتجاه المُجرَّب، والعلامات عليه ظلال السور.'] },
    { title: ['Flatten', 'التسطيح'],
      text: ['Now each surah keeps only its shadow: one number instead of two. Surahs that were far apart stay far apart; only the small spread across the line is lost, {K} is kept.',
        'الآن تحتفظ كل سورةٍ بظلها فقط: رقمٌ واحد بدل رقمين. فالسور المتباعدة تبقى متباعدة، ولا يضيع إلا الانتشار القليل عرضَ الخط، ويبقى {K}.'],
      sci: ['Projection onto the first principal axis: `t₁ = Z·v₁`.', 'الإسقاط على المحور الرئيسي الأول: `t₁ = Z·v₁`'],
      cap: ['Each surah has moved to its shadow on the line.', 'انتقلت كل سورةٍ إلى ظلها على الخط.'] },
    { title: ['All four measurements', 'القياسات الأربعة'],
      text: ['PCA does the same with all four measurements at once. The widest direction becomes the map\'s first axis; the next widest, at a right angle to it, the second. Together they keep 90% of the differences between surahs. The bars show what each direction is made of.',
        'يفعل التحليل الشيء نفسه بالقياسات الأربعة معًا: أوسع اتجاهٍ يصير المحور الأول للخريطة، والذي يليه عموديًا عليه يصير الثاني، ويحتفظان معًا بـ٩٠٪ من الفروق بين السور. والأشرطة تبيّن مِمّ يتألف كل اتجاه.'],
      sci: ['Eigenvalues of the 4 × 4 correlation matrix: 2.40, 1.20, 0.32, 0.08 (60.1, 29.9, 8.0 and 2.0% of the variance). Bars: loadings (eigenvector entries).', 'القيم الذاتية لمصفوفة الارتباط ٤ × ٤: ‏2.40 و1.20 و0.32 و0.08 (٦٠٫١ و٢٩٫٩ و٨٫٠ و٢٫٠٪ من التباين). والأشرطة: التحميلات (عناصر المتجهات الذاتية).'],
      cap: ['The map: across, the first direction; up, the second. Gold: Meccan, green: Medinan.', 'الخريطة: أفقيًا الاتجاه الأول، وعموديًا الاتجاه الثاني. الذهبي مكي والأخضر مدني.'] },
    { title: ['Groups', 'المجموعات'],
      text: ['Finally, k-means sorts the surahs into four groups, using all four measurements. The colours now show the groups; the map lets you see them.',
        'وأخيرًا تقسم خوارزمية k-means السور إلى أربع مجموعاتٍ بالقياسات الأربعة كلها. والألوان الآن ألوان المجموعات، والخريطة تتيح لك رؤيتها.'],
      sci: ['[[kmeans|k-means]], K = 4, on the four standardized measurements (not on the map), best of 10 starts, seed 42.', '[[kmeans|k-means]] بـ`K = 4` على القياسات الأربعة المقيَّسة (لا على الخريطة)، أفضل عشر بدايات، البذرة ٤٢.'] },
  ];

  return { SCI, GLOSS, PCA };
})();
